import { CreatePDFRequest, ICreatePDFRequest } from "@src/shared/pdf/requests/create-pdf.request";
import { ITreatmentModel } from "@src/modules/site/patient-list/models";
import { PdfAssesmentUgd } from "@src/modules/emergency-room/assessment/requests/pdf-assement-ugd.request";
import citymapping from "@src/modules/outpatient/proof-of-outpatient-services/const/citymapping";
import { DateTimeConverter } from "@src/shared/datetime-converter";

export interface IPdfAsesmenPraOperasi extends ICreatePDFRequest {
  data: {
    nomor_mr: string,
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string,
    'pasien.Jenis_Kelamin': string,
    medis_td: string,
    medis_nadi: string,
    medis_rr: string,
    medis_suhu: string,
    medis_nyeri: string,
    alegi_tidak_ada: string,
    alegi_ada: string,
    medis_alergi: string,
    penyakit_tidak_ada: string,
    penyakit_ada: string,
    medis_penyakit_penyerta: string,
    pengobatan_tidak_ada: string,
    pengobatan_ada: string,
    medis_pengobatan_saat_ini: string,
    penyakit_dm: string,
    penyakit_infark: string,
    penyakit_hepar: string,
    penyakit_hipertensi: string,
    penyakit_koroner: string,
    penyakit_ginjal: string,
    penyakit_dekompensasi: string,
    penyakit_darah: string,
    penyakit_lain_lain: string,
    pengobatan_ht: string,
    pengobatan_sedatine: string,
    pengobatan_dm: string,
    pengobatan_corticosteroid: string,
    pengobatan_lain_lain: string,
    tonometri_dll: string,
    penunjang_biometri: string,
    penunjang_usg: string,
    penunjang_foto_pundus: string,
    penunjang_oct: string,
    penunjang_dll: string,
    hasil_konsultasi: string,
    persediaan_ada: string,
    persediaan_tidak: string,
    persetujuan_darah_ada: string,
    persetujuan_darah_belum: string,
    anestesi_rencana_umum: string,
    anestesi_rencana_sedasi: string,
    anestesi_rencana_lokal: string,
    alegi_tidak_topikal: string,
    jenis_kasus_bersih: string,
    jenis_kasus_bersih_tercemar: string,
    jenis_kasus_tercemar: string,
    jenis_kasus_kotor: string,
    diagnosa: string,
    rencana_operasi: string,
    tanggal_operasi: string,
    ahli_bedah: string,
    nama_kota: string,
    tanggal_simpan: string,
    nama_dokter_operator: string,
    ttd_dokter_operator: string,
    penyakit_penyerta_lain: string,
    pengobatan_saat_ini_lain: string,
    nik: string,
  }
}

export class PdfAsesmenPraOperasi extends CreatePDFRequest {
  data: {
    nomor_mr: string,
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string,
    'pasien.Jenis_Kelamin': string,
    medis_td: string,
    medis_nadi: string,
    medis_rr: string,
    medis_suhu: string,
    medis_nyeri: string,
    alegi_tidak_ada: string,
    alegi_ada: string,
    medis_alergi: string,
    penyakit_tidak_ada: string,
    penyakit_ada: string,
    medis_penyakit_penyerta: string,
    pengobatan_tidak_ada: string,
    pengobatan_ada: string,
    medis_pengobatan_saat_ini: string,
    penyakit_dm: string,
    penyakit_infark: string,
    penyakit_hepar: string,
    penyakit_hipertensi: string,
    penyakit_koroner: string,
    penyakit_ginjal: string,
    penyakit_dekompensasi: string,
    penyakit_darah: string,
    penyakit_lain_lain: string,
    pengobatan_ht: string,
    pengobatan_sedatine: string,
    pengobatan_dm: string,
    pengobatan_corticosteroid: string,
    pengobatan_lain_lain: string,
    tonometri_dll: string,
    penunjang_biometri: string,
    penunjang_usg: string,
    penunjang_foto_pundus: string,
    penunjang_oct: string,
    penunjang_dll: string,
    hasil_konsultasi: string,
    persediaan_ada: string,
    persediaan_tidak: string,
    persetujuan_darah_ada: string,
    persetujuan_darah_belum: string,
    anestesi_rencana_umum: string,
    anestesi_rencana_sedasi: string,
    anestesi_rencana_lokal:  string,
    alegi_tidak_topikal: string,
    jenis_kasus_bersih: string,
    jenis_kasus_bersih_tercemar: string,
    jenis_kasus_tercemar: string,
    jenis_kasus_kotor: string,
    diagnosa: string,
    rencana_operasi: string,
    tanggal_operasi: string,
    ahli_bedah: string,
    nama_kota: string,
    tanggal_simpan: string,
    nama_dokter_operator: string,
    ttd_dokter_operator: string,
    penyakit_penyerta_lain: string,
    pengobatan_saat_ini_lain: string,
    nik: string,
  }

  constructor(req: IPdfAsesmenPraOperasi) {
    super(req);
    this.data = req.data;
  }

  static createFromJson(json: IPdfAsesmenPraOperasi) {
    return new PdfAsesmenPraOperasi(json);
  }

  static createPdfRequest(val: any, treatment: ITreatmentModel): PdfAsesmenPraOperasi {
    const getCity = (companyCode: string) => {
      const selected = citymapping.find((item: any) => item.company_code === companyCode);
      if (selected) {
        return selected.city;
      } else {
        return '';
      }
    }

    return new PdfAsesmenPraOperasi({
      emr_id: treatment.EMR_ID,
      form_name: 'ok_asesmen-pra-operasi',
      row_filter: '',
      preview: false,
      data: {
        nomor_mr: val?.nomor_mr ?? '',
        'pasien.Nama': val?.pasien?.Nama ?? '',
        'pasien.Tgl_Lahir': DateTimeConverter.convertToNormalDate(val?.pasien?.Tgl_Lahir),
        'pasien.Umur': this.normalizeAge(treatment?.Pasien?.Umur_Lengkap),
        'pasien.Jenis_Kelamin': val?.pasien?.Jenis_Kelamin ?? '',
        medis_td: val?.form?.Td ?? '',
        medis_nadi: val?.form?.Nadi ?? '',
        medis_rr: val?.form?.Rr ?? '',
        medis_suhu: val?.form?.Suhu ?? '',
        medis_nyeri: val?.form?.Skala_Nyeri ?? '',
        alegi_tidak_ada: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Alergi === '0'),
        alegi_ada: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Alergi === '2'),
        medis_alergi: val?.form?.Alergi_Keterangan ?? '',
        penyakit_tidak_ada: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Penyakit_Peserta === '0'),
        penyakit_ada: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Penyakit_Peserta === '2'),
        medis_penyakit_penyerta: val?.form?.Penyakit_Peserta_Keterangan ?? '',
        pengobatan_tidak_ada: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Pengobatan_Saat_Ini === '0'),
        pengobatan_ada: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Pengobatan_Saat_Ini === '2'),
        medis_pengobatan_saat_ini: val?.form?.Pengobatan_Saat_Ini_Lain ?? '',
        penyakit_dm: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Penyakit_Peserta?.Diabetes_Melitus === 1),
        penyakit_infark: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Penyakit_Peserta?.Jantung === 1),
        penyakit_hepar: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Penyakit_Peserta?.Hepar === 1),
        penyakit_hipertensi: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Penyakit_Peserta?.Hipertensi === 1),
        penyakit_koroner: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Penyakit_Peserta?.Koroner === 1),
        penyakit_ginjal: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Penyakit_Peserta?.Ginjal === 1),
        penyakit_dekompensasi: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Penyakit_Peserta?.Dekompensasi === 1),
        penyakit_darah: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Penyakit_Peserta?.Pembekuan_Darah === 1),
        penyakit_lain_lain: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Penyakit_Peserta?.Lain_lain === 1),
        pengobatan_ht: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Pengobatan_Saat_Ini?.Obat_Hipertensi === 1),
        pengobatan_sedatine: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Pengobatan_Saat_Ini?.Sedatine ===  1),
        pengobatan_dm: PdfAssesmentUgd.getCheckImage(val?.form?.Pengobatan_Saat_Ini?.Obat_Dm === 1),
        pengobatan_corticosteroid:  PdfAssesmentUgd.getCheckImage(val?.form?.Pengobatan_Saat_Ini?.Corticosteroid === 1),
        pengobatan_lain_lain: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Pengobatan_Saat_Ini?.Lain_lain === 1),
        tonometri_dll: val?.form?.Tonometri ?? '',
        penunjang_biometri: val?.form?.Biometri ?? '',
        penunjang_usg: val?.form?.Usg_Mata ?? '',
        penunjang_foto_pundus: val?.form?.Foto_Fundus ?? '',
        penunjang_oct: val?.form?.Oct_Makula ?? '',
        penunjang_dll: val?.form?.Dll ?? '',
        hasil_konsultasi: val?.form?.Hasil_Konsultasi ?? '',
        penyakit_penyerta_lain: val?.form?.Penyakit_Peserta_Keterangan ?? '',
        pengobatan_saat_ini_lain: val?.form?.Pengobatan_Saat_Ini_Lain ?? '',
        persediaan_ada: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Persediaan_Darah === '0'),
        persediaan_tidak: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Persediaan_Darah === '1'),
        persetujuan_darah_ada: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Persetujuan === '1'),
        persetujuan_darah_belum: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Persetujuan === '0'),
        anestesi_rencana_umum: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Anestesi === '1'),
        anestesi_rencana_sedasi: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Anestesi === '2'),
        anestesi_rencana_lokal: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Anestesi === '3'),
        alegi_tidak_topikal: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Anestesi === '4'),
        jenis_kasus_bersih: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Jenis_Kasus === '1'),
        jenis_kasus_bersih_tercemar: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Jenis_Kasus === '2'),
        jenis_kasus_tercemar: PdfAsesmenPraOperasi.getCheckImage(val?.form?.Jenis_Kasus === '3'),
        jenis_kasus_kotor: PdfAssesmentUgd.getCheckImage(val?.form?.Jenis_Kasus === '4'),
        diagnosa: val?.form?.Diagnosa ?? '',
        rencana_operasi: val?.form?.Rencana_Operasi ?? '',
        tanggal_operasi: DateTimeConverter.convertToNormalDate(val?.form?.Tanggal_Operasi),
        ahli_bedah: val?.form?.Ahli_Bedah ?? '',
        nama_kota: getCity(treatment.Kode_Cabang),
        tanggal_simpan: DateTimeConverter.convertToNormalDate(val?.form?.Tanggal),
        nama_dokter_operator: (val?.form?.Nama_Dokter !== '') ? val?.form?.Nama_Dokter : undefined,
        ttd_dokter_operator: (val?.form?.TTD_Dokter !== '') ? val?.form?.TTD_Dokter : undefined,
        nik: val?.pasien?.NIK ?? '',
      },
    })
  }
}
