import { DateTimeConverter } from "@src/shared/datetime-converter";
import { CreatePDFRequest, ICreatePDFRequest } from "@src/shared/pdf/requests/create-pdf.request";

export interface IPdfPreparationOfAnestheticEquipmentRequest extends ICreatePDFRequest {
  data: {
    nomor_mr: string,
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string,
    'pasien.Jenis_Kelamin': string,
    unit: string,
    tanggal_jam_tindakan: string,
    jenis_operasi: string,
    teknik_anestesia: string,
    '1_1': string,
    '1_2': string,
    '1_3': string,
    '2_1': string,
    '2_2': string,
    '2_3': string,
    '2_4': string,
    '2_5': string,
    '2_6': string,
    '3_1': string,
    '3_2': string,
    '3_3': string,
    '3_4': string,
    '3_5': string,
    '4_1': string,
    '4_2': string,
    '4_3': string,
    '4_4': string,
    '4_5': string,
    '4_6': string,
    '4_7': string,
    '4_8': string,
    '4_9': string,
    '5_1': string,
    '5_2': string,
    '5_3': string,
    '5_4': string,
    '5_5': string,
    '5_6': string,
    '6_1': string,
    '6_2': string,
    '6_3': string,
    '6_4': string,
    '6_5': string,
    '6_6': string,
    '6_7': string,
    '7_1': string,
    '7_2': string,
    '7_3': string,
    '7_4': string,
    '7_5': string,
    '7_6': string,
    '7_7': string,
    obat_lain_lain: string,
    ttd_Perawat_Anestesi: string,
    Nama_Perawat_Anestesi: string,
    ttd_Dokter_Anestesi: string,
    Nama_Dokter_Anestesi: string,
    nik: string;
  }
}

export class PdfPreparationOfAnestheticEquipmentRequest extends CreatePDFRequest {
  data: {
    nomor_mr: string,
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string,
    'pasien.Jenis_Kelamin': string,
    unit: string,
    tanggal_jam_tindakan: string,
    jenis_operasi: string,
    teknik_anestesia: string,
    '1_1': string,
    '1_2': string,
    '1_3': string,
    '2_1': string,
    '2_2': string,
    '2_3': string,
    '2_4': string,
    '2_5': string,
    '2_6': string,
    '3_1': string,
    '3_2': string,
    '3_3': string,
    '3_4': string,
    '3_5': string,
    '4_1': string,
    '4_2': string,
    '4_3': string,
    '4_4': string,
    '4_5': string,
    '4_6': string,
    '4_7': string,
    '4_8': string,
    '4_9': string,
    '5_1': string,
    '5_2': string,
    '5_3': string,
    '5_4': string,
    '5_5': string,
    '5_6': string,
    '6_1': string,
    '6_2': string,
    '6_3': string,
    '6_4': string,
    '6_5': string,
    '6_6': string,
    '6_7': string,
    '7_1': string,
    '7_2': string,
    '7_3': string,
    '7_4': string,
    '7_5': string,
    '7_6': string,
    '7_7': string,
    obat_lain_lain: string,
    ttd_Perawat_Anestesi: string,
    Nama_Perawat_Anestesi: string,
    ttd_Dokter_Anestesi: string,
    Nama_Dokter_Anestesi: string,
    nik: string,
  }

  constructor(req: IPdfPreparationOfAnestheticEquipmentRequest) {
    super(req);
    this.data = req.data;
  }

  static createFromJson(json: IPdfPreparationOfAnestheticEquipmentRequest) {
    return new PdfPreparationOfAnestheticEquipmentRequest(json);
  }

  static createPdfRequest(val: any, emrId: string): PdfPreparationOfAnestheticEquipmentRequest {
    return new PdfPreparationOfAnestheticEquipmentRequest({
      emr_id: emrId,
      form_name: 'ok_persiapan-peralatan',
      row_filter: '',
      preview: false,
      data: {
        nomor_mr: val?.nomor_mr ?? '',
        'pasien.Nama': val?.pasien?.Nama ?? '',
        'pasien.Tgl_Lahir': DateTimeConverter.convertToNormalDate(val?.pasien?.Tgl_Lahir),
        'pasien.Umur': this.normalizeAge(val?.umur_lengkap),
        'pasien.Jenis_Kelamin': val?.pasien?.Jenis_Kelamin ?? '',
        unit: val?.form?.Unit ?? '',
        tanggal_jam_tindakan: DateTimeConverter.convertToDateTime(val?.form?.Tanggal_Tindakan),
        jenis_operasi: val?.form?.Jenis_Operasi ?? '',
        teknik_anestesia: val?.form?.Teknik_Anestesi ?? '',
        '1_1': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Listrik_1 === '1'),
        '1_2': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Listrik_2 === '1'),
        '1_3': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Listrik_3 === '1'),
        '2_1': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Gas_1 === '1'),
        '2_2': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Gas_2 === '1'),
        '2_3': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Gas_3 === '1'),
        '2_4': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Gas_4 === '1'),
        '2_5': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Gas_5 === '1'),
        '2_6': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Gas_6 === '1'),
        '3_1': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Mesin_Anestesi_1 === '1'),
        '3_2': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Mesin_Anestesi_2 === '1'),
        '3_3': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Mesin_Anestesi_3 === '1'),
        '3_4': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Mesin_Anestesi_4 === '1'),
        '3_5': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Mesin_Anestesi_5 === '1'),
        '4_1': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Manajemen_Nafas_1 === '1'),
        '4_2': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Manajemen_Nafas_2 === '1'),
        '4_3': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Manajemen_Nafas_3 === '1'),
        '4_4': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Manajemen_Nafas_4 === '1'),
        '4_5': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Manajemen_Nafas_5 === '1'),
        '4_6': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Manajemen_Nafas_6 === '1'),
        '4_7': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Manajemen_Nafas_7 === '1'),
        '4_8': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Manajemen_Nafas_8 === '1'),
        '4_9': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Manajemen_Nafas_9 === '1'),
        '5_1': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Pemantauan_1 === '1'),
        '5_2': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Pemantauan_2 === '1'),
        '5_3': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Pemantauan_3 === '1'),
        '5_4': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Pemantauan_4 === '1'),
        '5_5': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Pemantauan_5 === '1'),
        '5_6': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Pemantauan_6 === '1'),
        '6_1': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Lainnya_1 === '1'),
        '6_2': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Lainnya_2 === '1'),
        '6_3': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Lainnya_3 === '1'),
        '6_4': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Lainnya_4 === '1'),
        '6_5': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Lainnya_5 === '1'),
        '6_6': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Lainnya_6 === '1'),
        '6_7': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Lainnya_7 === '1'),
        '7_1': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Obat_1 === '1'),
        '7_2': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Obat_2 === '1'),
        '7_3': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Obat_3 === '1'),
        '7_4': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Obat_4 === '1'),
        '7_5': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Obat_5 === '1'),
        '7_6': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Obat_6 === '1'),
        '7_7': PdfPreparationOfAnestheticEquipmentRequest.getCheckImage(val?.form?.Obat_7 === '1'),
        obat_lain_lain: val?.form?.Obat_7_Teks ?? '',
        ttd_Perawat_Anestesi: (val?.form?.TTD_Penata_Anestesi !== '') ? val?.form?.TTD_Penata_Anestesi : undefined,
        Nama_Perawat_Anestesi: (val?.form?.Nama_Penata_Anestesi !== '') ? val?.form?.Nama_Penata_Anestesi : undefined,
        ttd_Dokter_Anestesi: (val?.form?.TTD_Dokter_Anestesi !== '') ? val?.form?.TTD_Dokter_Anestesi : undefined,
        Nama_Dokter_Anestesi: (val?.form?.Nama_Dokter_Anestesi !== '') ? val?.form?.Nama_Dokter_Anestesi : undefined,
        nik: val?.pasien?.NIK ?? '',
      },
    })
  }
}
