import { DataModel, IDataModel } from "@src/shared/model"

export interface IApprovalOrRefusalOfAnestheticActionFormModel {
  ID_Dokter_Pelaksana: string;
  Nama_Dokter_Pelaksana: string;
  ID_Pemberi_Informasi: string;
  Nama_Pemberi_Informasi: string;
  Penerima_Informasi: string;
  Diagnosis_Check: string;
  Dasar_Diagnosis_Check: string;
  Dasar_Klinis: string;
  Dasar_Radiologi: string;
  Dasar_EKG: string;
  Dasar_Laboratorium: string;
  Tindakan_Kedokteran_Check: string;
  Anestesi_Umum_Intubasi_Check: string;
  Anestesi_Umum_LMA_Check: string;
  Anestesi_Umum_FM_Check: string;
  Anestesi_Umum_TIVA_Check: string;
  Anestesi_Regional_Spinal_Check: string;
  Anestesi_Regional_Epidural_Check: string;
  Anestesi_Regional_Perifer_Check: string;
  Indikasi_Tindakan_Tujuan_Check: string;
  Tata_Cara_Tindakan_Check: string;
  Tata_Cara_Tindakan: string;
  Risiko_Check: string;
  Shock_Check: string;
  Henti_Jantung_Check: string;
  Meninggal_Check: string;
  Tujuan_Check: string;
  Tujuan: string;
  Komplikasi_Check: string;
  Komplikasi_Umum_1: string;
  Komplikasi_Umum_2: string;
  Komplikasi_Umum_3: string;
  Komplikasi_Umum_4: string;
  Komplikasi_Umum_5: string;
  Komplikasi_Umum_6: string;
  Komplikasi_Umum_7: string;
  Komplikasi_Umum_8: string;
  Komplikasi_Umum_9: string;
  Komplikasi_Umum_10: string;
  Komplikasi_Regional_1: string;
  Komplikasi_Regional_2: string;
  Komplikasi_Regional_3: string;
  Komplikasi_Regional_4: string;
  Komplikasi_Regional_5: string;
  Komplikasi_Regional_6: string;
  Komplikasi_Regional_7: string;
  Komplikasi_Regional_8: string;
  Komplikasi_Regional_9: string;
  Komplikasi_Regional_10: string;
  Komplikasi_Regional_11: string;
  Komplikasi_Regional_12: string;
  Prognosis_Check: string;
  Prognosis: string;
  Alternatif_Tindakan_Check: string;
  Alternatif_Tindakan: string;
  Lain_Lain_Check: string;
  Lain_Lain: string;
  ID_Dokter_Pelaksana_TTD: string;
  TTD_Dokter_Pelaksana: string;
  Nama_Dokter_Pelaksana_TTD: string;
  TTD_Penerima_Informasi: string;
  Waktu: string;
  Kota: string;
  Pernyataan_Id: string;
  Tanda_Tangan: string;
  Tanda_Tangan_Pasien: string;
  Tanda_Tangan_Saksi: string;
  ID_Saksi: string;
  Nama_Saksi: string;
  Pasien_Kota: string;
  Pasien_Tanggal: string;
  Updated_At: string;
  Updated_By: string;
  Updated_By_Name: string;
  Tanda_Tangan_Nama: string;
  Tanda_Tangan_Tgl_Lahir: string;
  Tanda_Tangan_JK: string;
  Tanda_Tangan_Telp: string;
  Tanda_Tangan_Alamat: string;
  Tindakan_Operasi: string;
  ID_Petugas: string;
  Nama_Petugas: string;
  Nama_Saksi_Keluarga: string;
  Tanda_Tangan_Saksi_2: string;
  Tanda_Tangan_Hubungan: string;
}

export class ApprovalOrRefusalOfAnestheticActionFormModel {
  ID_Dokter_Pelaksana: string;
  Nama_Dokter_Pelaksana: string;
  ID_Pemberi_Informasi: string;
  Nama_Pemberi_Informasi: string;
  Penerima_Informasi: string;
  Diagnosis_Check: string;
  Dasar_Diagnosis_Check: string;
  Dasar_Klinis: string;
  Dasar_Radiologi: string;
  Dasar_EKG: string;
  Dasar_Laboratorium: string;
  Tindakan_Kedokteran_Check: string;
  Anestesi_Umum_Intubasi_Check: string;
  Anestesi_Umum_LMA_Check: string;
  Anestesi_Umum_FM_Check: string;
  Anestesi_Umum_TIVA_Check: string;
  Anestesi_Regional_Spinal_Check: string;
  Anestesi_Regional_Epidural_Check: string;
  Anestesi_Regional_Perifer_Check: string;
  Indikasi_Tindakan_Tujuan_Check: string;
  Tata_Cara_Tindakan_Check: string;
  Tata_Cara_Tindakan: string;
  Risiko_Check: string;
  Shock_Check: string;
  Henti_Jantung_Check: string;
  Meninggal_Check: string;
  Tujuan_Check: string;
  Tujuan: string;
  Komplikasi_Check: string;
  Komplikasi_Umum_1: string;
  Komplikasi_Umum_2: string;
  Komplikasi_Umum_3: string;
  Komplikasi_Umum_4: string;
  Komplikasi_Umum_5: string;
  Komplikasi_Umum_6: string;
  Komplikasi_Umum_7: string;
  Komplikasi_Umum_8: string;
  Komplikasi_Umum_9: string;
  Komplikasi_Umum_10: string;
  Komplikasi_Regional_1: string;
  Komplikasi_Regional_2: string;
  Komplikasi_Regional_3: string;
  Komplikasi_Regional_4: string;
  Komplikasi_Regional_5: string;
  Komplikasi_Regional_6: string;
  Komplikasi_Regional_7: string;
  Komplikasi_Regional_8: string;
  Komplikasi_Regional_9: string;
  Komplikasi_Regional_10: string;
  Komplikasi_Regional_11: string;
  Komplikasi_Regional_12: string;
  Prognosis_Check: string;
  Prognosis: string;
  Alternatif_Tindakan_Check: string;
  Alternatif_Tindakan: string;
  Lain_Lain_Check: string;
  Lain_Lain: string;
  ID_Dokter_Pelaksana_TTD: string;
  TTD_Dokter_Pelaksana: string;
  Nama_Dokter_Pelaksana_TTD: string;
  TTD_Penerima_Informasi: string;
  Waktu: string;
  Kota: string;
  Pernyataan_Id: string;
  Tanda_Tangan: string;
  Tanda_Tangan_Pasien: string;
  Tanda_Tangan_Saksi: string;
  ID_Saksi: string;
  Nama_Saksi: string;
  Pasien_Kota: string;
  Pasien_Tanggal: string;
  Updated_At: string;
  Updated_By: string;
  Updated_By_Name: string;
  Tanda_Tangan_Nama: string;
  Tanda_Tangan_Tgl_Lahir: string;
  Tanda_Tangan_JK: string;
  Tanda_Tangan_Telp: string;
  Tanda_Tangan_Alamat: string;
  Tindakan_Operasi: string;
  ID_Petugas: string;
  Nama_Petugas: string;
  Nama_Saksi_Keluarga: string;
  Tanda_Tangan_Saksi_2: string;
  Tanda_Tangan_Hubungan: string;
  constructor(request: IApprovalOrRefusalOfAnestheticActionFormModel) {
    this.ID_Dokter_Pelaksana = request.ID_Dokter_Pelaksana;
    this.Nama_Dokter_Pelaksana = request.Nama_Dokter_Pelaksana;
    this.ID_Pemberi_Informasi = request.ID_Pemberi_Informasi;
    this.Nama_Pemberi_Informasi = request.Nama_Pemberi_Informasi;
    this.Penerima_Informasi = request.Penerima_Informasi;
    this.Diagnosis_Check = request.Diagnosis_Check;
    this.Dasar_Diagnosis_Check = request.Dasar_Diagnosis_Check;
    this.Dasar_Klinis = request.Dasar_Klinis;
    this.Dasar_Radiologi = request.Dasar_Radiologi;
    this.Dasar_EKG = request.Dasar_EKG;
    this.Dasar_Laboratorium = request.Dasar_Laboratorium;
    this.Tindakan_Kedokteran_Check = request.Tindakan_Kedokteran_Check;
    this.Anestesi_Umum_Intubasi_Check = request.Anestesi_Umum_Intubasi_Check;
    this.Anestesi_Umum_LMA_Check = request.Anestesi_Umum_LMA_Check;
    this.Anestesi_Umum_FM_Check = request.Anestesi_Umum_FM_Check;
    this.Anestesi_Umum_TIVA_Check = request.Anestesi_Umum_TIVA_Check;
    this.Anestesi_Regional_Spinal_Check = request.Anestesi_Regional_Spinal_Check;
    this.Anestesi_Regional_Epidural_Check = request.Anestesi_Regional_Epidural_Check;
    this.Anestesi_Regional_Perifer_Check = request.Anestesi_Regional_Perifer_Check;
    this.Indikasi_Tindakan_Tujuan_Check = request.Indikasi_Tindakan_Tujuan_Check;
    this.Tata_Cara_Tindakan_Check = request.Tata_Cara_Tindakan_Check;
    this.Tata_Cara_Tindakan = request.Tata_Cara_Tindakan;
    this.Risiko_Check = request.Risiko_Check;
    this.Shock_Check = request.Shock_Check;
    this.Henti_Jantung_Check = request.Henti_Jantung_Check;
    this.Meninggal_Check = request.Meninggal_Check;
    this.Tujuan_Check = request.Tujuan_Check;
    this.Tujuan = request.Tujuan;
    this.Komplikasi_Check = request.Komplikasi_Check;
    this.Komplikasi_Umum_1 = request.Komplikasi_Umum_1;
    this.Komplikasi_Umum_2 = request.Komplikasi_Umum_2;
    this.Komplikasi_Umum_3 = request.Komplikasi_Umum_3;
    this.Komplikasi_Umum_4 = request.Komplikasi_Umum_4;
    this.Komplikasi_Umum_5 = request.Komplikasi_Umum_5;
    this.Komplikasi_Umum_6 = request.Komplikasi_Umum_6;
    this.Komplikasi_Umum_7 = request.Komplikasi_Umum_7;
    this.Komplikasi_Umum_8 = request.Komplikasi_Umum_8;
    this.Komplikasi_Umum_9 = request.Komplikasi_Umum_9;
    this.Komplikasi_Umum_10 = request.Komplikasi_Umum_10;
    this.Komplikasi_Regional_1 = request.Komplikasi_Regional_1;
    this.Komplikasi_Regional_2 = request.Komplikasi_Regional_2;
    this.Komplikasi_Regional_3 = request.Komplikasi_Regional_3;
    this.Komplikasi_Regional_4 = request.Komplikasi_Regional_4;
    this.Komplikasi_Regional_5 = request.Komplikasi_Regional_5;
    this.Komplikasi_Regional_6 = request.Komplikasi_Regional_6;
    this.Komplikasi_Regional_7 = request.Komplikasi_Regional_7;
    this.Komplikasi_Regional_8 = request.Komplikasi_Regional_8;
    this.Komplikasi_Regional_9 = request.Komplikasi_Regional_9;
    this.Komplikasi_Regional_10 = request.Komplikasi_Regional_10;
    this.Komplikasi_Regional_11 = request.Komplikasi_Regional_11;
    this.Komplikasi_Regional_12 = request.Komplikasi_Regional_12;
    this.Prognosis_Check = request.Prognosis_Check;
    this.Prognosis = request.Prognosis;
    this.Alternatif_Tindakan_Check = request.Alternatif_Tindakan_Check;
    this.Alternatif_Tindakan = request.Alternatif_Tindakan;
    this.Lain_Lain_Check = request.Lain_Lain_Check;
    this.Lain_Lain = request.Lain_Lain;
    this.ID_Dokter_Pelaksana_TTD = request.ID_Dokter_Pelaksana_TTD;
    this.TTD_Dokter_Pelaksana = request.TTD_Dokter_Pelaksana;
    this.Nama_Dokter_Pelaksana_TTD = request.Nama_Dokter_Pelaksana_TTD;
    this.TTD_Penerima_Informasi = request.TTD_Penerima_Informasi;
    this.Waktu = request.Waktu;
    this.Kota = request.Kota;
    this.Pernyataan_Id = request.Pernyataan_Id;
    this.Tanda_Tangan = request.Tanda_Tangan;
    this.Tanda_Tangan_Pasien = request.Tanda_Tangan_Pasien;
    this.Tanda_Tangan_Saksi = request.Tanda_Tangan_Saksi;
    this.ID_Saksi = request.ID_Saksi;
    this.Nama_Saksi = request.Nama_Saksi;
    this.Pasien_Kota = request.Pasien_Kota;
    this.Pasien_Tanggal = request.Pasien_Tanggal;
    this.Updated_At = request.Updated_At;
    this.Updated_By = request.Updated_By;
    this.Updated_By_Name = request.Updated_By_Name;
    this.Tanda_Tangan_Nama = request.Tanda_Tangan_Nama;
    this.Tanda_Tangan_Tgl_Lahir = request.Tanda_Tangan_Tgl_Lahir;
    this.Tanda_Tangan_JK = request.Tanda_Tangan_JK;
    this.Tanda_Tangan_Telp = request.Tanda_Tangan_Telp;
    this.Tanda_Tangan_Alamat = request.Tanda_Tangan_Alamat;
    this.Tindakan_Operasi = request.Tindakan_Operasi;
    this.ID_Petugas = request.ID_Petugas;
    this.Nama_Petugas = request.Nama_Petugas;
    this.Nama_Saksi_Keluarga = request.Nama_Saksi_Keluarga;
    this.Tanda_Tangan_Saksi_2 = request.Tanda_Tangan_Saksi_2;
    this.Tanda_Tangan_Hubungan = request.Tanda_Tangan_Hubungan;
  }

  static createFromJson(json: IApprovalOrRefusalOfAnestheticActionFormModel) {
    return new ApprovalOrRefusalOfAnestheticActionFormModel(json);
  }
}

export interface IApprovalOrRefusalOfAnestheticActionModel extends IDataModel {
  form: IApprovalOrRefusalOfAnestheticActionFormModel;
}

export class ApprovalOrRefusalOfAnestheticActionModel extends DataModel {
  form?: IApprovalOrRefusalOfAnestheticActionFormModel;
  rawat_inap: any;
  constructor(request: IApprovalOrRefusalOfAnestheticActionModel) {
    super(request);
    // if (request.form) {
    this.form = request.form;
    // }
  }
}
