import { DataModel, IDataModel } from "@src/shared/model";

export interface IHaisSurveillanceInfectionFormDetail {
  Ruangan_Hais: string;
  Tanggal_Berobat: string;
  Diagnosa_Masuk: string;
  Asal_Masuk: string;
  Vena_Sentral_Check: string;
  Vena_Perifer_Check: string;
  Lokasi_VS: string;
  Mulai_VS: string;
  Selesai_VS: string;
  Total_Hari_VS: string;
  Tanggal_Infeksi_VS: string;
  Catatan_VS: string;
  Lokasi_VP: string;
  Mulai_VP: string;
  Selesai_VP: string;
  Total_Hari_VP: string;
  Tanggal_Infeksi_VP: string;
  Catatan_VP: string;
  Tindakan_Alkes_Lain: string;
  Lokasi_Lain: string;
  Mulai_Lain: string;
  Selesai_Lain: string;
  Total_Hari_Lain: string;
  Tanggal_Infeksi_Lain: string;
  Catatan_Lain: string;
  HBS_Ag: string;
  Anti_HCV: string;
  Anti_HIV: string;
  Faktor_Penyakit_Lain: string;
  Lab_Leukocyt: string;
  Lab_LED: string;
  Lab_Lain: string;
  Hasil_Radiologi: string;
  Merokok: string;
  Steroid_Jangka_Panjang: string;
  Mandi_Sebelum_Operasi: string;
  Operasi_Karena_Trauma: string;
  Obat_Pengencer_Darah: string;
  Memakai_Make_Up: string;
  Gula_Darah: string
  Suhu_Pasien: string;
  Infeksi_Mata_Check: string;
  Infeksi_THT_Check: string;
  Infeksi_Mulut_Check: string;
  Infeksi_Paru_Check: string;
  Infeksi_Kulit_Check: string;
  Infeksi_GI_Check: string;
  Infeksi_Lainnya_Check: string;
  Infeksi_Lainnya_Text: string;
  Penyakit_DM_Check: string;
  Penyakit_Hipertensi_Check: string;
  Penyakit_GGK_Check: string;
  Penyakit_Sepsis_Check: string;
  Riwayat_Pasien_Sekarang: string;
  Jenis_Operasi: string;
  ASA_Score: string;
  Jenis_Anestesi: string;
  Operator_Anestesi: string;
  Kelembapan_Udara: string;
  Suhu_Ruangan: string;
  Komplikasi_Saat_Operasi: string;
  Profilaksis: string;
  Obat_Profilaksis: string;
  Antibiotik_Tambahan: string;
  Obat_Antibiotik: string;
  Dosis_Antibiotik: string;
  Jam_Diberikan_Antibiotik: string;
  Probe_Laser: string;
  Tubing_Vitrectomy: string;
  Chlorhexidine_Check: string;
  Povidone_Iodine_Check: string;
  Alkohol_70_Check: string;
  Jahitan: string;
  Indikator_Instrumen: string;
  Sterilisasi_CSSD: string;
  Inisial_Dr: string;
  Asisten_Op: string;
  Urutan_Op: string;
  Implant: string;
  Lama_Op: string;
  Ruang_Operasi: string;
  Klasifikasi_Luka: string;
  Prosedur_Op: string;
  Kualifikasi_Dokter_Bedah: string;
  Jumlah_Staf: string;
  Diagnosa_Akhir: string;
  Tanggal_Pasien_Keluar: string;
  Cara_Pasien_Keluar: string;
  Nama_Pindah_Faskes: string;
  ID_Perawat: string;
  TTD_Perawat: string;
  Nama_Perawat: string;
  ID_Perawat_IPCN: string;
  TTD_Perawat_IPCN: string;
  Nama_Perawat_IPCN: string;
  Updated_At: string;
  Updated_By: string;
  ID_Petugas: string;
  Nama_Petugas: string;
}

export class HaisSurveillanceInfectionFormDetail {
  Ruangan_Hais: string;
  Tanggal_Berobat: string;
  Diagnosa_Masuk: string;
  Asal_Masuk: string;
  Vena_Sentral_Check: string;
  Vena_Perifer_Check: string;
  Lokasi_VS: string;
  Mulai_VS: string;
  Selesai_VS: string;
  Total_Hari_VS: string;
  Tanggal_Infeksi_VS: string;
  Catatan_VS: string;
  Lokasi_VP: string;
  Mulai_VP: string;
  Selesai_VP: string;
  Total_Hari_VP: string;
  Tanggal_Infeksi_VP: string;
  Catatan_VP: string;
  Tindakan_Alkes_Lain: string;
  Lokasi_Lain: string;
  Mulai_Lain: string;
  Selesai_Lain: string;
  Total_Hari_Lain: string;
  Tanggal_Infeksi_Lain: string;
  Catatan_Lain: string;
  HBS_Ag: string;
  Anti_HCV: string;
  Anti_HIV: string;
  Faktor_Penyakit_Lain: string;
  Lab_Leukocyt: string;
  Lab_LED: string;
  Lab_Lain: string;
  Hasil_Radiologi: string;
  Merokok: string;
  Steroid_Jangka_Panjang: string;
  Mandi_Sebelum_Operasi: string;
  Operasi_Karena_Trauma: string;
  Obat_Pengencer_Darah: string;
  Memakai_Make_Up: string;
  Gula_Darah: string
  Suhu_Pasien: string;
  Infeksi_Mata_Check: string;
  Infeksi_THT_Check: string;
  Infeksi_Mulut_Check: string;
  Infeksi_Paru_Check: string;
  Infeksi_Kulit_Check: string;
  Infeksi_GI_Check: string;
  Infeksi_Lainnya_Check: string;
  Infeksi_Lainnya_Text: string;
  Penyakit_DM_Check: string;
  Penyakit_Hipertensi_Check: string;
  Penyakit_GGK_Check: string;
  Penyakit_Sepsis_Check: string;
  Riwayat_Pasien_Sekarang: string;
  Jenis_Operasi: string;
  ASA_Score: string;
  Jenis_Anestesi: string;
  Operator_Anestesi: string;
  Kelembapan_Udara: string;
  Suhu_Ruangan: string;
  Komplikasi_Saat_Operasi: string;
  Profilaksis: string;
  Obat_Profilaksis: string;
  Antibiotik_Tambahan: string;
  Obat_Antibiotik: string;
  Dosis_Antibiotik: string;
  Jam_Diberikan_Antibiotik: string;
  Probe_Laser: string;
  Tubing_Vitrectomy: string;
  Chlorhexidine_Check: string;
  Povidone_Iodine_Check: string;
  Alkohol_70_Check: string;
  Jahitan: string;
  Indikator_Instrumen: string;
  Sterilisasi_CSSD: string;
  Inisial_Dr: string;
  Asisten_Op: string;
  Urutan_Op: string;
  Implant: string;
  Lama_Op: string;
  Ruang_Operasi: string;
  Klasifikasi_Luka: string;
  Prosedur_Op: string;
  Kualifikasi_Dokter_Bedah: string;
  Jumlah_Staf: string;
  Diagnosa_Akhir: string;
  Tanggal_Pasien_Keluar: string;
  Cara_Pasien_Keluar: string;
  Nama_Pindah_Faskes: string;
  ID_Perawat: string;
  TTD_Perawat: string;
  Nama_Perawat: string;
  ID_Perawat_IPCN: string;
  TTD_Perawat_IPCN: string;
  Nama_Perawat_IPCN: string;
  Updated_At: string;
  Updated_By: string;
  ID_Petugas: string;
  Nama_Petugas: string;

  constructor(req: IHaisSurveillanceInfectionFormDetail) {
    this.Ruangan_Hais = req.Ruangan_Hais;
    this.Tanggal_Berobat = req.Tanggal_Berobat;
    this.Diagnosa_Masuk = req.Diagnosa_Masuk;
    this.Asal_Masuk = req.Asal_Masuk;
    this.Vena_Sentral_Check = req.Vena_Sentral_Check;
    this.Vena_Perifer_Check = req.Vena_Perifer_Check;
    this.Lokasi_VS = req.Lokasi_VS;
    this.Mulai_VS = req.Mulai_VS;
    this.Selesai_VS = req.Selesai_VS;
    this.Total_Hari_VS = req.Total_Hari_VS;
    this.Tanggal_Infeksi_VS = req.Tanggal_Infeksi_VS;
    this.Catatan_VS = req.Catatan_VS;
    this.Lokasi_VP = req.Lokasi_VP;
    this.Mulai_VP = req.Mulai_VP;
    this.Selesai_VP = req.Selesai_VP;
    this.Total_Hari_VP = req.Total_Hari_VP;
    this.Tanggal_Infeksi_VP = req.Tanggal_Infeksi_VP;
    this.Catatan_VP = req.Catatan_VP;
    this.Tindakan_Alkes_Lain = req.Tindakan_Alkes_Lain;
    this.Lokasi_Lain = req.Lokasi_Lain;
    this.Mulai_Lain = req.Mulai_Lain;
    this.Selesai_Lain = req.Selesai_Lain;
    this.Total_Hari_Lain = req.Total_Hari_Lain;
    this.Tanggal_Infeksi_Lain = req.Tanggal_Infeksi_Lain;
    this.Catatan_Lain = req.Catatan_Lain;
    this.HBS_Ag = req.HBS_Ag;
    this.Anti_HCV = req.Anti_HCV;
    this.Anti_HIV = req.Anti_HIV;
    this.Faktor_Penyakit_Lain = req.Faktor_Penyakit_Lain;
    this.Lab_Leukocyt = req.Lab_Leukocyt;
    this.Lab_LED = req.Lab_LED;
    this.Lab_Lain = req.Lab_Lain;
    this.Hasil_Radiologi = req.Hasil_Radiologi;
    this.Merokok = req.Merokok;
    this.Steroid_Jangka_Panjang = req.Steroid_Jangka_Panjang;
    this.Mandi_Sebelum_Operasi = req.Mandi_Sebelum_Operasi;
    this.Operasi_Karena_Trauma = req.Operasi_Karena_Trauma;
    this.Obat_Pengencer_Darah = req.Obat_Pengencer_Darah;
    this.Memakai_Make_Up = req.Memakai_Make_Up
    this.Gula_Darah = req.Gula_Darah;
    this.Suhu_Pasien = req.Suhu_Pasien;
    this.Infeksi_Mata_Check = req.Infeksi_Mata_Check;
    this.Infeksi_THT_Check = req.Infeksi_THT_Check;
    this.Infeksi_Mulut_Check = req.Infeksi_Mulut_Check;
    this.Infeksi_Paru_Check = req.Infeksi_Paru_Check;
    this.Infeksi_Kulit_Check = req.Infeksi_Kulit_Check;
    this.Infeksi_GI_Check = req.Infeksi_GI_Check;
    this.Infeksi_Lainnya_Check = req.Infeksi_Lainnya_Check;
    this.Infeksi_Lainnya_Text = req.Infeksi_Lainnya_Text;
    this.Penyakit_DM_Check = req.Penyakit_DM_Check;
    this.Penyakit_Hipertensi_Check = req.Penyakit_Hipertensi_Check;
    this.Penyakit_GGK_Check = req.Penyakit_GGK_Check;
    this.Penyakit_Sepsis_Check = req.Penyakit_Sepsis_Check;
    this.Riwayat_Pasien_Sekarang = req.Riwayat_Pasien_Sekarang;
    this.Jenis_Operasi = req.Jenis_Operasi;
    this.ASA_Score = req.ASA_Score;
    this.Jenis_Anestesi = req.Jenis_Anestesi;
    this.Operator_Anestesi = req.Operator_Anestesi;
    this.Kelembapan_Udara = req.Kelembapan_Udara;
    this.Suhu_Ruangan = req.Suhu_Ruangan;
    this.Komplikasi_Saat_Operasi = req.Komplikasi_Saat_Operasi;
    this.Profilaksis = req.Profilaksis;
    this.Obat_Profilaksis = req.Obat_Profilaksis;
    this.Antibiotik_Tambahan = req.Antibiotik_Tambahan;
    this.Obat_Antibiotik = req.Obat_Antibiotik;
    this.Dosis_Antibiotik = req.Dosis_Antibiotik;
    this.Jam_Diberikan_Antibiotik = req.Jam_Diberikan_Antibiotik;
    this.Probe_Laser = req.Probe_Laser;
    this.Tubing_Vitrectomy = req.Tubing_Vitrectomy;
    this.Chlorhexidine_Check = req.Chlorhexidine_Check;
    this.Povidone_Iodine_Check = req.Povidone_Iodine_Check;
    this.Alkohol_70_Check = req.Alkohol_70_Check;
    this.Jahitan = req.Jahitan;
    this.Indikator_Instrumen = req.Indikator_Instrumen;
    this.Sterilisasi_CSSD = req.Sterilisasi_CSSD;
    this.Inisial_Dr = req.Inisial_Dr;
    this.Asisten_Op = req.Asisten_Op;
    this.Urutan_Op = req.Urutan_Op;
    this.Implant = req.Implant;
    this.Lama_Op = req.Lama_Op;
    this.Ruang_Operasi = req.Ruang_Operasi;
    this.Klasifikasi_Luka = req.Klasifikasi_Luka;
    this.Prosedur_Op = req.Prosedur_Op;
    this.Kualifikasi_Dokter_Bedah = req.Kualifikasi_Dokter_Bedah;
    this.Jumlah_Staf = req.Jumlah_Staf;
    this.Diagnosa_Akhir = req.Diagnosa_Akhir;
    this.Tanggal_Pasien_Keluar = req.Tanggal_Pasien_Keluar;
    this.Cara_Pasien_Keluar = req.Cara_Pasien_Keluar;
    this.Nama_Pindah_Faskes = req.Nama_Pindah_Faskes;
    this.ID_Perawat = req.ID_Perawat;
    this.TTD_Perawat = req.TTD_Perawat;
    this.Nama_Perawat = req.Nama_Perawat;
    this.ID_Perawat_IPCN = req.ID_Perawat_IPCN;
    this.TTD_Perawat_IPCN = req.TTD_Perawat_IPCN;
    this.Nama_Perawat_IPCN = req.Nama_Perawat_IPCN;
    this.Updated_At = req.Updated_At;
    this.Updated_By = req.Updated_By;
    this.ID_Petugas = req.ID_Petugas;
    this.Nama_Petugas = req.Nama_Petugas;
  }

  static createFromJson(json: IHaisSurveillanceInfectionFormDetail) {
    return new HaisSurveillanceInfectionFormDetail(json);
  }
}

export interface IHaisSurveillanceInfectionForm extends IDataModel {
  form: IHaisSurveillanceInfectionFormDetail;
}

export class HaisSurveillanceInfectionForm extends DataModel {
  form?: HaisSurveillanceInfectionFormDetail;

  constructor(req: IHaisSurveillanceInfectionForm) {
    super(req);
    if (req.form) {
      this.form = new HaisSurveillanceInfectionFormDetail(req.form);
    }
  }
}
