import { DateTimeConverter } from "@src/shared/datetime-converter";
import { CreatePDFRequest,  ICreatePDFRequest } from "@src/shared/pdf/requests/create-pdf.request";

export interface IPdfDischargePlanningRequest extends  ICreatePDFRequest {
  data: {
    nomor_mr: string,
    'pasien.Nama': string,
    'pasien.Tgl_Lahir':  string,
    'pasien.Umur': string,
    'pasien.Jenis_Kelamin': string,
    diagnosa_medis: string,
    dpjp: string,
    date_time_in_rs: string,
    alsan_masuk_rs: string,
    date_time_discharge_planning: string,
    estimasi_tgl_pulang: string,
    nama_perawat: string,
    pengaruh_ranap_pasien_ya: string,
    pengaruh_ranap_pasien_tidak: string,
    pengaruh_ranap_pekerjaan_ya: string,
    pengaruh_ranap_pekerjaan_tidak: string,
    pengaruh_ranap_keuangan_ya: string,
    pengaruh_ranap_keuangan_tidak: string,
    antisipasi_masalah_ya: string,
    antisipasi_masalah_tidak: string,
    Penjelasan_antisipasi_masalah: string,
    bantuan_diperlukan_1: string,
    bantuan_diperlukan_2: string,
    bantuan_diperlukan_3: string,
    bantuan_diperlukan_4: string,
    bantuan_diperlukan_5: string,
    bantuan_diperlukan_6: string,
    bantuan_diperlukan_7: string,
    bantuan_diperlukan_8: string,
    hambatan_pembelajaran_tidak: string,
    hambatan_pembelajaran_ya: string,
    penjelasan_membantu_keperluan_diatas: string,
    tinggal_sendiri_tidak: string,
    tinggal_sendiri_ya: string,
    orang_yg_merawat: string,
    peralatan_medis_tidak: string,
    peralatan_medis_ya: string,
    peralatan_medis_dirumah: string,
    alat_bantu_tidak: string,
    alat_bantu_ya: string,
    alat_bantu_dirumah: string,
    bantuan_khusus_tidak: string,
    bantuan_khusus_ya: string,
    bantuan_khusus_dirumah: string,
    kebutuhan_pribadi_dirumah_tidak: string,
    kebutuhan_pribadi_dirumah_ya: string,
    kebutuhan_pribadi_dirumah: string,
    nyeri_kronis_tidak: string,
    nyeri_kronis_ya: string,
    nyeri_kronis: string,
    edukasi_kesehatan_tidak: string,
    edukasi_kesehatan_ya: string,
    edukasi_keseharan_dirumah: string,
    keterampilan_khusus_dirumah_tidak: string,
    keterampilan_khusus_dirumah_ya: string,
    keterampilan_khusus_dirumah: string,
    jadwal_kontrol_tidak: string,
    jadwal_kontrol_ya: string,
    jadwal_kontrol_ket: string,
    obat_pulang: string,
    date_obat: string,
    time_obat: string,
    ket_obat: string,
    surat_kontrol: string,
    date_surkon: string,
    time_surkon: string,
    ket_surkon: string,
    Tanda_Tangan_Perawat_pengkaji: string,
    'form.Nama_Perawat_pengkaji': string,
    Tanda_Tangan_Pasien: string,
    'form.Nama_pasien': string,
    nik: string,
  }
}

export class PdfDischargePlanningRequest extends CreatePDFRequest {
  data: {
    nomor_mr: string,
    'pasien.Nama': string,
    'pasien.Tgl_Lahir':  string,
    'pasien.Umur': string,
    'pasien.Jenis_Kelamin': string,
    diagnosa_medis: string,
    dpjp: string,
    date_time_in_rs: string,
    alsan_masuk_rs: string,
    date_time_discharge_planning: string,
    estimasi_tgl_pulang: string,
    nama_perawat: string,
    pengaruh_ranap_pasien_ya: string,
    pengaruh_ranap_pasien_tidak: string,
    pengaruh_ranap_pekerjaan_ya: string,
    pengaruh_ranap_pekerjaan_tidak: string,
    pengaruh_ranap_keuangan_ya: string,
    pengaruh_ranap_keuangan_tidak: string,
    antisipasi_masalah_ya: string,
    antisipasi_masalah_tidak: string,
    Penjelasan_antisipasi_masalah: string,
    bantuan_diperlukan_1: string,
    bantuan_diperlukan_2: string,
    bantuan_diperlukan_3: string,
    bantuan_diperlukan_4: string,
    bantuan_diperlukan_5: string,
    bantuan_diperlukan_6: string,
    bantuan_diperlukan_7: string,
    bantuan_diperlukan_8: string,
    hambatan_pembelajaran_tidak: string,
    hambatan_pembelajaran_ya: string,
    penjelasan_membantu_keperluan_diatas: string,
    tinggal_sendiri_tidak: string,
    tinggal_sendiri_ya: string,
    orang_yg_merawat: string,
    peralatan_medis_tidak: string,
    peralatan_medis_ya: string,
    peralatan_medis_dirumah: string,
    alat_bantu_tidak: string,
    alat_bantu_ya: string,
    alat_bantu_dirumah: string,
    bantuan_khusus_tidak: string,
    bantuan_khusus_ya: string,
    bantuan_khusus_dirumah: string,
    kebutuhan_pribadi_dirumah_tidak: string,
    kebutuhan_pribadi_dirumah_ya: string,
    kebutuhan_pribadi_dirumah: string,
    nyeri_kronis_tidak: string,
    nyeri_kronis_ya: string,
    nyeri_kronis: string,
    edukasi_kesehatan_tidak: string,
    edukasi_kesehatan_ya: string,
    edukasi_keseharan_dirumah: string,
    keterampilan_khusus_dirumah_tidak: string,
    keterampilan_khusus_dirumah_ya: string,
    keterampilan_khusus_dirumah: string,
    jadwal_kontrol_tidak: string,
    jadwal_kontrol_ya: string,
    jadwal_kontrol_ket: string,
    obat_pulang: string,
    date_obat: string,
    time_obat: string,
    ket_obat: string,
    surat_kontrol: string,
    date_surkon: string,
    time_surkon: string,
    ket_surkon: string,
    Tanda_Tangan_Perawat_pengkaji: string,
    'form.Nama_Perawat_pengkaji': string,
    Tanda_Tangan_Pasien: string,
    'form.Nama_pasien': string,
    nik: string,
  }

  constructor(req: IPdfDischargePlanningRequest) {
    super(req);
    this.data = req.data;
  }

  static createPdfRequest(val: any, emrId: string): PdfDischargePlanningRequest {
    return new PdfDischargePlanningRequest({
      emr_id: emrId,
      form_name: 'rawat-inap_rencana-pemulangan-pasien',
      row_filter: '',
      preview: false,
      data: {
        nomor_mr: val?.nomor_mr ?? '',
        'pasien.Nama': val?.pasien?.Nama ?? '',
        'pasien.Tgl_Lahir': DateTimeConverter.convertToNormalDate(val?.pasien?.Tgl_Lahir),
        'pasien.Umur': this.normalizeAge(val?.umur_lengkap),
        'pasien.Jenis_Kelamin': val?.pasien?.Jenis_Kelamin ?? '',
        diagnosa_medis: val?.form?.Pasien_Diagnosa_Medis ?? '',
        dpjp:  val?.form?.Nama_Dokter_DPJP ?? '',
        date_time_in_rs: DateTimeConverter.convertToDateTime(val?.form?.Pasien_Tanggal),
        alsan_masuk_rs: val?.form?.Pasien_Alasan ?? '',
        date_time_discharge_planning: DateTimeConverter.convertToDateTime(val?.form?.Waktu_Discharge),
        estimasi_tgl_pulang: DateTimeConverter.convertToDateTime(val?.form?.Estimasi_Pemulangan_Pasien),
        nama_perawat: val?.form?.Pasien_Perawat_Nama ?? '',
        pengaruh_ranap_pasien_ya: PdfDischargePlanningRequest.getCheckImage(val?.form?.Pengaruh_Keluarga === '1'),
        pengaruh_ranap_pasien_tidak: PdfDischargePlanningRequest.getCheckImage(val?.form?.Pengaruh_Keluarga === '0'),
        pengaruh_ranap_pekerjaan_ya: PdfDischargePlanningRequest.getCheckImage(val?.form?.Pengaruh_Pekerjaan === '1'),
        pengaruh_ranap_pekerjaan_tidak: PdfDischargePlanningRequest.getCheckImage(val?.form?.Pengaruh_Pekerjaan === '0'),
        pengaruh_ranap_keuangan_ya: PdfDischargePlanningRequest.getCheckImage(val?.form?.Pengaruh_Keuangan === '1'),
        pengaruh_ranap_keuangan_tidak: PdfDischargePlanningRequest.getCheckImage(val?.form?.Pengaruh_Keuangan === '0'),
        antisipasi_masalah_ya: PdfDischargePlanningRequest.getCheckImage(val?.form?.Antisipasi_Pulang === '1'),
        antisipasi_masalah_tidak: PdfDischargePlanningRequest.getCheckImage(val?.form?.Antisipasi_Pulang === '0'),
        Penjelasan_antisipasi_masalah: val?.form?.Antisipasi_Pulang_Keterangan ?? '',
        bantuan_diperlukan_1: PdfDischargePlanningRequest.getCheckImage(val?.form?.Bantuan?.Minum === 1),
        bantuan_diperlukan_2: PdfDischargePlanningRequest.getCheckImage(val?.form?.Bantuan?.Makan === 1),
        bantuan_diperlukan_3: PdfDischargePlanningRequest.getCheckImage(val?.form?.Bantuan?.Menyiapkan_Makanan === 1),
        bantuan_diperlukan_4: PdfDischargePlanningRequest.getCheckImage(val?.form?.Bantuan?.Edukasi === 1),
        bantuan_diperlukan_5: PdfDischargePlanningRequest.getCheckImage(val?.form?.Bantuan?.Mandi === 1),
        bantuan_diperlukan_6: PdfDischargePlanningRequest.getCheckImage(val?.form?.Bantuan?.Diet === 1),
        bantuan_diperlukan_7: PdfDischargePlanningRequest.getCheckImage(val?.form?.Bantuan?.Berpakaian === 1),
        bantuan_diperlukan_8: PdfDischargePlanningRequest.getCheckImage(val?.form?.Bantuan?.Transportasi === 1),
        hambatan_pembelajaran_tidak: PdfDischargePlanningRequest.getCheckImage(val?.form?.Membantu_Keperluan === '0'),
        hambatan_pembelajaran_ya: PdfDischargePlanningRequest.getCheckImage(val?.form?.Membantu_Keperluan === '1'),
        penjelasan_membantu_keperluan_diatas: val?.form?.Membantu_Keperluan_Keterangan ?? '',
        tinggal_sendiri_tidak: PdfDischargePlanningRequest.getCheckImage(val?.form?.Tinggal_Sendiri === '0'),
        tinggal_sendiri_ya: PdfDischargePlanningRequest.getCheckImage(val?.form?.Tinggal_Sendiri === '1'),
        orang_yg_merawat: val?.form?.Tinggal_Sendiri_Keterangan ?? '',
        peralatan_medis_tidak: PdfDischargePlanningRequest.getCheckImage(val?.form?.Peralatan_Sendiri === '0'),
        peralatan_medis_ya: PdfDischargePlanningRequest.getCheckImage(val?.form?.Peralatan_Sendiri === '1'),
        peralatan_medis_dirumah: val?.form?.Peralatan_Sendiri_Keterangan ?? '',
        alat_bantu_tidak: PdfDischargePlanningRequest.getCheckImage(val?.form?.Alat_Bantu_Sendiri === '0'),
        alat_bantu_ya: PdfDischargePlanningRequest.getCheckImage(val?.form?.Alat_Bantu_Sendiri === '1'),
        alat_bantu_dirumah: val?.form?.Alat_Bantu_Sendiri_Keterangan ?? '',
        bantuan_khusus_tidak: PdfDischargePlanningRequest.getCheckImage(val?.form?.Bantuan_Khusus === '0'),
        bantuan_khusus_ya: PdfDischargePlanningRequest.getCheckImage(val?.form?.Bantuan_Khusus === '1'),
        bantuan_khusus_dirumah: val?.form?.Bantuan_Khusus_Keterangan ?? '',
        kebutuhan_pribadi_dirumah_tidak: PdfDischargePlanningRequest.getCheckImage(val?.form?.Bantuan_Pribadi === '0'),
        kebutuhan_pribadi_dirumah_ya: PdfDischargePlanningRequest.getCheckImage(val?.form?.Bantuan_Pribadi === '1'),
        kebutuhan_pribadi_dirumah:  val?.form?.Bantuan_Pribadi_Keterangan ?? '',
        nyeri_kronis_tidak: PdfDischargePlanningRequest.getCheckImage(val?.form?.Nyeri_Kronis === '0'),
        nyeri_kronis_ya: PdfDischargePlanningRequest.getCheckImage(val?.form?.Nyeri_Kronis === '1'),
        nyeri_kronis: val?.form?.Nyeri_Kronis_Keterangan ?? '',
        edukasi_kesehatan_tidak: PdfDischargePlanningRequest.getCheckImage(val?.form?.Edukasi_Kesehatan === '0'),
        edukasi_kesehatan_ya: PdfDischargePlanningRequest.getCheckImage(val?.form?.Edukasi_Kesehatan === '1'),
        edukasi_keseharan_dirumah: val?.form?.Edukasi_Kesehatan_Keterangan ?? '',
        keterampilan_khusus_dirumah_tidak: PdfDischargePlanningRequest.getCheckImage(val?.form?.Keterampilan_Khusus === '0'),
        keterampilan_khusus_dirumah_ya: PdfDischargePlanningRequest.getCheckImage(val?.form?.Keterampilan_Khusus === '1'),
        keterampilan_khusus_dirumah: val?.form?.Keterampilan_Khusus_Keterangan ?? '',
        jadwal_kontrol_tidak: PdfDischargePlanningRequest.getCheckImage(val?.form?.Jadwal_Kontrol === '0'),
        jadwal_kontrol_ya: PdfDischargePlanningRequest.getCheckImage(val?.form?.Jadwal_Kontrol === '1'),
        jadwal_kontrol_ket: val?.form?.Jadwal_Kontrol_Keterangan ?? '',
        obat_pulang: PdfDischargePlanningRequest.getCheckImage(val?.form?.Obat_Pulang_Check === '1'),
        date_obat: DateTimeConverter.convertToNormalDate(val?.form?.Obat_Pulang_Waktu && val?.form?.Obat_Pulang_Waktu !== '' ? val?.form?.Obat_Pulang_Waktu.substring(0, 10) : ''),
        time_obat: val?.form?.Obat_Pulang_Waktu && val?.form?.Obat_Pulang_Waktu !== '' ? val?.form?.Obat_Pulang_Waktu.substring(11, 16) : '',
        ket_obat: val?.form?.Obat_Pulang_Keterangan ?? '',
        surat_kontrol: PdfDischargePlanningRequest.getCheckImage(val?.form?.Surat_Kontrol_Check === '1'),
        date_surkon: DateTimeConverter.convertToNormalDate(val?.form?.Surat_Kontrol_Waktu && val?.form?.Surat_Kontrol_Waktu !== '' ? val?.form?.Surat_Kontrol_Waktu.substring(0, 10) : ''),
        time_surkon: val?.form?.Surat_Kontrol_Waktu && val?.form?.Surat_Kontrol_Waktu !== '' ? val?.form?.Surat_Kontrol_Waktu.substring(11, 16) : '',
        ket_surkon: val?.form?.Surat_Kontrol_Keterangan ?? '',
        Tanda_Tangan_Perawat_pengkaji: (val?.form?.Tanda_Tangan_Perawat_Pengkaji !== '') ? val?.form?.Tanda_Tangan_Perawat_Pengkaji : undefined,
        'form.Nama_Perawat_pengkaji': (val?.form?.Nama_Perawat_Pengkaji !== '') ? val?.form?.Nama_Perawat_Pengkaji : undefined,
        Tanda_Tangan_Pasien: (val?.form?.Tanda_Tangan_Pasien !== '') ? val?.form?.Tanda_Tangan_Pasien : undefined,
        'form.Nama_pasien': val?.pasien?.Nama ?? '',
        nik: val?.pasien?.NIK ?? '',
      },
    })
  }
}