import { CreatePDFRequest, ICreatePDFRequest } from '@shared/pdf/requests/create-pdf.request';
import { PreAnesthesiaFormModel } from '@modules/inpatient/pre-anesthesia-form/models/pre-anesthesia-form.model';
import { DateTimeConverter } from '@src/shared/datetime-converter';

export interface IPdfPreAnesthesiaFormRequest extends ICreatePDFRequest {
  data: {
    nomor_mr: string;
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string,
    'pasien.Jenis_Kelamin': string,
    pekerjaan: string,
    banyak_rokok: string,
    banyak_ktc: string,
    banyak_alkohol: string,
    banyak_olga: string,
    obat_resep: string,
    obat_bebas: string,
    df_aspirin_plavix: string,
    df_anti_sakit: string,
    daftar_obat_reaksi: string,
    penjelasan_riwayat_keluarga: string,
    penjelasan_riwayat_pasien: string,
    tahun_tranfusi: string,
    tahun_hiv: string,
    pakai_lain_lain: string,
    riwayat_operasi: string,
    keluhan_reaksi_lokal: string,
    keluhan_reaksi_regional: string,
    keluhan_reaksi_umum: string,
    tempat_terakhir_periksa: string,
    gangguan_terakhir_periksa: string,
    tanggal_pengisian: string,
    keterangan_kajian_sistem: string,
    fisik_tinggi: string,
    fisik_berat: string,
    fisik_td: string,
    fisik_nadi: string,
    fisik_suhu: string,
    umum_skor_mallampati: string,
    umum_gigi_palsu: string,
    umum_jantung: string,
    umum_paru_paru: string,
    umum_abdomen: string,
    umum_tulang_belakang: string,
    umum_ekstremitas: string,
    umum_neurologi: string,
    umum_keterangan: string,
    lab_hbht: string,
    lab_pt: string,
    lab_glukosa: string,
    lab_kehamilan: string,
    lab_kalium: string,
    lab_ureum: string,
    lab_keterangan: string,
    lab_leukosit: string,
    lab_trombosit: string,
    lab_rontgen: string,
    lab_ekg: string,
    lab_nacl: string,
    lab_kreatinin: string,
    diagnosa_icdx: string,
    catatan_tindak_lanjut: string,
    keterangan_anestesi_lain: string,
    teknik_sedasi: string,
    teknik_ga: string,
    teknik_lain: string,
    monitoring_lain: string,
    alat_lain: string,
    jam_puasa_mulai: string,
    jam_pre_medikasi: string,
    jam_transportasi: string,
    jam_rencana_operasi: string,
    catatan_persiapan_pra_anestesi: string,
    nama_dokter_anestesi: string,
    tgl_terakhir_periksa: '',
    nama_pasien_wali: '',

    kelamin_lk: string,
    kelamin_pr: string,
    menikah_ya: string,
    menikah_tidak: string,
    merokok_tidak: string,
    merokok_ya: string,
    alkohol_tidak: string,
    alkohol_ya: string,
    ktc_tidak: string,
    ktc_ya: string,
    olga_tidak: string,
    olga_ya: string,
    aspirin_tidak: string,
    aspirin_ya: string,
    anti_sakit_tidak: string,
    anti_sakit_ya: string,
    alergi_obat_tidak: string,
    alergi_obat_ya: string,
    alergi_makanan_tidak: string,
    alergi_makanan_ya: string,

    pytn_tidak: string,
    pytn_ya: string,
    pdytn_tidak: string,
    pdytn_ya: string,
    pdp_tidak: string,
    pdp_ya: string,
    dtpo_tidak: string,
    dtpo_ya: string,
    diabetes_tidak: string,
    diabetes_ya: string,
    sj_tidak: string,
    sj_ya: string,
    gij_tidak: string,
    gij_ya: string,
    hipertensi_tidak: string,
    hipertensi_ya: string,
    tuberkolosis_tidak: string,
    tuberkolosis_ya: string,
    berat_lain_tidak: string,
    berat_lain_ya: string,

    pytn_pasien_tidak: string,
    pytn_pasien_ya: string,
    pdytn_pasien_tidak: string,
    pdytn_pasien_ya: string,
    maag_tidak: string,
    maag_ya: string,
    anemia_tidak: string,
    anemia_ya: string,
    nyeri_dada_tidak: string,
    nyeri_dada_ya: string,
    asma_tidak: string,
    asma_ya: string,
    diabetes_pasien_tidak: string,
    diabetes_pasien_ya: string,
    pingsan_tidak: string,
    pingsan_ya: string,
    mengorok_tidak: string,
    mengorok_ya: string,
    hepatitis_tidak: string,
    hepatitis_ya: string,
    hipertensi_pasien_tidak: string,
    hipertensi_pasien_ya: string,
    berat_pasien_tidak: string,
    berat_pasien_ya: string,
    kejang_tidak: string,
    kejang_ya: string,
    penyakit_bawaan_tidak: string,
    penyakit_bawaan_ya: string,

    tranfusi_darah_tidak: string,
    tranfusi_darah_ya: string,
    diagnosis_hiv_tidak: string,
    diagnosis_hiv_ya: string,
    hasil_hiv_positif: string,
    hasil_hiv_negatif: string,
    pakai_lensa_kontak: string,
    pakai_kacamata: string,
    pakai_alat_bantu_dengar: string,
    pakai_gigi_palsu: string,
    pakai_lainnya: string,
    riwayat_anestesia_lokal: string,
    riwayat_anestesia_regional: string,
    riwayat_anestesia_umum: string,

    hilang_gigi_tidak: string,
    hilang_gigi_ya: string,
    mobilisasi_lahir_tidak: string,
    mobilisasi_lahir_ya: string,
    leher_pendek_tidak: string,
    leher_pendek_ya: string,
    batuk_tidak: string,
    batuk_ya: string,
    sesak_napas_tidak: string,
    sesak_napas_ya: string,
    baru_ispa_tidak: string,
    baru_ispa_ya: string,
    sakit_dada_tidak: string,
    sakit_dada_ya: string,
    denyut_jantung_tidak: string,
    denyut_jantung_ya: string,

    muntah_tidak: string,
    muntah_ya: string,
    // pingsan_tidak: string,
    // pingsan_ya: string,
    stroke_tidak: string,
    stroke_ya: string,
    // kejang_tidak: string,
    // kejang_ya: string,
    sedang_hamil_tidak: string,
    sedang_hamil_ya: string,
    tulang_belakang_tidak: string,
    tulang_belakang_ya: string,
    obesitas_tidak: string,
    obesitas_ya: string,

    asa_classification_1: string,
    asa_classification_2: string,
    asa_classification_3: string,
    asa_classification_4: string,

    tanda_1: string,
    tanda_2: string,

    rencana_teknik_sedasi: string,
    rencana_teknik_ga: string,
    rencana_teknik_lain: string,
    teknik_khusus_1: string,
    teknik_khusus_2: string,
    teknik_khusus_3: string,
    teknik_khusus_4: string,
    teknik_khusus_5: string,
    monitoring_1: string,
    monitoring_2: string,
    monitoring_3: string,
    monitoring_4: string,
    monitoring_5: string,
    monitoring_6: string,
    monitoring_7: string,
    monitoring_8: string,
    monitoring_9: string,
    alat_khusus_1: string,
    alat_khusus_2: string,
    alat_khusus_3: string,
    alat_khusus_4: string,
    alat_khusus_5: string,

    ttd_pasien_wali?: string,
    ttd_dokter_anestesi?: string,
    tanggal_puasa_mulai: string,
    tanggal_pre_medikasi: string,
    tanggal_transportasi: string,
    tanggal_rencana_operasi: string,
    nik: string,
  }
}

export class PdfPreAnesthesiaFormRequest extends CreatePDFRequest {
  data: {
    nomor_mr: string;
    'pasien.Nama': string;
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string,
    'pasien.Jenis_Kelamin': string,
    pekerjaan: string,
    banyak_rokok: string,
    banyak_ktc: string,
    banyak_alkohol: string,
    banyak_olga: string,
    obat_resep: string,
    obat_bebas: string,
    df_aspirin_plavix: string,
    df_anti_sakit: string,
    daftar_obat_reaksi: string,
    penjelasan_riwayat_keluarga: string,
    penjelasan_riwayat_pasien: string,
    tahun_tranfusi: string,
    tahun_hiv: string,
    pakai_lain_lain: string,
    riwayat_operasi: string,
    keluhan_reaksi_lokal: string,
    keluhan_reaksi_regional: string,
    keluhan_reaksi_umum: string,
    tempat_terakhir_periksa: string,
    gangguan_terakhir_periksa: string,
    tanggal_pengisian: string,
    keterangan_kajian_sistem: string,
    fisik_tinggi: string,
    fisik_berat: string,
    fisik_td: string,
    fisik_nadi: string,
    fisik_suhu: string,
    umum_skor_mallampati: string,
    umum_gigi_palsu: string,
    umum_jantung: string,
    umum_paru_paru: string,
    umum_abdomen: string,
    umum_tulang_belakang: string,
    umum_ekstremitas: string,
    umum_neurologi: string,
    umum_keterangan: string,
    lab_hbht: string,
    lab_pt: string,
    lab_glukosa: string,
    lab_kehamilan: string,
    lab_kalium: string,
    lab_ureum: string,
    lab_keterangan: string,
    lab_leukosit: string,
    lab_trombosit: string,
    lab_rontgen: string,
    lab_ekg: string,
    lab_nacl: string,
    lab_kreatinin: string,
    diagnosa_icdx: string,
    catatan_tindak_lanjut: string,
    keterangan_anestesi_lain: string,
    teknik_sedasi: string,
    teknik_ga: string,
    teknik_lain: string,
    monitoring_lain: string,
    alat_lain: string,
    jam_puasa_mulai: string,
    jam_pre_medikasi: string,
    jam_transportasi: string,
    jam_rencana_operasi: string,
    catatan_persiapan_pra_anestesi: string,
    nama_dokter_anestesi: string,
    tgl_terakhir_periksa: '',
    nama_pasien_wali: '',

    kelamin_lk: string,
    kelamin_pr: string,
    menikah_ya: string,
    menikah_tidak: string,
    merokok_tidak: string,
    merokok_ya: string,
    alkohol_tidak: string,
    alkohol_ya: string,
    ktc_tidak: string,
    ktc_ya: string,
    olga_tidak: string,
    olga_ya: string,
    aspirin_tidak: string,
    aspirin_ya: string,
    anti_sakit_tidak: string,
    anti_sakit_ya: string,
    alergi_obat_tidak: string,
    alergi_obat_ya: string,
    alergi_makanan_tidak: string,
    alergi_makanan_ya: string,

    pytn_tidak: string,
    pytn_ya: string,
    pdytn_tidak: string,
    pdytn_ya: string,
    pdp_tidak: string,
    pdp_ya: string,
    dtpo_tidak: string,
    dtpo_ya: string,
    diabetes_tidak: string,
    diabetes_ya: string,
    sj_tidak: string,
    sj_ya: string,
    gij_tidak: string,
    gij_ya: string,
    hipertensi_tidak: string,
    hipertensi_ya: string,
    tuberkolosis_tidak: string,
    tuberkolosis_ya: string,
    berat_lain_tidak: string,
    berat_lain_ya: string,

    pytn_pasien_tidak: string,
    pytn_pasien_ya: string,
    pdytn_pasien_tidak: string,
    pdytn_pasien_ya: string,
    maag_tidak: string,
    maag_ya: string,
    anemia_tidak: string,
    anemia_ya: string,
    nyeri_dada_tidak: string,
    nyeri_dada_ya: string,
    asma_tidak: string,
    asma_ya: string,
    diabetes_pasien_tidak: string,
    diabetes_pasien_ya: string,
    pingsan_tidak: string,
    pingsan_ya: string,
    mengorok_tidak: string,
    mengorok_ya: string,
    hepatitis_tidak: string,
    hepatitis_ya: string,
    hipertensi_pasien_tidak: string,
    hipertensi_pasien_ya: string,
    berat_pasien_tidak: string,
    berat_pasien_ya: string,
    kejang_tidak: string,
    kejang_ya: string,
    penyakit_bawaan_tidak: string,
    penyakit_bawaan_ya: string,

    tranfusi_darah_tidak: string,
    tranfusi_darah_ya: string,
    diagnosis_hiv_tidak: string,
    diagnosis_hiv_ya: string,
    hasil_hiv_positif: string,
    hasil_hiv_negatif: string,
    pakai_lensa_kontak: string,
    pakai_kacamata: string,
    pakai_alat_bantu_dengar: string,
    pakai_gigi_palsu: string,
    pakai_lainnya: string,
    riwayat_anestesia_lokal: string,
    riwayat_anestesia_regional: string,
    riwayat_anestesia_umum: string,

    hilang_gigi_tidak: string,
    hilang_gigi_ya: string,
    mobilisasi_lahir_tidak: string,
    mobilisasi_lahir_ya: string,
    leher_pendek_tidak: string,
    leher_pendek_ya: string,
    batuk_tidak: string,
    batuk_ya: string,
    sesak_napas_tidak: string,
    sesak_napas_ya: string,
    baru_ispa_tidak: string,
    baru_ispa_ya: string,
    sakit_dada_tidak: string,
    sakit_dada_ya: string,
    denyut_jantung_tidak: string,
    denyut_jantung_ya: string,

    muntah_tidak: string,
    muntah_ya: string,
    // pingsan_tidak: string,
    // pingsan_ya: string,
    stroke_tidak: string,
    stroke_ya: string,
    // kejang_tidak: string,
    // kejang_ya: string,
    sedang_hamil_tidak: string,
    sedang_hamil_ya: string,
    tulang_belakang_tidak: string,
    tulang_belakang_ya: string,
    obesitas_tidak: string,
    obesitas_ya: string,

    asa_classification_1: string,
    asa_classification_2: string,
    asa_classification_3: string,
    asa_classification_4: string,

    tanda_1: string,
    tanda_2: string,

    rencana_teknik_sedasi: string,
    rencana_teknik_ga: string,
    rencana_teknik_lain: string,
    teknik_khusus_1: string,
    teknik_khusus_2: string,
    teknik_khusus_3: string,
    teknik_khusus_4: string,
    teknik_khusus_5: string,
    monitoring_1: string,
    monitoring_2: string,
    monitoring_3: string,
    monitoring_4: string,
    monitoring_5: string,
    monitoring_6: string,
    monitoring_7: string,
    monitoring_8: string,
    monitoring_9: string,
    alat_khusus_1: string,
    alat_khusus_2: string,
    alat_khusus_3: string,
    alat_khusus_4: string,
    alat_khusus_5: string,

    ttd_pasien_wali?: string,
    ttd_dokter_anestesi?: string,
    tanggal_puasa_mulai: string,
    tanggal_pre_medikasi: string,
    tanggal_transportasi: string,
    tanggal_rencana_operasi: string,
    nik: string,
  }

  constructor(req: IPdfPreAnesthesiaFormRequest) {
    super(req);
    this.data = req.data;
  }

  static createFromJson(json: IPdfPreAnesthesiaFormRequest) {
    return new PdfPreAnesthesiaFormRequest(json);
  }

  static createPdfRequest(val: any, emrId: string): PdfPreAnesthesiaFormRequest {
    return new PdfPreAnesthesiaFormRequest({
      emr_id: emrId,
      form_name: 'rawat-inap_pra-anestesi-sedasi',
      row_filter: '',
      preview: false,
      data: {
        nomor_mr: val?.nomor_mr ?? '',
        'pasien.Nama': val?.pasien?.Nama ?? '',
        'pasien.Tgl_Lahir': DateTimeConverter.convertToNormalDate(val?.pasien?.Tgl_Lahir),
        'pasien.Umur': this.normalizeAge(val?.umur_lengkap),
        'pasien.Jenis_Kelamin': val?.pasien?.Jenis_Kelamin ?? '',
        pekerjaan: val?.pasien?.Pekerjaan ?? '',
        banyak_rokok: val?.form?.Merokok_Teks ?? '',
        banyak_ktc: val?.form?.Kopi_Teks ?? '',
        banyak_alkohol: val?.form?.Alkohol_Teks ?? '',
        banyak_olga: val?.form?.Olahraga_Teks ?? '',
        obat_resep: val?.form?.Obat_Resep ?? '',
        obat_bebas: val?.form?.Obat_Bebas ?? '',
        df_aspirin_plavix: val?.form?.Aspirin_Teks ?? '',
        df_anti_sakit: val?.form?.Anti_Sakit_Teks ?? '',
        daftar_obat_reaksi: val?.form?.Alergi_Obat ?? '',
        penjelasan_riwayat_keluarga: val?.form?.Keluarga_Teks ?? '',
        penjelasan_riwayat_pasien: val?.form?.Pasien_Teks ?? '',
        tahun_tranfusi: val?.form?.Pasien_Transfusi_Teks ?? '',
        tahun_hiv: val?.form?.Pasien_Diagnosis_HIV_Teks ?? '',
        riwayat_operasi: val?.form?.Riwayat_Operasi ?? '',
        keluhan_reaksi_lokal: val?.form?.Anestesi_Lokal ?? '',
        keluhan_reaksi_regional: val?.form?.Anestesi_Regional ?? '',
        keluhan_reaksi_umum: val?.form?.Anestesi_Umum ?? '',
        tgl_terakhir_periksa: '',
        nama_pasien_wali: '',
        tempat_terakhir_periksa: '',
        gangguan_terakhir_periksa: '',
        tanggal_pengisian: '',
        keterangan_kajian_sistem: val?.form?.Sistem_Teks ?? '',
        fisik_tinggi: val?.form?.Tinggi_Badan ?? '',
        fisik_berat: val?.form?.Berat_Badan ?? '',
        fisik_td: val?.form?.Tekanan_Darah ?? '',
        fisik_nadi: val?.form?.Nadi ?? '',
        fisik_suhu: val?.form?.Suhu ?? '',
        umum_skor_mallampati: val?.form?.Kajian_Teks_Mallampati ?? '',
        umum_gigi_palsu: val?.form?.Kajian_Teks_Gigi_Palsu ?? '',
        umum_jantung: val?.form?.Kajian_Teks_Jantung ?? '',
        umum_paru_paru: val?.form?.Kajian_Teks_Paru ?? '',
        umum_abdomen: val?.form?.Kajian_Teks_Abdomen ?? '',
        umum_tulang_belakang: val?.form?.Kajian_Teks_Tulang_Belakang ?? '',
        umum_ekstremitas: val?.form?.Kajian_Teks_Ekstremitas ?? '',
        umum_neurologi: val?.form?.Kajian_Teks_Neurologi ?? '',
        umum_keterangan: val?.form?.Kajian_Teks_Keterangan ?? '',
        lab_hbht: val?.form?.Laboratorium_Hb_Ht ?? '',
        lab_pt: val?.form?.Laboratorium_Pt ?? '',
        lab_glukosa: val?.form?.Laboratorium_Glukosa ?? '',
        lab_kehamilan: val?.form?.Laboratorium_Kehamilan ?? '',
        lab_kalium: val?.form?.Laboratorium_Kalium ?? '',
        lab_ureum: val?.form?.Laboratorium_Ureum ?? '',
        lab_keterangan: val?.form?.Laboratorium_Teks ?? '',
        lab_leukosit: val?.form?.Laboratorium_Leukosit ?? '',
        lab_trombosit: val?.form?.Laboratorium_Trombosit ?? '',
        lab_rontgen: val?.form?.Laboratorium_Rontgen ?? '',
        lab_ekg: val?.form?.Laboratorium_EKG ?? '',
        lab_nacl: val?.form?.Laboratorium_Na_Cl ?? '',
        lab_kreatinin: val?.form?.Laboratorium_Kreatinin ?? '',
        diagnosa_icdx: val?.form?.Diagnosis_ICD_X ?? '',
        catatan_tindak_lanjut: val?.form?.Catatan_Tindak_Lanjut ?? '',
        keterangan_anestesi_lain: val?.form?.Penyulit_Lain_Teks ?? '',
        teknik_sedasi: val?.form?.Perencanaan_Anestesi_Sedasi_Teks ?? '',
        teknik_ga: val?.form?.Perencanaan_Anestesi_GA_Teks ?? '',
        teknik_lain: val?.form?.Perencanaan_Anestesi_Lainnya_Teks ?? '',
        monitoring_lain: val?.form?.Perencanaan_Monitoring_Lainnya_Teks ?? '',
        alat_lain: val?.form?.Perencanaan_Alat_Khusus_Lainnya_Teks ?? '',
        jam_puasa_mulai: val?.form?.Perencanaan_Persiapan_Puasa_Waktu && val?.form?.Perencanaan_Persiapan_Puasa_Waktu !== '' ? val?.form?.Perencanaan_Persiapan_Puasa_Waktu.substring(11, 16) : '',
        jam_pre_medikasi: val?.form?.Perencanaan_Persiapan_Pre_Medikasi_Waktu && val?.form?.Perencanaan_Persiapan_Pre_Medikasi_Waktu !== '' ? val?.form?.Perencanaan_Persiapan_Pre_Medikasi_Waktu.substring(11, 16) : '',
        jam_transportasi: val?.form?.Perencanaan_Persiapan_Transportasi_Kamar_Bedah_Waktu && val?.form?.Perencanaan_Persiapan_Transportasi_Kamar_Bedah_Waktu !==  '' ? val?.form?.Perencanaan_Persiapan_Transportasi_Kamar_Bedah_Waktu.substring(11, 16) : '',
        jam_rencana_operasi: val?.form?.Perencanaan_Persiapan_Rencana_Operasi_Waktu && val?.form?.Perencanaan_Persiapan_Rencana_Operasi_Waktu !== '' ? val?.form?.Perencanaan_Persiapan_Rencana_Operasi_Waktu.substring(11, 16) : '',
        tanggal_puasa_mulai: DateTimeConverter.convertToNormalDate(val?.form?.Perencanaan_Persiapan_Puasa_Waktu && val?.form?.Perencanaan_Persiapan_Puasa_Waktu !== '' ? val?.form?.Perencanaan_Persiapan_Puasa_Waktu.substring(0, 10) : ''),
        tanggal_pre_medikasi: DateTimeConverter.convertToNormalDate(val?.form?.Perencanaan_Persiapan_Pre_Medikasi_Waktu && val?.form?.Perencanaan_Persiapan_Pre_Medikasi_Waktu !== '' ? val?.form?.Perencanaan_Persiapan_Pre_Medikasi_Waktu.substring(0, 10) : ''),
        tanggal_transportasi: DateTimeConverter.convertToNormalDate(val?.form?.Perencanaan_Persiapan_Transportasi_Kamar_Bedah_Waktu && val?.form?.Perencanaan_Persiapan_Transportasi_Kamar_Bedah_Waktu !== '' ? val?.form?.Perencanaan_Persiapan_Transportasi_Kamar_Bedah_Waktu.substring(0, 10) : ''),
        tanggal_rencana_operasi: DateTimeConverter.convertToNormalDate(val?.form?.Perencanaan_Persiapan_Rencana_Operasi_Waktu && val?.form?.Perencanaan_Persiapan_Rencana_Operasi_Waktu !== '' ? val?.form?.Perencanaan_Persiapan_Rencana_Operasi_Waktu.substring(0, 10) : ''),
        catatan_persiapan_pra_anestesi: '',
        nama_dokter_anestesi: (val?.form?.Nama_TTD_Dokter !== '') ? val?.form?.Nama_TTD_Dokter : undefined,

        kelamin_lk: this.getCheckImage(false),
        kelamin_pr: this.getCheckImage(false),
        menikah_ya: val?.pasien?.Status_Nikah === 'Nikah' ? 'https://bucket.rsmatasmec.com/checklist.jpeg' : 'https://bucket.rsmatasmec.com/blank.jpeg',
        menikah_tidak: val?.pasien?.Status_Nikah !== 'Nikah' ? 'https://bucket.rsmatasmec.com/checklist.jpeg' : 'https://bucket.rsmatasmec.com/blank.jpeg',
        merokok_tidak: this.getCheckImage(Number(val?.form?.Merokok_Radio) === 0),
        merokok_ya: this.getCheckImage(Number(val?.form?.Merokok_Radio) === 1),
        alkohol_tidak: this.getCheckImage(Number(val?.form?.Alkohol_Radio) === 0),
        alkohol_ya: this.getCheckImage(Number(val?.form?.Alkohol_Radio) === 1),
        ktc_tidak: this.getCheckImage(Number(val?.form?.Kopi_Radio) === 0),
        ktc_ya: this.getCheckImage(Number(val?.form?.Kopi_Radio) === 1),
        olga_tidak: this.getCheckImage(Number(val?.form?.Olahraga_Radio) === 0),
        olga_ya: this.getCheckImage(Number(val?.form?.Olahraga_Radio) === 1),
        aspirin_tidak: this.getCheckImage(Number(val?.form?.Aspirin_Radio) === 0),
        aspirin_ya: this.getCheckImage(Number(val?.form?.Aspirin_Radio) === 1),
        anti_sakit_tidak: this.getCheckImage(Number(val?.form?.Anti_Sakit_Radio) === 0),
        anti_sakit_ya: this.getCheckImage(Number(val?.form?.Anti_Sakit_Radio) === 1),
        alergi_obat_tidak: this.getCheckImage(Number(val?.form?.Alergi_Obat) === 0),
        alergi_obat_ya: this.getCheckImage(Number(val?.form?.Alergi_Obat) === 1),
        alergi_makanan_tidak: this.getCheckImage(Number(val?.form?.Alergi_Makanan) === 2),
        alergi_makanan_ya: this.getCheckImage(Number(val?.form?.Alergi_Makanan) === 1),

        pytn_tidak: this.getCheckImage(Number(val?.form?.Keluarga_Pendarahan_Radio) === 0),
        pytn_ya: this.getCheckImage(Number(val?.form?.Keluarga_Pendarahan_Radio) === 1),
        pdytn_tidak: this.getCheckImage(Number(val?.form?.Keluarga_Pembekuan_Darah_Radio) === 0),
        pdytn_ya: this.getCheckImage(Number(val?.form?.Keluarga_Pembekuan_Darah_Radio) === 1),
        pdp_tidak: this.getCheckImage(Number(val?.form?.Keluarga_Pembiusan_Radio) === 0),
        pdp_ya: this.getCheckImage(Number(val?.form?.Keluarga_Pembiusan_Radio) === 1),
        dtpo_tidak: this.getCheckImage(Number(val?.form?.Keluarga_Demam_Radio) === 0),
        dtpo_ya: this.getCheckImage(Number(val?.form?.Keluarga_Demam_Radio) === 1),
        diabetes_tidak: this.getCheckImage(Number(val?.form?.Keluarga_Diabetes_Radio) === 0),
        diabetes_ya: this.getCheckImage(Number(val?.form?.Keluarga_Diabetes_Radio) === 1),
        sj_tidak: this.getCheckImage(Number(val?.form?.Keluarga_Jantung_Radio) === 0),
        sj_ya: this.getCheckImage(Number(val?.form?.Keluarga_Jantung_Radio) === 1),
        gij_tidak: this.getCheckImage(Number(val?.form?.Keluarga_Irama_Jantung_Radio) === 0),
        gij_ya: this.getCheckImage(Number(val?.form?.Keluarga_Irama_Jantung_Radio) === 1),
        hipertensi_tidak: this.getCheckImage(Number(val?.form?.Keluarga_Hipertensi_Radio) === 0),
        hipertensi_ya: this.getCheckImage(Number(val?.form?.Keluarga_Hipertensi_Radio) === 1),
        tuberkolosis_tidak: this.getCheckImage(Number(val?.form?.Keluarga_Tuberkulosis_Radio) === 0),
        tuberkolosis_ya: this.getCheckImage(Number(val?.form?.Keluarga_Tuberkulosis_Radio) === 1),
        berat_lain_tidak: this.getCheckImage(Number(val?.form?.Keluarga_Lainnya_Radio) === 0),
        berat_lain_ya: this.getCheckImage(Number(val?.form?.Keluarga_Lainnya_Radio) === 1),

        pytn_pasien_tidak: this.getCheckImage(Number(val?.form?.Pasien_Pendarahan_Radio) === 0),
        pytn_pasien_ya: this.getCheckImage(Number(val?.form?.Pasien_Pendarahan_Radio) === 1),
        pdytn_pasien_tidak: this.getCheckImage(Number(val?.form?.Pasien_Pembekuan_Darah_Radio) === 0),
        pdytn_pasien_ya: this.getCheckImage(Number(val?.form?.Pasien_Pembekuan_Darah_Radio) === 1),
        maag_tidak: this.getCheckImage(Number(val?.form?.Pasien_Maag_Radio) === 0),
        maag_ya: this.getCheckImage(Number(val?.form?.Pasien_Maag_Radio) === 1),
        anemia_tidak: this.getCheckImage(Number(val?.form?.Pasien_Anemia_Radio) === 0),
        anemia_ya: this.getCheckImage(Number(val?.form?.Pasien_Anemia_Radio) === 1),
        nyeri_dada_tidak: this.getCheckImage(Number(val?.form?.Pasien_Jantung_Radio) === 0),
        nyeri_dada_ya: this.getCheckImage(Number(val?.form?.Pasien_Jantung_Radio) === 1),
        asma_tidak: this.getCheckImage(Number(val?.form?.Pasien_Asthma_Radio) === 0),
        asma_ya: this.getCheckImage(Number(val?.form?.Pasien_Asthma_Radio) === 1),
        diabetes_pasien_tidak: this.getCheckImage(Number(val?.form?.Pasien_Diabetes_Radio) === 0),
        diabetes_pasien_ya: this.getCheckImage(Number(val?.form?.Pasien_Diabetes_Radio) === 1),
        pingsan_tidak: this.getCheckImage(Number(val?.form?.Pasien_Pingsan_Radio) === 0),
        pingsan_ya: this.getCheckImage(Number(val?.form?.Pasien_Pingsan_Radio) === 1),
        mengorok_tidak: this.getCheckImage(Number(val?.form?.Pasien_Mengorok_Radio) === 0),
        mengorok_ya: this.getCheckImage(Number(val?.form?.Pasien_Mengorok_Radio) === 1),
        hepatitis_tidak: this.getCheckImage(Number(val?.form?.Pasien_Hepatitis_Radio) === 0),
        hepatitis_ya: this.getCheckImage(Number(val?.form?.Pasien_Hepatitis_Radio) === 1),
        hipertensi_pasien_tidak: this.getCheckImage(Number(val?.form?.Pasien_Hipertensi_Radio) === 0),
        hipertensi_pasien_ya: this.getCheckImage(Number(val?.form?.Pasien_Hipertensi_Radio) === 1),
        berat_pasien_tidak: this.getCheckImage(Number(val?.form?.Pasien_Lainnya_Radio) === 0),
        berat_pasien_ya: this.getCheckImage(Number(val?.form?.Pasien_Lainnya_Radio) === 1),
        kejang_tidak: this.getCheckImage(Number(val?.form?.Pasien_Kejang_Radio) === 0),
        kejang_ya: this.getCheckImage(Number(val?.form?.Pasien_Kejang_Radio) === 1),
        penyakit_bawaan_tidak: this.getCheckImage(Number(val?.form?.Pasien_Bawaan_Radio) === 0),
        penyakit_bawaan_ya: this.getCheckImage(Number(val?.form?.Pasien_Bawaan_Radio) === 1),

        tranfusi_darah_tidak: this.getCheckImage(Number(val?.form?.Pasien_Transfusi) === 0),
        tranfusi_darah_ya: this.getCheckImage(Number(val?.form?.Pasien_Transfusi) === 1),
        diagnosis_hiv_tidak: this.getCheckImage(Number(val?.form?.Pasien_Diagnosis_HIV) === 0),
        diagnosis_hiv_ya: this.getCheckImage(Number(val?.form?.Pasien_Diagnosis_HIV) === 1),
        hasil_hiv_positif: this.getCheckImage(val?.form?.Pasien_Diagnosis_HIV_Hasil === '0'),
        hasil_hiv_negatif: this.getCheckImage(val?.form?.Pasien_Diagnosis_HIV_Hasil === '1'),
        pakai_lensa_kontak: this.getCheckImage(Number(val?.form?.Pasien_Lensa_Kontak) === 1),
        pakai_kacamata: this.getCheckImage(Number(val?.form?.Pasien_Kacamata) === 1),
        pakai_alat_bantu_dengar: this.getCheckImage(Number(val?.form?.Pasien_Alat_Bantu_Dengar) === 1),
        pakai_gigi_palsu: this.getCheckImage(Number(val?.form?.Pasien_Gigi_Palsu) === 1),
        pakai_lain_lain: this.getCheckImage(Number(val?.form?.Pasien_Pakai_Lainnya) === 1),
        pakai_lainnya: val?.form?.Pasien_Pakai_Lainnya_Teks ?? '',
        riwayat_anestesia_lokal: this.getCheckImage(!!val?.form?.Anestesi_Lokal && val?.form?.Anestesi_Lokal !== ''),
        riwayat_anestesia_regional: this.getCheckImage(!!val?.form?.Anestesi_Regional && val?.form?.Anestesi_Regional !== ''),
        riwayat_anestesia_umum: this.getCheckImage(!!val?.form?.Anestesi_Umum && val?.form?.Anestesi_Umum !== ''),

        hilang_gigi_tidak: this.getCheckImage(Number(val?.form?.Sistem_Gigi_Radio) === 0),
        hilang_gigi_ya: this.getCheckImage(Number(val?.form?.Sistem_Gigi_Radio) === 1),
        mobilisasi_lahir_tidak: this.getCheckImage(Number(val?.form?.Sistem_Mobilisasi_Leher_Radio) === 0),
        mobilisasi_lahir_ya: this.getCheckImage(Number(val?.form?.Sistem_Mobilisasi_Leher_Radio) === 1),
        leher_pendek_tidak: this.getCheckImage(Number(val?.form?.Sistem_Leher_Pendek_Radio) === 0),
        leher_pendek_ya: this.getCheckImage(Number(val?.form?.Sistem_Leher_Pendek_Radio) === 1),
        batuk_tidak: this.getCheckImage(Number(val?.form?.Sistem_Batuk_Radio) === 0),
        batuk_ya: this.getCheckImage(Number(val?.form?.Sistem_Batuk_Radio) === 1),
        sesak_napas_tidak: this.getCheckImage(Number(val?.form?.Sistem_Sesak_Napas_Radio) === 0),
        sesak_napas_ya: this.getCheckImage(Number(val?.form?.Sistem_Sesak_Napas_Radio) === 1),
        baru_ispa_tidak: this.getCheckImage(Number(val?.form?.Sistem_ISPA_Radio) === 0),
        baru_ispa_ya: this.getCheckImage(Number(val?.form?.Sistem_ISPA_Radio) === 1),
        sakit_dada_tidak: this.getCheckImage(Number(val?.form?.Sistem_Dada_Radio) === 0),
        sakit_dada_ya: this.getCheckImage(Number(val?.form?.Sistem_Dada_Radio) === 1),
        denyut_jantung_tidak: this.getCheckImage(Number(val?.form?.Sistem_Denyut_Jantung_Radio) === 0),
        denyut_jantung_ya: this.getCheckImage(Number(val?.form?.Sistem_Denyut_Jantung_Radio) === 1),

        muntah_tidak: this.getCheckImage(Number(val?.form?.Sistem_Muntah_Radio) === 0),
        muntah_ya: this.getCheckImage(Number(val?.form?.Sistem_Muntah_Radio) === 1),
        // pingsan_tidak: this.getCheckImage(Number(val?.form) === 0),
        // pingsan_ya: this.getCheckImage(Number(val?.form) === 0),
        stroke_tidak: this.getCheckImage(Number(val?.form?.Sistem_Stroke_Radio) === 0),
        stroke_ya: this.getCheckImage(Number(val?.form?.Sistem_Stroke_Radio) === 1),
        // kejang_tidak: this.getCheckImage(Number(val?.form) === 0),
        // kejang_ya: this.getCheckImage(Number(val?.form) === 0),
        sedang_hamil_tidak: this.getCheckImage(Number(val?.form?.Sistem_Hamil_Radio) === 0),
        sedang_hamil_ya: this.getCheckImage(Number(val?.form?.Sistem_Hamil_Radio) === 1),
        tulang_belakang_tidak: this.getCheckImage(Number(val?.form?.Sistem_Tulang_Belakang_Radio) === 0),
        tulang_belakang_ya: this.getCheckImage(Number(val?.form?.Sistem_Tulang_Belakang_Radio) === 1),
        obesitas_tidak: this.getCheckImage(Number(val?.form?.Sistem_Obesitas_Radio) === 0),
        obesitas_ya: this.getCheckImage(Number(val?.form?.Sistem_Obesitas_Radio) === 1),

        asa_classification_1: this.getCheckImage(Number(val?.form?.ASA_1) === 1),
        asa_classification_2: this.getCheckImage(Number(val?.form?.ASA_2) === 1),
        asa_classification_3: this.getCheckImage(Number(val?.form?.ASA_3) === 1),
        asa_classification_4: this.getCheckImage(Number(val?.form?.ASA_4) === 1),

        tanda_1: this.getCheckImage(Number(val?.form?.Penyulit_Lain_Radio) === 0),
        tanda_2: this.getCheckImage(Number(val?.form?.Penyulit_Lain_Radio) === 1),

        rencana_teknik_sedasi: this.getCheckImage(Number(val?.form?.Perencanaan_Anestesi_Sedasi) === 1),
        rencana_teknik_ga: this.getCheckImage(Number(val?.form?.Perencanaan_Anestesi_GA) === 1),
        rencana_teknik_lain: this.getCheckImage(Number(val?.form?.Perencanaan_Anestesi_Lainnya) === 1),
        teknik_khusus_1: this.getCheckImage(Number(val?.form?.Perencanaan_Khusus_Tidak_Ada) === 1),
        teknik_khusus_2: this.getCheckImage(Number(val?.form?.Perencanaan_Khusus_Hipotensi) === 1),
        teknik_khusus_3: this.getCheckImage(Number(val?.form?.Perencanaan_Khusus_Ventilasi) === 1),
        teknik_khusus_4: this.getCheckImage(Number(val?.form?.Perencanaan_Khusus_TCI) === 1),
        teknik_khusus_5: this.getCheckImage(Number(val?.form?.Perencanaan_Khusus_Lainnya) === 1),
        monitoring_1: this.getCheckImage(Number(val?.form?.Perencanaan_Monitoring_EKG_Lead) === 1),
        monitoring_2: this.getCheckImage(Number(val?.form?.Perencanaan_Monitoring_SPO2) === 1),
        monitoring_3: this.getCheckImage(Number(val?.form?.Perencanaan_Monitoring_BIS) === 1),
        monitoring_4: this.getCheckImage(Number(val?.form?.Perencanaan_Monitoring_CVP) === 1),
        monitoring_5: this.getCheckImage(Number(val?.form?.Perencanaan_Monitoring_ET_CO2) === 1),
        monitoring_6: this.getCheckImage(Number(val?.form?.Perencanaan_Monitoring_Temp) === 1),
        monitoring_7: this.getCheckImage(Number(val?.form?.Perencanaan_Monitoring_Arteri_Line) === 1),
        monitoring_8: this.getCheckImage(Number(val?.form?.Perencanaan_Monitoring_NIBP) === 1),
        monitoring_9: this.getCheckImage(Number(val?.form?.Perencanaan_Monitoring_Lainnya) === 1),
        alat_khusus_1: this.getCheckImage(false),
        alat_khusus_2: this.getCheckImage(Number(val?.form?.Perencanaan_Alat_Khusus_Bronchoscopy) === 1),
        alat_khusus_3: this.getCheckImage(Number(val?.form?.Perencanaan_Alat_Khusus_Glidescope) === 1),
        alat_khusus_4: this.getCheckImage(Number(val?.form?.Perencanaan_Alat_Khusus_USG) === 1),
        alat_khusus_5: this.getCheckImage(Number(val?.form?.Perencanaan_Alat_Khusus_Lainnya) === 1),

        ttd_pasien_wali: undefined,
        nik: val?.pasien?.NIK ?? '',
        ttd_dokter_anestesi: (val?.form?.Tanda_Tangan_Dokter !== '') ? val?.form?.Tanda_Tangan_Dokter : undefined,
      },
    })
  }
}
