import { CreatePDFRequest, ICreatePDFRequest } from '@shared/pdf/requests/create-pdf.request';
import { DateTimeConverter } from '@src/shared/datetime-converter';

export interface IPdfAssesmentUgd extends ICreatePDFRequest {
  data: {
    nomor_mr: string;
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string,
    J_K: string,
    tanggal_ppp: string,
    jam_ppp: string,
    ppp: string,
    tindakan_resusitasi: string,
    val_e: string,
    val_m: string,
    val_v: string,
    score: string,
    value_rr: string,
    value_dn: string,
    value_td: string,
    value_k: string,
    value_s: string,
    skala_nyeri: string,
    sum_a: string,
    alergi_makanan: string,
    alergi_obat: string,
    informasi_datang: string,
    hub_allo: string,
    rpt: string,
    rpo: string,
    gravida: string,
    para: string,
    abortus: string,
    hpht: string,
    tinggi_badan: string,
    berat_badan: string,
    ttl_skor: string,
    diagnosa_khusus: string,
    tgl_lanjut_gizi: string,
    lain_lain_psikolog: string,
    masalah_perilaku_lain: string,
    kekerasan_lain: string,
    nama_kerabat: string,
    hub_kerabat: string,
    telp_kerabat: string,
    agama_pasien: string,
    dk_lain: string,
    rk_lain: string,
    vod: string,
    vos: string,
    tod: string,
    tos: string,
    subj_umum: string,
    kepala_umum: string,
    mata_umum: string,
    telinga_umum: string,
    hidung_umum: string,
    gigi_umum: string,
    tengg_umum: string,
    leher_umum: string,
    dada_umum: string,
    baru_umum: string,
    abdomen_umum: string,
    genita_umum: string,
    kand_umum: string,
    eksa_umum: string,
    eksb_umum: string,
    jantung_umum: string,
    pp_umum: string,
    asess_umum: string,
    tp_umum: string,
    anj_umum: string,
    nama_dokter_umum: string,
    od_position: string,
    od_movement: string,
    od_palpebra_superior: string,
    od_palpebra_inferior: string,
    conj_tarsal_superior_od: string,
    conj_tarsal_inferior_od: string,
    conj_bulbi_od: string,
    cornea_od: string,
    coa_od: string,
    od_pupil: string,
    od_iris: string,
    od_lens: string,
    od_vitreous: string,
    funduscopy_od: string,
    os_position: string,
    os_movement: string,
    os_palpebra_superior: string,
    os_palpebra_inferior: string,
    conj_tarsal_superior_os: string,
    conj_tarsal_inferior_os: string,
    conj_bulbi_os: string,
    cornea_os: string,
    coa_os: string,
    os_pupil: string,
    os_iris: string,
    os_lens: string,
    os_vitreous: string,
    funduscopy_os: string,
    diagnose: string,
    terapi: string,
    rencana: string,
    anjuran: string,
    namaDokterMata: string,

    triase_1: string,
    triase_2: string,
    triase_3: string,
    triase_4: string,
    kesadaran_1: string,
    kesadaran_2: string,
    kesadaran_3: string,
    kesadaran_4: string,
    pernapasan_1: string,
    pernapasan_2: string,
    pernapasan_3: string,
    pernapasan_4: string,
    sirkulasi_1: string,
    sirkulasi_2: string,
    sirkulasi_3: string,
    sirkulasi_4: string,
    jalan_nafas_1: string,
    jalan_nafas_2: string,
    jalan_nafas_3: string,
    bantuan_nafas_1: string,
    bantuan_nafas_2: string,
    bantuan_nafas_3: string,
    sirkulasi_tr_1: string,
    sirkulasi_tr_2: string,
    sirkulasi_tr_3: string,
    autoanamnese: string,
    alloanamnese: string,
    fungsi_1: string,
    fungsi_2: string,
    fungsi_3: string,
    jatuh_1: string,
    jatuh_2: string,
    jatuh_3: string,
    jatuh_4: string,
    jatuh_5: string,
    hamil_1: string,
    hamil_2: string,
    gizi_1_1: string,
    gizi_1_2: string,
    gizi_1_3: string,
    gizi_1_3_1: string,
    gizi_1_3_2: string,
    gizi_1_3_3: string,
    gizi_1_3_4: string,
    gizi_1_3_5: string,
    gizi_2_1: string,
    gizi_2_2: string,
    gizi_3_1: string,
    gizi_3_2: string,
    lanjut_ya?: string,
    lanjut_tidak?: string,
    psikolog_1: string,
    psikolog_2: string,
    psikolog_3: string,
    psikolog_4: string,
    psikolog_5: string,
    psikolog_6: string,
    mental_1: string,
    mental_2: string,
    mental_3: string,
    sosial_baik?: string,
    sosial_tidak_baik?: string,
    dk_1: string,
    dk_2: string,
    dk_3: string,
    dk_4: string,
    dk_5: string,
    dk_6: string,
    dk_7: string,
    dk_8: string,
    rk_1: string,
    rk_2: string,
    rk_3: string,
    rk_4: string,
    rk_5: string,
    rk_6: string,
    rk_7: string,
    rk_8: string,
    ttd_dokter_umum: string,
    MataOD: string,
    MataOS: string,
    ttd_dokter_mata: string,

    isResep: any;
    isResep0: any;
    resep: any;
    resep0: any;
    nama_perawat: string;
    ttd_perawat_pemeriksa: string;
    nik: string;
  }
}

export class PdfAssesmentUgd extends CreatePDFRequest {
  data: {
    nomor_mr: string;
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string,
    J_K: string,
    tanggal_ppp: string,
    jam_ppp: string,
    ppp: string,
    tindakan_resusitasi: string,
    val_e: string,
    val_m: string,
    val_v: string,
    score: string,
    value_rr: string,
    value_dn: string,
    value_td: string,
    value_k: string,
    value_s: string,
    skala_nyeri: string,
    sum_a: string,
    alergi_makanan: string,
    alergi_obat: string,
    informasi_datang: string,
    hub_allo: string,
    rpt: string,
    rpo: string,
    gravida: string,
    para: string,
    abortus: string,
    hpht: string,
    tinggi_badan: string,
    berat_badan: string,
    ttl_skor: string,
    diagnosa_khusus: string,
    tgl_lanjut_gizi: string,
    lain_lain_psikolog: string,
    masalah_perilaku_lain: string,
    kekerasan_lain: string,
    nama_kerabat: string,
    hub_kerabat: string,
    telp_kerabat: string,
    agama_pasien: string,
    dk_lain: string,
    rk_lain: string,
    vod: string,
    vos: string,
    tod: string,
    tos: string,
    subj_umum: string,
    kepala_umum: string,
    mata_umum: string,
    telinga_umum: string,
    hidung_umum: string,
    gigi_umum: string,
    tengg_umum: string,
    leher_umum: string,
    dada_umum: string,
    baru_umum: string,
    abdomen_umum: string,
    genita_umum: string,
    kand_umum: string,
    eksa_umum: string,
    eksb_umum: string,
    jantung_umum: string,
    pp_umum: string,
    asess_umum: string,
    tp_umum: string,
    anj_umum: string,
    nama_dokter_umum: string,
    od_position: string,
    od_movement: string,
    od_palpebra_superior: string,
    od_palpebra_inferior: string,
    conj_tarsal_superior_od: string,
    conj_tarsal_inferior_od: string,
    conj_bulbi_od: string,
    cornea_od: string,
    coa_od: string,
    od_pupil: string,
    od_iris: string,
    od_lens: string,
    od_vitreous: string,
    funduscopy_od: string,
    os_position: string,
    os_movement: string,
    os_palpebra_superior: string,
    os_palpebra_inferior: string,
    conj_tarsal_superior_os: string,
    conj_tarsal_inferior_os: string,
    conj_bulbi_os: string,
    cornea_os: string,
    coa_os: string,
    os_pupil: string,
    os_iris: string,
    os_lens: string,
    os_vitreous: string,
    funduscopy_os: string,
    diagnose: string,
    terapi: string,
    rencana: string,
    anjuran: string,
    namaDokterMata: string,

    triase_1: string,
    triase_2: string,
    triase_3: string,
    triase_4: string,
    kesadaran_1: string,
    kesadaran_2: string,
    kesadaran_3: string,
    kesadaran_4: string,
    pernapasan_1: string,
    pernapasan_2: string,
    pernapasan_3: string,
    pernapasan_4: string,
    sirkulasi_1: string,
    sirkulasi_2: string,
    sirkulasi_3: string,
    sirkulasi_4: string,
    jalan_nafas_1: string,
    jalan_nafas_2: string,
    jalan_nafas_3: string,
    bantuan_nafas_1: string,
    bantuan_nafas_2: string,
    bantuan_nafas_3: string,
    sirkulasi_tr_1: string,
    sirkulasi_tr_2: string,
    sirkulasi_tr_3: string,
    autoanamnese: string,
    alloanamnese: string,
    fungsi_1: string,
    fungsi_2: string,
    fungsi_3: string,
    jatuh_1: string,
    jatuh_2: string,
    jatuh_3: string,
    jatuh_4: string,
    jatuh_5: string,
    hamil_1: string,
    hamil_2: string,
    gizi_1_1: string,
    gizi_1_2: string,
    gizi_1_3: string,
    gizi_1_3_1: string,
    gizi_1_3_2: string,
    gizi_1_3_3: string,
    gizi_1_3_4: string,
    gizi_1_3_5: string,
    gizi_2_1: string,
    gizi_2_2: string,
    gizi_3_1: string,
    gizi_3_2: string,
    lanjut_ya?: string,
    lanjut_tidak?: string,
    psikolog_1: string,
    psikolog_2: string,
    psikolog_3: string,
    psikolog_4: string,
    psikolog_5: string,
    psikolog_6: string,
    mental_1: string,
    mental_2: string,
    mental_3: string,
    sosial_baik?: string,
    sosial_tidak_baik?: string,
    dk_1: string,
    dk_2: string,
    dk_3: string,
    dk_4: string,
    dk_5: string,
    dk_6: string,
    dk_7: string,
    dk_8: string,
    rk_1: string,
    rk_2: string,
    rk_3: string,
    rk_4: string,
    rk_5: string,
    rk_6: string,
    rk_7: string,
    rk_8: string,
    ttd_dokter_umum: string,
    MataOD: string,
    MataOS: string,
    ttd_dokter_mata: string,

    isResep: any;
    isResep0: any;
    resep: any;
    resep0: any;
    nama_perawat: string;
    ttd_perawat_pemeriksa: string;
    nik: string;
  }

  constructor(req: IPdfAssesmentUgd) {
    super(req);
    this.data = req.data;
  }

  static createFromJson(json: IPdfAssesmentUgd) {
    return new PdfAssesmentUgd(json);
  }

  static createPdfRequest(val: any, emrId: string): PdfAssesmentUgd {
    const nilaiE = +((val?.form?.GCS_E ?? '').split('.')[0] ?? 0);
    const nilaiM = +((val?.form?.GCS_M ?? '').split('.')[0] ?? 0);
    const nilaiV = +((val?.form?.GCS_V ?? '').split('.')[0] ?? 0);
    const score = nilaiE + nilaiM + nilaiV;
    let valueK = '';
    switch (true) {
    case score >= 1 && score <= 1:
      valueK = 'Coma';
      break;
    case score >= 4 && score <= 4:
      valueK = 'Stupor';
      break;
    case score >= 7 && score <= 7:
      valueK = 'Somnolen';
      break;
    case score >= 10 && score <= 10:
      valueK = 'Delirium';
      break;
    case score >= 12 && score <= 12:
      valueK = 'Apatis';
      break;
    case score >= 14:
      valueK = 'Composmentis';
      break;
    }
    return new PdfAssesmentUgd({
      emr_id: emrId,
      form_name: 'asessmen-ugd',
      row_filter: '',
      preview: false,
      data: {
        nomor_mr: val?.nomor_mr ?? '',
        'pasien.Nama': val?.pasien?.Nama ?? '',
        'pasien.Tgl_Lahir': DateTimeConverter.convertToNormalDate(val?.pasien?.Tgl_Lahir),
        'pasien.Umur': this.normalizeAge(val?.umur_lengkap),

        J_K: val?.pasien?.Jenis_Kelamin ?? '',
        tanggal_ppp: DateTimeConverter.convertToNormalDate(val?.form?.Pertolongan_Pertama ?? '').split('T')[0],
        jam_ppp: (val?.form?.Pertolongan_Pertama ?? '').split('T').length > 1 ? (val?.form?.Pertolongan_Pertama ?? '').split('T')[1] : '',
        // ppp: val?.form?.Pertolongan_Pertama ?? '',
        ppp: DateTimeConverter.convertToDateTime(val?.form?.Pertolongan_Pertama),
        tindakan_resusitasi: val?.form?.Tindakan_Resusitasi ?? '',
        val_e: val?.form?.GCS_E ?? '',
        val_m: val?.form?.GCS_M ?? '',
        val_v: val?.form?.GCS_V ?? '',
        score: `${score}`,
        value_rr: val?.form?.Vital_Respiratory_Rate ?? '',
        value_dn: val?.form?.Vital_Denyut_Nadi ?? '',
        value_td: val?.form?.Vital_Tekanan_Darah ?? '',
        value_k: valueK,
        value_s: val?.form?.Vital_Suhu ?? '',
        skala_nyeri: val?.form?.Skala_Nyeri ?? '',
        sum_a: val?.form?.ASDASD ?? '',
        alergi_makanan: val?.form?.Alergi_Makanan ?? '',
        alergi_obat: val?.form?.Alergi_Obat ?? '',
        informasi_datang: val?.form?.Kedatangan_Pasien ?? '',
        hub_allo: val?.form?.Asal_Informasi_Hubungan ?? '',
        rpt: val?.form?.Penyakit_Terdahulu ?? '',
        rpo: val?.form?.Pengobatan_Terdahulu ?? '',
        gravida: val?.form?.Status_Kehamilan_Gravida ?? '',
        para: val?.form?.Status_Kehamilan_Para ?? '',
        abortus: val?.form?.Status_Kehamilan_Abortus ?? '',
        hpht: val?.form?.Status_Kehamilan_HPHT ?? '',
        tinggi_badan: val?.form?.Nutrisi_Tinggi ?? '',
        berat_badan: val?.form?.Nutrisi_Berat ?? '',
        ttl_skor: val?.form?.ASDASD ?? '',
        diagnosa_khusus: val?.form?.Nutrisi_Diagnosa_Khusus ?? '',
        tgl_lanjut_gizi: val?.form?.ASDASD ?? '',
        lain_lain_psikolog: val?.form?.Psikologis_Lain_Lain_Keterangan ?? '',
        masalah_perilaku_lain: val?.form?.Mental_Perilaku_Keterangan ?? '',
        kekerasan_lain: val?.form?.Mental_Kekerasan_Keterangan ?? '',
        nama_kerabat: val?.form?.Kerabat_Nama ?? '',
        hub_kerabat: val?.form?.Kerabat_Hubungan ?? '',
        telp_kerabat: val?.form?.Kerabat_Telepon ?? '',
        agama_pasien: val?.form?.Spiritual_Agama ?? '',
        dk_lain: val?.form?.Keperawatan_Diagnosa_Lainnya ?? '',
        rk_lain: val?.form?.Keperawatan_Rencana_Lainnya ?? '',
        vod: val?.form?.Pengkajian_OD_VA ?? '',
        vos: val?.form?.Pengkajian_OS_VA ?? '',
        tod: val?.form?.Pengkajian_OD_Tonometri ?? '',
        tos: val?.form?.Pengkajian_OS_Tonometri ?? '',
        subj_umum: val?.form?.Pengkajian_Subjektif ?? '',
        kepala_umum: val?.form?.Pengkajian_Kepala ?? '',
        mata_umum: val?.form?.Pengkajian_Mata ?? '',
        telinga_umum: val?.form?.Pengkajian_Telinga ?? '',
        hidung_umum: val?.form?.Pengkajian_Hidung ?? '',
        gigi_umum: val?.form?.Pengkajian_Gigi ?? '',
        tengg_umum: val?.form?.Pengkajian_Tenggorokan ?? '',
        leher_umum: val?.form?.Pengkajian_Leher ?? '',
        dada_umum: val?.form?.Pengkajian_Dada ?? '',
        baru_umum: val?.form?.Pengkajian_Paru ?? '',
        abdomen_umum: val?.form?.Pengkajian_Abdomen ?? '',
        genita_umum: val?.form?.Pengkajian_Genitalia ?? '',
        kand_umum: val?.form?.Pengkajian_Kandungan ?? '',
        eksa_umum: val?.form?.Pengkajian_Eks_Atas ?? '',
        eksb_umum: val?.form?.Pengkajian_Eks_Bawah ?? '',
        jantung_umum: val?.form?.Pengkajian_Jantung ?? '',
        pp_umum: val?.form?.Pengkajian_Pemeriksaan_Penunjang ?? '',
        asess_umum: val?.form?.Pengkajian_Assesmen ?? '',
        tp_umum: val?.form?.Pengkajian_Terapi_Penatalaksaan ?? '',
        anj_umum: val?.form?.Pengkajian_Anjuran ?? '',
        nama_dokter_umum: val?.form?.Nama_Pengkajian_Dokter ?? '',

        od_position: val?.form?.Dokter_Mata_Posisi_OD ?? '',
        od_movement: val?.form?.Dokter_Mata_Pergerakan_OD ?? '',
        od_palpebra_superior: val?.form?.Dokter_Mata_Palpebra_Superior_OD ?? '',
        od_palpebra_inferior: val?.form?.Dokter_Mata_Palpebra_Inferior_OD ?? '',
        conj_tarsal_superior_od: val?.form?.Dokter_Mata_Conj_Tarsal_Superior_OD ?? '',
        conj_tarsal_inferior_od: val?.form?.Dokter_Mata_Conj_Tarsal_Inferior_OD ?? '',
        conj_bulbi_od: val?.form?.Dokter_Mata_Conj_Bulbi_OD ?? '',
        cornea_od: val?.form?.Dokter_Mata_Cornea_OD ?? '',
        coa_od: val?.form?.Dokter_Mata_COA_OD ?? '',
        od_pupil: val?.form?.Dokter_Mata_Pupil_OD ?? '',
        od_iris: val?.form?.Dokter_Mata_Iris_OD ?? '',
        od_lens: val?.form?.Dokter_Mata_Lensa_OD ?? '',
        od_vitreous: val?.form?.Dokter_Mata_Vitreous_OD ?? '',
        funduscopy_od: val?.form?.Dokter_Mata_Funduscopy_OD ?? '',

        os_position: val?.form?.Dokter_Mata_Posisi_OS ?? '',
        os_movement: val?.form?.Dokter_Mata_Pergerakan_OS ?? '',
        os_palpebra_superior: val?.form?.Dokter_Mata_Palpebra_Superior_OS ?? '',
        os_palpebra_inferior: val?.form?.Dokter_Mata_Palpebra_Inferior_OS ?? '',
        conj_tarsal_superior_os: val?.form?.Dokter_Mata_Conj_Tarsal_Superior_OS ?? '',
        conj_tarsal_inferior_os: val?.form?.Dokter_Mata_Conj_Tarsal_Inferior_OS ?? '',
        conj_bulbi_os: val?.form?.Dokter_Mata_Conj_Bulbi_OS ?? '',
        cornea_os: val?.form?.Dokter_Mata_Cornea_OS ?? '',
        coa_os: val?.form?.Dokter_Mata_COA_OS ?? '',
        os_pupil: val?.form?.Dokter_Mata_Pupil_OS ?? '',
        os_iris: val?.form?.Dokter_Mata_Iris_OS ?? '',
        os_lens: val?.form?.Dokter_Mata_Lensa_OS ?? '',
        os_vitreous: val?.form?.Dokter_Mata_Vitreous_OS ?? '',
        funduscopy_os: val?.form?.Dokter_Mata_Funduscopy_OS ?? '',
        diagnose: val?.form?.Dokter_Mata_Diagnosa ?? '',
        terapi: val?.form?.Dokter_Mata_Terapi ?? '',
        rencana: val?.form?.Dokter_Mata_Rencana_Pengobatan ?? '',
        anjuran: val?.form?.Dokter_Mata_Anjuran ?? '',
        namaDokterMata: val?.form?.Nama_Dokter_Mata_Dokter ?? '',
        nama_perawat: (val?.form?.Nama_Perawat !== '') ? val?.form?.Nama_Perawat : undefined,
        ttd_perawat_pemeriksa: (val?.form?.TTD_Perawat !== '') ? val?.form?.TTD_Perawat : undefined,
        nik: val?.pasien?.NIK ?? '',

        triase_1: PdfAssesmentUgd.getCheckImage(val?.form?.Triase_Sekunder === 'Merah'),
        triase_2: PdfAssesmentUgd.getCheckImage(val?.form?.Triase_Sekunder === 'Kuning'),
        triase_3: PdfAssesmentUgd.getCheckImage(val?.form?.Triase_Sekunder === 'Hijau'),
        triase_4: PdfAssesmentUgd.getCheckImage(val?.form?.Triase_Sekunder === 'Hitam'),
        kesadaran_1: PdfAssesmentUgd.getCheckImage(val?.form?.Kesadaran_Value === '1'),
        kesadaran_2: PdfAssesmentUgd.getCheckImage(val?.form?.Kesadaran_Value === '2'),
        kesadaran_3: PdfAssesmentUgd.getCheckImage(val?.form?.Kesadaran_Value === '3'),
        kesadaran_4: PdfAssesmentUgd.getCheckImage(val?.form?.Kesadaran_Value === '4'),
        pernapasan_1: PdfAssesmentUgd.getCheckImage(val?.form?.Pernafasan_Value === '1'),
        pernapasan_2: PdfAssesmentUgd.getCheckImage(val?.form?.Pernafasan_Value === '2'),
        pernapasan_3: PdfAssesmentUgd.getCheckImage(val?.form?.Pernafasan_Value === '3'),
        pernapasan_4: PdfAssesmentUgd.getCheckImage(val?.form?.Pernafasan_Value === '4'),
        sirkulasi_1: PdfAssesmentUgd.getCheckImage(val?.form?.Sirkulasi_Value === '1'),
        sirkulasi_2: PdfAssesmentUgd.getCheckImage(val?.form?.Sirkulasi_Value === '2'),
        sirkulasi_3: PdfAssesmentUgd.getCheckImage(val?.form?.Sirkulasi_Value === '3'),
        sirkulasi_4: PdfAssesmentUgd.getCheckImage(val?.form?.Sirkulasi_Value === '4'),
        jalan_nafas_1: PdfAssesmentUgd.getCheckImage(val?.form?.Jalan_Nafas_Value === '1'),
        jalan_nafas_2: PdfAssesmentUgd.getCheckImage(val?.form?.Jalan_Nafas_Value === '2'),
        jalan_nafas_3: PdfAssesmentUgd.getCheckImage(val?.form?.Jalan_Nafas_Value === '3'),
        bantuan_nafas_1: PdfAssesmentUgd.getCheckImage(val?.form?.Bantuan_Nafas_Value === '1'),
        bantuan_nafas_2: PdfAssesmentUgd.getCheckImage(val?.form?.Bantuan_Nafas_Value === '2'),
        bantuan_nafas_3: PdfAssesmentUgd.getCheckImage(val?.form?.Bantuan_Nafas_Value === '3'),
        sirkulasi_tr_1: PdfAssesmentUgd.getCheckImage(val?.form?.Sirkulasi_Resusitasi_Value === '1'),
        sirkulasi_tr_2: PdfAssesmentUgd.getCheckImage(val?.form?.Sirkulasi_Resusitasi_Value === '2'),
        sirkulasi_tr_3: PdfAssesmentUgd.getCheckImage(val?.form?.Sirkulasi_Resusitasi_Value === '3'),
        autoanamnese: PdfAssesmentUgd.getCheckImage(val?.form?.Asal_Informasi === '1'),
        alloanamnese: PdfAssesmentUgd.getCheckImage(val?.form?.Asal_Informasi === '2'),
        fungsi_1: PdfAssesmentUgd.getCheckImage(val?.form?.Pengkajian_Fungsi === '1'),
        fungsi_2: PdfAssesmentUgd.getCheckImage(val?.form?.Pengkajian_Fungsi === '2'),
        fungsi_3: PdfAssesmentUgd.getCheckImage(val?.form?.Pengkajian_Fungsi === '3'),

        jatuh_1: PdfAssesmentUgd.getCheckImage(val?.form?.Penilaian_Risiko_Jatuh === 1),
        jatuh_2: PdfAssesmentUgd.getCheckImage(val?.form?.Penilaian_Risiko_Jatuh === 2),
        jatuh_3: PdfAssesmentUgd.getCheckImage(val?.form?.Risiko_Jatuh_Ibu_Hamil === 1),
        jatuh_4: PdfAssesmentUgd.getCheckImage(val?.form?.Risiko_Jatuh_Lanjut_Usia === 1),
        jatuh_5: PdfAssesmentUgd.getCheckImage(val?.form?.Risiko_Jatuh_Alat_Bantu === 1),
        hamil_1: PdfAssesmentUgd.getCheckImage(val?.form?.Status_Kehamilan === 2),
        hamil_2: PdfAssesmentUgd.getCheckImage(val?.form?.Status_Kehamilan === 1),
        gizi_1_1: PdfAssesmentUgd.getCheckImage(val?.form?.Penurunan_Berat_Badan === 0),
        gizi_1_2: PdfAssesmentUgd.getCheckImage(val?.form?.Penurunan_Berat_Badan === 2),
        gizi_1_3: PdfAssesmentUgd.getCheckImage(val?.form?.Penurunan_Berat_Badan === 3),
        gizi_1_3_1: PdfAssesmentUgd.getCheckImage(val?.form?.Penurunan_Berat_Badan === 3 && val?.form?.Penurunan_Berat_Badan_Nilai === 1),
        gizi_1_3_2: PdfAssesmentUgd.getCheckImage(val?.form?.Penurunan_Berat_Badan === 3 && val?.form?.Penurunan_Berat_Badan_Nilai === 2),
        gizi_1_3_3: PdfAssesmentUgd.getCheckImage(val?.form?.Penurunan_Berat_Badan === 3 && val?.form?.Penurunan_Berat_Badan_Nilai === 3),
        gizi_1_3_4: PdfAssesmentUgd.getCheckImage(val?.form?.Penurunan_Berat_Badan === 3 && val?.form?.Penurunan_Berat_Badan_Nilai === 4),
        gizi_1_3_5: PdfAssesmentUgd.getCheckImage(val?.form?.Penurunan_Berat_Badan === 3 && val?.form?.Penurunan_Berat_Badan_Nilai === 5),

        gizi_2_1: PdfAssesmentUgd.getCheckImage(val?.form?.Penurunan_Nafsu_Makan === 1),
        gizi_2_2: PdfAssesmentUgd.getCheckImage(val?.form?.Penurunan_Nafsu_Makan === 0),
        gizi_3_1: PdfAssesmentUgd.getCheckImage(!val?.form?.Nutrisi_Diagnosa_Khusus || val?.form?.Nutrisi_Diagnosa_Khusus === '' || val?.form?.Nutrisi_Diagnosa_Khusus === 'Tidak'),
        gizi_3_2: PdfAssesmentUgd.getCheckImage(val?.form?.Nutrisi_Diagnosa_Khusus && val?.form?.Nutrisi_Diagnosa_Khusus !== '' && val?.form?.Nutrisi_Diagnosa_Khusus !== 'Tidak'),
        lanjut_ya: undefined,
        lanjut_tidak: undefined,

        psikolog_1: PdfAssesmentUgd.getCheckImage(val?.form?.Psikologis_Cemas === 1),
        psikolog_2: PdfAssesmentUgd.getCheckImage(val?.form?.Psikologis_Takut === 1),
        psikolog_3: PdfAssesmentUgd.getCheckImage(val?.form?.Psikologis_Marah === 1),
        psikolog_4: PdfAssesmentUgd.getCheckImage(val?.form?.Psikologis_Sedih === 1),
        psikolog_5: PdfAssesmentUgd.getCheckImage(val?.form?.Psikologis_Kecenderungan_Bunuh_Diri === 1),
        psikolog_6: PdfAssesmentUgd.getCheckImage(val?.form?.Psikologis_Lain_Lain === 1),
        mental_1: PdfAssesmentUgd.getCheckImage(val?.form?.Mental_Sadar === 1),
        mental_2: PdfAssesmentUgd.getCheckImage(val?.form?.Mental_Perilaku === 1),
        mental_3: PdfAssesmentUgd.getCheckImage(val?.form?.Mental_Kekerasan === 1),
        sosial_baik: PdfAssesmentUgd.getCheckImage(false),
        sosial_tidak_baik: PdfAssesmentUgd.getCheckImage(false),
        dk_1: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Diagnosa_0 === 1),
        dk_2: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Diagnosa_1 === 1),
        dk_3: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Diagnosa_2 === 1),
        dk_4: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Diagnosa_3 === 1),
        dk_5: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Diagnosa_4 === 1),
        dk_6: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Diagnosa_5 === 1),
        dk_7: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Diagnosa_6 === 1),
        dk_8: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Diagnosa_7 === 1),
        rk_1: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Rencana_0 === 1),
        rk_2: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Rencana_1 === 1),
        rk_3: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Rencana_2 === 1),
        rk_4: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Rencana_3 === 1),
        rk_5: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Rencana_4 === 1),
        rk_6: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Rencana_5 === 1),
        rk_7: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Rencana_6 === 1),
        rk_8: PdfAssesmentUgd.getCheckImage(val?.form?.Keperawatan_Rencana_7 === 1),
        ttd_dokter_umum: (val?.form?.TTD_Dokter_Pengkaji !== '') ? val?.form?.TTD_Dokter_Pengkaji : undefined,
        MataOD: (val?.form?.Gambar_Mata_OD !== '') ? val?.form?.Gambar_Mata_OD : undefined,
        MataOS: (val?.form?.Gambar_Mata_OS !== '') ? val?.form?.Gambar_Mata_OS : undefined,
        ttd_dokter_mata: (val?.form?.TTD_Dokter_Mata !== '') ? val?.form?.TTD_Dokter_Mata : undefined,

        isResep: true,
        isResep0: true,
        resep: Array.isArray(val?.form?.Resep) ? val.form?.Resep.map((resep: any, i: number) => {
          return {
            no: `${i + 1}`,
            namaObat: resep.Nama_Obat,
            namaSatuan: resep.Nama_Satuan,
            jumlah: resep.Jumlah,
            aturanPakai: resep.Nama_AturanPakai,
            catatan: resep.Catatan,
          }
        }) : [],
        resep0: Array.isArray(val?.form?.Resep_Umum) ? val.form?.Resep_Umum.map((resep: any, i: number) => {
          return {
            no0: `${i + 1}`,
            namaObat0: resep.Nama_Obat,
            namaSatuan0: resep.Nama_Satuan,
            jumlah0: resep.Jumlah,
            aturanPakai0: resep.Nama_AturanPakai,
            catatan0: resep.Catatan,
          }
        }) : [],
      },
    })
  }
}
