import { DateTimeConverter } from "@src/shared/datetime-converter";
import { CreatePDFRequest, ICreatePDFRequest } from "@src/shared/pdf/requests/create-pdf.request";

export interface IPdfChecklistPraOperasiRequest extends ICreatePDFRequest {
  data: {
    nomor_mr: string,
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string,
    'pasien.Jenis_Kelamin': string,
    bb: string,
    tb: string,
    td: string,
    nadi: string,
    rr: string,
    t: string,
    '1_ya': string,
    '1_tidak': string,
    '2_ya': string,
    '2_tidak': string,
    '3_ya': string,
    '3_tidak': string,
    '4_ya': string,
    '4_tidak': string,
    '5_ya': string,
    '5_tidak': string,
    '6_ya': string,
    '6_tidak': string,
    '7_ya': string,
    '7_tidak': string,
    darah_a: string,
    darah_b: string,
    darah_ab: string,
    darah_o: string,
    rhesus_faktor: string,
    '8_ya': string,
    '8_tidak': string,
    pd_ya: string,
    pd_tidak: string,
    cc: string,
    '9_ya': string,
    '9_tidak': string,
    '10_ya': string,
    '10_tidak': string,
    '11_ya': string,
    '11_tidak': string,
    '12_ya': string,
    '12_tidak': string,
    '13_ya': string,
    '13_tidak': string,
    '14_ya': string,
    '14_tidak': string,
    '15_ya': string,
    '15_tidak': string,
    pemeriksaan_lain: string,
    catatan_perawat_ruangan: string,
    sato2: string,
    '16_cito': string,
    '16_elektif': string,
    '17_ya': string,
    jam_puasa: string,
    '17_tidak': string,
    '18_ya': string,
    dr_anestesi: string,
    '18_tidak': string,
    '19_ya': string,
    alergi: string,
    '19_tidak': string,
    '21_ya': string,
    '21_tidak': string,
    '21_tidak_ada': string,
    '22_ya': string,
    '22_tidak': string,
    '22_tidak_ada': string,
    '23_ya': string,
    '23_tidak': string,
    '23_tidak_ada': string,
    '24_ya': string,
    '24_tidak': string,
    '24_tidak_ada': string,
    '25_ya': string,
    '25_tidak': string,
    '25_tidak_ada': string,
    '26_ya': string,
    '26_tidak': string,
    '26_tidak_ada': string,
    '27_ya': string,
    '27_tidak': string,
    '27_tidak_ada': string,
    j_cairan: string,
    c_masuk: string,
    n_no: string,
    lokasi: string,
    j_mulai: string,
    dipasang_oleh: string,
    '20_ya': string,
    '20_tidak': string,
    '28_penandaan': string,
    '28_cukur': string,
    '28_pencucian': string,
    kk_lembab: string,
    kk_kering: string,
    kk_lainnya: string,
    tanggal_ttd: string,
    ttd_perawat_pengantar: string,
    nama_perawat_pengantar: string,
    ttd_perawat_penerima: string,
    nama_perawat_penerima: string,
    ttd_kaunit: string,
    nama_kaunit: string,
    nik: string,
  }
}

export class PdfChecklistPraOperasiRequest extends CreatePDFRequest {
  data: {
    nomor_mr: string,
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string,
    'pasien.Jenis_Kelamin': string,
    bb: string,
    tb: string,
    td: string,
    nadi: string,
    rr: string,
    t: string,
    '1_ya': string,
    '1_tidak': string,
    '2_ya': string,
    '2_tidak': string,
    '3_ya': string,
    '3_tidak': string,
    '4_ya': string,
    '4_tidak': string,
    '5_ya': string,
    '5_tidak': string,
    '6_ya': string,
    '6_tidak': string,
    '7_ya': string,
    '7_tidak': string,
    darah_a: string,
    darah_b: string,
    darah_ab: string,
    darah_o: string,
    rhesus_faktor: string,
    '8_ya': string,
    '8_tidak': string,
    pd_ya: string,
    pd_tidak: string,
    cc: string,
    '9_ya': string,
    '9_tidak': string,
    '10_ya': string,
    '10_tidak': string,
    '11_ya': string,
    '11_tidak': string,
    '12_ya': string,
    '12_tidak': string,
    '13_ya': string,
    '13_tidak': string,
    '14_ya': string,
    '14_tidak': string,
    '15_ya': string,
    '15_tidak': string,
    pemeriksaan_lain: string,
    catatan_perawat_ruangan: string,
    sato2: string,
    '16_cito': string,
    '16_elektif': string,
    '17_ya': string,
    jam_puasa: string,
    '17_tidak': string,
    '18_ya': string,
    dr_anestesi: string,
    '18_tidak': string,
    '19_ya': string,
    alergi: string,
    '19_tidak': string,
    '21_ya': string,
    '21_tidak': string,
    '21_tidak_ada': string,
    '22_ya': string,
    '22_tidak': string,
    '22_tidak_ada': string,
    '23_ya': string,
    '23_tidak': string,
    '23_tidak_ada': string,
    '24_ya': string,
    '24_tidak': string,
    '24_tidak_ada': string,
    '25_ya': string,
    '25_tidak': string,
    '25_tidak_ada': string,
    '26_ya': string,
    '26_tidak': string,
    '26_tidak_ada': string,
    '27_ya': string,
    '27_tidak': string,
    '27_tidak_ada': string,
    j_cairan: string,
    c_masuk: string,
    n_no: string,
    lokasi: string,
    j_mulai: string,
    dipasang_oleh: string,
    '20_ya': string,
    '20_tidak': string,
    '28_penandaan': string,
    '28_cukur': string,
    '28_pencucian': string,
    kk_lembab: string,
    kk_kering: string,
    kk_lainnya: string,
    tanggal_ttd: string,
    ttd_perawat_pengantar: string,
    nama_perawat_pengantar: string,
    ttd_perawat_penerima: string,
    nama_perawat_penerima: string,
    ttd_kaunit: string,
    nama_kaunit: string,
    nik: string,
  }

  constructor(req: IPdfChecklistPraOperasiRequest) {
    super(req);
    this.data = req.data;
  }

  static createFromJson(json: IPdfChecklistPraOperasiRequest) {
    return new PdfChecklistPraOperasiRequest(json);
  }

  static createPdfRequest(val: any, emrId: string): PdfChecklistPraOperasiRequest {
    return new PdfChecklistPraOperasiRequest({
      emr_id: emrId,
      form_name: 'rawat-jalan_checklist-pra-operasi',
      row_filter: '',
      preview: false,
      data: {
        nomor_mr: val?.nomor_mr ?? '',
        'pasien.Nama': val?.pasien?.Nama ?? '',
        'pasien.Tgl_Lahir': DateTimeConverter.convertToNormalDate(val?.pasien?.Tgl_Lahir),
        'pasien.Umur': this.normalizeAge(val?.umur_lengkap),
        'pasien.Jenis_Kelamin': val?.pasien?.Jenis_Kelamin ?? '',
        bb: val?.form?.Bb ?? '',
        tb: val?.form?.Tb ?? '',
        td: val?.form?.Td ?? '',
        nadi: val?.form?.Nadi ?? '',
        rr: val?.form?.Rr ?? '',
        t: val?.form?.T ?? '',
        '1_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Inform_Consent_Bedah === '1'),
        '1_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Inform_Consent_Bedah === '2'),
        '2_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Inform_Consent === '1'),
        '2_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Inform_Consent === '2'),
        '3_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Hamil === '1'),
        '3_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Hamil === '2'),
        '4_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Izin_Sterilisasi === '1'),
        '4_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Izin_Sterilisasi === '2'),
        '5_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Gelang_Pengenal === '1'),
        '5_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Gelang_Pengenal === '2'),
        '6_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Gelang_Alergi === '1'),
        '6_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Gelang_Alergi === '2'),
        '7_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Implant === '1'),
        '7_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Implant === '2'),
        darah_a: PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Golongan_Darah === '1'),
        darah_b: PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Golongan_Darah === '2'),
        darah_ab: PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Golongan_Darah === '3'),
        darah_o: PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Golongan_Darah === '4'),
        rhesus_faktor: val?.form?.Rhesus_Fektor ?? '',
        '8_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Ekg === '1'),
        '8_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Ekg === '2'),
        pd_ya: PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Persiapan_Darah === '1'),
        pd_tidak: PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Persiapan_Darah === '2'),
        cc: val?.form?.Persiapan_Darah_Keterangan ?? '',
        '9_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Foto_Fundus === '1'),
        '9_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Foto_Fundus === '2'),
        '10_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Usg_Mata === '1'),
        '10_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Usg_Mata === '2'),
        '11_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Biometri === '1'),
        '11_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Biometri === '2'),
        '12_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Makula === '1'),
        '12_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Makula === '2'),
        '13_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Laboratorium === '1'),
        '13_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Laboratorium === '2'),
        '14_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Radiologi === '1'),
        '14_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Radiologi === '2'),
        '15_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Resiko_Jatuh === '1'),
        '15_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Resiko_Jatuh === '2'),
        pemeriksaan_lain: val?.form?.Pemeriksaan_Lainnya ?? '',
        catatan_perawat_ruangan: val?.form?.Catatan_Perawat ?? '',
        sato2: val?.form?.Sat ?? '',
        '16_cito': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Jenis_Pasien === '1'),
        '16_elektif': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Jenis_Pasien === '2'),
        '17_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Puasa === '1'),
        jam_puasa: val?.form?.Puasa_Keterangan ?? '',
        '17_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Puasa === '2'),
        '18_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Anestesi === '1'),
        dr_anestesi: val?.form?.Dokter_Anestesi_Nama ?? '',
        '18_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Anestesi === '2'),
        '19_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Alergi === '1'),
        alergi: val?.form?.Alergi_Keterangan ?? '',
        '19_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Alergi === '2'),
        '21_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Gigi_Palsu === '1'),
        '21_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Gigi_Palsu === '3'),
        '21_tidak_ada': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Gigi_Palsu === '2'),
        '22_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Lensa === '1'),
        '22_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Lensa === '3'),
        '22_tidak_ada': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Lensa === '2'),
        '23_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Perhiasan === '1'),
        '23_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Perhiasan === '2'),
        '23_tidak_ada': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Perhiasan === '3'),
        '24_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Rambut === '1'),
        '24_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Rambut === '3'),
        '24_tidak_ada': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Rambut === '2'),
        '25_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Kosmetik === '1'),
        '25_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Kosmetik === '2'),
        '25_tidak_ada': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Kosmetik === '3'),
        '26_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Kandung_Kemih === '1'),
        '26_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Kandung_Kemih === '3'),
        '26_tidak_ada': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Kandung_Kemih === '2'),
        '27_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Gliserin === '1'),
        '27_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Gliserin === '3'),
        '27_tidak_ada': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Gliserin === '2'),
        j_cairan: val?.form?.Jenis_Cairan ?? '',
        c_masuk: val?.form?.Cairan_Masuk ?? '',
        n_no: val?.form?.Needle_No ?? '',
        lokasi: val?.form?.Lokasi ?? '',
        j_mulai: val?.form?.Jam_Mulai ?? '',
        dipasang_oleh: val?.form?.Infus_Dipasang ?? '',
        '20_ya': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Pre_Medikasi === '1'),
        '20_tidak': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Pre_Medikasi === '2'),
        '28_penandaan': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Pembedahan === '1'),
        '28_cukur': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Pembedahan === '2'),
        '28_pencucian': PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Pembedahan === '3'),
        kk_lembab: PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Kondisi_Kulit_Id === '1'),
        kk_kering: PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Kondisi_Kulit_Id === '2'),
        kk_lainnya: PdfChecklistPraOperasiRequest.getCheckImage(val?.form?.Kondisi_Kulit_Id === '3'),
        tanggal_ttd: DateTimeConverter.convertToNormalDate(val?.form?.Tanggal && val?.form?.Tanggal !== '' ? val?.form?.Tanggal.substring(0, 10) : ''),
        ttd_perawat_pengantar: (val?.form?.Tanda_Tangan_Perawat_Pengantar !== '') ? val?.form?.Tanda_Tangan_Perawat_Pengantar : 'https://bucket.rsmatasmec.com/gambar_putih_ttd.jpeg',
        nama_perawat_pengantar: (val?.form?.Nama_Perawat_Pengantar !== '') ? val?.form?.Nama_Perawat_Pengantar : undefined,
        ttd_perawat_penerima: (val?.form?.Tanda_Tangan_Perawat_Penerima !== '') ? val?.form?.Tanda_Tangan_Perawat_Penerima : undefined,
        nama_perawat_penerima: (val?.form?.Nama_Perawat_Penerima !== '') ? val?.form?.Nama_Perawat_Penerima : undefined,
        ttd_kaunit: (val?.form?.Tanda_Tangan_Kepala_Bedah !== '') ? val?.form?.Tanda_Tangan_Kepala_Bedah : undefined,
        nama_kaunit: (val?.form?.Nama_Kepala_Bedah !== '') ? val?.form?.Nama_Kepala_Bedah : undefined,
        nik: val?.pasien?.NIK ?? '',
      },
    })
  }
}
