import { DoctorModel, IDoctorModel } from "@src/shared/doctor/models/doctor.model";
import { DataModel, IDataModel } from '@shared/model';
import { IAssessmentUgdFormModel } from "@src/modules/emergency-room/assessment/models/assessment-ugd-models";
import { INursingEarlyWarning } from "@src/modules/inpatient/nursing-early-warning-scoring-table/models/nursing-early-warning-scoring.model";
import { IPerioperativeNursingRecordsFormModel } from "@src/modules/operating-room/perioperative-nursing-records/models/perioperative-nursing-records.model";

export interface IChecklistPraOperasiForm {
    T: string;
    Bb: string;
    Rr: string;
    Tb: string;
    Td: string;
    Ekg: string;
    Sat: string;
    Nadi: string;
    Hamil: string;
    Lensa: string;
    Puasa: string;
    Alergi: string;
    Lokasi: string;
    Makula: string;
    Rambut: string;
    Implant: string;
    Tanggal: string;
    Anestesi: string;
    Biometri: string;
    Gliserin: string;
    Kosmetik: string;
    Usg_Mata: string;
    Jam_Mulai: string;
    Needle_No: string;
    Perhiasan: string;
    Radiologi: string;
    Gigi_Palsu: string;
    ID_Petugas: string;
    Pembedahan: string;
    Updated_At: string;
    Updated_By: string;
    Foto_Fundus: string;
    Cairan_Masuk: string;
    Jenis_Cairan: string;
    Jenis_Pasien: string;
    Dokter_Anestesi_Id: string;
    Dokter_Anestesi_Nama: string
    Laboratorium: string;
    Nama_Petugas: string;
    Pre_Medikasi: string;
    Resiko_Jatuh: string;
    Gelang_Alergi: string;
    Kandung_Kemih: string;
    Rhesus_Fektor: string;
    Golongan_Darah: string;
    Inform_Consent: string;
    Infus_Dipasang: string;
    Catatan_Perawat: string;
    Gelang_Pengenal: string;
    Persiapan_Darah: string;
    Izin_Sterilisasi: string;
    Kondisi_Kulit_Id: string;
    Puasa_Keterangan: string;
    Alergi_Keterangan: string;
    Nama_Kepala_Bedah: string;
    Pemeriksaan_Lainnya: string;
    Inform_Consent_Bedah: string;
    Nama_Perawat_Penerima: string;
    Nama_Perawat_Pengantar: string;
    Tanda_Tangan_Kepala_Bedah: string;
    Persiapan_Darah_Keterangan: string;
    ID_Tanda_Tangan_Kepala_Bedah: string;
    Tanda_Tangan_Perawat_Penerima: string;
    Tanda_Tangan_Perawat_Pengantar: string;
    ID_Tanda_Tangan_Perawat_Penerima: string;
    ID_Tanda_Tangan_Perawat_Pengantar: string;
}

export class IChecklistPraOperasiForm {
    T: string;
    Bb: string;
    Rr: string;
    Tb: string;
    Td: string;
    Ekg: string;
    Sat: string;
    Nadi: string;
    Hamil: string;
    Lensa: string;
    Puasa: string;
    Alergi: string;
    Lokasi: string;
    Makula: string;
    Rambut: string;
    Implant: string;
    Tanggal: string;
    Anestesi: string;
    Biometri: string;
    Gliserin: string;
    Kosmetik: string;
    Usg_Mata: string;
    Jam_Mulai: string;
    Needle_No: string;
    Perhiasan: string;
    Radiologi: string;
    Gigi_Palsu: string;
    ID_Petugas: string;
    Pembedahan: string;
    Updated_At: string;
    Updated_By: string;
    Foto_Fundus: string;
    Cairan_Masuk: string;
    Jenis_Cairan: string;
    Jenis_Pasien: string;
    Dokter_Anestesi_Id: string;
    Dokter_Anestesi_Nama: string
    Laboratorium: string;
    Nama_Petugas: string;
    Pre_Medikasi: string;
    Resiko_Jatuh: string;
    Gelang_Alergi: string;
    Kandung_Kemih: string;
    Rhesus_Fektor: string;
    Golongan_Darah: string;
    Inform_Consent: string;
    Infus_Dipasang: string;
    Catatan_Perawat: string;
    Gelang_Pengenal: string;
    Persiapan_Darah: string;
    Izin_Sterilisasi: string;
    Kondisi_Kulit_Id: string;
    Puasa_Keterangan: string;
    Alergi_Keterangan: string;
    Nama_Kepala_Bedah: string;
    Pemeriksaan_Lainnya: string;
    Inform_Consent_Bedah: string;
    Nama_Perawat_Penerima: string;
    Nama_Perawat_Pengantar: string;
    Tanda_Tangan_Kepala_Bedah: string;
    Persiapan_Darah_Keterangan: string;
    ID_Tanda_Tangan_Kepala_Bedah: string;
    Tanda_Tangan_Perawat_Penerima: string;
    Tanda_Tangan_Perawat_Pengantar: string;
    ID_Tanda_Tangan_Perawat_Penerima: string;
    ID_Tanda_Tangan_Perawat_Pengantar: string;

    constructor(request: IChecklistPraOperasiForm) {
      this.T = request.T;
      this.Bb = request.Bb;
      this.Rr = request.Rr;
      this.Tb = request.Tb;
      this.Td = request.Td;
      this.Ekg = request.Ekg;
      this.Sat = request.Sat;
      this.Nadi = request.Nadi;
      this.Hamil = request.Hamil;
      this.Lensa = request.Lensa;
      this.Puasa = request.Puasa;
      this.Alergi = request.Alergi;
      this.Lokasi = request.Lokasi;
      this.Makula = request.Makula;
      this.Rambut = request.Rambut;
      this.Implant = request.Implant;
      this.Tanggal = request.Tanggal;
      this.Anestesi = request.Anestesi;
      this.Biometri = request.Biometri;
      this.Gliserin = request.Gliserin;
      this.Kosmetik = request.Kosmetik;
      this.Usg_Mata = request.Usg_Mata;
      this.Jam_Mulai = request.Jam_Mulai;
      this.Needle_No = request.Needle_No;
      this.Perhiasan = request.Perhiasan;
      this.Radiologi = request.Radiologi;
      this.Gigi_Palsu = request.Gigi_Palsu;
      this.ID_Petugas = request.ID_Petugas;
      this.Pembedahan = request.Pembedahan;
      this.Updated_At = request.Updated_At;
      this.Updated_By = request.Updated_By;
      this.Foto_Fundus = request.Foto_Fundus;
      this.Cairan_Masuk = request.Cairan_Masuk;
      this.Jenis_Cairan = request.Jenis_Cairan;
      this.Jenis_Pasien = request.Jenis_Pasien;
      this.Dokter_Anestesi_Id = request.Dokter_Anestesi_Id;
      this.Dokter_Anestesi_Nama = request.Dokter_Anestesi_Nama;
      this.Laboratorium = request.Laboratorium;
      this.Nama_Petugas = request.Nama_Petugas;
      this.Pre_Medikasi = request.Pre_Medikasi;
      this.Resiko_Jatuh = request.Resiko_Jatuh;
      this.Gelang_Alergi = request.Gelang_Alergi;
      this.Kandung_Kemih = request.Kandung_Kemih;
      this.Rhesus_Fektor = request.Rhesus_Fektor;
      this.Golongan_Darah = request.Golongan_Darah;
      this.Inform_Consent = request.Inform_Consent;
      this.Infus_Dipasang = request.Infus_Dipasang;
      this.Catatan_Perawat = request.Catatan_Perawat;
      this.Gelang_Pengenal = request.Gelang_Pengenal;
      this.Persiapan_Darah = request.Persiapan_Darah;
      this.Izin_Sterilisasi = request.Izin_Sterilisasi;
      this.Kondisi_Kulit_Id = request.Kondisi_Kulit_Id;
      this.Puasa_Keterangan = request.Puasa_Keterangan;
      this.Alergi_Keterangan = request.Alergi_Keterangan;
      this.Nama_Kepala_Bedah = request.Nama_Kepala_Bedah;
      this.Pemeriksaan_Lainnya = request.Pemeriksaan_Lainnya;
      this.Inform_Consent_Bedah = request.Inform_Consent_Bedah;
      this.Nama_Perawat_Penerima = request.Nama_Perawat_Penerima;
      this.Nama_Perawat_Pengantar = request.Nama_Perawat_Pengantar;
      this.Tanda_Tangan_Kepala_Bedah = request.Tanda_Tangan_Kepala_Bedah;
      this.Persiapan_Darah_Keterangan = request.Persiapan_Darah_Keterangan;
      this.ID_Tanda_Tangan_Kepala_Bedah = request.ID_Tanda_Tangan_Kepala_Bedah;
      this.Tanda_Tangan_Perawat_Penerima = request.Tanda_Tangan_Perawat_Penerima;
      this.Tanda_Tangan_Perawat_Pengantar = request.Tanda_Tangan_Perawat_Pengantar;
      this.ID_Tanda_Tangan_Perawat_Penerima = request.ID_Tanda_Tangan_Perawat_Penerima;
      this.ID_Tanda_Tangan_Perawat_Pengantar = request.ID_Tanda_Tangan_Perawat_Pengantar;
    }
}

export interface IChecklistPraOperasiModel extends IDataModel {
    form: IChecklistPraOperasiForm;
    dokter: Array<IDoctorModel>;
    asesmen: IAssessmentUgdFormModel;
    ews: INursingEarlyWarning;
    tanda_vital: IPerioperativeNursingRecordsFormModel;
}

export class ChecklistPraOperasiModel extends DataModel {
    form: IChecklistPraOperasiForm;
    dokter: Array<IDoctorModel>;
    asesmen?: IAssessmentUgdFormModel;
    ews?: INursingEarlyWarning;
    tanda_vital: IPerioperativeNursingRecordsFormModel;

    constructor(req: IChecklistPraOperasiModel) {
      super(req)
      this.form = req.form;
      this.dokter = (Array.isArray(req.dokter)) ? req.dokter.map((a) => new DoctorModel(a)) : [];
      this.asesmen = req.asesmen;
      this.ews = req.ews;
      this.tanda_vital = req.tanda_vital;
    }
}
