export default [
  {
    id: '1',
    text: 'Apakah ada laporan efek samping Obat yang serupa?',
    label_ya:'1',
    label_tidak:'0',
    label_tidak_diketahui:'0',
  },
  {
    id: '2',
    text: 'Apakah efek samping Obat terjadi setelah pemberian Obat yang dicurigai?',
    label_ya:'2',
    label_tidak:'-1',
    label_tidak_diketahui:'0',
  },
  {
    id: '3',
    text: 'Apakah efek samping Obat membaik setelah Obat dihentikan atau Obat antagonis khusus diberikan? ',
    label_ya:'1',
    label_tidak:'0',
    label_tidak_diketahui:'0',
  },
  {
    id: '4',
    text: 'Apakah efek samping Obat terjadi berulang setelah obat diberikan kembali?',
    label_ya:'2',
    label_tidak:'-1',
    label_tidak_diketahui:'0',
  },
  {
    id: '5',
    text: 'Apakah ada alternative penyebab yang dapat menjelaskan kemungkinan terjadinya efek samping Obat?',
    label_ya:'-1',
    label_tidak:'2',
    label_tidak_diketahui:'0',
  },
  {
    id: '6',
    text: 'Apakah efek samping Obat muncul kembali ketika placebo diberikan?',
    label_ya:'-1',
    label_tidak:'-1',
    label_tidak_diketahui:'0',
  },
  {
    id: '7',
    text: 'Apakah Obat yang dicurigai terdeteksi di dalam darah atau cairan tubuh lainnya dengan konsentrasi yang toksik?',
    label_ya:'1',
    label_tidak:'0',
    label_tidak_diketahui:'0',
  },
  {
    id: '8',
    text: 'Apakah efek samping Obat bertambah parah ketika dosis Obat ditingkatkan atau bertambah ringan ketika Obat diturunkan dosisnya?',
    label_ya:'1',
    label_tidak:'0',
    label_tidak_diketahui:'0',
  },
  {
    id: '9',
    text: 'Apakah pasien pernah mengalami efek samping Obat yang sama atau dengan Obat yang mirip sebelumnya?',
    label_ya:'1',
    label_tidak:'0',
    label_tidak_diketahui:'0',
  },
  {
    id: '10',
    text: 'Apakah efek samping Obat dapat dikonfirmasi dengan bukti yang obyekti?',
    label_ya:'1',
    label_tidak:'0',
    label_tidak_diketahui:'0',
  },
];