import { IProvisionOfInformationFormModel } from "@src/modules/outpatient/inform-consent/models/inform-consent.model";
import { DataModel, IDataModel } from "@src/shared/model"


/*kamar*/
export interface IRoomModel {
  ID_Kamar: number;
  ID_KelasKamar: string;
  Nama_Kamar: string;
  Kode_Kamar: string;
  Tarif: number;
}

export class RoomModel {
  ID_Kamar: number;
  ID_KelasKamar: string;
  Nama_Kamar: string;
  Kode_Kamar: string;
  Tarif: number;

  constructor(request: IRoomModel) {
    this.ID_Kamar = request.ID_Kamar;
    this.ID_KelasKamar = request.ID_KelasKamar;
    this.Nama_Kamar = request.Nama_Kamar;
    this.Kode_Kamar = request.Kode_Kamar;
    this.Tarif = request.Tarif;
  }

}


export interface INursingCarePlanModel {
  Diagnosa_Medis: string;
  Kamar_Id: string;
  Perawat_Id: string;
  Nama_Perawat: string;

  Tanggal_Si: string;
  Diagnosa1_Si_Check: string;
  Diagnosa1_Si_1_Check: string;
  Diagnosa1_Si_2_Check: string;
  Diagnosa1_Si_3_Check: string;

  Diagnosa2_Si_Check: string;
  Diagnosa2_Si_1_Check: string;
  Diagnosa2_Si_2_Check: string;
  Diagnosa2_Si_3_Check: string;

  Diagnosa3_Si_Check: string;
  Diagnosa3_Si_1_Check: string;
  Diagnosa3_Si_2_Check: string;

  Tujuan1_Si_Check: string;
  Tujuan1_Si_Jam_1: string;
  Tujuan1_Si_Jam_2: string;
  Tujuan1_Si_1_Check: string;
  Tujuan1_Si_2_Check: string;
  Tujuan1_Si_3_Check: string;
  Tujuan1_Si_3_Text: string;
  Tujuan2_Si_Check: string;
  Tujuan2_Si_Jam_1: string;
  Tujuan2_Si_Jam_2: string;
  Tujuan2_Si_1_Check: string;
  Tujuan2_Si_2_Check: string;
  Tujuan2_Si_3_Check: string;
  Tujuan2_Si_4_Check: string;
  Tujuan2_Si_5_Check: string;
  Tujuan3_Si_Check: string;
  Tujuan3_Si_Text : string;

  Rencana1_Si_Check: string;
  Rencana1_Si_1_Check: string;
  Rencana1_Si_2_Check: string;
  Rencana1_Si_3_Check: string;
  Rencana1_Si_4_Check: string;
  Rencana1_Si_5_Check: string;
  Rencana1_Si_6_Check: string;
  Rencana1_Si_7_Check: string;
  Rencana1_Si_8_Check: string;
  Rencana2_Si_Check: string;
  Rencana2_Si_1_Check: string;
  Rencana2_Si_1_Text: string;
  Rencana2_Si_2_Check: string;
  Rencana2_Si_2_Text: string;
  Rencana2_Si_3_Check: string;
  Rencana2_Si_3_Text: string;

  Tanggal_Ps: string;
  Diagnosa1_Ps_Check: string;
  Diagnosa1_Ps_1_Check: string;
  Diagnosa1_Ps_1_Text: string;
  Diagnosa1_Ps_2_Check: string;
  Diagnosa1_Ps_2_Text: string;
  Diagnosa1_Ps_3_Check: string;
  Diagnosa1_Ps_3_Text: string;
  Diagnosa1_Ps_4_Check: string;
  Diagnosa1_Ps_5_Check: string;
  Diagnosa1_Ps_6_Check: string;

  Tujuan1_Ps_Check: string;
  Tujuan1_Ps_Jam_1: string;
  Tujuan1_Ps_Jam_2: string;
  Tujuan1_Ps_1_Check: string;
  Tujuan1_Ps_2_Check: string;
  Tujuan1_Ps_3_Check: string;
  Tujuan1_Ps_4_Check: string;

  Rencana1_Ps_1_Check: string;
  Rencana1_Ps_2_Check: string;
  Rencana1_Ps_3_Check: string;
  Rencana1_Ps_4_Check: string;
  Rencana1_Ps_5_Check: string;
  Rencana1_Ps_6_Check: string;
  Rencana1_Ps_7_Check: string;
  Rencana2_Ps_1_Check: string;
  Rencana2_Ps_1_Text: string;
  Rencana2_Ps_2_Check: string;
  Rencana2_Ps_2_Text: string;
  Rencana2_Ps_3_Check: string;
  Rencana2_Ps_3_Text: string;

  Tanggal_Nc: string;
  Diagnosa1_Nc_Check: string;
  Diagnosa1_Nc_1_Check: string;
  Diagnosa1_Nc_2_Check: string;
  Diagnosa1_Nc_3_Check: string;
  Diagnosa2_Nc_Check: string;
  Diagnosa2_Nc_1_Check: string;
  Diagnosa3_Nc_Check: string;
  Diagnosa3_Nc_1_Check: string;
  Diagnosa3_Nc_2_Check: string;
  Diagnosa3_Nc_3_Check: string;
  Diagnosa3_Nc_4_Check: string;
  Diagnosa3_Nc_5_Check: string;
  Diagnosa3_Nc_5_Text: string;
  Diagnosa4_Nc_Check: string;
  Diagnosa4_Nc_1_Check: string;
  Diagnosa5_Nc_Check: string;
  Diagnosa5_Nc_1_Check: string;
  Diagnosa5_Nc_2_Check: string;
  Tujuan1_Nc_Check: string;
  Tujuan1_Nc_Jam_1: string;
  Tujuan1_Nc_Jam_2: string;
  Tujuan1_Nc_1_Check: string;
  Tujuan1_Nc_2_Check: string;
  Tujuan1_Nc_3_Check: string;
  Tujuan1_Nc_4_Check: string;
  Tujuan1_Nc_5_Check: string;
  Tujuan1_Nc_6_Check: string;
  Tujuan1_Nc_6_Text: string;
  Tujuan2_Nc_Check: string;
  Tujuan2_Nc_Jam_1: string;
  Tujuan2_Nc_Jam_2: string;
  Tujuan2_Nc_1_Check: string;
  Tujuan2_Nc_2_Check: string;
  Tujuan2_Nc_3_Check: string;
  Tujuan2_Nc_4_Check: string;
  Tujuan3_Nc_Check: string;
  Tujuan3_Nc_Jam_1: string;
  Tujuan3_Nc_Jam_2: string;
  Tujuan3_Nc_1_Check: string;
  Tujuan3_Nc_2_Check: string;
  Tujuan3_Nc_3_Check: string;
  Tujuan3_Nc_3_Text: string;
  Tujuan4_Nc_Check: string;
  Rencana1_Nc_1_Check: string;
  Rencana1_Nc_2_Check: string;
  Rencana1_Nc_3_Check: string;
  Rencana1_Nc_3_Text: string;
  Rencana1_Nc_4_Check: string;
  Rencana1_Nc_5_Check: string;
  Rencana1_Nc_6_Check: string;
  Rencana1_Nc_7_Check: string;
  Rencana1_Nc_8_Check: string;
  Rencana1_Nc_9_Check: string;
  Rencana1_Nc_10_Check: string;
  Rencana1_Nc_11_Check: string;
  Rencana1_Nc_12_Check: string;
  Rencana1_Nc_12_Text: string;
  Rencana2_Nc_1_Check: string;
  Rencana2_Nc_2_Check: string;
  Rencana2_Nc_3_Check: string;
  Rencana2_Nc_3_Text: string;

  Tanggal_Kd: string;
  Diagnosa1_Kd_Check: string;
  Diagnosa1_Kd_1_Check: string;
  Diagnosa1_Kd_2_Check: string;
  Diagnosa1_Kd_3_Check: string;
  Diagnosa1_Kd_4_Check: string;
  Diagnosa2_Kd_Check: string;
  Diagnosa2_Kd_Text: string;
  Tujuan1_Kd_Check: string;
  Tujuan1_Kd_Jam_1: string;
  Tujuan1_Kd_Jam_2: string;
  Tujuan1_Kd_1_Check: string;
  Tujuan1_Kd_2_Check: string;
  Tujuan2_Kd_Check: string;
  Tujuan2_Kd_Jam_1: string;
  Tujuan2_Kd_Jam_2: string;
  Tujuan2_Kd_1_Check: string;
  Tujuan2_Kd_1_Text: string;
  Rencana1_Kd_1_Check: string;
  Rencana1_Kd_2_Check: string;
  Rencana1_Kd_3_Check: string;
  Rencana1_Kd_4_Check: string;
  Rencana1_Kd_5_Check: string;
  Rencana1_Kd_6_Check: string;
  Rencana1_Kd_7_Check: string;
  Rencana1_Kd_7_Text: string;
  Rencana2_Kd_1_Check: string;
  Rencana2_Kd_1_Text: string;


  Tanggal_It: string;
  Diagnosa1_It_Check: string;
  Diagnosa1_It_1_Check: string;
  Diagnosa1_It_2_Check: string;
  Diagnosa2_It_Check: string;
  Diagnosa2_It_1_Check: string;
  Diagnosa2_It_2_Check: string;
  Diagnosa2_It_3_Check: string;
  Diagnosa3_It_Check: string;
  Diagnosa3_It_Text: string;
  Tujuan1_It_Check: string;
  Tujuan1_It_Jam_1: string;
  Tujuan1_It_Jam_2: string;
  Tujuan1_It_1_Check: string;
  Tujuan1_It_2_Check: string;
  Tujuan1_It_3_Check: string;
  Tujuan1_It_4_Check: string;
  Tujuan2_It_Check: string;
  Tujuan2_It_Jam_1: string;
  Tujuan2_It_Jam_2: string;
  Tujuan2_It_1_Check: string;
  Tujuan2_It_2_Check: string;
  Tujuan2_It_2_Text: string;
  Rencana1_It_1_Check: string;
  Rencana1_It_2_Check: string;
  Rencana1_It_3_Check: string;
  Rencana1_It_4_Check: string;
  Rencana1_It_5_Check: string;
  Rencana1_It_6_Check: string;
  Rencana1_It_7_Check: string;
  Rencana1_It_8_Check: string;
  Rencana1_It_9_Check: string;
  Rencana1_It_10_Check: string;
  Rencana1_It_10_Text: string;
  Rencana2_It_1_Check: string;
  Rencana2_It_1_Text: string;
  Rencana2_It_2_Check: string;
  Rencana2_It_2_Text: string;

  Tanggal_Psi: string;
  Diagnosa1_Psi_Check: string;
  Diagnosa1_Psi_1_Check: string;
  Diagnosa1_Psi_2_Check: string;
  Diagnosa1_Psi_3_Check: string;
  Diagnosa1_Psi_4_Check: string;
  Diagnosa1_Psi_5_Check: string;
  Diagnosa2_Psi_Check: string;
  Diagnosa2_Psi_1_Check: string;
  Diagnosa2_Psi_2_Check: string;
  Diagnosa2_Psi_3_Check: string;
  Diagnosa3_Psi_Check: string;
  Diagnosa3_Psi_1_Check: string;
  Diagnosa3_Psi_2_Check: string;
  Diagnosa3_Psi_3_Check: string;
  Tujuan1_Psi_Check: string;
  Tujuan1_Psi_Jam_1: string;
  Tujuan1_Psi_Jam_2: string;
  Tujuan1_Psi_1_Check: string;
  Tujuan1_Psi_2_Check: string;
  Tujuan1_Psi_3_Check: string;
  Tujuan1_Psi_4_Check: string;
  Tujuan2_Psi_Check: string;
  Tujuan2_Psi_Jam_1: string;
  Tujuan2_Psi_Jam_2: string;
  Tujuan2_Psi_1_Check: string;
  Tujuan2_Psi_2_Check: string;
  Tujuan3_Psi_Check: string;
  Tujuan3_Psi_Jam_1: string;
  Tujuan3_Psi_Jam_2: string;
  Tujuan3_Psi_1_Check: string;
  Tujuan3_Psi_2_Check: string;
  Tujuan3_Psi_3_Check: string;
  Rencana1_Psi_1_Check: string;
  Rencana1_Psi_2_Check: string;
  Rencana1_Psi_3_Check: string;
  Rencana1_Psi_4_Check: string;
  Rencana1_Psi_5_Check: string;
  Rencana1_Psi_6_Check: string;
  Rencana1_Psi_7_Check: string;
  Rencana1_Psi_8_Check: string;
  Rencana1_Psi_9_Check: string;
  Rencana1_Psi_10_Check: string;
  Rencana1_Psi_11_Check: string;
  Rencana2_Psi_1_Check: string;
  Rencana2_Psi_2_Check: string;
  Rencana2_Psi_2_Text: string;
  Rencana2_Psi_3_Check: string;
  Rencana2_Psi_3_Text: string;
  Tanggal_Ps1: string;
  Diagnosa1_Ps1_Check: string;
  Diagnosa1_Ps1_1_Check: string;
  Diagnosa1_Ps1_1_Text: string;
  Diagnosa1_Ps1_2_Check: string;
  Diagnosa1_Ps1_2_Text: string;
  Diagnosa1_Ps1_3_Check: string;
  Diagnosa1_Ps1_3_Text: string;
  Diagnosa1_Ps1_4_Check: string;
  Diagnosa1_Ps1_5_Check: string;
  Tujuan1_Ps1_Check: string;
  Tujuan1_Ps1_1_Check: string;
  Tujuan1_Ps1_2_Check: string;
  Rencana1_Ps1_1_Check: string;
  Rencana1_Ps1_2_Check: string;
  Rencana1_Ps1_3_Check: string;
  Rencana1_Ps1_4_Check: string;
  Rencana1_Ps1_5_Check: string;
  Rencana2_Ps1_1_Check: string;
  Rencana2_Ps1_2_Check: string;
  Rencana2_Ps1_2_Text: string;
  Tanggal_Si1: string;
  Diagnosa1_Si1_Check: string;
  Diagnosa1_Si1_1_Check: string;
  Diagnosa1_Si1_2_Check: string;
  Diagnosa1_Si1_3_Check: string;
  Diagnosa1_Si1_4_Check: string;
  Diagnosa1_Si1_5_Check: string;
  Tujuan1_Si1_Check: string;
  Tujuan1_Si1_Jam_1: string;
  Tujuan1_Si1_Jam_2: string;
  Tujuan1_Si1_1_Check: string;
  Tujuan1_Si1_2_Check: string;
  Tujuan1_Si1_3_Check: string;
  Tujuan1_Si1_3_Text: string;
  Rencana1_Si1_1_Check: string;
  Rencana1_Si1_2_Check: string;
  Rencana1_Si1_3_Check: string;
  Rencana1_Si1_4_Check: string;
  Rencana1_Si1_5_Check: string;
  Rencana1_Si1_6_Check: string;
  Rencana1_Si1_7_Check: string;
  Rencana1_Si1_8_Check: string;
  Rencana2_Si1_1_Check: string;
  Rencana2_Si1_1_Text: string;
  Rencana2_Si1_2_Check: string;
  Rencana2_Si1_2_Text: string;
  Rencana2_Si1_3_Check: string;
  Rencana2_Si1_3_Text: string
  Updated_At: string;
  Updated_By: string;
}

export class NursingCarePlanModel {
  Diagnosa_Medis: string;
  Kamar_Id: string;
  Perawat_Id: string;
  Nama_Perawat: string;

  Tanggal_Si: string;
  Diagnosa1_Si_Check: string;
  Diagnosa1_Si_1_Check: string;
  Diagnosa1_Si_2_Check: string;
  Diagnosa1_Si_3_Check: string;

  Diagnosa2_Si_Check: string;
  Diagnosa2_Si_1_Check: string;
  Diagnosa2_Si_2_Check: string;
  Diagnosa2_Si_3_Check: string;

  Diagnosa3_Si_Check: string;
  Diagnosa3_Si_1_Check: string;
  Diagnosa3_Si_2_Check: string;

  Tujuan1_Si_Check: string;
  Tujuan1_Si_Jam_1: string;
  Tujuan1_Si_Jam_2: string;
  Tujuan1_Si_1_Check: string;
  Tujuan1_Si_2_Check: string;
  Tujuan1_Si_3_Check: string;
  Tujuan1_Si_3_Text: string;
  Tujuan2_Si_Check: string;
  Tujuan2_Si_Jam_1: string;
  Tujuan2_Si_Jam_2: string;
  Tujuan2_Si_1_Check: string;
  Tujuan2_Si_2_Check: string;
  Tujuan2_Si_3_Check: string;
  Tujuan2_Si_4_Check: string;
  Tujuan2_Si_5_Check: string;
  Tujuan3_Si_Check: string;

  Rencana1_Si_Check: string;
  Rencana1_Si_1_Check: string;
  Rencana1_Si_2_Check: string;
  Rencana1_Si_3_Check: string;
  Rencana1_Si_4_Check: string;
  Rencana1_Si_5_Check: string;
  Rencana1_Si_6_Check: string;
  Rencana1_Si_7_Check: string;
  Rencana1_Si_8_Check: string;
  Rencana2_Si_Check: string;
  Rencana2_Si_1_Check: string;
  Rencana2_Si_1_Text: string;
  Rencana2_Si_2_Check: string;
  Rencana2_Si_2_Text: string;
  Rencana2_Si_3_Check: string;
  Rencana2_Si_3_Text: string;
  Tujuan3_Si_Text : string;

  Tanggal_Ps: string;
  Diagnosa1_Ps_Check: string;
  Diagnosa1_Ps_1_Check: string;
  Diagnosa1_Ps_1_Text: string;
  Diagnosa1_Ps_2_Check: string;
  Diagnosa1_Ps_2_Text: string;
  Diagnosa1_Ps_3_Check: string;
  Diagnosa1_Ps_3_Text: string;
  Diagnosa1_Ps_4_Check: string;
  Diagnosa1_Ps_5_Check: string;
  Diagnosa1_Ps_6_Check: string;
  Tujuan1_Ps_Check: string;
  Tujuan1_Ps_Jam_1: string;
  Tujuan1_Ps_Jam_2: string;
  Tujuan1_Ps_1_Check: string;
  Tujuan1_Ps_2_Check: string;
  Tujuan1_Ps_3_Check: string;
  Tujuan1_Ps_4_Check: string;
  Rencana1_Ps_1_Check: string;
  Rencana1_Ps_2_Check: string;
  Rencana1_Ps_3_Check: string;
  Rencana1_Ps_4_Check: string;
  Rencana1_Ps_5_Check: string;
  Rencana1_Ps_6_Check: string;
  Rencana1_Ps_7_Check: string;
  Rencana2_Ps_1_Check: string;
  Rencana2_Ps_1_Text: string;
  Rencana2_Ps_2_Check: string;
  Rencana2_Ps_2_Text: string;
  Rencana2_Ps_3_Check: string;
  Rencana2_Ps_3_Text: string;
  Tanggal_Nc: string;
  Diagnosa1_Nc_Check: string;
  Diagnosa1_Nc_1_Check: string;
  Diagnosa1_Nc_2_Check: string;
  Diagnosa1_Nc_3_Check: string;
  Diagnosa2_Nc_Check: string;
  Diagnosa2_Nc_1_Check: string;
  Diagnosa3_Nc_Check: string;
  Diagnosa3_Nc_1_Check: string;
  Diagnosa3_Nc_2_Check: string;
  Diagnosa3_Nc_3_Check: string;
  Diagnosa3_Nc_4_Check: string;
  Diagnosa3_Nc_5_Check: string;
  Diagnosa3_Nc_5_Text: string;
  Diagnosa4_Nc_Check: string;
  Diagnosa4_Nc_1_Check: string;
  Diagnosa5_Nc_Check: string;
  Diagnosa5_Nc_1_Check: string;
  Diagnosa5_Nc_2_Check: string;
  Tujuan1_Nc_Check: string;
  Tujuan1_Nc_Jam_1: string;
  Tujuan1_Nc_Jam_2: string;
  Tujuan1_Nc_1_Check: string;
  Tujuan1_Nc_2_Check: string;
  Tujuan1_Nc_3_Check: string;
  Tujuan1_Nc_4_Check: string;
  Tujuan1_Nc_5_Check: string;
  Tujuan1_Nc_6_Check: string;
  Tujuan1_Nc_6_Text: string;
  Tujuan2_Nc_Check: string;
  Tujuan2_Nc_Jam_1: string;
  Tujuan2_Nc_Jam_2: string;
  Tujuan2_Nc_1_Check: string;
  Tujuan2_Nc_2_Check: string;
  Tujuan2_Nc_3_Check: string;
  Tujuan2_Nc_4_Check: string;
  Tujuan3_Nc_Check: string;
  Tujuan3_Nc_Jam_1: string;
  Tujuan3_Nc_Jam_2: string;
  Tujuan3_Nc_1_Check: string;
  Tujuan3_Nc_2_Check: string;
  Tujuan3_Nc_3_Check: string;
  Tujuan3_Nc_3_Text: string;
  Tujuan4_Nc_Check: string;

  Rencana1_Nc_1_Check: string;
  Rencana1_Nc_2_Check: string;
  Rencana1_Nc_3_Check: string;
  Rencana1_Nc_3_Text: string;
  Rencana1_Nc_4_Check: string;
  Rencana1_Nc_5_Check: string;
  Rencana1_Nc_6_Check: string;
  Rencana1_Nc_7_Check: string;
  Rencana1_Nc_8_Check: string;
  Rencana1_Nc_9_Check: string;
  Rencana1_Nc_10_Check: string;
  Rencana1_Nc_11_Check: string;
  Rencana1_Nc_12_Check: string;
  Rencana1_Nc_12_Text: string;
  Rencana2_Nc_1_Check: string;
  Rencana2_Nc_2_Check: string;
  Rencana2_Nc_3_Check: string;
  Rencana2_Nc_3_Text: string;
  Tanggal_Kd: string;
  Diagnosa1_Kd_Check: string;
  Diagnosa1_Kd_1_Check: string;
  Diagnosa1_Kd_2_Check: string;
  Diagnosa1_Kd_3_Check: string;
  Diagnosa1_Kd_4_Check: string;
  Diagnosa2_Kd_Check: string;
  Diagnosa2_Kd_Text: string;
  Tujuan1_Kd_Check: string;
  Tujuan1_Kd_Jam_1: string;
  Tujuan1_Kd_Jam_2: string;
  Tujuan1_Kd_1_Check: string;
  Tujuan1_Kd_2_Check: string;
  Tujuan2_Kd_Check: string;
  Tujuan2_Kd_Jam_1: string;
  Tujuan2_Kd_Jam_2: string;
  Tujuan2_Kd_1_Check: string;
  Tujuan2_Kd_1_Text: string;
  Rencana1_Kd_1_Check: string;
  Rencana1_Kd_2_Check: string;
  Rencana1_Kd_3_Check: string;
  Rencana1_Kd_4_Check: string;
  Rencana1_Kd_5_Check: string;
  Rencana1_Kd_6_Check: string;
  Rencana1_Kd_7_Check: string;
  Rencana1_Kd_7_Text: string;
  Rencana2_Kd_1_Check: string;
  Rencana2_Kd_1_Text: string;
  Tanggal_It: string;
  Diagnosa1_It_Check: string;
  Diagnosa1_It_1_Check: string;
  Diagnosa1_It_2_Check: string;
  Diagnosa2_It_Check: string;
  Diagnosa2_It_1_Check: string;
  Diagnosa2_It_2_Check: string;
  Diagnosa2_It_3_Check: string;
  Diagnosa3_It_Check: string;
  Diagnosa3_It_Text: string;
  Tujuan1_It_Check: string;
  Tujuan1_It_Jam_1: string;
  Tujuan1_It_Jam_2: string;
  Tujuan1_It_1_Check: string;
  Tujuan1_It_2_Check: string;
  Tujuan1_It_3_Check: string;
  Tujuan1_It_4_Check: string;
  Tujuan2_It_Check: string;
  Tujuan2_It_Jam_1: string;
  Tujuan2_It_Jam_2: string;
  Tujuan2_It_1_Check: string;
  Tujuan2_It_2_Check: string;
  Tujuan2_It_2_Text: string;
  Rencana1_It_1_Check: string;
  Rencana1_It_2_Check: string;
  Rencana1_It_3_Check: string;
  Rencana1_It_4_Check: string;
  Rencana1_It_5_Check: string;
  Rencana1_It_6_Check: string;
  Rencana1_It_7_Check: string;
  Rencana1_It_8_Check: string;
  Rencana1_It_9_Check: string;
  Rencana1_It_10_Check: string;
  Rencana1_It_10_Text: string;
  Rencana2_It_1_Check: string;
  Rencana2_It_1_Text: string;
  Rencana2_It_2_Check: string;
  Rencana2_It_2_Text: string;
  Tanggal_Psi: string;
  Diagnosa1_Psi_Check: string;
  Diagnosa1_Psi_1_Check: string;
  Diagnosa1_Psi_2_Check: string;
  Diagnosa1_Psi_3_Check: string;
  Diagnosa1_Psi_4_Check: string;
  Diagnosa1_Psi_5_Check: string;
  Diagnosa2_Psi_Check: string;
  Diagnosa2_Psi_1_Check: string;
  Diagnosa2_Psi_2_Check: string;
  Diagnosa2_Psi_3_Check: string;
  Diagnosa3_Psi_Check: string;
  Diagnosa3_Psi_1_Check: string;
  Diagnosa3_Psi_2_Check: string;
  Diagnosa3_Psi_3_Check: string;
  Tujuan1_Psi_Check: string;
  Tujuan1_Psi_Jam_1: string;
  Tujuan1_Psi_Jam_2: string;
  Tujuan1_Psi_1_Check: string;
  Tujuan1_Psi_2_Check: string;
  Tujuan1_Psi_3_Check: string;
  Tujuan1_Psi_4_Check: string;
  Tujuan2_Psi_Check: string;
  Tujuan2_Psi_Jam_1: string;
  Tujuan2_Psi_Jam_2: string;
  Tujuan2_Psi_1_Check: string;
  Tujuan2_Psi_2_Check: string;
  Tujuan3_Psi_Check: string;
  Tujuan3_Psi_Jam_1: string;
  Tujuan3_Psi_Jam_2: string;
  Tujuan3_Psi_1_Check: string;
  Tujuan3_Psi_2_Check: string;
  Tujuan3_Psi_3_Check: string;
  Rencana1_Psi_1_Check: string;
  Rencana1_Psi_2_Check: string;
  Rencana1_Psi_3_Check: string;
  Rencana1_Psi_4_Check: string;
  Rencana1_Psi_5_Check: string;
  Rencana1_Psi_6_Check: string;
  Rencana1_Psi_7_Check: string;
  Rencana1_Psi_8_Check: string;
  Rencana1_Psi_9_Check: string;
  Rencana1_Psi_10_Check: string;
  Rencana1_Psi_11_Check: string;
  Rencana2_Psi_1_Check: string;
  Rencana2_Psi_2_Check: string;
  Rencana2_Psi_2_Text: string;
  Rencana2_Psi_3_Check: string;
  Rencana2_Psi_3_Text: string;
  Tanggal_Ps1: string;
  Diagnosa1_Ps1_Check: string;
  Diagnosa1_Ps1_1_Check: string;
  Diagnosa1_Ps1_1_Text: string;
  Diagnosa1_Ps1_2_Check: string;
  Diagnosa1_Ps1_2_Text: string;
  Diagnosa1_Ps1_3_Check: string;
  Diagnosa1_Ps1_3_Text: string;
  Diagnosa1_Ps1_4_Check: string;
  Diagnosa1_Ps1_5_Check: string;
  Tujuan1_Ps1_Check: string;
  Tujuan1_Ps1_1_Check: string;
  Tujuan1_Ps1_2_Check: string;
  Rencana1_Ps1_1_Check: string;
  Rencana1_Ps1_2_Check: string;
  Rencana1_Ps1_3_Check: string;
  Rencana1_Ps1_4_Check: string;
  Rencana1_Ps1_5_Check: string;
  Rencana2_Ps1_1_Check: string;
  Rencana2_Ps1_2_Check: string;
  Rencana2_Ps1_2_Text: string;
  Tanggal_Si1: string;
  Diagnosa1_Si1_Check: string;
  Diagnosa1_Si1_1_Check: string;
  Diagnosa1_Si1_2_Check: string;
  Diagnosa1_Si1_3_Check: string;
  Diagnosa1_Si1_4_Check: string;
  Diagnosa1_Si1_5_Check: string;
  Tujuan1_Si1_Check: string;
  Tujuan1_Si1_Jam_1: string;
  Tujuan1_Si1_Jam_2: string;
  Tujuan1_Si1_1_Check: string;
  Tujuan1_Si1_2_Check: string;
  Tujuan1_Si1_3_Check: string;
  Tujuan1_Si1_3_Text: string;
  Rencana1_Si1_1_Check: string;
  Rencana1_Si1_2_Check: string;
  Rencana1_Si1_3_Check: string;
  Rencana1_Si1_4_Check: string;
  Rencana1_Si1_5_Check: string;
  Rencana1_Si1_6_Check: string;
  Rencana1_Si1_7_Check: string;
  Rencana1_Si1_8_Check: string;
  Rencana2_Si1_1_Check: string;
  Rencana2_Si1_1_Text: string;
  Rencana2_Si1_2_Check: string;
  Rencana2_Si1_2_Text: string;
  Rencana2_Si1_3_Check: string;
  Rencana2_Si1_3_Text: string;
  Updated_At: string;
  Updated_By: string;


  constructor(form: NursingCarePlanModel) {
    this.Diagnosa_Medis = form.Diagnosa_Medis;
    this.Kamar_Id =  form.Kamar_Id;
    this.Perawat_Id =  form.Perawat_Id;
    this.Nama_Perawat =  form.Nama_Perawat;

    this.Tanggal_Si =  form.Tanggal_Si;
    this.Diagnosa1_Si_Check =  form.Diagnosa1_Si_Check;
    this.Diagnosa1_Si_1_Check =  form.Diagnosa1_Si_1_Check;
    this.Diagnosa1_Si_2_Check =  form.Diagnosa1_Si_2_Check;
    this.Diagnosa1_Si_3_Check =  form.Diagnosa1_Si_3_Check;

    this.Diagnosa2_Si_Check =  form.Diagnosa2_Si_Check;
    this.Diagnosa2_Si_1_Check =  form.Diagnosa2_Si_1_Check;
    this.Diagnosa2_Si_2_Check =  form.Diagnosa2_Si_2_Check;
    this.Diagnosa2_Si_3_Check =  form.Diagnosa2_Si_3_Check;

    this.Diagnosa3_Si_Check =  form.Diagnosa3_Si_Check;
    this.Diagnosa3_Si_1_Check =  form.Diagnosa3_Si_1_Check;
    this.Diagnosa3_Si_2_Check =  form.Diagnosa3_Si_2_Check;

    this.Tujuan1_Si_Check =  form.Tujuan1_Si_Check;
    this.Tujuan1_Si_Jam_1 =  form.Tujuan1_Si_Jam_1;
    this.Tujuan1_Si_Jam_2 =  form.Tujuan1_Si_Jam_2;
    this.Tujuan1_Si_1_Check =  form.Tujuan1_Si_1_Check;
    this.Tujuan1_Si_2_Check =  form.Tujuan1_Si_2_Check;
    this.Tujuan1_Si_3_Check =  form.Tujuan1_Si_3_Check;
    this.Tujuan1_Si_3_Text =  form.Tujuan1_Si_3_Text;
    this.Tujuan2_Si_Check =  form.Tujuan2_Si_Check;
    this.Tujuan2_Si_Jam_1 =  form.Tujuan2_Si_Jam_1;
    this.Tujuan2_Si_Jam_2 =  form.Tujuan2_Si_Jam_2;
    this.Tujuan2_Si_1_Check =  form.Tujuan2_Si_1_Check;
    this.Tujuan2_Si_2_Check =  form.Tujuan2_Si_2_Check;
    this.Tujuan2_Si_3_Check =  form.Tujuan2_Si_3_Check;
    this.Tujuan2_Si_4_Check =  form.Tujuan2_Si_4_Check;
    this.Tujuan2_Si_5_Check =  "";
    this.Tujuan3_Si_Check =  form.Tujuan3_Si_Check;
    this.Tujuan3_Si_Text  =  form.Tujuan3_Si_Text;

    this.Rencana1_Si_Check =  "";
    this.Rencana1_Si_1_Check =  form.Rencana1_Si_1_Check;
    this.Rencana1_Si_2_Check =  form.Rencana1_Si_2_Check;
    this.Rencana1_Si_3_Check =  form.Rencana1_Si_3_Check;
    this.Rencana1_Si_4_Check =  form.Rencana1_Si_4_Check;
    this.Rencana1_Si_5_Check =  form.Rencana1_Si_5_Check;
    this.Rencana1_Si_6_Check =  form.Rencana1_Si_6_Check;
    this.Rencana1_Si_7_Check =  form.Rencana1_Si_7_Check;
    this.Rencana1_Si_8_Check =  form.Rencana1_Si_8_Check;
    this.Rencana2_Si_Check =  "";
    this.Rencana2_Si_1_Check =  form.Rencana2_Si_1_Check;
    this.Rencana2_Si_1_Text =  form.Rencana2_Si_1_Text;
    this.Rencana2_Si_2_Check =  form.Rencana2_Si_2_Check;
    this.Rencana2_Si_2_Text =  form.Rencana2_Si_2_Text;
    this.Rencana2_Si_3_Check =  form.Rencana2_Si_3_Check;
    this.Rencana2_Si_3_Text =  form.Rencana2_Si_3_Text;

    this.Tanggal_Ps =  form.Tanggal_Ps;
    this.Diagnosa1_Ps_Check =  form.Diagnosa1_Ps_Check;
    this.Diagnosa1_Ps_1_Check =  form.Diagnosa1_Ps_1_Check;
    this.Diagnosa1_Ps_1_Text =  form.Diagnosa1_Ps_1_Text;
    this.Diagnosa1_Ps_2_Check =  form.Diagnosa1_Ps_2_Check;
    this.Diagnosa1_Ps_2_Text =  form.Diagnosa1_Ps_2_Text;
    this.Diagnosa1_Ps_3_Check =  form.Diagnosa1_Ps_3_Check;
    this.Diagnosa1_Ps_3_Text =  form.Diagnosa1_Ps_3_Text;
    this.Diagnosa1_Ps_4_Check =  form.Diagnosa1_Ps_4_Check;
    this.Diagnosa1_Ps_5_Check =  form.Diagnosa1_Ps_5_Check;
    this.Diagnosa1_Ps_6_Check =  form.Diagnosa1_Ps_6_Check;
    this.Tujuan1_Ps_Check =  form.Tujuan1_Ps_Check;
    this.Tujuan1_Ps_Jam_1 =  form.Tujuan1_Ps_Jam_1;
    this.Tujuan1_Ps_Jam_2 =  form.Tujuan1_Ps_Jam_2;
    this.Tujuan1_Ps_1_Check =  form.Tujuan1_Ps_1_Check;
    this.Tujuan1_Ps_2_Check =  form.Tujuan1_Ps_2_Check;
    this.Tujuan1_Ps_3_Check =  form.Tujuan1_Ps_3_Check;
    this.Tujuan1_Ps_4_Check =  form.Tujuan1_Ps_4_Check;
    this.Rencana1_Ps_1_Check =  form.Rencana1_Ps_1_Check;
    this.Rencana1_Ps_2_Check =  form.Rencana1_Ps_2_Check;
    this.Rencana1_Ps_3_Check =  form.Rencana1_Ps_3_Check;
    this.Rencana1_Ps_4_Check =  form.Rencana1_Ps_4_Check;
    this.Rencana1_Ps_5_Check =  form.Rencana1_Ps_5_Check;
    this.Rencana1_Ps_6_Check =  form.Rencana1_Ps_6_Check;
    this.Rencana1_Ps_7_Check =  form.Rencana1_Ps_7_Check;
    this.Rencana2_Ps_1_Check =  form.Rencana2_Ps_1_Check;
    this.Rencana2_Ps_1_Text =  form.Rencana2_Ps_1_Text;
    this.Rencana2_Ps_2_Check =  form.Rencana2_Ps_2_Check;
    this.Rencana2_Ps_2_Text =  form.Rencana2_Ps_2_Text;
    this.Rencana2_Ps_3_Check =  form.Rencana2_Ps_3_Check;
    this.Rencana2_Ps_3_Text =  form.Rencana2_Ps_3_Text;


    this.Tanggal_Nc =  form.Tanggal_Nc;
    this.Diagnosa1_Nc_Check =  form.Diagnosa1_Nc_Check;
    this.Diagnosa1_Nc_1_Check =  form.Diagnosa1_Nc_1_Check;
    this.Diagnosa1_Nc_2_Check =  form.Diagnosa1_Nc_2_Check;
    this.Diagnosa1_Nc_3_Check =  form.Diagnosa1_Nc_3_Check;
    this.Diagnosa2_Nc_Check =  form.Diagnosa2_Nc_Check;
    this.Diagnosa2_Nc_1_Check =  form.Diagnosa2_Nc_1_Check;
    this.Diagnosa3_Nc_Check =  form.Diagnosa3_Nc_Check;
    this.Diagnosa3_Nc_1_Check =  form.Diagnosa3_Nc_1_Check;
    this.Diagnosa3_Nc_2_Check =  form.Diagnosa3_Nc_2_Check;
    this.Diagnosa3_Nc_3_Check =  form.Diagnosa3_Nc_3_Check;
    this.Diagnosa3_Nc_4_Check =  form.Diagnosa3_Nc_4_Check;
    this.Diagnosa3_Nc_5_Check =  form.Diagnosa3_Nc_5_Check;
    this.Diagnosa3_Nc_5_Text =  form.Diagnosa3_Nc_5_Text;
    this.Diagnosa4_Nc_Check =  form.Diagnosa4_Nc_Check;
    this.Diagnosa4_Nc_1_Check =  form.Diagnosa4_Nc_1_Check;
    this.Diagnosa5_Nc_Check =  form.Diagnosa5_Nc_Check;
    this.Diagnosa5_Nc_1_Check =  form.Diagnosa5_Nc_1_Check;
    this.Diagnosa5_Nc_2_Check =  form.Diagnosa5_Nc_2_Check;
    this.Tujuan1_Nc_Check =  form.Tujuan1_Nc_Check;
    this.Tujuan1_Nc_Jam_1 =  form.Tujuan1_Nc_Jam_1;
    this.Tujuan1_Nc_Jam_2 =  form.Tujuan1_Nc_Jam_2;
    this.Tujuan1_Nc_1_Check =  form.Tujuan1_Nc_1_Check;
    this.Tujuan1_Nc_2_Check =  form.Tujuan1_Nc_2_Check;
    this.Tujuan1_Nc_3_Check =  form.Tujuan1_Nc_3_Check;
    this.Tujuan1_Nc_4_Check =  form.Tujuan1_Nc_4_Check;
    this.Tujuan1_Nc_5_Check =  form.Tujuan1_Nc_5_Check;
    this.Tujuan1_Nc_6_Check =  form.Tujuan1_Nc_6_Check;
    this.Tujuan1_Nc_6_Text =  form.Tujuan1_Nc_6_Text;
    this.Tujuan2_Nc_Check =  form.Tujuan2_Nc_Check;
    this.Tujuan2_Nc_Jam_1 =  form.Tujuan2_Nc_Jam_1;
    this.Tujuan2_Nc_Jam_2 =  form.Tujuan2_Nc_Jam_2;
    this.Tujuan2_Nc_1_Check =  form.Tujuan2_Nc_1_Check;
    this.Tujuan2_Nc_2_Check =  form.Tujuan2_Nc_2_Check;
    this.Tujuan2_Nc_3_Check =  form.Tujuan2_Nc_3_Check;
    this.Tujuan2_Nc_4_Check =  form.Tujuan2_Nc_4_Check;
    this.Tujuan3_Nc_Check =  form.Tujuan3_Nc_Check;
    this.Tujuan3_Nc_Jam_1 =  form.Tujuan3_Nc_Jam_1;
    this.Tujuan3_Nc_Jam_2 =  form.Tujuan3_Nc_Jam_2;
    this.Tujuan3_Nc_1_Check =  form.Tujuan3_Nc_1_Check;
    this.Tujuan3_Nc_2_Check =  form.Tujuan3_Nc_2_Check;
    this.Tujuan3_Nc_3_Check =  form.Tujuan3_Nc_3_Check;
    this.Tujuan3_Nc_3_Text =  form.Tujuan3_Nc_3_Text;

    this.Tujuan4_Nc_Check =  form.Tujuan4_Nc_Check;
    this.Rencana1_Nc_1_Check =  form.Rencana1_Nc_1_Check;
    this.Rencana1_Nc_2_Check =  form.Rencana1_Nc_2_Check;
    this.Rencana1_Nc_3_Check =  form.Rencana1_Nc_3_Check;
    this.Rencana1_Nc_3_Text  =  form.Rencana1_Nc_3_Text;
    this.Rencana1_Nc_4_Check =  form.Rencana1_Nc_4_Check;
    this.Rencana1_Nc_5_Check =  form.Rencana1_Nc_5_Check;
    this.Rencana1_Nc_6_Check =  form.Rencana1_Nc_6_Check;
    this.Rencana1_Nc_7_Check =  form.Rencana1_Nc_7_Check;
    this.Rencana1_Nc_8_Check =  form.Rencana1_Nc_8_Check;
    this.Rencana1_Nc_9_Check =  form.Rencana1_Nc_9_Check;
    this.Rencana1_Nc_10_Check =  form.Rencana1_Nc_10_Check;
    this.Rencana1_Nc_11_Check =  form.Rencana1_Nc_11_Check;
    this.Rencana1_Nc_12_Check =  form.Rencana1_Nc_12_Check;
    this.Rencana1_Nc_12_Text =  form.Rencana1_Nc_12_Text;

    this.Rencana2_Nc_1_Check =  form.Rencana2_Nc_1_Check;
    this.Rencana2_Nc_2_Check =  form.Rencana2_Nc_2_Check;
    this.Rencana2_Nc_3_Check =  form.Rencana2_Nc_3_Check;
    this.Rencana2_Nc_3_Text =  form.Rencana2_Nc_3_Text;


    this.Tanggal_Kd =  form.Tanggal_Kd;
    this.Diagnosa1_Kd_Check =  form.Diagnosa1_Kd_Check;
    this.Diagnosa1_Kd_1_Check =  form.Diagnosa1_Kd_1_Check;
    this.Diagnosa1_Kd_2_Check =  form.Diagnosa1_Kd_2_Check;
    this.Diagnosa1_Kd_3_Check =  form.Diagnosa1_Kd_3_Check;
    this.Diagnosa1_Kd_4_Check =  form.Diagnosa1_Kd_4_Check;
    this.Diagnosa2_Kd_Check =  form.Diagnosa2_Kd_Check;
    this.Diagnosa2_Kd_Text =  form.Diagnosa2_Kd_Text;
    this.Tujuan1_Kd_Check =  form.Tujuan1_Kd_Check;
    this.Tujuan1_Kd_Jam_1 =  form.Tujuan1_Kd_Jam_1;
    this.Tujuan1_Kd_Jam_2 =  form.Tujuan1_Kd_Jam_2;
    this.Tujuan1_Kd_1_Check =  form.Tujuan1_Kd_1_Check;
    this.Tujuan1_Kd_2_Check =  form.Tujuan1_Kd_2_Check;
    this.Tujuan2_Kd_Check =  form.Tujuan2_Kd_Check;
    this.Tujuan2_Kd_Jam_1 =  form.Tujuan2_Kd_Jam_1;
    this.Tujuan2_Kd_Jam_2 =  form.Tujuan2_Kd_Jam_2;
    this.Tujuan2_Kd_1_Check =  form.Tujuan2_Kd_1_Check;
    this.Tujuan2_Kd_1_Text =  form.Tujuan2_Kd_1_Text;
    this.Rencana1_Kd_1_Check =  form.Rencana1_Kd_1_Check;
    this.Rencana1_Kd_2_Check =  form.Rencana1_Kd_2_Check;
    this.Rencana1_Kd_3_Check =  form.Rencana1_Kd_3_Check;
    this.Rencana1_Kd_4_Check =  form.Rencana1_Kd_4_Check;
    this.Rencana1_Kd_5_Check =  form.Rencana1_Kd_5_Check;
    this.Rencana1_Kd_6_Check =  form.Rencana1_Kd_6_Check;
    this.Rencana1_Kd_7_Check =  form.Rencana1_Kd_7_Check;
    this.Rencana1_Kd_7_Text =  form.Rencana1_Kd_7_Text;
    this.Rencana2_Kd_1_Check =  form.Rencana2_Kd_1_Check;
    this.Rencana2_Kd_1_Text =  form.Rencana2_Kd_1_Text;


    this.Tanggal_It =  form.Tanggal_It;
    this.Diagnosa1_It_Check =  form.Diagnosa1_It_Check;
    this.Diagnosa1_It_1_Check =  form.Diagnosa1_It_1_Check;
    this.Diagnosa1_It_2_Check =  form.Diagnosa1_It_2_Check;
    this.Diagnosa2_It_Check =  form.Diagnosa2_It_Check;
    this.Diagnosa2_It_1_Check =  form.Diagnosa2_It_1_Check;
    this.Diagnosa2_It_2_Check =  form.Diagnosa2_It_2_Check;
    this.Diagnosa2_It_3_Check =  form.Diagnosa2_It_3_Check;
    this.Diagnosa3_It_Check =  form.Diagnosa3_It_Check;
    this.Diagnosa3_It_Text =  form.Diagnosa3_It_Text;
    this.Tujuan1_It_Check =  form.Tujuan1_It_Check;
    this.Tujuan1_It_Jam_1 =  form.Tujuan1_It_Jam_1;
    this.Tujuan1_It_Jam_2 =  form.Tujuan1_It_Jam_2;
    this.Tujuan1_It_1_Check =  form.Tujuan1_It_1_Check;
    this.Tujuan1_It_2_Check =  form.Tujuan1_It_2_Check;
    this.Tujuan1_It_3_Check =  form.Tujuan1_It_3_Check;
    this.Tujuan1_It_4_Check =  form.Tujuan1_It_4_Check;
    this.Tujuan2_It_Check =  form.Tujuan2_It_Check;
    this.Tujuan2_It_Jam_1 =  form.Tujuan2_It_Jam_1;
    this.Tujuan2_It_Jam_2 =  form.Tujuan2_It_Jam_2;
    this.Tujuan2_It_1_Check =  form.Tujuan2_It_1_Check;
    this.Tujuan2_It_2_Check =  form.Tujuan2_It_2_Check;
    this.Tujuan2_It_2_Text =  form.Tujuan2_It_2_Text;
    this.Rencana1_It_1_Check =  form.Rencana1_It_1_Check;
    this.Rencana1_It_2_Check =  form.Rencana1_It_2_Check;
    this.Rencana1_It_3_Check =  form.Rencana1_It_3_Check;
    this.Rencana1_It_4_Check =  form.Rencana1_It_4_Check;
    this.Rencana1_It_5_Check =  form.Rencana1_It_5_Check;
    this.Rencana1_It_6_Check =  form.Rencana1_It_6_Check;
    this.Rencana1_It_7_Check =  form.Rencana1_It_7_Check;
    this.Rencana1_It_8_Check =  form.Rencana1_It_8_Check;
    this.Rencana1_It_9_Check =  form.Rencana1_It_9_Check;
    this.Rencana1_It_10_Check =  form.Rencana1_It_10_Check;
    this.Rencana1_It_10_Text =  form.Rencana1_It_10_Text;
    this.Rencana2_It_1_Check =  form.Rencana2_It_1_Check;
    this.Rencana2_It_1_Text =  form.Rencana2_It_1_Check;
    this.Rencana2_It_2_Check =  form.Rencana2_It_2_Check;
    this.Rencana2_It_2_Text =  form.Rencana2_It_2_Text;

    this.Tanggal_Psi =  form.Tanggal_Psi;
    this.Diagnosa1_Psi_Check =  form.Diagnosa1_Psi_Check;
    this.Diagnosa1_Psi_1_Check =  form.Diagnosa1_Psi_1_Check;
    this.Diagnosa1_Psi_2_Check =  form.Diagnosa1_Psi_2_Check;
    this.Diagnosa1_Psi_3_Check =  form.Diagnosa1_Psi_3_Check;
    this.Diagnosa1_Psi_4_Check =  form.Diagnosa1_Psi_4_Check;
    this.Diagnosa1_Psi_5_Check =  form.Diagnosa1_Psi_5_Check;
    this.Diagnosa2_Psi_Check =  form.Diagnosa2_Psi_Check;
    this.Diagnosa2_Psi_1_Check =  form.Diagnosa2_Psi_1_Check;
    this.Diagnosa2_Psi_2_Check =  form.Diagnosa2_Psi_2_Check;
    this.Diagnosa2_Psi_3_Check =  form.Diagnosa2_Psi_3_Check;
    this.Diagnosa3_Psi_Check =  form.Diagnosa3_Psi_Check;
    this.Diagnosa3_Psi_1_Check =  form.Diagnosa3_Psi_1_Check;
    this.Diagnosa3_Psi_2_Check =  form.Diagnosa3_Psi_2_Check;
    this.Diagnosa3_Psi_3_Check =  form.Diagnosa3_Psi_3_Check;
    this.Tujuan1_Psi_Check =  form.Tujuan1_Psi_Check;
    this.Tujuan1_Psi_Jam_1 =  form.Tujuan1_Psi_Jam_1;
    this.Tujuan1_Psi_Jam_2 =  form.Tujuan1_Psi_Jam_2;
    this.Tujuan1_Psi_1_Check =  form.Tujuan1_Psi_1_Check;
    this.Tujuan1_Psi_2_Check =  form.Tujuan1_Psi_2_Check;
    this.Tujuan1_Psi_3_Check =  form.Tujuan1_Psi_3_Check;
    this.Tujuan1_Psi_4_Check =  form.Tujuan1_Psi_4_Check;
    this.Tujuan2_Psi_Check =  form.Tujuan2_Psi_Check;
    this.Tujuan2_Psi_Jam_1 =  form.Tujuan2_Psi_Jam_1;
    this.Tujuan2_Psi_Jam_2 =  form.Tujuan2_Psi_Jam_2;
    this.Tujuan2_Psi_1_Check =  form.Tujuan2_Psi_1_Check;
    this.Tujuan2_Psi_2_Check =  form.Tujuan2_Psi_2_Check;
    this.Tujuan3_Psi_Check =  form.Tujuan3_Psi_Check;
    this.Tujuan3_Psi_Jam_1 =  form.Tujuan3_Psi_Jam_1;
    this.Tujuan3_Psi_Jam_2 =  form.Tujuan3_Psi_Jam_2;
    this.Tujuan3_Psi_1_Check =  form.Tujuan3_Psi_1_Check;
    this.Tujuan3_Psi_2_Check =  form.Tujuan3_Psi_2_Check;
    this.Tujuan3_Psi_3_Check =  form.Tujuan3_Psi_3_Check;
    this.Rencana1_Psi_1_Check =  form.Rencana1_Psi_1_Check;
    this.Rencana1_Psi_2_Check =  form.Rencana1_Psi_2_Check;
    this.Rencana1_Psi_3_Check =  form.Rencana1_Psi_3_Check;
    this.Rencana1_Psi_4_Check =  form.Rencana1_Psi_4_Check;
    this.Rencana1_Psi_5_Check =  form.Rencana1_Psi_4_Check;
    this.Rencana1_Psi_6_Check =  form.Rencana1_Psi_6_Check;
    this.Rencana1_Psi_7_Check =  form.Rencana1_Psi_7_Check;
    this.Rencana1_Psi_8_Check =  form.Rencana1_Psi_8_Check;
    this.Rencana1_Psi_9_Check =  form.Rencana1_Psi_9_Check;
    this.Rencana1_Psi_10_Check =  form.Rencana1_Psi_10_Check;
    this.Rencana1_Psi_11_Check =  form.Rencana1_Psi_11_Check;
    this.Rencana2_Psi_1_Check =  form.Rencana2_Psi_1_Check;
    this.Rencana2_Psi_2_Check =  form.Rencana2_Psi_2_Check;
    this.Rencana2_Psi_2_Text =  form.Rencana2_Psi_2_Text;
    this.Rencana2_Psi_3_Check =  form.Rencana2_Psi_3_Check;
    this.Rencana2_Psi_3_Text =  form.Rencana2_Psi_3_Text;


    this.Tanggal_Ps1 =  form.Tanggal_Ps1;
    this.Diagnosa1_Ps1_Check =  form.Diagnosa1_Ps1_Check;
    this.Diagnosa1_Ps1_1_Check =  form.Diagnosa1_Ps1_1_Check;
    this.Diagnosa1_Ps1_1_Text =  form.Diagnosa1_Ps1_1_Text;
    this.Diagnosa1_Ps1_2_Check =  form.Diagnosa1_Ps1_2_Check;
    this.Diagnosa1_Ps1_2_Text =  form.Diagnosa1_Ps1_2_Text;
    this.Diagnosa1_Ps1_3_Check =  form.Diagnosa1_Ps1_3_Check;
    this.Diagnosa1_Ps1_3_Text =  form.Diagnosa1_Ps1_3_Text;
    this.Diagnosa1_Ps1_4_Check =  form.Diagnosa1_Ps1_4_Check;
    this.Diagnosa1_Ps1_5_Check =  form.Diagnosa1_Ps1_5_Check;
    this.Tujuan1_Ps1_Check =  form.Tujuan1_Ps1_Check;
    this.Tujuan1_Ps1_1_Check =  form.Tujuan1_Ps1_1_Check;
    this.Tujuan1_Ps1_2_Check =  form.Tujuan1_Ps1_2_Check;
    this.Rencana1_Ps1_1_Check =  form.Rencana1_Ps1_1_Check;
    this.Rencana1_Ps1_2_Check =  form.Rencana1_Ps1_2_Check;
    this.Rencana1_Ps1_3_Check =  form.Rencana1_Ps1_3_Check;
    this.Rencana1_Ps1_4_Check =  form.Rencana1_Ps1_4_Check;
    this.Rencana1_Ps1_5_Check =  form.Rencana1_Ps1_5_Check;
    this.Rencana2_Ps1_1_Check =  form.Rencana2_Ps1_1_Check;
    this.Rencana2_Ps1_2_Check =  form.Rencana2_Ps1_2_Check;
    this.Rencana2_Ps1_2_Text =  form.Rencana2_Ps1_2_Text;

    this.Tanggal_Si1 =  form.Tanggal_Si1;
    this.Diagnosa1_Si1_Check =  form.Diagnosa1_Si1_Check;
    this.Diagnosa1_Si1_1_Check =  form.Diagnosa1_Si1_1_Check;
    this.Diagnosa1_Si1_2_Check =  form.Diagnosa1_Si1_2_Check;
    this.Diagnosa1_Si1_3_Check =  form.Diagnosa1_Si1_3_Check;
    this.Diagnosa1_Si1_4_Check =  form.Diagnosa1_Si1_4_Check;
    this.Diagnosa1_Si1_5_Check =  form.Diagnosa1_Si1_5_Check;
    this.Tujuan1_Si1_Check =  form.Tujuan1_Si1_Check;
    this.Tujuan1_Si1_Jam_1 =  form.Tujuan1_Si1_Jam_1;
    this.Tujuan1_Si1_Jam_2 =  form.Tujuan1_Si1_Jam_2;
    this.Tujuan1_Si1_1_Check =  form.Tujuan1_Si1_1_Check;
    this.Tujuan1_Si1_2_Check =  form.Tujuan1_Si1_2_Check;
    this.Tujuan1_Si1_3_Check =  form.Tujuan1_Si1_3_Check;
    this.Tujuan1_Si1_3_Text =  form.Tujuan1_Si1_3_Text;
    this.Rencana1_Si1_1_Check =  form.Rencana1_Si1_1_Check;
    this.Rencana1_Si1_2_Check =  form.Rencana1_Si1_2_Check;
    this.Rencana1_Si1_3_Check =  form.Rencana1_Si1_3_Check;
    this.Rencana1_Si1_4_Check =  form.Rencana1_Si1_4_Check;
    this.Rencana1_Si1_5_Check =  form.Rencana1_Si1_5_Check;
    this.Rencana1_Si1_6_Check =  form.Rencana1_Si1_6_Check;
    this.Rencana1_Si1_7_Check =  form.Rencana1_Si1_7_Check;
    this.Rencana1_Si1_8_Check =  form.Rencana1_Si1_8_Check;
    this.Rencana2_Si1_1_Check =  form.Rencana2_Si1_1_Check;
    this.Rencana2_Si1_1_Text =  form.Rencana2_Si1_1_Text;
    this.Rencana2_Si1_2_Check =  form.Rencana2_Si1_2_Check;
    this.Rencana2_Si1_2_Text =  form.Rencana2_Si1_2_Text;
    this.Rencana2_Si1_3_Check =  form.Rencana2_Si1_3_Check;
    this.Rencana2_Si1_3_Text = form.Rencana2_Si1_3_Text;
    this.Updated_At = form.Updated_At;
    this.Updated_By = form.Updated_By;
  }

}

export interface INursingCarePlanModel extends IDataModel {
  kamar : Array<IRoomModel>;
  form: INursingCarePlanModel;
  inform_consent: IProvisionOfInformationFormModel;
}

export class NursingCarePlan extends DataModel {
  kamar : Array<IRoomModel>;
  form?: NursingCarePlanModel;
  inform_consent: IProvisionOfInformationFormModel;

  constructor(req: INursingCarePlanModel) {
    super(req);
    this.kamar = req.kamar
    this.form = new NursingCarePlanModel(req.form);
    this.inform_consent = req.inform_consent;
  }
}
