import { CreatePDFRequest, ICreatePDFRequest } from '@shared/pdf/requests/create-pdf.request';
import { Record } from '@modules/outpatient/patient-transfers/models/patient-transfer-model';
import nilai from '../const/nilai';
import { DateTimeConverter } from '@src/shared/datetime-converter';

export interface IPdfPatientTransfer extends ICreatePDFRequest {
  data: {
    nomor_mr: string;
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string,
    'pasien.Jenis_Kelamin': string,
    dokter_dpjp: string,
    dokter_op: string,
    date: string,
    time: string,
    indikasi_transfer: string,
    date_masuk: string,
    time_masuk: string,
    diagnosa_medis: string,
    td: string,
    nadi: string,
    pernafasan: string,
    temp: string,
    sp02: string,
    vod: string,
    vos: string,
    tod: string,
    tods: string,
    time_puasa: string,
    keluhan_saat_ini: string,
    akt_dwsa: string,
    sir_dwsa: string,
    per_dwsa: string,
    kes_dwsa: string,
    war_dwsa: string,
    total_dwsa: string,
    kes_anak: string,
    per_anak: string,
    mot_anak: string,
    total_anak: string,
    laboratorium: string,
    diagnostik_lainya: string,
    terapi_yg_sudah_diberikan: string,
    rencana_pengobatan: string,
    diet: string,
    nama_perawat_pengantar: string,
    nama_perawat_penerima: string,

    pengantar_ugd: string,
    pengantar_rajal: string,
    pengantar_ranap: string,
    pengantar_ok: string,
    penerima_rajal: string,
    penerima_ranap: string,
    penerima_ok: string,
    kesadaran_1: string,
    kesadaran_2: string,
    kesadaran_3: string,
    kesadaran_4: string,
    kesadaran_5: string,
    kesadaran_6: string,
    skala_nyeri_1: string,
    skala_nyeri_2: string,
    skala_nyeri_3: string,
    skala_nyeri_4: string,
    skala_nyeri_5: string,
    skala_nyeri_6: string,
    skala_nyeri_7: string,
    skala_nyeri_8: string,
    skala_nyeri_9: string,
    skala_nyeri_10: string,
    diagnostik_ekg: string,
    diagnostik_usg: string,
    diagnostik_oct_macula: string,
    diagnostik_ct_scan: string,
    diagnostik_oct_papil: string,
    diagnostik_lab: string,
    diagnostik_biometri: string,
    diagnostik_thorax: string,
    diagnostik_ff: string,
    diagnostik_lain_lain: string,
    Tanda_Tangan_Perawat_Pengantar: string,
    Tanda_Tangan_Perawat_Penerima: string,
    puasa_tidak: string,
    puasa_ya: string,
    nik: string,
  }
}

export class PdfPatientTransfer extends CreatePDFRequest {
  data: {
    nomor_mr: string;
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string,
    'pasien.Jenis_Kelamin': string,
    dokter_dpjp: string,
    dokter_op: string,
    date: string,
    time: string,
    indikasi_transfer: string,
    date_masuk: string,
    time_masuk: string,
    diagnosa_medis: string,
    td: string,
    nadi: string,
    pernafasan: string,
    temp: string,
    sp02: string,
    vod: string,
    vos: string,
    tod: string,
    tods: string,
    time_puasa: string,
    keluhan_saat_ini: string,
    akt_dwsa: string,
    sir_dwsa: string,
    per_dwsa: string,
    kes_dwsa: string,
    war_dwsa: string,
    total_dwsa: string,
    kes_anak: string,
    per_anak: string,
    mot_anak: string,
    total_anak: string,
    laboratorium: string,
    diagnostik_lainya: string,
    terapi_yg_sudah_diberikan: string,
    rencana_pengobatan: string,
    diet: string,
    nama_perawat_pengantar: string,
    nama_perawat_penerima: string,

    pengantar_ugd: string,
    pengantar_rajal: string,
    pengantar_ranap: string,
    pengantar_ok: string,
    penerima_rajal: string,
    penerima_ranap: string,
    penerima_ok: string,
    kesadaran_1: string,
    kesadaran_2: string,
    kesadaran_3: string,
    kesadaran_4: string,
    kesadaran_5: string,
    kesadaran_6: string,
    skala_nyeri_1: string,
    skala_nyeri_2: string,
    skala_nyeri_3: string,
    skala_nyeri_4: string,
    skala_nyeri_5: string,
    skala_nyeri_6: string,
    skala_nyeri_7: string,
    skala_nyeri_8: string,
    skala_nyeri_9: string,
    skala_nyeri_10: string,
    diagnostik_ekg: string,
    diagnostik_usg: string,
    diagnostik_oct_macula: string,
    diagnostik_ct_scan: string,
    diagnostik_oct_papil: string,
    diagnostik_lab: string,
    diagnostik_biometri: string,
    diagnostik_thorax: string,
    diagnostik_ff: string,
    diagnostik_lain_lain: string,
    Tanda_Tangan_Perawat_Pengantar: string,
    Tanda_Tangan_Perawat_Penerima: string,
    puasa_tidak: string,
    puasa_ya: string,
    nik: string,
  }

  constructor(req: IPdfPatientTransfer) {
    super(req);
    this.data = req.data;
  }

  static createFromJson(json: IPdfPatientTransfer) {
    return new PdfPatientTransfer(json);
  }

  static createPdfRequest(val: Record | any, emrId: string): PdfPatientTransfer {
    const getName = (value: any) => {
      const selectedName = nilai.find((val: any) => val.value === value)
      if (selectedName) {
        return selectedName.name;
      } else {
        return ''
      }
    }
    const patientTransfer: Record = val;
    return new PdfPatientTransfer({
      emr_id: emrId,
      form_name: 'transfer-pasien',
      row_filter: '',
      preview: false,
      data: {
        nomor_mr: val?.nomor_mr ?? '',
        'pasien.Nama': val?.pasien?.Nama ?? '',
        'pasien.Tgl_Lahir': DateTimeConverter.convertToNormalDate(val?.pasien?.Tgl_Lahir),
        'pasien.Umur': this.normalizeAge(val?.umur_lengkap),
        'pasien.Jenis_Kelamin': val?.pasien?.Jenis_Kelamin ?? '',
        dokter_dpjp: patientTransfer?.Nama_Dokter_Dpjp ?? '',
        dokter_op: patientTransfer?.Nama_Dokter_Operator ?? '',
        date: DateTimeConverter.convertToNormalDate(patientTransfer?.Tanggal_Transfer),
        time: '',
        indikasi_transfer: patientTransfer?.Indikasi_Transfer ?? '',
        date_masuk: DateTimeConverter.convertToNormalDate(patientTransfer?.Tanggal_Masuk_Rs),
        time_masuk: '',
        diagnosa_medis: patientTransfer?.Diagnosa ?? '',
        td: patientTransfer?.Vital_TD ?? '',
        nadi: patientTransfer?.Vital_N ?? '',
        pernafasan: patientTransfer?.Vital_P ?? '',
        temp: patientTransfer?.Vital_T ?? '',
        sp02: patientTransfer?.Vital_Sat_O2 ?? '',
        vod: patientTransfer?.Visus_OD ?? '',
        vos: patientTransfer?.Visus_OS ?? '',
        tod: patientTransfer?.Tonometer_OD ?? '',
        tods: patientTransfer?.Tonometer_OS ?? '',
        time_puasa: patientTransfer?.Waktu_Puasa ?? '',
        keluhan_saat_ini: patientTransfer?.Keluhan ?? '',
        akt_dwsa: getName(patientTransfer?.Alderette_Aktivitas ?? ''),
        sir_dwsa: getName(patientTransfer?.Alderette_Sirkulasi ?? ''),
        per_dwsa: getName(patientTransfer?.Alderette_Pernafasan ?? ''),
        kes_dwsa: getName(patientTransfer?.Alderette_Kesadaran ?? ''),
        war_dwsa: getName(patientTransfer?.Alderette_Warna_Kulit ?? ''),
        total_dwsa: `${((+patientTransfer?.Alderette_Aktivitas ?? 0) + (+patientTransfer?.Alderette_Sirkulasi ?? 0) + (+patientTransfer?.Alderette_Pernafasan ?? 0) + (+patientTransfer?.Alderette_Kesadaran ?? 0) + (+patientTransfer?.Alderette_Warna_Kulit ?? 0))}`,
        kes_anak: getName(patientTransfer?.Steward_Kesadaran ?? ''),
        per_anak: getName(patientTransfer?.Steward_Pernafasan ?? ''),
        mot_anak: getName(patientTransfer?.Steward_Motorik ?? ''),
        total_anak: `${((+patientTransfer?.Steward_Kesadaran ?? 0) + (+patientTransfer?.Steward_Pernafasan ?? 0) + (+patientTransfer?.Steward_Motorik ?? 0))}`,
        laboratorium: patientTransfer?.Pemeriksaan_Alat_Laboratorium_Text ?? '',
        diagnostik_lainya: patientTransfer?.Diagnosa ?? '',
        terapi_yg_sudah_diberikan: patientTransfer?.Terapi ?? '',
        rencana_pengobatan: patientTransfer?.Rencana ?? '',
        diet: patientTransfer?.Diet ?? '',
        puasa_tidak: this.getCheckImage(patientTransfer?.Puasa === 'puasa_tidak'),
        puasa_ya: this.getCheckImage(patientTransfer?.Puasa === 'puasa_ya'),
        nama_perawat_pengantar: patientTransfer?.Nama_Perawat_Pengantar ?? '',
        nama_perawat_penerima: patientTransfer?.Nama_Perawat_Penerima ?? '',

        pengantar_ugd: this.getCheckImage(patientTransfer?.Pengantar === 'UGD'),
        pengantar_rajal: this.getCheckImage(patientTransfer?.Pengantar === 'Rawat Jalan'),
        pengantar_ranap: this.getCheckImage(patientTransfer?.Pengantar === 'Rawat Inap'),
        pengantar_ok: this.getCheckImage(patientTransfer?.Pengantar === 'Kamar Bedah'),
        penerima_rajal: this.getCheckImage(patientTransfer?.Penerima === 'Rawat Jalan'),
        penerima_ranap: this.getCheckImage(patientTransfer?.Penerima === 'Rawat Inap'),
        penerima_ok: this.getCheckImage(patientTransfer?.Penerima === 'Kamar Bedah'),
        kesadaran_1: this.getCheckImage(patientTransfer?.Kesadaran === 'compos'),
        kesadaran_2: this.getCheckImage(patientTransfer?.Kesadaran === 'somnolen'),
        kesadaran_3: this.getCheckImage(patientTransfer?.Kesadaran === 'sopor'),
        kesadaran_4: this.getCheckImage(patientTransfer?.Kesadaran === 'apatis'),
        kesadaran_5: this.getCheckImage(patientTransfer?.Kesadaran === 'delirium'),
        kesadaran_6: this.getCheckImage(patientTransfer?.Kesadaran === 'koma'),
        skala_nyeri_1: this.getCheckImage(patientTransfer?.Skala_Nyeri === '1'),
        skala_nyeri_2: this.getCheckImage(patientTransfer?.Skala_Nyeri === '2'),
        skala_nyeri_3: this.getCheckImage(patientTransfer?.Skala_Nyeri === '3'),
        skala_nyeri_4: this.getCheckImage(patientTransfer?.Skala_Nyeri === '4'),
        skala_nyeri_5: this.getCheckImage(patientTransfer?.Skala_Nyeri === '5'),
        skala_nyeri_6: this.getCheckImage(patientTransfer?.Skala_Nyeri === '6'),
        skala_nyeri_7: this.getCheckImage(patientTransfer?.Skala_Nyeri === '7'),
        skala_nyeri_8: this.getCheckImage(patientTransfer?.Skala_Nyeri === '8'),
        skala_nyeri_9: this.getCheckImage(patientTransfer?.Skala_Nyeri === '9'),
        skala_nyeri_10: this.getCheckImage(patientTransfer?.Skala_Nyeri === '10'),
        diagnostik_ekg: this.getCheckImage(patientTransfer?.Pemeriksaan_Alat_Ekg === '1'),
        diagnostik_usg: this.getCheckImage(patientTransfer?.Pemeriksaan_Alat_Usg === '1'),
        diagnostik_oct_macula: this.getCheckImage(patientTransfer?.Pemeriksaan_Alat_Oct_Macula === '1'),
        diagnostik_ct_scan: this.getCheckImage(patientTransfer?.Pemeriksaan_Alat_Ct_Scan === '1'),
        diagnostik_oct_papil: this.getCheckImage(patientTransfer?.Pemeriksaan_Alat_Oct_Papil === '1'),
        diagnostik_lab: this.getCheckImage(patientTransfer?.Pemeriksaan_Alat_Laboratorium === '1'),
        diagnostik_biometri: this.getCheckImage(patientTransfer?.Pemeriksaan_Alat_Biometri === '1'),
        diagnostik_thorax: this.getCheckImage(patientTransfer?.Pemeriksaan_Alat_Thorax_Foto === '1'),
        diagnostik_ff: this.getCheckImage(patientTransfer?.Pemeriksaan_Alat_Foto_Fundus === '1'),
        diagnostik_lain_lain: this.getCheckImage(patientTransfer?.Pemeriksaan_Alat_Lain_Lain === '1'),
        Tanda_Tangan_Perawat_Pengantar: patientTransfer?.Tanda_Tangan_Perawat_Pengantar ?? undefined,
        Tanda_Tangan_Perawat_Penerima: patientTransfer?.Tanda_Tangan_Perawat_Penerima ?? undefined,
        nik: val?.pasien?.NIK ?? '',
      },
    })
  }
}
