import { DataModel, IDataModel } from '@shared/model';


export interface IAnestheticStatusModel {

  ID_DPJP_Anestesi: string;
  ID_DPJP_Bedah: string;
  ID_Asisten_Anestesi: string;
  Diagnosa_Pra_Bedah: string;
  Diagnosis_Pasca_Bedah: string;
  Jenis_Pembedahan: string;
  Teknik_Anestesi: string;
  Teknik_Anestesi_Lainnya: string;
  Teknik_Khusus_Hipotensi: string;
  Teknik_Khusus_Bronkoskopi: string;
  Teknik_Khusus_TCI: string;
  Teknik_Khusus_Glidescope: string;
  Teknik_Khusus_CPB: string;
  Teknik_Khusus_USG: string;
  Teknik_Khusus_Ventilasi: string;
  Teknik_Khusus_Stimulator: string;
  Teknik_Khusus_Lainnya: string;
  Teknik_Khusus_Lainnya_Teks: string;
  Monitoring_EKG: string;
  Monitoring_NIBP: string;
  Monitoring_Cath: string;
  Monitoring_Arteri: string;
  Monitoring_NGT: string;
  Monitoring_SpO2: string;
  Monitoring_EtCO2: string;
  Monitoring_BIS: string;
  Monitoring_Katerer: string;
  Monitoring_Stetoskop: string;
  Monitoring_CVP: string;
  Monitoring_Temp: string;
  Monitoring_Lainnya: string;
  Monitoring_Lainnya_Teks: string;
  Monitoring_EKG_Teks: string;
  Monitoring_Arteri_Teks: string;
  Monitoring_CVP_Teks: string;
  ASA: string;
  Alergi: string;
  Alergi_Keterangan: string;
  Penyulit_Pra_Anestesi: string;
  Checklist_Inform_Consent: string;
  Checklist_Monitoring: string;
  Checklist_Obat_Anestesi: string;
  Checklist_Obat_Emergensi: string;
  Checklist_Tatalaksana: string;
  Checklist_Mesin: string;
  Checklist_Suction: string;
  Pra_Induksi_Kesadaran: string;
  Pra_Induksi_Denyut_Nadi: string;
  Pra_Induksi_Lainnya: string;
  Pra_Induksi_RR: string;
  Pra_Induksi_Saturasi: string;
  Pra_Induksi_Suhu: string;
  Pra_Induksi_Tekanan_Darah: string;
  Jam_Pra_Induksi: string;
  Catatan: string;
  Infus_Perifer_1: string;
  Infus_Perifer_2: string;
  Infus_Perifer_3: string;
  Posisi: string;
  Posisi_Lainnya: string;
  Premedikasi_IM: string;
  Premedikasi_IV: string;
  Premedikasi_Oral: string;
  Induksi_Intravena: string;
  Induksi_Inhalasi: string;
  Face_Mask_No: string;
  Oro_No: string;
  ETT_No: string;
  ETT_Fiksasi: string;
  ETT_Jenis: string;
  LMA_Jenis: string;
  LMA_No: string;
  Trakhesotomi: string;
  Bronkoskopi_Fiber: string;
  Glidescope: string;
  Tata_Laksana_Lainnya: string;
  Intubasi_Sesudah_Tidur: string;
  Intubasi_Blind: string;
  Intubasi_Cuff: string;
  Intubasi_Dengan_Stilet: string;
  Intubasi_Kanan: string;
  Intubasi_Kiri: string;
  Intubasi_Level_ETT: string;
  Intubasi_Nasal: string;
  Intubasi_Oral: string;
  Intubasi_Pack: string;
  Intubasi_Sulit_Intubasi: string;
  Intubasi_Sulit_Intubasi_Teks: string;
  Intubasi_Sulit_Ventilasi: string;
  Intubasi_Sulit_Ventilasi_Teks: string;
  Intubasi_Trakheostomi: string;
  Intubasi_Dengan_Stilet_Teks: string;
  Ventilasi_Kendali: string;
  Ventilasi_Lainnya: string;
  Ventilasi_Lainnya_Teks: string;
  Ventilasi_Spontan: string;
  Ventilasi_Ventilator: string;
  Ventilasi_Ventilator_PEEP: string;
  Ventilasi_Ventilator_RR: string;
  Ventilasi_Ventilator_TV: string;
  CKP_Jam_Masuk: string;
  CKP_Tekanan_Darah: string;
  CKP_Denyut_Nadi: string;
  CKP_Instruksi_Khusus: string;
  CKP_Kesadaran: string;
  CKP_Penyulit_Intra_Operatif: string;
  CKP_Pernafasan: string;
  CKP_RR: string;
  CKP_Suhu: string;
  VAS: string;
  VAS_Pulih: string;
  Jam_Keluar_Pulih: string;
  Aldrette_Aktivitas: string;
  Aldrette_Kesadaran: string;
  Aldrette_Pernafasan: string;
  Aldrette_Sirkulasi: string;
  Aldrette_Skor_VAS: string;
  Aldrette_Total: string;
  Aldrette_Warna_Kulit: string;
  Steward_Kesadaran: string;
  Steward_Motorik: string;
  Steward_Pernafasan: string;
  Steward_Skor_VAS: string;
  Steward_Total: string;
  Pindah_Ke: string;
  Pindah_Ke_Lainnya: string;
  Grid_Chart_Data: string;
  Grid_Chart_Img: string;
  Catatan_Khusus_Ruang_Pemulihan: string;
  IPA_Antibiotik: string;
  IPA_Diet: string;
  IPA_Infus: string;
  IPA_Lainnya: string;
  IPA_Obat: string;
  IPA_Penanganan_Mual: string;
  IPA_Pengelolaan_Nyeri: string;
  IPA_Tensi_Selama: string;
  IPA_Tensi_Setiap: string;
  TTD_Dokter_Anestesi: string;
  ID_Dokter_Anestesi: string;
  TTD_Penata_Anestesi: string;
  ID_Penata_Anestesi: string;
  Nama_Asisten_Anestesi: string;
  Nama_Dokter_Anestesi: string;
  Nama_DPJP_Anestesi: string;
  Nama_DPJP_Bedah: string;
  Nama_Penata_Anestesi: string;
  ID_Petugas: string;
  Nama_Petugas: string;
  Updated_At: string;
  Updated_By: string;
  Url_Image_Chart: string;
  Name_Image_Chart: string;
  Size_Image_Chart: string;
  Type_Image_Chart: string;
  Json_Image_Chart: string;
  Skala_Anestesi: string;
  Image_1: string;
  Image_2: string;
  Image_3: string;
}

export class AnestheticStatusModel {

 ID_DPJP_Anestesi: string;
  ID_DPJP_Bedah: string;
  ID_Asisten_Anestesi: string;
  Diagnosa_Pra_Bedah: string;
  Diagnosis_Pasca_Bedah: string;
  Jenis_Pembedahan: string;
  Teknik_Anestesi: string;
  Teknik_Anestesi_Lainnya: string;
  Teknik_Khusus_Hipotensi: string;
  Teknik_Khusus_Bronkoskopi: string;
  Teknik_Khusus_TCI: string;
  Teknik_Khusus_Glidescope: string;
  Teknik_Khusus_CPB: string;
  Teknik_Khusus_USG: string;
  Teknik_Khusus_Ventilasi: string;
  Teknik_Khusus_Stimulator: string;
  Teknik_Khusus_Lainnya: string;
  Teknik_Khusus_Lainnya_Teks: string;
  Monitoring_EKG: string;
  Monitoring_NIBP: string;
  Monitoring_Cath: string;
  Monitoring_Arteri: string;
  Monitoring_NGT: string;
  Monitoring_SpO2: string;
  Monitoring_EtCO2: string;
  Monitoring_BIS: string;
  Monitoring_Katerer: string;
  Monitoring_Stetoskop: string;
  Monitoring_CVP: string;
  Monitoring_Temp: string;
  Monitoring_Lainnya: string;
  Monitoring_Lainnya_Teks: string;
  Monitoring_EKG_Teks: string;
  Monitoring_Arteri_Teks: string;
  Monitoring_CVP_Teks: string;
  ASA: string;
  Alergi: string;
  Alergi_Keterangan: string;
  Penyulit_Pra_Anestesi: string;
  Checklist_Inform_Consent: string;
  Checklist_Monitoring: string;
  Checklist_Obat_Anestesi: string;
  Checklist_Obat_Emergensi: string;
  Checklist_Tatalaksana: string;
  Checklist_Mesin: string;
  Checklist_Suction: string;
  Pra_Induksi_Kesadaran: string;
  Pra_Induksi_Denyut_Nadi: string;
  Pra_Induksi_Lainnya: string;
  Pra_Induksi_RR: string;
  Pra_Induksi_Saturasi: string;
  Pra_Induksi_Suhu: string;
  Pra_Induksi_Tekanan_Darah: string;
  Jam_Pra_Induksi: string;
  Catatan: string;
  Infus_Perifer_1: string;
  Infus_Perifer_2: string;
  Infus_Perifer_3: string;
  Posisi: string;
  Posisi_Lainnya: string;
  Premedikasi_IM: string;
  Premedikasi_IV: string;
  Premedikasi_Oral: string;
  Induksi_Intravena: string;
  Induksi_Inhalasi: string;
  Face_Mask_No: string;
  Oro_No: string;
  ETT_No: string;
  ETT_Fiksasi: string;
  ETT_Jenis: string;
  LMA_Jenis: string;
  LMA_No: string;
  Trakhesotomi: string;
  Bronkoskopi_Fiber: string;
  Glidescope: string;
  Tata_Laksana_Lainnya: string;
  Intubasi_Sesudah_Tidur: string;
  Intubasi_Blind: string;
  Intubasi_Cuff: string;
  Intubasi_Dengan_Stilet: string;
  Intubasi_Kanan: string;
  Intubasi_Kiri: string;
  Intubasi_Level_ETT: string;
  Intubasi_Nasal: string;
  Intubasi_Oral: string;
  Intubasi_Pack: string;
  Intubasi_Sulit_Intubasi: string;
  Intubasi_Sulit_Intubasi_Teks: string;
  Intubasi_Sulit_Ventilasi: string;
  Intubasi_Sulit_Ventilasi_Teks: string;
  Intubasi_Trakheostomi: string;
  Intubasi_Dengan_Stilet_Teks: string;
  Ventilasi_Kendali: string;
  Ventilasi_Lainnya: string;
  Ventilasi_Lainnya_Teks: string;
  Ventilasi_Spontan: string;
  Ventilasi_Ventilator: string;
  Ventilasi_Ventilator_PEEP: string;
  Ventilasi_Ventilator_RR: string;
  Ventilasi_Ventilator_TV: string;
  CKP_Jam_Masuk: string;
  CKP_Tekanan_Darah: string;
  CKP_Denyut_Nadi: string;
  CKP_Instruksi_Khusus: string;
  CKP_Kesadaran: string;
  CKP_Penyulit_Intra_Operatif: string;
  CKP_Pernafasan: string;
  CKP_RR: string;
  CKP_Suhu: string;
  VAS: string;
  VAS_Pulih: string;
  Jam_Keluar_Pulih: string;
  Aldrette_Aktivitas: string;
  Aldrette_Kesadaran: string;
  Aldrette_Pernafasan: string;
  Aldrette_Sirkulasi: string;
  Aldrette_Skor_VAS: string;
  Aldrette_Total: string;
  Aldrette_Warna_Kulit: string;
  Steward_Kesadaran: string;
  Steward_Motorik: string;
  Steward_Pernafasan: string;
  Steward_Skor_VAS: string;
  Steward_Total: string;
  Pindah_Ke: string;
  Pindah_Ke_Lainnya: string;
  Grid_Chart_Data: string;
  Grid_Chart_Img: string;
  Catatan_Khusus_Ruang_Pemulihan: string;
  IPA_Antibiotik: string;
  IPA_Diet: string;
  IPA_Infus: string;
  IPA_Lainnya: string;
  IPA_Obat: string;
  IPA_Penanganan_Mual: string;
  IPA_Pengelolaan_Nyeri: string;
  IPA_Tensi_Selama: string;
  IPA_Tensi_Setiap: string;
  TTD_Dokter_Anestesi: string;
  ID_Dokter_Anestesi: string;
  TTD_Penata_Anestesi: string;
  ID_Penata_Anestesi: string;
  Nama_Asisten_Anestesi: string;
  Nama_Dokter_Anestesi: string;
  Nama_DPJP_Anestesi: string;
  Nama_DPJP_Bedah: string;
  Nama_Penata_Anestesi: string;
  ID_Petugas: string;
  Nama_Petugas: string;
  Updated_At: string;
  Updated_By: string;
  Url_Image_Chart: string;
  Name_Image_Chart: string;
  Size_Image_Chart: string;
  Type_Image_Chart: string;
  Json_Image_Chart: string;
  Skala_Anestesi: string;
  Image_1: string;
  Image_2: string;
  Image_3: string;

  constructor(form: IAnestheticStatusModel) {

    this.ID_DPJP_Anestesi = form.ID_DPJP_Anestesi;
    this.ID_DPJP_Bedah = form.ID_DPJP_Bedah;
    this.ID_Asisten_Anestesi = form.ID_Asisten_Anestesi;
    this.Diagnosa_Pra_Bedah = form.Diagnosa_Pra_Bedah;
    this.Diagnosis_Pasca_Bedah = form.Diagnosis_Pasca_Bedah;
    this.Jenis_Pembedahan = form.Jenis_Pembedahan;
    this.Teknik_Anestesi = form.Teknik_Anestesi;
    this.Teknik_Anestesi_Lainnya = form.Teknik_Anestesi_Lainnya;
    this.Teknik_Khusus_Hipotensi = form.Teknik_Khusus_Hipotensi;
    this.Teknik_Khusus_Bronkoskopi = form.Teknik_Khusus_Bronkoskopi;
    this.Teknik_Khusus_TCI = form.Teknik_Khusus_TCI;
    this.Teknik_Khusus_Glidescope = form.Teknik_Khusus_Glidescope;
    this.Teknik_Khusus_CPB = form.Teknik_Khusus_CPB;
    this.Teknik_Khusus_USG = form.Teknik_Khusus_USG;
    this.Teknik_Khusus_Ventilasi = form.Teknik_Khusus_Ventilasi;
    this.Teknik_Khusus_Stimulator = form.Teknik_Khusus_Stimulator;
    this.Teknik_Khusus_Lainnya = form.Teknik_Khusus_Lainnya;
    this.Teknik_Khusus_Lainnya_Teks = form.Teknik_Khusus_Lainnya_Teks;
    this.Monitoring_EKG = form.Monitoring_EKG;
    this.Monitoring_NIBP = form.Monitoring_NIBP;
    this.Monitoring_Cath = form.Monitoring_Cath;
    this.Monitoring_Arteri = form.Monitoring_Arteri;
    this.Monitoring_NGT = form.Monitoring_NGT;
    this.Monitoring_SpO2 = form.Monitoring_SpO2;
    this.Monitoring_EtCO2 = form.Monitoring_EtCO2;
    this.Monitoring_BIS = form.Monitoring_BIS;
    this.Monitoring_Katerer = form.Monitoring_Katerer;
    this.Monitoring_Stetoskop = form.Monitoring_Stetoskop;
    this.Monitoring_CVP = form.Monitoring_CVP;
    this.Monitoring_Temp = form.Monitoring_Temp;
    this.Monitoring_Lainnya = form.Monitoring_Lainnya;
    this.Monitoring_Lainnya_Teks = form.Monitoring_Lainnya_Teks;
    this.Monitoring_EKG_Teks = form.Monitoring_EKG_Teks;
    this.Monitoring_Arteri_Teks = form.Monitoring_Arteri_Teks;
    this.Monitoring_CVP_Teks = form.Monitoring_CVP_Teks;
    this.ASA = form.ASA;
    this.Alergi = form.Alergi;
    this.Alergi_Keterangan = form.Alergi_Keterangan;
    this.Penyulit_Pra_Anestesi = form.Penyulit_Pra_Anestesi;
    this.Checklist_Inform_Consent = form.Checklist_Inform_Consent;
    this.Checklist_Monitoring = form.Checklist_Monitoring;
    this.Checklist_Obat_Anestesi = form.Checklist_Obat_Anestesi;
    this.Checklist_Obat_Emergensi = form.Checklist_Obat_Emergensi;
    this.Checklist_Tatalaksana = form.Checklist_Tatalaksana;
    this.Checklist_Mesin = form.Checklist_Mesin;
    this.Checklist_Suction = form.Checklist_Suction;
    this.Pra_Induksi_Kesadaran = form.Pra_Induksi_Kesadaran;
    this.Pra_Induksi_Denyut_Nadi = form.Pra_Induksi_Denyut_Nadi;
    this.Pra_Induksi_Lainnya = form.Pra_Induksi_Lainnya;
    this.Pra_Induksi_RR = form.Pra_Induksi_RR;
    this.Pra_Induksi_Saturasi = form.Pra_Induksi_Saturasi;
    this.Pra_Induksi_Suhu = form.Pra_Induksi_Suhu;
    this.Pra_Induksi_Tekanan_Darah = form.Pra_Induksi_Tekanan_Darah;
    this.Jam_Pra_Induksi = form.Jam_Pra_Induksi;
    this.Catatan = form.Catatan;
    this.Infus_Perifer_1 = form.Infus_Perifer_1;
    this.Infus_Perifer_2 = form.Infus_Perifer_2;
    this.Infus_Perifer_3 = form.Infus_Perifer_3;
    this.Posisi = form.Posisi;
    this.Posisi_Lainnya = form.Posisi_Lainnya;
    this.Premedikasi_IM = form.Premedikasi_IM;
    this.Premedikasi_IV = form.Premedikasi_IV;
    this.Premedikasi_Oral = form.Premedikasi_Oral;
    this.Induksi_Intravena = form.Induksi_Intravena;
    this.Induksi_Inhalasi = form.Induksi_Inhalasi;
    this.Face_Mask_No = form.Face_Mask_No;
    this.Oro_No = form.Oro_No;
    this.ETT_No = form.ETT_No;
    this.ETT_Fiksasi = form.ETT_Fiksasi;
    this.ETT_Jenis = form.ETT_Jenis;
    this.LMA_Jenis = form.LMA_Jenis;
    this.LMA_No = form.LMA_No;
    this.Trakhesotomi = form.Trakhesotomi;
    this.Bronkoskopi_Fiber = form.Bronkoskopi_Fiber;
    this.Glidescope = form.Glidescope;
    this.Tata_Laksana_Lainnya = form.Tata_Laksana_Lainnya;
    this.Intubasi_Sesudah_Tidur = form.Intubasi_Sesudah_Tidur;
    this.Intubasi_Blind = form.Intubasi_Blind;
    this.Intubasi_Cuff = form.Intubasi_Cuff;
    this.Intubasi_Dengan_Stilet = form.Intubasi_Dengan_Stilet;
    this.Intubasi_Kanan = form.Intubasi_Kanan;
    this.Intubasi_Kiri = form.Intubasi_Kiri;
    this.Intubasi_Level_ETT = form.Intubasi_Level_ETT;
    this.Intubasi_Nasal = form.Intubasi_Nasal;
    this.Intubasi_Oral = form.Intubasi_Oral;
    this.Intubasi_Pack = form.Intubasi_Pack;
    this.Intubasi_Sulit_Intubasi = form.Intubasi_Sulit_Intubasi;
    this.Intubasi_Sulit_Intubasi_Teks = form.Intubasi_Sulit_Intubasi_Teks;
    this.Intubasi_Sulit_Ventilasi = form.Intubasi_Sulit_Ventilasi;
    this.Intubasi_Sulit_Ventilasi_Teks = form.Intubasi_Sulit_Ventilasi_Teks;
    this.Intubasi_Trakheostomi = form.Intubasi_Trakheostomi;
    this.Intubasi_Dengan_Stilet_Teks = form.Intubasi_Dengan_Stilet_Teks;
    this.Ventilasi_Kendali = form.Ventilasi_Kendali;
    this.Ventilasi_Lainnya = form.Ventilasi_Lainnya;
    this.Ventilasi_Lainnya_Teks = form.Ventilasi_Lainnya_Teks;
    this.Ventilasi_Spontan = form.Ventilasi_Spontan;
    this.Ventilasi_Ventilator = form.Ventilasi_Ventilator;
    this.Ventilasi_Ventilator_PEEP = form.Ventilasi_Ventilator_PEEP;
    this.Ventilasi_Ventilator_RR = form.Ventilasi_Ventilator_RR;
    this.Ventilasi_Ventilator_TV = form.Ventilasi_Ventilator_TV;
    this.CKP_Jam_Masuk = form.CKP_Jam_Masuk;
    this.CKP_Tekanan_Darah = form.CKP_Tekanan_Darah;
    this.CKP_Denyut_Nadi = form.CKP_Denyut_Nadi;
    this.CKP_Instruksi_Khusus = form.CKP_Instruksi_Khusus;
    this.CKP_Kesadaran = form.CKP_Kesadaran;
    this.CKP_Penyulit_Intra_Operatif = form.CKP_Penyulit_Intra_Operatif;
    this.CKP_Pernafasan = form.CKP_Pernafasan;
    this.CKP_RR = form.CKP_RR;
    this.CKP_Suhu = form.CKP_Suhu;
    this.VAS = form.VAS;
    this.VAS_Pulih = form.VAS_Pulih;
    this.Jam_Keluar_Pulih = form.Jam_Keluar_Pulih;
    this.Aldrette_Aktivitas = form.Aldrette_Aktivitas;
    this.Aldrette_Kesadaran = form.Aldrette_Kesadaran;
    this.Aldrette_Pernafasan = form.Aldrette_Pernafasan;
    this.Aldrette_Sirkulasi = form.Aldrette_Sirkulasi;
    this.Aldrette_Skor_VAS = form.Aldrette_Skor_VAS;
    this.Aldrette_Total = form.Aldrette_Total;
    this.Aldrette_Warna_Kulit = form.Aldrette_Warna_Kulit;
    this.Steward_Kesadaran = form.Steward_Kesadaran;
    this.Steward_Motorik = form.Steward_Motorik;
    this.Steward_Pernafasan = form.Steward_Pernafasan;
    this.Steward_Skor_VAS = form.Steward_Skor_VAS;
    this.Steward_Total = form.Steward_Total;
    this.Pindah_Ke = form.Pindah_Ke;
    this.Pindah_Ke_Lainnya = form.Pindah_Ke_Lainnya;
    this.Grid_Chart_Data = form.Grid_Chart_Data;
    this.Grid_Chart_Img = form.Grid_Chart_Img;
    this.Catatan_Khusus_Ruang_Pemulihan = form.Catatan_Khusus_Ruang_Pemulihan;
    this.IPA_Antibiotik = form.IPA_Antibiotik;
    this.IPA_Diet = form.IPA_Diet;
    this.IPA_Infus = form.IPA_Infus;
    this.IPA_Lainnya = form.IPA_Lainnya;
    this.IPA_Obat = form.IPA_Obat;
    this.IPA_Penanganan_Mual = form.IPA_Penanganan_Mual;
    this.IPA_Pengelolaan_Nyeri = form.IPA_Pengelolaan_Nyeri;
    this.IPA_Tensi_Selama = form.IPA_Tensi_Selama;
    this.IPA_Tensi_Setiap = form.IPA_Tensi_Setiap;
    this.TTD_Dokter_Anestesi = form.TTD_Dokter_Anestesi;
    this.ID_Dokter_Anestesi = form.ID_Dokter_Anestesi;
    this.TTD_Penata_Anestesi = form.TTD_Penata_Anestesi;
    this.ID_Penata_Anestesi = form.ID_Penata_Anestesi;
    this.Nama_Asisten_Anestesi = form.Nama_Asisten_Anestesi;
    this.Nama_Dokter_Anestesi = form.Nama_Dokter_Anestesi;
    this.Nama_DPJP_Anestesi = form.Nama_DPJP_Anestesi;
    this.Nama_DPJP_Bedah = form.Nama_DPJP_Bedah;
    this.Nama_Penata_Anestesi = form.Nama_Penata_Anestesi;
    this.ID_Petugas = form.ID_Petugas;
    this.Nama_Petugas = form.Nama_Petugas;
    this.Updated_At = form.Updated_At;
    this.Updated_By = form.Updated_By;
    this.Url_Image_Chart = form.Url_Image_Chart;
    this.Name_Image_Chart = form.Name_Image_Chart;
    this.Size_Image_Chart = form.Size_Image_Chart;
    this.Type_Image_Chart = form.Type_Image_Chart;
    this.Json_Image_Chart = form.Json_Image_Chart;
    this.Skala_Anestesi = form.Skala_Anestesi;
    this.Image_1 = form.Image_1;
    this.Image_2 = form.Image_2;
    this.Image_3 = form.Image_3;
  }
}

export interface IAnestheticStatusModel extends IDataModel {
  form: IAnestheticStatusModel;

}

export class AnestheticStatus extends DataModel {
  form?: AnestheticStatusModel;


  constructor(model: IAnestheticStatusModel) {
    super(model);
    if (model.form) {
      this.form = new AnestheticStatusModel(model.form);

    }
  }
}

