export default [
  'Glukoma + Katarak',
  'Glukoma Akut',
  'Endopthalmitis',
  'Corpus Auneum Cornea',
  'Katarak Senilis Imatur',
  'Katarak Senilis Matur',
  'AMD',
  'Laserasi Kornea',
  'PCO (Posterior Capsular Opacity)',
  'Diabetik Macular Edema',
  'Irigasi',
  'Amt + BCL',
  'Pterygium',
  'Heacting',
  'ICCE ECCCE Secondary',
  'Injeksi Antivegf',
  'Injeksi PB',
  'Injeksi Vancomicin',
  'Chalazion / Hordeoulum',
  'Laser',
  'Laser PDR',
  'ALR',
  'Epilasi Katarak Juvenile',
  'custom',
]
