// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 'Glukoma + Katarak',
    diagnose_wd_dd: 'Glukoma + Katarak',
    base_diagnose: 'Katarak dengan kekeruhan lensa',
    doctor_action: 'Infus manitol',
    action_indication: 'Menurunkan tekanan bola mata',
    how_to: 'Pasang infus manitol (60 tetes/menit)',
    goals: 'Menurunkan tekanan bola mata',
    risk: 'Tidak ada',
    complication: 'Hematoma. stuing',
    prognosis: 'Untuk tindakan fakoemulsifikasi',
    alternative_risk: 'Tidak ada',
    other_things: 'Tidak ada',
  },
  {
    id: 'Glukoma Akut',
    diagnose_wd_dd: 'Glukoma Akut',
    base_diagnose: 'Tekanan bola mata tinggi',
    doctor_action: 'Infus manitol',
    action_indication: 'Tekanan bola mata yang tinggi',
    how_to: 'Pasang infus manitol (60 tetes/menit)',
    goals: 'Menurunkan tekanan bola mata',
    risk: 'Tidak ada',
    complication: 'Hematoma. stuing',
    prognosis: 'Tidak ada',
    alternative_risk: 'Tidak ada',
    other_things: 'Tidak ada',
  },
  {
    id: 'Endopthalmitis',
    diagnose_wd_dd: 'Endopthalmitis',
    base_diagnose: 'Infeksi Intraokular',
    doctor_action: 'Injeksi Intravitrecil',
    action_indication: 'Infeksi Intraokular',
    how_to: 'Anestesi lokal, Injeksi intravitreal',
    goals: 'Mengatasi Infeksi',
    risk: 'Ringan',
    complication: 'Pendarahan Sub konjungtiva',
    prognosis: 'Baik',
    alternative_risk: 'Tidak ada',
    other_things: 'Tidak ada',
  },
  {
    id: 'Corpus Auneum Cornea',
    diagnose_wd_dd: 'Corpus Auneum Cornea',
    base_diagnose: 'Ada benda asing di kornea',
    doctor_action: 'Eskforposi benda asing',
    action_indication: 'Menghilangkan benda asing',
    how_to: 'Anestesi Topical, Eksforposi cospur almeun, Obat',
    goals: 'Mencegah Infeksi',
    risk: 'Ringan / Sedang',
    complication: 'Perforasi Kornea',
    prognosis: 'Baik',
    alternative_risk: 'Tidak ada',
    other_things: 'Tidak ada',
  },
  {
    id: 'Katarak Senilis Imatur',
    diagnose_wd_dd: 'Katarak Senilis Imatur',
    base_diagnose: 'Kekeruhan lensa',
    doctor_action: 'Fakoemulsifikasi + IOL',
    action_indication: 'Penglihatan kabur',
    how_to: 'Anestesi Topical, Emulsifikasi lensa, Implantasi IOL',
    goals: 'Memperbaiki Penglihatan',
    risk: 'Infeksi',
    complication: 'Corneal Oedema',
    prognosis: 'Baik',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'Katarak Senilis Matur',
    diagnose_wd_dd: 'Katarak Senilis Matur',
    base_diagnose: 'Kekeruhan lensa',
    doctor_action: 'Fakoemulsifikasi + IOL',
    action_indication: 'Penglihatan kabur',
    how_to: 'Anestesi Topical, Emulsifikasi lensa, Implantasi IOL',
    goals: 'Memperbaiki Penglihatan',
    risk: 'Infeksi',
    complication: 'Corneal Oedema',
    prognosis: 'Baik',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'AMD',
    diagnose_wd_dd: 'AMD',
    base_diagnose: 'Indirect',
    doctor_action: 'Injeksi Anti VEGF Intra Vitreus',
    action_indication: 'Subretinal Fluid',
    how_to: 'Topikal',
    goals: 'Mengurangi Subretinal Fluid',
    risk: 'Infeksi & Peradangan',
    complication: 'TIO Meningkat',
    prognosis: 'Dubia',
    alternative_risk: 'Tidak ada',
    other_things: 'Tidak ada',
  },
  {
    id: 'Laserasi Kornea',
    diagnose_wd_dd: 'Laserasi Kornea',
    base_diagnose: 'Robekan pada kornea',
    doctor_action: 'Heacting Kornea (Jahit Kornea)',
    action_indication: 'Menutup Luka Kornea',
    how_to: 'Anestesi umum / lokal, menjahit luka',
    goals: 'Mencegah Infeksi Intraocular',
    risk: 'Ringan / Sedang / Berat',
    complication: 'Infeksi / Radang',
    prognosis: 'Baik / Buruk',
    alternative_risk: 'Tidak ada',
    other_things: 'Tidak ada',
  },
  {
    id: 'PCO (Posterior Capsular Opacity)',
    diagnose_wd_dd: 'PCO (Posterior Capsular Opacity)',
    base_diagnose: 'Pengapuran kapsul posterior',
    doctor_action: 'Nd: Yag Laser',
    action_indication: 'Penurunan Visus, Silau',
    how_to: 'Anestesi Topical, Laser',
    goals: 'Memperbaiki Penglihatan',
    risk: 'Tidak ada',
    complication: 'Inflamasi / peninggian tekanan intraokuler',
    prognosis: 'Baik',
    alternative_risk: 'Tidak ada',
    other_things: 'Tidak ada',
  },
  {
    id: 'Diabetik Macular Edema',
    diagnose_wd_dd: 'Diabetik Macular Edema',
    base_diagnose: 'Indirect, OCT',
    doctor_action: 'Injeksi Anti VEGF Intra Vitreus',
    action_indication: 'Macular Edema',
    how_to: 'Topikal',
    goals: 'Mengurangi Edema Macular',
    risk: 'Endoftalmitis',
    complication: 'TIO Meningkat',
    prognosis: 'Dubia',
    alternative_risk: 'Tidak ada',
    other_things: 'Tidak ada',
  },
  {
    id: 'Irigasi',
    diagnose_wd_dd: '',
    base_diagnose: 'Trauma Kimia',
    doctor_action: 'Irigasi',
    action_indication: 'Menghilangkan zat kimia',
    how_to: 'Topikal',
    goals: 'Menghilangkan zat kimia',
    risk: 'Erosi',
    complication: '',
    prognosis: 'Dubia (Tergantung kondisi kornea & zat kimianya)',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'Amt + BCL',
    diagnose_wd_dd: 'AMT BCLFLAP GRAFT',
    base_diagnose: 'Discontiunitas kornea dengan rasa nyeri',
    doctor_action: 'Amt + BCL',
    action_indication: 'Mangurangi nyeri, mencegah perforasi',
    how_to: '- Anestesi Topical - Scrapping kornea',
    goals: 'Mengurangi nyeri, mempercepat penyembuhan',
    risk: '- Infeksi - Perforasi - Radang',
    complication: 'Infeksi, Radang , Perforasi',
    prognosis: '',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'Pterygium',
    diagnose_wd_dd: 'Pterygium',
    base_diagnose: 'Selaput masuk ke kornea',
    doctor_action: 'Eksisi pterygium',
    action_indication: 'Sering merah dan mengganjal',
    how_to: '- Topikal Anestesi - Eksisi',
    goals: 'Menghilangkan selaput di kornea',
    risk: 'Rekuren',
    complication: 'Pendarahan conjunctiva + oedema conjunctiva',
    prognosis: '',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'Heacting',
    diagnose_wd_dd: 'Laserasi Kornea',
    base_diagnose: 'Robekan pada kornea',
    doctor_action: 'Heacting kornea (jahit kornea)',
    action_indication: 'Menutup luka kornea',
    how_to: '- Anestesi umum / lokal - Menjahit luka',
    goals: 'Mencegah infeksi intraokular',
    risk: 'Ringan / Sedang / Berat',
    complication: 'Ringan / Sedang / Berat',
    prognosis: '',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'ICCE ECCCE Secondary',
    diagnose_wd_dd: '',
    base_diagnose: '',
    doctor_action: '',
    action_indication: 'Penglihatan Kabur',
    how_to: '- Anestesi Topikal',
    goals: 'Memperbaiki pengelihatan',
    risk: 'Infeksi, Pendarahan',
    complication: 'Corneal Oedema, Ablasio Retina',
    prognosis: '',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'Injeksi Antivegf',
    diagnose_wd_dd: '',
    base_diagnose: 'OCT',
    doctor_action: 'Injeksi anti VEGF/LA',
    action_indication: 'Mengurangi Edema pada makula, mengurangi pendarahan pada vitreous',
    how_to: 'topikal',
    goals: 'Mengurangi Edema pada makula, mengurangi pendarahan pada vitreous',
    risk: 'Inflamasi, Infeksi,Retinal Detachment, pendarahan vitreous',
    complication: '',
    prognosis: 'Hasil bergantung syaraf mata',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'Injeksi PB',
    diagnose_wd_dd: '',
    base_diagnose: 'COA = Membran (+), USG bersih',
    doctor_action: 'Injeksi Peribulbar Dexametason/LA',
    action_indication: 'Untuk mencegah infeksi lebih lanjut',
    how_to: 'Anastesi lokal',
    goals: 'Meredakan peradangan paska operasi',
    risk: '- pendarahan peribulbar - infeksi',
    complication: '',
    prognosis: 'Tergantung kondisi syaraf mata',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'Injeksi Vancomicin',
    diagnose_wd_dd: 'Endopthalmitis',
    base_diagnose: 'Infeksi Intraokuler',
    doctor_action: 'Injeksi Intravitreal',
    action_indication: 'Infeksi Intraokuler',
    how_to: '- Anestesi topikal - Injeksi intravitreal',
    goals: 'Mengatasi infeksi',
    risk: 'Ringan',
    complication: 'Pendarahan Subkonjunctiva',
    prognosis: '',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'Chalazion / Hordeoulum',
    diagnose_wd_dd: 'Chalazion / Hordeoulum',
    base_diagnose: 'Benjolan pada kelopak mata',
    doctor_action: 'Insisi Chalazion / Hordeoulum',
    action_indication: 'Hordeoulum Supuratif',
    how_to: '- Anestesi Lokal - Insisi - Kuretase',
    goals: 'Menghilangkan benjolan',
    risk: 'Hematoma, pendarahan',
    complication: '',
    prognosis: '',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'Laser',
    diagnose_wd_dd: '',
    base_diagnose: 'OCT , Indirect. Ophthalmoscopy',
    doctor_action: '',
    action_indication: 'Mencegah terjadinya robekan pada syaraf mata',
    how_to: 'Topikal',
    goals: 'Preventif',
    risk: '- Robekan pada retina - Pendarahan - Inflamasi',
    complication: '',
    prognosis: '',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'Laser PDR',
    diagnose_wd_dd: '',
    base_diagnose: 'OCT',
    doctor_action: '',
    action_indication: 'Preventif kerusakan lebih lanjut',
    how_to: 'Topikal',
    goals: '',
    risk: '- Robekan pada retina - Pendarahan - Inflamasi',
    complication: 'Preventif kerusakan lebih lanjut',
    prognosis: 'Dubia bergantung kondisi retina',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'ALR',
    diagnose_wd_dd: 'Entropion Superior',
    base_diagnose: 'Lekukan tepi palpebral kea rah bulbus okuli',
    doctor_action: 'ALR',
    action_indication: 'Mencegah kerusakan pada kornea',
    how_to: '- Anestesi Lokal - Fixsasi lemak orbita - Insisi Kulit - Eksisi musfulus',
    goals: 'Memperbaiki posisi kelopak mata bawah sesuai anatomi',
    risk: '- Infeksi - Malposisi',
    complication: 'Infeksi',
    prognosis: '',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'Epilasi',
    diagnose_wd_dd: 'Entropion – Trichiasis',
    base_diagnose: 'Bulu mata masuk',
    doctor_action: 'Epilasi',
    action_indication: 'Bulu mata masuk',
    how_to: '- Pantocain - Epilasi',
    goals: 'Mengurangi inflamasi, erosi kornea',
    risk: 'Inflamasi',
    complication: '',
    prognosis: '',
    alternative_risk: '',
    other_things: '',
  },
  {
    id: 'Katarak Juvenile',
    diagnose_wd_dd: 'Katarak Juvenile',
    base_diagnose: 'kekeruhan lensa, visual aquity',
    doctor_action: 'Fakoemulsifikasi + IOL',
    action_indication: 'Penglihatan Kabur',
    how_to: '- Anestesi Topikal - Emulsifikasi lensa - Implantasi IOL',
    goals: 'Memperbaiki pengelihatan',
    risk: 'Infeksi, Pendarahan',
    complication: 'Corneal Oedema, Ablasio Retina',
    prognosis: '',
    alternative_risk: '',
    other_things: '',
  },
]
