import { CreatePDFRequest, ICreatePDFRequest } from '@shared/pdf/requests/create-pdf.request';
import { InpatientInitialNursingAssessment } from '@modules/inpatient/inpatient-initial-nursing-assessment/models/inpatient-initial-nursing-assessment.model';
import { DateTimeConverter } from '@src/shared/datetime-converter';

export interface IPdfInpatientInitialNursingAssessmentRequest extends ICreatePDFRequest {
  data: {
    nomor_mr: string;
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string | number,
    'pasien.Jenis_Kelamin': string,
    tempat_tinggal1: string;
    tempat_tinggal2: string;
    tempat_tinggal3: string;
    tempat_tinggal4: string;
    diagnosa_khusus_lain: string,
    sosial_baik: string,
    sosial_tidak: string,
    tgl_ranap: string,
    alergi_obat: string,
    alergi_makanan: string,
    alergi_lainya: string,
    reaksi_alergiobat: string,
    reaksi_alergimakanan: string,
    reaksi_alergilainya: string,
    Keluhan_utama: string,
    riwayat_kesehatan: string,
    riwayat_ranap: string,
    alat_implant_ket: string,
    status_psikologis_lain_lain: string,
    masalah_prilaku_ket: string,
    perilaku_kekerasan_ket: string,
    nama_kerabat: string,
    hubungan_kerabat: string,
    tlp_kerabat: string,
    agama: string,
    keyakinan: string,
    nilai_nilai_kepercayaan: string,
    kegiatan_spiritual: string,
    td: string,
    suhu: string,
    nadi: string,
    bb: string,
    p: string,
    tb: string,
    get_date_time_nutrisionis: string,
    aktivitas_bantua_ket: string,
    alat_bantu_jalan: string,
    provocating: string,
    quality: string,
    region: string,
    severity: string,
    time: string,
    nyeri_hilang_lain: string,
    hambatan_pembelajaran_lain: string,
    topic_keperawatan_ket: string,
    topic_pembelajaran_lain: string,
    lokas_MataOD: string,
    lokas_MataOS: string,
    mkn_1: string,
    mkn_2: string,
    mkn_3: string,
    mkn_4: string,
    mkn_5: string,
    mkn_6: string,
    mandi_1: string,
    mandi_2: string,
    mandi_3: string,
    mandi_4: string,
    mandi_5: string,
    mandi_6: string,
    rawat_1: string,
    rawat_2: string,
    rawat_3: string,
    rawat_4: string,
    rawat_5: string,
    rawat_6: string,
    pakaian_1: string,
    pakaian_2: string,
    pakaian_3: string,
    pakaian_4: string,
    pakaian_5: string,
    pakaian_6: string,
    bak_1: string,
    bak_2: string,
    bak_3: string,
    bak_4: string,
    bak_5: string,
    bak_6: string,
    bab_1: string,
    bab_2: string,
    bab_3: string,
    bab_4: string,
    bab_5: string,
    bab_6: string,
    toilet_1: string,
    toilet_2: string,
    toilet_3: string,
    toilet_4: string,
    toilet_5: string,
    toilet_6: string,
    tf_1: string,
    tf_2: string,
    tf_3: string,
    tf_4: string,
    tf_5: string,
    tf_6: string,
    mobilitas_1: string,
    mobilitas_2: string,
    mobilitas_3: string,
    mobilitas_4: string,
    mobilitas_5: string,
    mobilitas_6: string,
    tangga_1: string,
    tangga_2: string,
    tangga_3: string,
    tangga_4: string,
    tangga_5: string,
    tangga_6: string,
    total_1: string,
    total_2: string,
    total_3: string,
    total_4: string,
    total_5: string,
    total_6: string,
    date: string,
    'form.Nama_Perawat_pengkaji': string,
    skrining_gizi_1a: string,
    skrining_gizi_1b: string,
    skrining_gizi_1c_1: string,
    skrining_gizi_1c_2: string,
    skrining_gizi_1c_3: string,
    skrining_gizi_1c_4: string,
    skrining_gizi_1c_5: string,
    skrining_gizi_2a: string,
    skrining_gizi_2b: string,
    skala_nyeri_1: string,
    skala_nyeri_2: string,
    skala_nyeri_3: string,
    skala_nyeri_4: string,
    skala_nyeri_5: string,
    skala_nyeri_6: string,
    skala_nyeri_7: string,
    skala_nyeri_8: string,
    skala_nyeri_9: string,
    skala_nyeri_10: string,

    riwayat_1: string,
    riwayat_2: string,
    riwayat_3: string,
    riwayat_4: string,
    riwayat_5: string,
    riwayat_6: string,
    pernah_dirawat_1: string,
    pernah_dirawat_2: string,
    alat_implant_1: string,
    alat_implant_2: string,
    status_psikologis_1: string,
    status_psikologis_2: string,
    status_psikologis_3: string,
    status_psikologis_4: string,
    status_psikologis_5: string,
    status_psikologis_6: string,
    status_mental_1: string,
    status_mental_2: string,
    status_mental_3: string,
    dx_khusus_1: string,
    dx_khusus_2: string,
    dx_khusus_3: string,
    dx_khusus_4: string,
    dx_khusus_5: string,
    dx_khusus_6: string,
    dx_khusus_7: string,
    dx_khusus_8: string,
    dx_khusus_9: string,
    nutrisionis_ya: string,
    nutrisionis_tidak: string,
    risiko_jatuh_tidak: string,
    risiko_jatuh_ya_1: string,
    risiko_jatuh_ya_2: string,
    aktivitas_1: string,
    aktivitas_2: string,
    skrining_nyeri_tidak: string,
    skrining_nyeri_ya: string,
    nyeri_hilang_1: string,
    nyeri_hilang_2: string,
    nyeri_hilang_3: string,
    nyeri_hilang_4: string,
    nyeri_hilang_5: string,
    hambatan_pembelajaran_tidak: string,
    hambatan_pembelajaran_ya: string,
    hambatan_pembelajaran_ya_1: string,
    hambatan_pembelajaran_ya_2: string,
    hambatan_pembelajaran_ya_3: string,
    hambatan_pembelajaran_ya_4: string,
    hambatan_pembelajaran_ya_5: string,
    hambatan_pembelajaran_ya_6: string,
    hambatan_pembelajaran_ya_7: string,
    hambatan_pembelajaran_ya_8: string,
    hambatan_pembelajaran_ya_9: string,
    topic_pembelajaran_1: string,
    topic_pembelajaran_2: string,
    topic_pembelajaran_3: string,
    topic_pembelajaran_4: string,
    topic_pembelajaran_5: string,
    topic_pembelajaran_6: string,
    topic_pembelajaran_7: string,
    gangguang_pengelihatan: string,
    penurunan_kesadaran: string,
    nyeri: string,
    infeksi: string,
    intake: string,
    resiko_jatuh: string,
    Hiperthermia: string,
    tio: string,
    lainya: string,
    masalah_keperawatan: string,
    rencana_keperawatan: string,
    Tanda_Tangan_Perawat_Pengkaji: string,
    skala_nyeri_0: string,
    nik: string,
  }
}

export class PdfInpatientInitialNursingAssessmentRequest extends CreatePDFRequest {
  data: {
    nomor_mr: string;
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string | number,
    'pasien.Jenis_Kelamin': string,
    tempat_tinggal1: string;
    tempat_tinggal2: string;
    tempat_tinggal3: string;
    tempat_tinggal4: string;
    diagnosa_khusus_lain: string,
    sosial_baik: string,
    sosial_tidak: string,
    tgl_ranap: string,
    alergi_obat: string,
    alergi_makanan: string,
    alergi_lainya: string,
    reaksi_alergiobat: string,
    reaksi_alergimakanan: string,
    reaksi_alergilainya: string,
    Keluhan_utama: string,
    riwayat_kesehatan: string,
    riwayat_ranap: string,
    alat_implant_ket: string,
    status_psikologis_lain_lain: string,
    masalah_prilaku_ket: string,
    perilaku_kekerasan_ket: string,
    nama_kerabat: string,
    hubungan_kerabat: string,
    tlp_kerabat: string,
    agama: string,
    keyakinan: string,
    nilai_nilai_kepercayaan: string,
    kegiatan_spiritual: string,
    td: string,
    suhu: string,
    nadi: string,
    bb: string,
    p: string,
    tb: string,
    get_date_time_nutrisionis: string,
    aktivitas_bantua_ket: string,
    alat_bantu_jalan: string,
    provocating: string,
    quality: string,
    region: string,
    severity: string,
    time: string,
    nyeri_hilang_lain: string,
    hambatan_pembelajaran_lain: string,
    topic_keperawatan_ket: string,
    topic_pembelajaran_lain: string,
    mkn_1: string,
    mkn_2: string,
    mkn_3: string,
    mkn_4: string,
    mkn_5: string,
    mkn_6: string,
    mandi_1: string,
    mandi_2: string,
    mandi_3: string,
    mandi_4: string,
    mandi_5: string,
    mandi_6: string,
    rawat_1: string,
    rawat_2: string,
    rawat_3: string,
    rawat_4: string,
    rawat_5: string,
    rawat_6: string,
    pakaian_1: string,
    pakaian_2: string,
    pakaian_3: string,
    pakaian_4: string,
    pakaian_5: string,
    pakaian_6: string,
    bak_1: string,
    bak_2: string,
    bak_3: string,
    bak_4: string,
    bak_5: string,
    bak_6: string,
    bab_1: string,
    bab_2: string,
    bab_3: string,
    bab_4: string,
    bab_5: string,
    bab_6: string,
    toilet_1: string,
    toilet_2: string,
    toilet_3: string,
    toilet_4: string,
    toilet_5: string,
    toilet_6: string,
    tf_1: string,
    tf_2: string,
    tf_3: string,
    tf_4: string,
    tf_5: string,
    tf_6: string,
    mobilitas_1: string,
    mobilitas_2: string,
    mobilitas_3: string,
    mobilitas_4: string,
    mobilitas_5: string,
    mobilitas_6: string,
    tangga_1: string,
    tangga_2: string,
    tangga_3: string,
    tangga_4: string,
    tangga_5: string,
    tangga_6: string,
    total_1: string,
    total_2: string,
    total_3: string,
    total_4: string,
    total_5: string,
    total_6: string,
    date: string,
    lokas_MataOD: string,
    lokas_MataOS: string,
    'form.Nama_Perawat_pengkaji': string,
    skrining_gizi_1a: string,
    skrining_gizi_1b: string,
    skrining_gizi_1c_1: string,
    skrining_gizi_1c_2: string,
    skrining_gizi_1c_3: string,
    skrining_gizi_1c_4: string,
    skrining_gizi_1c_5: string,
    skrining_gizi_2a: string,
    skrining_gizi_2b: string,
    skala_nyeri_0: string,
    skala_nyeri_1: string,
    skala_nyeri_2: string,
    skala_nyeri_3: string,
    skala_nyeri_4: string,
    skala_nyeri_5: string,
    skala_nyeri_6: string,
    skala_nyeri_7: string,
    skala_nyeri_8: string,
    skala_nyeri_9: string,
    skala_nyeri_10: string,

    riwayat_1: string,
    riwayat_2: string,
    riwayat_3: string,
    riwayat_4: string,
    riwayat_5: string,
    riwayat_6: string,
    pernah_dirawat_1: string,
    pernah_dirawat_2: string,
    alat_implant_1: string,
    alat_implant_2: string,
    status_psikologis_1: string,
    status_psikologis_2: string,
    status_psikologis_3: string,
    status_psikologis_4: string,
    status_psikologis_5: string,
    status_psikologis_6: string,
    status_mental_1: string,
    status_mental_2: string,
    status_mental_3: string,
    dx_khusus_1: string,
    dx_khusus_2: string,
    dx_khusus_3: string,
    dx_khusus_4: string,
    dx_khusus_5: string,
    dx_khusus_6: string,
    dx_khusus_7: string,
    dx_khusus_8: string,
    dx_khusus_9: string,
    nutrisionis_ya: string,
    nutrisionis_tidak: string,
    risiko_jatuh_tidak: string,
    risiko_jatuh_ya_1: string,
    risiko_jatuh_ya_2: string,
    aktivitas_1: string,
    aktivitas_2: string,
    skrining_nyeri_tidak: string,
    skrining_nyeri_ya: string,
    nyeri_hilang_1: string,
    nyeri_hilang_2: string,
    nyeri_hilang_3: string,
    nyeri_hilang_4: string,
    nyeri_hilang_5: string,
    hambatan_pembelajaran_tidak: string,
    hambatan_pembelajaran_ya: string,
    hambatan_pembelajaran_ya_1: string,
    hambatan_pembelajaran_ya_2: string,
    hambatan_pembelajaran_ya_3: string,
    hambatan_pembelajaran_ya_4: string,
    hambatan_pembelajaran_ya_5: string,
    hambatan_pembelajaran_ya_6: string,
    hambatan_pembelajaran_ya_7: string,
    hambatan_pembelajaran_ya_8: string,
    hambatan_pembelajaran_ya_9: string,
    topic_pembelajaran_1: string,
    topic_pembelajaran_2: string,
    topic_pembelajaran_3: string,
    topic_pembelajaran_4: string,
    topic_pembelajaran_5: string,
    topic_pembelajaran_6: string,
    topic_pembelajaran_7: string,
    gangguang_pengelihatan: string,
    penurunan_kesadaran: string,
    nyeri: string,
    infeksi: string,
    intake: string,
    resiko_jatuh: string,
    Hiperthermia: string,
    tio: string,
    lainya: string,
    masalah_keperawatan: string,
    rencana_keperawatan: string,
    Tanda_Tangan_Perawat_Pengkaji: string,
    nik: string,
  }

  constructor(req: IPdfInpatientInitialNursingAssessmentRequest) {
    super(req);
    this.data = req.data;
  }

  static createFromJson(json: IPdfInpatientInitialNursingAssessmentRequest) {
    return new PdfInpatientInitialNursingAssessmentRequest(json);
  }

  static createPdfRequest(val: any, emrId: string): PdfInpatientInitialNursingAssessmentRequest {
    return new PdfInpatientInitialNursingAssessmentRequest({
      emr_id: emrId,
      form_name: 'rawat-inap_pengkajian-awal-keperawatan-dewasa',
      row_filter: '',
      preview: false,
      data: {
        nomor_mr: val?.nomor_mr ?? '',
        'pasien.Nama': val?.pasien?.Nama ?? '',
        'pasien.Tgl_Lahir': DateTimeConverter.convertToNormalDate(val?.pasien?.Tgl_Lahir),
        'pasien.Umur': this.normalizeAge(val?.umur_lengkap),
        'pasien.Jenis_Kelamin': val?.pasien?.Jenis_Kelamin ?? '',

        tempat_tinggal1: this.getCheckImage(val?.form?.Tempat_Tinggal === '0'),
        tempat_tinggal2: this.getCheckImage(val?.form?.Tempat_Tinggal === '1'),
        tempat_tinggal3: this.getCheckImage(val?.form?.Tempat_Tinggal === '2'),
        tempat_tinggal4: this.getCheckImage(val?.form?.Tempat_Tinggal === '3'),
        diagnosa_khusus_lain: val?.form?.Penyakit_Lain_Keterangan ?? '',
        tgl_ranap: DateTimeConverter.convertToNormalDate(val?.form?.Tanggal_Masuk_Rawat_Inap),
        alergi_obat: val?.form?.Riwayat_Alergi_Obat_Keterangan ?? '',
        alergi_makanan: val?.form?.Riwayat_Alergi_Makanan_Keterangan ?? '',
        alergi_lainya: val?.form?.Riwayat_Alergi_Lainnya_Keterangan ?? '',
        reaksi_alergiobat: val?.form?.Riwayat_Alergi_Obat_Reaksi ?? '',
        reaksi_alergimakanan: val?.form?.Riwayat_Alergi_Makanan_Reaksi ?? '',
        reaksi_alergilainya: val?.form?.Riwayat_Alergi_Lainnya_Reaksi ?? '',
        Keluhan_utama: val?.form?.Keluhan_Utama ?? '',
        riwayat_kesehatan: val?.form?.Riwayat_Pengobatan_Sebelumnya ?? '',
        riwayat_ranap: val?.form?.Pernah_Dirawat_Keterangan ?? '',
        alat_implant_ket: val?.form?.Implant_Terpasang_Keterangan ?? '',
        status_psikologis_lain_lain: val?.form?.Status_Psikologis_Keterangan ?? '',
        masalah_prilaku_ket: val?.form?.Status_Mental_Lain_Keterangan ?? '',
        perilaku_kekerasan_ket: val?.form?.Status_Mental_Kekerasan_Keterangan ?? '',
        nama_kerabat: val?.form?.Kerabat_Nama ?? '',
        hubungan_kerabat: val?.form?.Kerabat_Hubungan ?? '',
        tlp_kerabat: val?.form?.Kerabat_No_Telepon ?? '',
        agama: val?.form?.Agama ?? '',
        keyakinan: val?.form?.Keyakinan ?? '',
        nilai_nilai_kepercayaan: val?.form?.Nilai_Nilai ?? '',
        kegiatan_spiritual: val?.form?.Kegiatan_Spiritual ?? '',
        td: val?.form?.Pemeriksaan_Fisik?.Tekanan_Darah ?? '',
        suhu: val?.form?.Pemeriksaan_Fisik?.Suhu ?? '',
        nadi: val?.form?.Pemeriksaan_Fisik?.Nadi ?? '',
        bb: val?.form?.Pemeriksaan_Fisik?.Berat_Badan ?? '',
        p: val?.form?.Pemeriksaan_Fisik?.Pernafasan ?? '',
        tb: val?.form?.Pemeriksaan_Fisik?.Tinggi_Badan ?? '',
        get_date_time_nutrisionis: DateTimeConverter.convertToDateTime(val?.form?.Nutrisionis_Tanggal),
        aktivitas_bantua_ket: val?.form?.Status_Fungsional_Keterangan ?? '',
        alat_bantu_jalan: val?.form?.Alat_Bantu_Jalan_Id ?? '',
        provocating: val?.form?.Provocating ?? '',
        quality: val?.form?.Quality ?? '',
        region: val?.form?.Region ?? '',
        severity: val?.form?.Severity ?? '',
        time: val?.form?.Tanggal_Masuk_Rawat_Inap && val?.form?.Tanggal_Masuk_Rawat_Inap !== '' ? val?.form?.Tanggal_Masuk_Rawat_Inap.substring(11, 16) : '',
        nyeri_hilang_lain: val?.form?.Nyeri_Hilang_Lainnya_Text ?? '',
        hambatan_pembelajaran_lain: val?.form?.Jenis_Hambatan_Lain_Keterangan ?? '',
        topic_keperawatan_ket: '',
        topic_pembelajaran_lain: val?.form?.Topik_Pembelajaran_Lain_Keterangan ?? '',
        mkn_1: val?.form?.Sebelum_Sakit?.Makan ?? '',
        mkn_2: val?.form?.Saat_Masuk_RS?.Makan ?? '',
        mkn_3: val?.form?.Minggu_2_RS?.Makan ?? '',
        mkn_4: val?.form?.Minggu_3_RS?.Makan ?? '',
        mkn_5: val?.form?.Minggu_4_RS?.Makan ?? '',
        mkn_6: val?.form?.Saat_Pulang?.Makan ?? '',
        mandi_1: val?.form?.Sebelum_Sakit?.Mandi ?? '',
        mandi_2: val?.form?.Saat_Masuk_RS?.Mandi ?? '',
        mandi_3: val?.form?.Minggu_2_RS?.Mandi ?? '',
        mandi_4: val?.form?.Minggu_3_RS?.Mandi ?? '',
        mandi_5: val?.form?.Minggu_4_RS?.Mandi ?? '',
        mandi_6: val?.form?.Saat_Pulang?.Mandi ?? '',
        skrining_gizi_1a: this.getCheckImage(val?.form?.Nutrisi_Turun_Bb === '0'),
        skrining_gizi_1b: this.getCheckImage(val?.form?.Nutrisi_Turun_Bb === '1'),
        skrining_gizi_1c_1: this.getCheckImage(val?.form?.Nutrisi_Turun_Bb === '2'),
        skrining_gizi_1c_2: this.getCheckImage(val?.form?.Nutrisi_Turun_Bb === '3'),
        skrining_gizi_1c_3: this.getCheckImage(val?.form?.Nutrisi_Turun_Bb === '4'),
        skrining_gizi_1c_4: this.getCheckImage(val?.form?.Nutrisi_Turun_Bb === '5'),
        skrining_gizi_1c_5: this.getCheckImage(val?.form?.Nutrisi_Turun_Bb === '6'),
        skrining_gizi_2a: this.getCheckImage(val?.form?.Asupan_Makan === '0'),
        skrining_gizi_2b: this.getCheckImage(val?.form?.Asupan_Makan === '1'),
        skala_nyeri_0: this.getCheckImage(val?.form?.Skala_Nyeri === '0'),
        skala_nyeri_1: this.getCheckImage(val?.form?.Skala_Nyeri === '1'),
        skala_nyeri_2: this.getCheckImage(val?.form?.Skala_Nyeri === '2'),
        skala_nyeri_3: this.getCheckImage(val?.form?.Skala_Nyeri === '3'),
        skala_nyeri_4: this.getCheckImage(val?.form?.Skala_Nyeri === '4'),
        skala_nyeri_5: this.getCheckImage(val?.form?.Skala_Nyeri === '5'),
        skala_nyeri_6: this.getCheckImage(val?.form?.Skala_Nyeri === '6'),
        skala_nyeri_7: this.getCheckImage(val?.form?.Skala_Nyeri === '7'),
        skala_nyeri_8: this.getCheckImage(val?.form?.Skala_Nyeri === '8'),
        skala_nyeri_9: this.getCheckImage(val?.form?.Skala_Nyeri === '9'),
        skala_nyeri_10: this.getCheckImage(val?.form?.Skala_Nyeri === '10'),
        rawat_1: val?.form?.Sebelum_Sakit?.Perawatan_Diri ?? '',
        rawat_2: val?.form?.Saat_Masuk_RS?.Perawatan_Diri ?? '',
        rawat_3: val?.form?.Minggu_2_RS?.Perawatan_Diri ?? '',
        rawat_4: val?.form?.Minggu_3_RS?.Perawatan_Diri ?? '',
        rawat_5: val?.form?.Minggu_4_RS?.Perawatan_Diri ?? '',
        rawat_6: val?.form?.Saat_Pulang?.Perawatan_Diri ?? '',
        pakaian_1: val?.form?.Sebelum_Sakit?.Berpakaian ?? '',
        pakaian_2: val?.form?.Saat_Masuk_RS?.Berpakaian ?? '',
        pakaian_3: val?.form?.Minggu_2_RS?.Berpakaian ?? '',
        pakaian_4: val?.form?.Minggu_3_RS?.Berpakaian ?? '',
        pakaian_5: val?.form?.Minggu_4_RS?.Berpakaian ?? '',
        pakaian_6: val?.form?.Saat_Pulang?.Berpakaian ?? '',
        bak_1: val?.form?.Sebelum_Sakit?.BAK ?? '',
        bak_2: val?.form?.Saat_Masuk_RS?.BAK ?? '',
        bak_3: val?.form?.Minggu_2_RS?.BAK ?? '',
        bak_4: val?.form?.Minggu_3_RS?.BAK ?? '',
        bak_5: val?.form?.Minggu_4_RS?.BAK ?? '',
        bak_6: val?.form?.Saat_Pulang?.BAK ?? '',
        bab_1: val?.form?.Sebelum_Sakit?.BAB ?? '',
        bab_2: val?.form?.Saat_Masuk_RS?.BAB ?? '',
        bab_3: val?.form?.Minggu_2_RS?.BAB ?? '',
        bab_4: val?.form?.Minggu_3_RS?.BAB ?? '',
        bab_5: val?.form?.Minggu_4_RS?.BAB ?? '',
        bab_6: val?.form?.Saat_Pulang?.BAB ?? '',
        toilet_1: val?.form?.Sebelum_Sakit?.Penggunaan_Toilet ?? '',
        toilet_2: val?.form?.Saat_Masuk_RS?.Penggunaan_Toilet ?? '',
        toilet_3: val?.form?.Minggu_2_RS?.Penggunaan_Toilet ?? '',
        toilet_4: val?.form?.Minggu_3_RS?.Penggunaan_Toilet ?? '',
        toilet_5: val?.form?.Minggu_4_RS?.Penggunaan_Toilet ?? '',
        toilet_6: val?.form?.Saat_Pulang?.Penggunaan_Toilet ?? '',
        tf_1: val?.form?.Sebelum_Sakit?.Transfer ?? '',
        tf_2: val?.form?.Saat_Masuk_RS?.Transfer ?? '',
        tf_3: val?.form?.Minggu_2_RS?.Transfer ?? '',
        tf_4: val?.form?.Minggu_3_RS?.Transfer ?? '',
        tf_5: val?.form?.Minggu_4_RS?.Transfer ?? '',
        tf_6: val?.form?.Saat_Pulang?.Transfer ?? '',
        mobilitas_1: val?.form?.Sebelum_Sakit?.Mobilitas ?? '',
        mobilitas_2: val?.form?.Saat_Masuk_RS?.Mobilitas ?? '',
        mobilitas_3: val?.form?.Minggu_2_RS?.Mobilitas ?? '',
        mobilitas_4: val?.form?.Minggu_3_RS?.Mobilitas ?? '',
        mobilitas_5: val?.form?.Minggu_4_RS?.Mobilitas ?? '',
        mobilitas_6: val?.form?.Saat_Pulang?.Mobilitas ?? '',
        tangga_1: val?.form?.Sebelum_Sakit?.Naik_Turun_Tangga ?? '',
        tangga_2: val?.form?.Saat_Masuk_RS?.Naik_Turun_Tangga ?? '',
        tangga_3: val?.form?.Minggu_2_RS?.Naik_Turun_Tangga ?? '',
        tangga_4: val?.form?.Minggu_3_RS?.Naik_Turun_Tangga ?? '',
        tangga_5: val?.form?.Minggu_4_RS?.Naik_Turun_Tangga ?? '',
        tangga_6: val?.form?.Saat_Pulang?.Naik_Turun_Tangga ?? '',
        total_1: val?.form?.Sebelum_Sakit_Total ?? '',
        total_2: val?.form?.Saat_Masuk_Total ?? '',
        total_3: val?.form?.Minggu_2_Total ?? '',
        total_4: val?.form?.Minggu_3_Total ?? '',
        total_5: val?.form?.Minggu_4_Total ?? '',
        total_6: val?.form?.Saat_Pulang_Total ?? '',
        date: DateTimeConverter.convertToNormalDate(val?.form?.Tanggal_Masuk_Rawat_Inap && val?.form?.Tanggal_Masuk_Rawat_Inap !== '' ? val?.form?.Tanggal_Masuk_Rawat_Inap.substring(0, 10) : ''),
        'form.Nama_Perawat_pengkaji': val?.form?.Nama_Perawat_Pengkajian_Masuk ?? '',

        riwayat_1: this.getCheckImage(val?.form?.Riwayat_Alergi_Tidak_Check === '1'),
        riwayat_2: this.getCheckImage(val?.form?.Riwayat_Alergi_Obat_Check === '1'),
        riwayat_3: this.getCheckImage(val?.form?.Riwayat_Alergi_Makanan_Check === '1'),
        riwayat_4: this.getCheckImage(val?.form?.Riwayat_Alergi_Lainnya_Check === '1'),
        riwayat_5: this.getCheckImage(val?.form?.Riwayat_Alergi_Klip_Tanda_Check === '1'),
        riwayat_6: this.getCheckImage(val?.form?.Riwayat_Alergi_Tidak_Diketahui_Check === '1'),
        sosial_baik: this.getCheckImage(val?.form?.Hubungan_Pasien_Keluarga === '0'),
        sosial_tidak: this.getCheckImage(val?.form?.Hubungan_Pasien_Keluarga === '1'),
        pernah_dirawat_1: this.getCheckImage(val?.form?.Pernah_Dirawat === '0'),
        pernah_dirawat_2: this.getCheckImage(val?.form?.Pernah_Dirawat === '1'),
        alat_implant_1: this.getCheckImage(val?.form?.Implant_Terpasang === '0'),
        alat_implant_2: this.getCheckImage(val?.form?.Implant_Terpasang === '1'),
        status_psikologis_1: this.getCheckImage(val?.form?.Status_Psikologis === '0'),
        status_psikologis_2: this.getCheckImage(val?.form?.Status_Psikologis === '1'),
        status_psikologis_3: this.getCheckImage(val?.form?.Status_Psikologis === '2'),
        status_psikologis_4: this.getCheckImage(val?.form?.Status_Psikologis === '3'),
        status_psikologis_5: this.getCheckImage(val?.form?.Status_Psikologis === '4'),
        status_psikologis_6: this.getCheckImage(val?.form?.Status_Psikologis === '5'),
        status_mental_1: this.getCheckImage(val?.form?.Status_Mental === '0'),
        status_mental_2: this.getCheckImage(val?.form?.Status_Mental === '1'),
        status_mental_3: this.getCheckImage(val?.form?.Status_Mental === '2'),
        dx_khusus_1: this.getCheckImage(val?.form?.Penyakit?.Dm === 1),
        dx_khusus_2: this.getCheckImage(val?.form?.Penyakit?.Ginjal === 1),
        dx_khusus_3: this.getCheckImage(val?.form?.Penyakit?.Hati === 1),
        dx_khusus_4: this.getCheckImage(val?.form?.Penyakit?.Jantung === 1),
        dx_khusus_5: this.getCheckImage(val?.form?.Penyakit?.Paru === 1),
        dx_khusus_6: this.getCheckImage(val?.form?.Penyakit?.Stroke === 1),
        dx_khusus_7: this.getCheckImage(val?.form?.Penyakit?.Kanker === 1),
        dx_khusus_8: this.getCheckImage(val?.form?.Penyakit?.Geriatri === 1),
        dx_khusus_9: this.getCheckImage(val?.form?.Penyakit?.Lain === 1),
        nutrisionis_ya: this.getCheckImage(val?.form?.Nutrisionis === '1'),
        nutrisionis_tidak: this.getCheckImage(val?.form?.Nutrisionis === '0'),
        risiko_jatuh_tidak: this.getCheckImage(val?.form?.Risiko_Jatuh === '0'),
        risiko_jatuh_ya_1: this.getCheckImage(val?.form?.Risiko_Jatuh === '1'),
        risiko_jatuh_ya_2: this.getCheckImage(val?.form?.Risiko_Jatuh === '1'),
        aktivitas_1: this.getCheckImage(val?.form?.Status_Fungsional === '0'),
        aktivitas_2: this.getCheckImage(val?.form?.Status_Fungsional === '1'),
        skrining_nyeri_tidak: this.getCheckImage(val?.form?.Skrining_Nyeri === '0'),
        skrining_nyeri_ya: this.getCheckImage(val?.form?.Skrining_Nyeri === '1'),
        nyeri_hilang_1: this.getCheckImage(val?.form?.Nyeri_Hilang?.Minum_Obat === 1),
        nyeri_hilang_2: this.getCheckImage(val?.form?.Nyeri_Hilang?.Istirahat === 1),
        nyeri_hilang_3: this.getCheckImage(val?.form?.Nyeri_Hilang?.Mendengar_Musik === 1),
        nyeri_hilang_4: this.getCheckImage(val?.form?.Nyeri_Hilang?.Posisi_Tidur === 1),
        nyeri_hilang_5: this.getCheckImage(val?.form?.Nyeri_Hilang?.Lainnya === 1),
        hambatan_pembelajaran_tidak: this.getCheckImage(val?.form?.Hambatan === '0'),
        hambatan_pembelajaran_ya: this.getCheckImage(val?.form?.Hambatan === '1'),
        hambatan_pembelajaran_ya_1: this.getCheckImage(val?.form?.Jenis_Hambatan?.Pendengaran === 1),
        hambatan_pembelajaran_ya_2: this.getCheckImage(val?.form?.Jenis_Hambatan?.Penglihatan === 1),
        hambatan_pembelajaran_ya_3: this.getCheckImage(val?.form?.Jenis_Hambatan?.Kognitif === 1),
        hambatan_pembelajaran_ya_4: this.getCheckImage(val?.form?.Jenis_Hambatan?.Fisik === 1),
        hambatan_pembelajaran_ya_5: this.getCheckImage(val?.form?.Jenis_Hambatan?.Budaya === 1),
        hambatan_pembelajaran_ya_6: this.getCheckImage(val?.form?.Jenis_Hambatan?.Agama === 1),
        hambatan_pembelajaran_ya_7: this.getCheckImage(val?.form?.Jenis_Hambatan?.Emosi === 1),
        hambatan_pembelajaran_ya_8: this.getCheckImage(val?.form?.Jenis_Hambatan?.Bahasa === 1),
        hambatan_pembelajaran_ya_9: this.getCheckImage(val?.form?.Jenis_Hambatan?.Lain === 1),
        topic_pembelajaran_1: this.getCheckImage(val?.form?.Topik_Pembelajaran?.Diagnosis_Manajemen_Penyakit === 1),
        topic_pembelajaran_2: this.getCheckImage(val?.form?.Topik_Pembelajaran?.Obat === 1),
        topic_pembelajaran_3: this.getCheckImage(val?.form?.Topik_Pembelajaran?.Diet_Nutrisi === 1),
        topic_pembelajaran_4: this.getCheckImage(val?.form?.Topik_Pembelajaran?.Keperawatan === 1),
        topic_pembelajaran_5: this.getCheckImage(val?.form?.Topik_Pembelajaran?.Rehabilitasi === 1),
        topic_pembelajaran_6: this.getCheckImage(val?.form?.Topik_Pembelajaran?.Manajemen_Nyeri === 1),
        topic_pembelajaran_7: this.getCheckImage(val?.form?.Topik_Pembelajaran?.Lain === 1),
        lokas_MataOD: val.form && val.form.Gambar_Mata_OD && val.form.Gambar_Mata_OD !== '' ? val.form.Gambar_Mata_OD : 'https://bucket.rsmatasmec.com/eye-clean.jpeg',
        lokas_MataOS: val.form && val.form.Gambar_Mata_OS && val.form.Gambar_Mata_OS !== '' ? val.form.Gambar_Mata_OS : 'https://bucket.rsmatasmec.com/eye-clean.jpeg',
        gangguang_pengelihatan: this.getCheckImage(val?.form?.Keperawatan_1_Check === '1'),
        penurunan_kesadaran: this.getCheckImage(val?.form?.Keperawatan_2_Check === '1'),
        nyeri: this.getCheckImage(val?.form?.Keperawatan_3_Check === '1'),
        infeksi: this.getCheckImage(val?.form?.Keperawatan_4_Check === '1'),
        intake: this.getCheckImage(val?.form?.Keperawatan_5_Check === '1'),
        resiko_jatuh: this.getCheckImage(val?.form?.Keperawatan_6_Check === '1'),
        Hiperthermia: this.getCheckImage(val?.form?.Keperawatan_7_Check === '1'),
        tio: this.getCheckImage(val?.form?.Keperawatan_8_Check === '1'),
        lainya: this.getCheckImage(val?.form?.Keperawatan_9_Check === '1'),
        masalah_keperawatan: val?.form?.Masalah_Keperawatan_Lainnya_Text ?? '',
        rencana_keperawatan: val?.form?.Rencana_Keperawatan_Lainnya_Text ?? '',
        Tanda_Tangan_Perawat_Pengkaji: val.form && val.form.TTD_Perawat_Pengkajian_Masuk && val.form.TTD_Perawat_Pengkajian_Masuk !== '' ? val.form.TTD_Perawat_Pengkajian_Masuk : 'https://bucket.rsmatasmec.com/gambar_putih_ttd.jpeg',
        nik: val?.pasien?.NIK ?? '',
      },
    })
  }
}
