import { IDataModel, DataModel } from "@src/shared/model";

export interface IDocumentationOfFallRiskPatientFormModel {
  ID_Pemberi_Informasi: string;
  Nama_Pemberi_Informasi: string;
  Penerima_Informasi: string;
  Nama_Penerima_Informasi: string;
  Faktor_Usia_Check: string;
  Faktor_Riwayat_Jatuh_Check: string;
  Faktor_Penyakit_Check: string;
  Faktor_Penggunaan_Alat_Check: string;
  Faktor_Terpasang_Infus_Check: string;
  Faktor_Kondisi_Mental_Check: string;
  Faktor_Mobilisasi_Check: string;
  Faktor_Mobilisasi_Text: string;
  Faktor_Post_Operasi_Check: string;
  Faktor_Post_Operasi_Text: string;
  Faktor_Respon_Obat_Check : string;
  Respon_Obat_Sedatif: string;
  Respon_Obat_Hipnotik: string;
  Respon_Obat_Antidepresan: string;
  Respon_Obat_Laxatives: string;
  Respon_Obat_Diuretika: string;
  Respon_Obat_Narkotika: string;
  Faktor_Riwayat_Check: string;
  Riwayat_Kejang: string;
  Riwayat_Vertigo: string;
  Riwayat_Depresi: string;
  Riwayat_Pingsan: string;
  Riwayat_Pusing: string;
  Riwayat_Delirium: string;
  Riwayat_Disorientasi: string;
  Faktor_Lain_Check: string;
  Faktor_Lain_Text: string;
  Tingkatan_Check: string;
  Tingkatan_Rendah: string;
  Tingkatan_Sedang: string;
  Tingkatan_Tinggi: string;
  Tindakan_Rem_Tempat_Tidur_Check: string;
  Tindakan_Kebutuhan_Pasien_Check: string;
  Tindakan_Tempatkan_Meja_Check: string;
  Tindakan_Pasang_Palang_Check: string;
  Tindakan_Pasang_Penanda_Check: string;
  Tindakan_Libatkan_Keluarga_Check: string;
  Tindakan_Cepat_Menanggapi_Check: string;
  Tujuan_Pasien_Aman_Check: string;
  Akibat_Timbulnya_Cedera_Check: string;
  Lainnya_Check: string;
  Lainnya_Text: string;
  ID_TTD_Pemberi_Informasi: string;
  TTD_Pemberi_Informasi: string;
  Nama_TTD_Pemberi_Informasi: string;
  ID_TTD_Penerima_Informasi: string;
  TTD_Penerima_Informasi: string;
  Nama_TTD_Penerima_Informasi: string;
  ID_Petugas: string;
  Nama_Petugas: string;
  Updated_At: string;
  Updated_By: string;
  Nama_Wali: string;
}

export class DocumentationOfFallRiskPatientFormModel {
  ID_Pemberi_Informasi: string;
  Nama_Pemberi_Informasi: string;
  Penerima_Informasi: string;
  Nama_Penerima_Informasi: string;
  Faktor_Usia_Check: string;
  Faktor_Riwayat_Jatuh_Check: string;
  Faktor_Penyakit_Check: string;
  Faktor_Penggunaan_Alat_Check: string;
  Faktor_Terpasang_Infus_Check: string;
  Faktor_Kondisi_Mental_Check: string;
  Faktor_Mobilisasi_Check: string;
  Faktor_Mobilisasi_Text: string;
  Faktor_Post_Operasi_Check: string;
  Faktor_Post_Operasi_Text: string;
  Faktor_Respon_Obat_Check : string;
  Respon_Obat_Sedatif: string;
  Respon_Obat_Hipnotik: string;
  Respon_Obat_Antidepresan: string;
  Respon_Obat_Laxatives: string;
  Respon_Obat_Diuretika: string;
  Respon_Obat_Narkotika: string;
  Faktor_Riwayat_Check: string;
  Riwayat_Kejang: string;
  Riwayat_Vertigo: string;
  Riwayat_Depresi: string;
  Riwayat_Pingsan: string;
  Riwayat_Pusing: string;
  Riwayat_Delirium: string;
  Riwayat_Disorientasi: string;
  Faktor_Lain_Check: string;
  Faktor_Lain_Text: string;
  Tingkatan_Check: string;
  Tingkatan_Rendah: string;
  Tingkatan_Sedang: string;
  Tingkatan_Tinggi: string;
  Tindakan_Rem_Tempat_Tidur_Check: string;
  Tindakan_Kebutuhan_Pasien_Check: string;
  Tindakan_Tempatkan_Meja_Check: string;
  Tindakan_Pasang_Palang_Check: string;
  Tindakan_Pasang_Penanda_Check: string;
  Tindakan_Libatkan_Keluarga_Check: string;
  Tindakan_Cepat_Menanggapi_Check: string;
  Tujuan_Pasien_Aman_Check: string;
  Akibat_Timbulnya_Cedera_Check: string;
  Lainnya_Check: string;
  Lainnya_Text: string;
  ID_TTD_Pemberi_Informasi: string;
  TTD_Pemberi_Informasi: string;
  Nama_TTD_Pemberi_Informasi: string;
  ID_TTD_Penerima_Informasi: string;
  TTD_Penerima_Informasi: string;
  Nama_TTD_Penerima_Informasi: string;
  ID_Petugas: string;
  Nama_Petugas: string;
  Updated_At: string;
  Updated_By: string;
  Nama_Wali: string;
  constructor(req: IDocumentationOfFallRiskPatientFormModel) {
    this.ID_Pemberi_Informasi = req.ID_Pemberi_Informasi;
    this.Nama_Pemberi_Informasi = req.Nama_Pemberi_Informasi;
    this.Penerima_Informasi = req.Penerima_Informasi;
    this.Nama_Penerima_Informasi = req.Nama_Penerima_Informasi;
    this.Faktor_Usia_Check = req.Faktor_Usia_Check;
    this.Faktor_Riwayat_Jatuh_Check = req.Faktor_Riwayat_Jatuh_Check;
    this.Faktor_Penyakit_Check = req.Faktor_Penyakit_Check;
    this.Faktor_Penggunaan_Alat_Check = req.Faktor_Penggunaan_Alat_Check;
    this.Faktor_Terpasang_Infus_Check = req.Faktor_Terpasang_Infus_Check;
    this.Faktor_Kondisi_Mental_Check = req.Faktor_Kondisi_Mental_Check;
    this.Faktor_Mobilisasi_Check = req.Faktor_Mobilisasi_Check;
    this.Faktor_Mobilisasi_Text = req.Faktor_Mobilisasi_Text;
    this.Faktor_Post_Operasi_Check = req.Faktor_Post_Operasi_Check;
    this.Faktor_Post_Operasi_Text = req.Faktor_Post_Operasi_Text;
    this.Faktor_Respon_Obat_Check = req.Faktor_Respon_Obat_Check;
    this.Respon_Obat_Sedatif = req.Respon_Obat_Sedatif;
    this.Respon_Obat_Hipnotik = req.Respon_Obat_Hipnotik;
    this.Respon_Obat_Antidepresan = req.Respon_Obat_Antidepresan;
    this.Respon_Obat_Laxatives = req.Respon_Obat_Laxatives;
    this.Respon_Obat_Diuretika = req.Respon_Obat_Diuretika;
    this.Respon_Obat_Narkotika = req.Respon_Obat_Narkotika;
    this.Faktor_Riwayat_Check = req.Faktor_Riwayat_Check;
    this.Riwayat_Kejang = req.Riwayat_Kejang;
    this.Riwayat_Vertigo = req.Riwayat_Vertigo;
    this.Riwayat_Depresi = req.Riwayat_Depresi;
    this.Riwayat_Pingsan = req.Riwayat_Pingsan;
    this.Riwayat_Pusing = req.Riwayat_Pusing;
    this.Riwayat_Delirium = req.Riwayat_Delirium;
    this.Riwayat_Disorientasi = req.Riwayat_Disorientasi;
    this.Faktor_Lain_Check = req.Faktor_Lain_Check;
    this.Faktor_Lain_Text = req.Faktor_Lain_Text;
    this.Tingkatan_Check = req.Tingkatan_Check;
    this.Tingkatan_Rendah = req.Tingkatan_Rendah;
    this.Tingkatan_Sedang = req.Tingkatan_Sedang;
    this.Tingkatan_Tinggi = req.Tingkatan_Tinggi;
    this.Tindakan_Rem_Tempat_Tidur_Check = req.Tindakan_Rem_Tempat_Tidur_Check;
    this.Tindakan_Kebutuhan_Pasien_Check = req.Tindakan_Kebutuhan_Pasien_Check;
    this.Tindakan_Tempatkan_Meja_Check = req.Tindakan_Tempatkan_Meja_Check;
    this.Tindakan_Pasang_Palang_Check = req.Tindakan_Pasang_Palang_Check;
    this.Tindakan_Pasang_Penanda_Check = req.Tindakan_Pasang_Penanda_Check;
    this.Tindakan_Libatkan_Keluarga_Check = req.Tindakan_Libatkan_Keluarga_Check;
    this.Tindakan_Cepat_Menanggapi_Check = req.Tindakan_Cepat_Menanggapi_Check;
    this.Tujuan_Pasien_Aman_Check = req.Tujuan_Pasien_Aman_Check;
    this.Akibat_Timbulnya_Cedera_Check = req.Akibat_Timbulnya_Cedera_Check;
    this.Lainnya_Check = req.Lainnya_Check;
    this.Lainnya_Text = req.Lainnya_Text;
    this.ID_TTD_Pemberi_Informasi = req.ID_TTD_Pemberi_Informasi;
    this.TTD_Pemberi_Informasi = req.TTD_Pemberi_Informasi;
    this.Nama_TTD_Pemberi_Informasi = req.Nama_TTD_Pemberi_Informasi;
    this.ID_TTD_Penerima_Informasi = req.ID_TTD_Penerima_Informasi;
    this.TTD_Penerima_Informasi = req.TTD_Penerima_Informasi;
    this.Nama_TTD_Penerima_Informasi = req.Nama_TTD_Penerima_Informasi;
    this.ID_Petugas = req.ID_Petugas;
    this.Nama_Petugas = req.Nama_Petugas;
    this.Updated_At = req.Updated_At;
    this.Updated_By = req.Updated_By;
    this.Nama_Wali = req.Nama_Wali;
  }
}

export interface IDocumentationOfFallRiskPatientModel extends IDataModel {
  form: IDocumentationOfFallRiskPatientFormModel;
}

export class DocumentationOfFallRiskPatientModel extends DataModel {
  form: IDocumentationOfFallRiskPatientFormModel;
  constructor(request: IDocumentationOfFallRiskPatientModel) {
    super(request);
    this.form = request.form;
  }
}
