import { DataModel, IDataModel } from '@shared/model';
import { IAssessmentUgdFormModel } from '@src/modules/emergency-room/assessment/models/assessment-ugd-models';
import { INursingEarlyWarning } from '../../nursing-early-warning-scoring-table/models/nursing-early-warning-scoring.model';

export interface IPreAnesthesiaForm {
  Merokok_Radio: string;
  Kopi_Radio: string;
  Alkohol_Radio: string;
  Olahraga_Radio: string;
  Aspirin_Radio: string;
  Anti_Sakit_Radio: string;
  Keluarga_Pendarahan_Radio: string;
  Keluarga_Pembekuan_Darah_Radio: string;
  Keluarga_Pembiusan_Radio: string;
  Keluarga_Demam_Radio: string;
  Keluarga_Diabetes_Radio: string;
  Keluarga_Jantung_Radio: string;
  Keluarga_Irama_Jantung_Radio: string;
  Keluarga_Hipertensi_Radio: string;
  Keluarga_Tuberkulosis_Radio: string;
  Keluarga_Lainnya_Radio: string;
  Pasien_Pendarahan_Radio: string;
  Pasien_Pembekuan_Darah_Radio: string;
  Pasien_Maag_Radio: string;
  Pasien_Anemia_Radio: string;
  Pasien_Jantung_Radio: string;
  Pasien_Asthma_Radio: string;
  Pasien_Diabetes_Radio: string;
  Pasien_Pingsan_Radio: string;
  Pasien_Mengorok_Radio: string;
  Pasien_Hepatitis_Radio: string;
  Pasien_Hipertensi_Radio: string;
  Pasien_Lainnya_Radio: string;
  Pasien_Kejang_Radio: string;
  Pasien_Bawaan_Radio: string;
  Pasien_Transfusi: string;
  Pasien_Diagnosis_HIV: string;
  Sistem_Gigi_Radio: string;
  Sistem_Mobilisasi_Leher_Radio: string;
  Sistem_Leher_Pendek_Radio: string;
  Sistem_Batuk_Radio: string;
  Sistem_Sesak_Napas_Radio: string;
  Sistem_ISPA_Radio: string;
  Sistem_Dada_Radio: string;
  Sistem_Denyut_Jantung_Radio: string;
  Sistem_Muntah_Radio: string;
  Sistem_Pingsan_Radio: string;
  Sistem_Stroke_Radio: string;
  Sistem_Kejang_Radio: string;
  Sistem_Hamil_Radio: string;
  Sistem_Tulang_Belakang_Radio: string;
  Sistem_Obesitas_Radio: string;
  Penyulit_Lain_Radio: string;
  Merokok_Teks: string;
  Kopi_Teks: string;
  Alkohol_Teks: string;
  Olahraga_Teks: string;
  Anti_Sakit_Teks: string;
  Aspirin_Teks: string;
  Obat_Resep: string;
  Obat_Bebas: string;
  Alergi_Obat: string;
  Alergi_Makanan: string;
  Keluarga_Teks: string;
  Pasien_Teks: string;
  Pasien_Transfusi_Teks: string;
  Pasien_Diagnosis_HIV_Teks: string;
  Pasien_Pakai_Lainnya_Teks: string;
  Riwayat_Operasi: string;
  Anestesi_Lokal: string;
  Anestesi_Regional: string;
  Anestesi_Umum: string;
  Sistem_Teks: string;
  Berat_Badan: string;
  Tinggi_Badan: string;
  Tekanan_Darah: string;
  Nadi: string;
  Suhu: string;
  Kajian_Teks_Mallampati: string;
  Kajian_Teks_Gigi_Palsu: string;
  Kajian_Teks_Jantung: string;
  Kajian_Teks_Paru: string;
  Kajian_Teks_Abdomen: string;
  Kajian_Teks_Tulang_Belakang: string;
  Kajian_Teks_Ekstremitas: string;
  Kajian_Teks_Neurologi: string;
  Kajian_Teks_Keterangan: string;
  Laboratorium_Hb_Ht: string;
  Laboratorium_Pt: string;
  Laboratorium_Glukosa: string;
  Laboratorium_Kehamilan: string;
  Laboratorium_Kalium: string;
  Laboratorium_Ureum: string;
  Laboratorium_Leukosit: string;
  Laboratorium_Trombosit: string;
  Laboratorium_Rontgen: string;
  Laboratorium_EKG: string;
  Laboratorium_Na_Cl: string;
  Laboratorium_Kreatinin: string;
  Laboratorium_Teks: string;
  Diagnosis_ICD_X: string;
  Penyulit_Lain_Teks: string;
  Catatan_Tindak_Lanjut: string;
  Perencanaan_Anestesi_Sedasi_Teks: string;
  Perencanaan_Anestesi_GA_Teks: string;
  Perencanaan_Anestesi_Lainnya_Teks: string;
  Perencanaan_Khusus_Lainnya_Teks: string;
  Perencanaan_Monitoring_EKG_Lead_Teks: string;
  Perencanaan_Monitoring_CVP_Teks: string;
  Perencanaan_Monitoring_Arteri_Line_Teks: string;
  Perencanaan_Monitoring_Lainnya_Teks: string;
  Perencanaan_Alat_Khusus_Lainnya_Teks: string;
  Perencanaan_Perawatan_Lainnya_Teks: string;
  Perencanaan_Persiapan_Puasa_Waktu: string;
  Perencanaan_Persiapan_Pre_Medikasi_Waktu: string;
  Perencanaan_Persiapan_Transportasi_Kamar_Bedah_Waktu: string;
  Perencanaan_Persiapan_Rencana_Operasi_Waktu: string;
  Pasien_Diagnosis_HIV_Hasil: string;
  Pasien_Lensa_Kontak: string;
  Pasien_Kacamata: string;
  Pasien_Alat_Bantu_Dengar: string;
  Pasien_Gigi_Palsu: string;
  Pasien_Pakai_Lainnya: string;
  ASA_1: string;
  ASA_2: string;
  ASA_3: string;
  ASA_4: string;
  Perencanaan_Anestesi_Sedasi: string;
  Perencanaan_Anestesi_GA: string;
  Perencanaan_Anestesi_Lainnya: string;
  Perencanaan_Khusus_Tidak_Ada: string;
  Perencanaan_Khusus_Hipotensi: string;
  Perencanaan_Khusus_Ventilasi: string;
  Perencanaan_Khusus_TCI: string;
  Perencanaan_Khusus_Lainnya: string;
  Perencanaan_Monitoring_EKG_Lead: string;
  Perencanaan_Monitoring_CVP: string;
  Perencanaan_Monitoring_Arteri_Line: string;
  Perencanaan_Monitoring_SPO2: string;
  Perencanaan_Monitoring_ET_CO2: string;
  Perencanaan_Monitoring_NIBP: string;
  Perencanaan_Monitoring_BIS: string;
  Perencanaan_Monitoring_Temp: string;
  Perencanaan_Monitoring_Lainnya: string;
  Perencanaan_Alat_Khusus_Bronchoscopy: string;
  Perencanaan_Alat_Khusus_Glidescope: string;
  Perencanaan_Alat_Khusus_USG: string;
  Perencanaan_Alat_Khusus_Lainnya: string;
  Perencanaan_Perawatan_Rawat_Inap: string;
  Perencanaan_Perawatan_Rawat_Jalan: string;
  Perencanaan_Perawatan_Lainnya: string;
  Perencanaan_Persiapan_Puasa: string;
  Perencanaan_Persiapan_Pre_Medikasi: string;
  Perencanaan_Persiapan_Transportasi_Kamar_Bedah: string;
  Perencanaan_Persiapan_Rencana_Operasi: string;
  Waktu: string;
  ID_Petugas: string;
  Nama_Petugas: string;
  Updated_At: string;
  Updated_By: string;
  Tanda_Tangan_Pasien: string;
  Tanda_Tangan_Dokter: string;
  ID_TTD_Dokter: string;
  Catatan_Persiapan_Text: string;
  Nama_TTD_Dokter: string;
}

export class PreAnesthesiaForm {
  Merokok_Radio: string;
  Kopi_Radio: string;
  Alkohol_Radio: string;
  Olahraga_Radio: string;
  Aspirin_Radio: string;
  Anti_Sakit_Radio: string;
  Keluarga_Pendarahan_Radio: string;
  Keluarga_Pembekuan_Darah_Radio: string;
  Keluarga_Pembiusan_Radio: string;
  Keluarga_Demam_Radio: string;
  Keluarga_Diabetes_Radio: string;
  Keluarga_Jantung_Radio: string;
  Keluarga_Irama_Jantung_Radio: string;
  Keluarga_Hipertensi_Radio: string;
  Keluarga_Tuberkulosis_Radio: string;
  Keluarga_Lainnya_Radio: string;
  Pasien_Pendarahan_Radio: string;
  Pasien_Pembekuan_Darah_Radio: string;
  Pasien_Maag_Radio: string;
  Pasien_Anemia_Radio: string;
  Pasien_Jantung_Radio: string;
  Pasien_Asthma_Radio: string;
  Pasien_Diabetes_Radio: string;
  Pasien_Pingsan_Radio: string;
  Pasien_Mengorok_Radio: string;
  Pasien_Hepatitis_Radio: string;
  Pasien_Hipertensi_Radio: string;
  Pasien_Lainnya_Radio: string;
  Pasien_Kejang_Radio: string;
  Pasien_Bawaan_Radio: string;
  Pasien_Transfusi: string;
  Pasien_Diagnosis_HIV: string;
  Sistem_Gigi_Radio: string;
  Sistem_Mobilisasi_Leher_Radio: string;
  Sistem_Leher_Pendek_Radio: string;
  Sistem_Batuk_Radio: string;
  Sistem_Sesak_Napas_Radio: string;
  Sistem_ISPA_Radio: string;
  Sistem_Dada_Radio: string;
  Sistem_Denyut_Jantung_Radio: string;
  Sistem_Muntah_Radio: string;
  Sistem_Pingsan_Radio: string;
  Sistem_Stroke_Radio: string;
  Sistem_Kejang_Radio: string;
  Sistem_Hamil_Radio: string;
  Sistem_Tulang_Belakang_Radio: string;
  Sistem_Obesitas_Radio: string;
  Penyulit_Lain_Radio: string;
  Merokok_Teks: string;
  Kopi_Teks: string;
  Alkohol_Teks: string;
  Olahraga_Teks: string;
  Anti_Sakit_Teks: string;
  Aspirin_Teks: string;
  Obat_Resep: string;
  Obat_Bebas: string;
  Alergi_Obat: string;
  Alergi_Makanan: string;
  Keluarga_Teks: string;
  Pasien_Teks: string;
  Pasien_Transfusi_Teks: string;
  Pasien_Diagnosis_HIV_Teks: string;
  Pasien_Pakai_Lainnya_Teks: string;
  Riwayat_Operasi: string;
  Anestesi_Lokal: string;
  Anestesi_Regional: string;
  Anestesi_Umum: string;
  Sistem_Teks: string;
  Berat_Badan: string;
  Tinggi_Badan: string;
  Tekanan_Darah: string;
  Nadi: string;
  Suhu: string;
  Kajian_Teks_Mallampati: string;
  Kajian_Teks_Gigi_Palsu: string;
  Kajian_Teks_Jantung: string;
  Kajian_Teks_Paru: string;
  Kajian_Teks_Abdomen: string;
  Kajian_Teks_Tulang_Belakang: string;
  Kajian_Teks_Ekstremitas: string;
  Kajian_Teks_Neurologi: string;
  Kajian_Teks_Keterangan: string;
  Laboratorium_Hb_Ht: string;
  Laboratorium_Pt: string;
  Laboratorium_Glukosa: string;
  Laboratorium_Kehamilan: string;
  Laboratorium_Kalium: string;
  Laboratorium_Ureum: string;
  Laboratorium_Leukosit: string;
  Laboratorium_Trombosit: string;
  Laboratorium_Rontgen: string;
  Laboratorium_EKG: string;
  Laboratorium_Na_Cl: string;
  Laboratorium_Kreatinin: string;
  Laboratorium_Teks: string;
  Diagnosis_ICD_X: string;
  Penyulit_Lain_Teks: string;
  Catatan_Tindak_Lanjut: string;
  Perencanaan_Anestesi_Sedasi_Teks: string;
  Perencanaan_Anestesi_GA_Teks: string;
  Perencanaan_Anestesi_Lainnya_Teks: string;
  Perencanaan_Khusus_Lainnya_Teks: string;
  Perencanaan_Monitoring_EKG_Lead_Teks: string;
  Perencanaan_Monitoring_CVP_Teks: string;
  Perencanaan_Monitoring_Arteri_Line_Teks: string;
  Perencanaan_Monitoring_Lainnya_Teks: string;
  Perencanaan_Alat_Khusus_Lainnya_Teks: string;
  Perencanaan_Perawatan_Lainnya_Teks: string;
  Perencanaan_Persiapan_Puasa_Waktu: string;
  Perencanaan_Persiapan_Pre_Medikasi_Waktu: string;
  Perencanaan_Persiapan_Transportasi_Kamar_Bedah_Waktu: string;
  Perencanaan_Persiapan_Rencana_Operasi_Waktu: string;
  Pasien_Diagnosis_HIV_Hasil: string;
  Pasien_Lensa_Kontak: string;
  Pasien_Kacamata: string;
  Pasien_Alat_Bantu_Dengar: string;
  Pasien_Gigi_Palsu: string;
  Pasien_Pakai_Lainnya: string;
  ASA_1: string;
  ASA_2: string;
  ASA_3: string;
  ASA_4: string;
  Perencanaan_Anestesi_Sedasi: string;
  Perencanaan_Anestesi_GA: string;
  Perencanaan_Anestesi_Lainnya: string;
  Perencanaan_Khusus_Tidak_Ada: string;
  Perencanaan_Khusus_Hipotensi: string;
  Perencanaan_Khusus_Ventilasi: string;
  Perencanaan_Khusus_TCI: string;
  Perencanaan_Khusus_Lainnya: string;
  Perencanaan_Monitoring_EKG_Lead: string;
  Perencanaan_Monitoring_CVP: string;
  Perencanaan_Monitoring_Arteri_Line: string;
  Perencanaan_Monitoring_SPO2: string;
  Perencanaan_Monitoring_ET_CO2: string;
  Perencanaan_Monitoring_NIBP: string;
  Perencanaan_Monitoring_BIS: string;
  Perencanaan_Monitoring_Temp: string;
  Perencanaan_Monitoring_Lainnya: string;
  Perencanaan_Alat_Khusus_Bronchoscopy: string;
  Perencanaan_Alat_Khusus_Glidescope: string;
  Perencanaan_Alat_Khusus_USG: string;
  Perencanaan_Alat_Khusus_Lainnya: string;
  Perencanaan_Perawatan_Rawat_Inap: string;
  Perencanaan_Perawatan_Rawat_Jalan: string;
  Perencanaan_Perawatan_Lainnya: string;
  Perencanaan_Persiapan_Puasa: string;
  Perencanaan_Persiapan_Pre_Medikasi: string;
  Perencanaan_Persiapan_Transportasi_Kamar_Bedah: string;
  Perencanaan_Persiapan_Rencana_Operasi: string;
  Waktu: string;
  ID_Petugas: string;
  Nama_Petugas: string;
  Updated_At: string;
  Updated_By: string;
  Tanda_Tangan_Pasien: string;
  Tanda_Tangan_Dokter: string;
  ID_TTD_Dokter:  string;
  Catatan_Persiapan_Text: string;
  Nama_TTD_Dokter: string;
  constructor(form: IPreAnesthesiaForm) {
    this.Merokok_Radio = form.Merokok_Radio;
    this.Kopi_Radio = form.Kopi_Radio;
    this.Alkohol_Radio = form.Alkohol_Radio;
    this.Olahraga_Radio = form.Olahraga_Radio;
    this.Aspirin_Radio = form.Aspirin_Radio;
    this.Anti_Sakit_Radio = form.Anti_Sakit_Radio;
    this.Keluarga_Pendarahan_Radio = form.Keluarga_Pendarahan_Radio;
    this.Keluarga_Pembekuan_Darah_Radio = form.Keluarga_Pembekuan_Darah_Radio;
    this.Keluarga_Pembiusan_Radio = form.Keluarga_Pembiusan_Radio;
    this.Keluarga_Demam_Radio = form.Keluarga_Demam_Radio;
    this.Keluarga_Diabetes_Radio = form.Keluarga_Diabetes_Radio;
    this.Keluarga_Jantung_Radio = form.Keluarga_Jantung_Radio;
    this.Keluarga_Irama_Jantung_Radio = form.Keluarga_Irama_Jantung_Radio;
    this.Keluarga_Hipertensi_Radio = form.Keluarga_Hipertensi_Radio;
    this.Keluarga_Tuberkulosis_Radio = form.Keluarga_Tuberkulosis_Radio;
    this.Keluarga_Lainnya_Radio = form.Keluarga_Lainnya_Radio;
    this.Pasien_Pendarahan_Radio = form.Pasien_Pendarahan_Radio;
    this.Pasien_Pembekuan_Darah_Radio = form.Pasien_Pembekuan_Darah_Radio;
    this.Pasien_Maag_Radio = form.Pasien_Maag_Radio;
    this.Pasien_Anemia_Radio = form.Pasien_Anemia_Radio;
    this.Pasien_Jantung_Radio = form.Pasien_Jantung_Radio;
    this.Pasien_Asthma_Radio = form.Pasien_Asthma_Radio;
    this.Pasien_Diabetes_Radio = form.Pasien_Diabetes_Radio;
    this.Pasien_Pingsan_Radio = form.Pasien_Pingsan_Radio;
    this.Pasien_Mengorok_Radio = form.Pasien_Mengorok_Radio;
    this.Pasien_Hepatitis_Radio = form.Pasien_Hepatitis_Radio;
    this.Pasien_Hipertensi_Radio = form.Pasien_Hipertensi_Radio;
    this.Pasien_Lainnya_Radio = form.Pasien_Lainnya_Radio;
    this.Pasien_Kejang_Radio = form.Pasien_Kejang_Radio;
    this.Pasien_Bawaan_Radio = form.Pasien_Bawaan_Radio;
    this.Pasien_Transfusi = form.Pasien_Transfusi;
    this.Pasien_Diagnosis_HIV = form.Pasien_Diagnosis_HIV;
    this.Sistem_Gigi_Radio = form.Sistem_Gigi_Radio;
    this.Sistem_Mobilisasi_Leher_Radio = form.Sistem_Mobilisasi_Leher_Radio;
    this.Sistem_Leher_Pendek_Radio = form.Sistem_Leher_Pendek_Radio;
    this.Sistem_Batuk_Radio = form.Sistem_Batuk_Radio;
    this.Sistem_Sesak_Napas_Radio = form.Sistem_Sesak_Napas_Radio;
    this.Sistem_ISPA_Radio = form.Sistem_ISPA_Radio;
    this.Sistem_Dada_Radio = form.Sistem_Dada_Radio;
    this.Sistem_Denyut_Jantung_Radio = form.Sistem_Denyut_Jantung_Radio;
    this.Sistem_Muntah_Radio = form.Sistem_Muntah_Radio;
    this.Sistem_Pingsan_Radio = form.Sistem_Pingsan_Radio;
    this.Sistem_Stroke_Radio = form.Sistem_Stroke_Radio;
    this.Sistem_Kejang_Radio = form.Sistem_Kejang_Radio;
    this.Sistem_Hamil_Radio = form.Sistem_Hamil_Radio;
    this.Sistem_Tulang_Belakang_Radio = form.Sistem_Tulang_Belakang_Radio;
    this.Sistem_Obesitas_Radio = form.Sistem_Obesitas_Radio;
    this.Penyulit_Lain_Radio = form.Penyulit_Lain_Radio;
    this.Merokok_Teks = form.Merokok_Teks;
    this.Kopi_Teks = form.Kopi_Teks;
    this.Alkohol_Teks = form.Alkohol_Teks;
    this.Olahraga_Teks = form.Olahraga_Teks;
    this.Anti_Sakit_Teks = form.Anti_Sakit_Teks;
    this.Aspirin_Teks = form.Aspirin_Teks;
    this.Obat_Resep = form.Obat_Resep;
    this.Obat_Bebas = form.Obat_Bebas;
    this.Alergi_Obat = form.Alergi_Obat;
    this.Alergi_Makanan = form.Alergi_Makanan;
    this.Keluarga_Teks = form.Keluarga_Teks;
    this.Pasien_Teks = form.Pasien_Teks;
    this.Pasien_Transfusi_Teks = form.Pasien_Transfusi_Teks;
    this.Pasien_Diagnosis_HIV_Teks = form.Pasien_Diagnosis_HIV_Teks;
    this.Pasien_Pakai_Lainnya_Teks = form.Pasien_Pakai_Lainnya_Teks;
    this.Riwayat_Operasi = form.Riwayat_Operasi;
    this.Anestesi_Lokal = form.Anestesi_Lokal;
    this.Anestesi_Regional = form.Anestesi_Regional;
    this.Anestesi_Umum = form.Anestesi_Umum;
    this.Sistem_Teks = form.Sistem_Teks;
    this.Berat_Badan = form.Berat_Badan;
    this.Tinggi_Badan = form.Tinggi_Badan;
    this.Tekanan_Darah = form.Tekanan_Darah;
    this.Nadi = form.Nadi;
    this.Suhu = form.Suhu;
    this.Kajian_Teks_Mallampati = form.Kajian_Teks_Mallampati;
    this.Kajian_Teks_Gigi_Palsu = form.Kajian_Teks_Gigi_Palsu;
    this.Kajian_Teks_Jantung = form.Kajian_Teks_Jantung;
    this.Kajian_Teks_Paru = form.Kajian_Teks_Paru;
    this.Kajian_Teks_Abdomen = form.Kajian_Teks_Abdomen;
    this.Kajian_Teks_Tulang_Belakang = form.Kajian_Teks_Tulang_Belakang;
    this.Kajian_Teks_Ekstremitas = form.Kajian_Teks_Ekstremitas;
    this.Kajian_Teks_Neurologi = form.Kajian_Teks_Neurologi;
    this.Kajian_Teks_Keterangan = form.Kajian_Teks_Keterangan;
    this.Laboratorium_Hb_Ht = form.Laboratorium_Hb_Ht;
    this.Laboratorium_Pt = form.Laboratorium_Pt;
    this.Laboratorium_Glukosa = form.Laboratorium_Glukosa;
    this.Laboratorium_Kehamilan = form.Laboratorium_Kehamilan;
    this.Laboratorium_Kalium = form.Laboratorium_Kalium;
    this.Laboratorium_Ureum = form.Laboratorium_Ureum;
    this.Laboratorium_Leukosit = form.Laboratorium_Leukosit;
    this.Laboratorium_Trombosit = form.Laboratorium_Trombosit;
    this.Laboratorium_Rontgen = form.Laboratorium_Rontgen;
    this.Laboratorium_EKG = form.Laboratorium_EKG;
    this.Laboratorium_Na_Cl = form.Laboratorium_Na_Cl;
    this.Laboratorium_Kreatinin = form.Laboratorium_Kreatinin;
    this.Laboratorium_Teks = form.Laboratorium_Teks;
    this.Diagnosis_ICD_X = form.Diagnosis_ICD_X;
    this.Penyulit_Lain_Teks = form.Penyulit_Lain_Teks;
    this.Catatan_Tindak_Lanjut = form.Catatan_Tindak_Lanjut;
    this.Perencanaan_Anestesi_Sedasi_Teks = form.Perencanaan_Anestesi_Sedasi_Teks;
    this.Perencanaan_Anestesi_GA_Teks = form.Perencanaan_Anestesi_GA_Teks;
    this.Perencanaan_Anestesi_Lainnya_Teks = form.Perencanaan_Anestesi_Lainnya_Teks;
    this.Perencanaan_Khusus_Lainnya_Teks = form.Perencanaan_Khusus_Lainnya_Teks;
    this.Perencanaan_Monitoring_EKG_Lead_Teks = form.Perencanaan_Monitoring_EKG_Lead_Teks;
    this.Perencanaan_Monitoring_CVP_Teks = form.Perencanaan_Monitoring_CVP_Teks
    this.Perencanaan_Monitoring_Arteri_Line_Teks = form.Perencanaan_Monitoring_Arteri_Line_Teks;
    this.Perencanaan_Monitoring_Lainnya_Teks = form.Perencanaan_Monitoring_Lainnya_Teks;
    this.Perencanaan_Alat_Khusus_Lainnya_Teks = form.Perencanaan_Alat_Khusus_Lainnya_Teks;
    this.Perencanaan_Perawatan_Lainnya_Teks = form.Perencanaan_Perawatan_Lainnya_Teks;
    this.Perencanaan_Persiapan_Puasa_Waktu = form.Perencanaan_Persiapan_Puasa_Waktu;
    this.Perencanaan_Persiapan_Pre_Medikasi_Waktu = form.Perencanaan_Persiapan_Pre_Medikasi_Waktu;
    this.Perencanaan_Persiapan_Transportasi_Kamar_Bedah_Waktu = form.Perencanaan_Persiapan_Transportasi_Kamar_Bedah_Waktu;
    this.Perencanaan_Persiapan_Rencana_Operasi_Waktu = form.Perencanaan_Persiapan_Rencana_Operasi_Waktu;
    this.Pasien_Diagnosis_HIV_Hasil = form.Pasien_Diagnosis_HIV_Hasil;
    this.Pasien_Lensa_Kontak = form.Pasien_Lensa_Kontak;
    this.Pasien_Kacamata = form.Pasien_Kacamata;
    this.Pasien_Alat_Bantu_Dengar = form.Pasien_Alat_Bantu_Dengar;
    this.Pasien_Gigi_Palsu = form.Pasien_Gigi_Palsu;
    this.Pasien_Pakai_Lainnya = form.Pasien_Pakai_Lainnya;
    this.ASA_1 = form.ASA_1;
    this.ASA_2 = form.ASA_2;
    this.ASA_3 = form.ASA_3;
    this.ASA_4 = form.ASA_4;
    this.Perencanaan_Anestesi_Sedasi = form.Perencanaan_Anestesi_Sedasi;
    this.Perencanaan_Anestesi_GA = form.Perencanaan_Anestesi_GA;
    this.Perencanaan_Anestesi_Lainnya = form.Perencanaan_Anestesi_Lainnya;
    this.Perencanaan_Khusus_Tidak_Ada = form.Perencanaan_Khusus_Tidak_Ada;
    this.Perencanaan_Khusus_Hipotensi = form.Perencanaan_Khusus_Hipotensi;
    this.Perencanaan_Khusus_Ventilasi = form.Perencanaan_Khusus_Ventilasi;
    this.Perencanaan_Khusus_TCI = form.Perencanaan_Khusus_TCI;
    this.Perencanaan_Khusus_Lainnya = form.Perencanaan_Khusus_Lainnya;
    this.Perencanaan_Monitoring_EKG_Lead = form.Perencanaan_Monitoring_EKG_Lead;
    this.Perencanaan_Monitoring_CVP = form.Perencanaan_Monitoring_CVP;
    this.Perencanaan_Monitoring_Arteri_Line = form.Perencanaan_Monitoring_Arteri_Line;
    this.Perencanaan_Monitoring_SPO2 = form.Perencanaan_Monitoring_SPO2;
    this.Perencanaan_Monitoring_ET_CO2 = form.Perencanaan_Monitoring_ET_CO2;
    this.Perencanaan_Monitoring_NIBP = form.Perencanaan_Monitoring_NIBP;
    this.Perencanaan_Monitoring_BIS = form.Perencanaan_Monitoring_BIS;
    this.Perencanaan_Monitoring_Temp = form.Perencanaan_Monitoring_Temp;
    this.Perencanaan_Monitoring_Lainnya = form.Perencanaan_Monitoring_Lainnya;
    this.Perencanaan_Alat_Khusus_Bronchoscopy = form.Perencanaan_Alat_Khusus_Bronchoscopy;
    this.Perencanaan_Alat_Khusus_Glidescope = form.Perencanaan_Alat_Khusus_Glidescope;
    this.Perencanaan_Alat_Khusus_USG = form.Perencanaan_Alat_Khusus_USG;
    this.Perencanaan_Alat_Khusus_Lainnya = form.Perencanaan_Alat_Khusus_Lainnya;
    this.Perencanaan_Perawatan_Rawat_Inap = form.Perencanaan_Perawatan_Rawat_Inap;
    this.Perencanaan_Perawatan_Rawat_Jalan = form.Perencanaan_Perawatan_Rawat_Jalan;
    this.Perencanaan_Perawatan_Lainnya = form.Perencanaan_Perawatan_Lainnya;
    this.Perencanaan_Persiapan_Puasa = form.Perencanaan_Persiapan_Puasa;
    this.Perencanaan_Persiapan_Pre_Medikasi = form.Perencanaan_Persiapan_Pre_Medikasi;
    this.Perencanaan_Persiapan_Transportasi_Kamar_Bedah = form.Perencanaan_Persiapan_Transportasi_Kamar_Bedah;
    this.Perencanaan_Persiapan_Rencana_Operasi = form.Perencanaan_Persiapan_Rencana_Operasi;
    this.Waktu = form.Waktu;
    this.ID_Petugas = form.ID_Petugas;
    this.Nama_Petugas = form.Nama_Petugas;
    this.Updated_At = form.Updated_At;
    this.Updated_By = form.Updated_By;
    this.Tanda_Tangan_Pasien = form.Tanda_Tangan_Pasien;
    this.Tanda_Tangan_Dokter = form.Tanda_Tangan_Dokter;
    this.ID_TTD_Dokter = form.ID_TTD_Dokter;
    this.Catatan_Persiapan_Text = form.Catatan_Persiapan_Text;
    this.Nama_TTD_Dokter = form.Nama_TTD_Dokter;
  }
}

export interface IPreAnesthesiaFormModel extends IDataModel {
  form: IPreAnesthesiaForm;
  asesmen: IAssessmentUgdFormModel;
  ews: INursingEarlyWarning;
}

export class PreAnesthesiaFormModel extends DataModel {
  form?: PreAnesthesiaForm;
  asesmen?: IAssessmentUgdFormModel;
  ews?: INursingEarlyWarning;
  constructor(model: IPreAnesthesiaFormModel) {
    super(model);
    if (model.form) {
      this.form = new PreAnesthesiaForm(model.form);
    }
    if (model.asesmen) {
      this.asesmen = model.asesmen;
    }
    if (model.ews) {
      this.ews = model.ews;
    }
  }
}
