import { IPatientIdentityFormModel, IPatientIdentityModel } from "@src/modules/information/patient-identity/models/patient-identity.model";
import { HowToUse, IHowToUse, IMedicine, IPrescription, Medicine } from "@src/modules/outpatient/doctor-preliminary-study/models/doctor-preliminary-study.model";
import { IDoctorModel } from "@src/shared/doctor";
import { DoctorModel } from "@src/shared/doctor/models/doctor.model";
import { DataModel, IDataModel } from "@src/shared/model";

export interface ITriaseSekunder {
  merah: string;
  kuning: string;
  hijau: string;
  hitam: string;
}

export class TriaseSekunder {
  merah: string;
  kuning: string;
  hijau: string;
  hitam: string;

  constructor(req: ITriaseSekunder) {
    this.merah = req.merah;
    this.kuning = req.kuning;
    this.hijau = req.hijau;
    this.hitam = req.hitam;
  }
}

export interface ITriase {
  data: Array<ITriaseSekunder>;
}

export class Triase {
  data: Array<ITriaseSekunder>;

  constructor(req: ITriase) {
    this.data = (req.data && Array.isArray(req.data)) ? req.data : [];
  }
}

export interface IAssessmentUgdFormModel {
    GCS_E: string;
    GCS_M: string;
    GCS_V: string;
    Resep: Array<IPrescription>;
    Resep_Umum: Array<IPrescription>;
    GCS_Score: string;
    GCS_E_Teks: string;
    GCS_M_Teks: string;
    GCS_V_Teks: string;
    ID_Petugas: string;
    Updated_At: string;
    Updated_By: string;
    Vital_Suhu: string;
    Alergi_Obat: string;
    Skala_Nyeri: string;
    Kerabat_Nama: string;
    Mental_Sadar: number;
    Nama_Petugas: string;
    Nutrisi_Berat: string;
    Alergi_Lainnya: string;
    Alergi_Makanan: string;
    Asal_Informasi: string;
    Gambar_Mata_OD: string;
    Gambar_Mata_OS: string;
    Kesadaran_Teks: string;
    Nutrisi_Tinggi: string;
    Sirkulasi_Teks: string;
    Kerabat_Telepon: string;
    Kesadaran_Value: string;
    Mental_Perilaku: number;
    Pengkajian_Dada: string;
    Pengkajian_Gigi: string;
    Pengkajian_Mata: string;
    Pengkajian_Paru: string;
    Pernafasan_Teks: string;
    Sirkulasi_Value: string;
    Spiritual_Agama: string;
    TTD_Dokter_Mata: string;
    Triase_Sekunder: any;
    Vital_Kesadaran: string;
    Jalan_Nafas_Teks: string;
    Kerabat_Hubungan: string;
    Mental_Kekerasan: number;
    Pengkajian_Leher: string;
    Pengkajian_OD_VA: string;
    Pengkajian_OS_VA: string;
    Pernafasan_Value: string;
    Psikologis_Cemas: number;
    Psikologis_Marah: number;
    Psikologis_Sedih: number;
    Psikologis_Takut: number;
    Status_Kehamilan: number;
    Jalan_Nafas_Value: string;
    Kedatangan_Pasien: string;
    Pengkajian_Fungsi: string;
    Pengkajian_Hidung: string;
    Pengkajian_Kepala: string;
    Vital_Denyut_Nadi: string;
    Bantuan_Nafas_Teks: string;
    Dokter_Mata_COA_OD: string;
    Dokter_Mata_COA_OS: string;
    Dokter_Mata_Terapi: string;
    Nutrisi_Total_Skor: string;
    Pengkajian_Abdomen: string;
    Pengkajian_Anjuran: string;
    Pengkajian_Jantung: string;
    Pengkajian_Telinga: string;
    Penyakit_Terdahulu: string;
    Asal_Informasi_Teks: string;
    Bantuan_Nafas_Value: string;
    Dokter_Mata_Anjuran: string;
    Dokter_Mata_Iris_OD: string;
    Dokter_Mata_Iris_OS: string;
    Pengkajian_Assesmen: string;
    Pengkajian_Eks_Atas: string;
    Pertolongan_Pertama: string;
    TTD_Dokter_Pengkaji: string;
    Tindakan_Resusitasi: string;
    Vital_Tekanan_Darah: string;
    Dokter_Mata_Diagnosa: string;
    Dokter_Mata_Lensa_OD: string;
    Dokter_Mata_Lensa_OS: string;
    Dokter_Mata_Pupil_OD: string;
    Dokter_Mata_Pupil_OS: string;
    ID_Pengkajian_Dokter: string;
    Nutrisi_Lebih_Lanjut: string;
    Pengkajian_Eks_Bawah: string;
    Pengkajian_Genitalia: string;
    Pengkajian_Kandungan: string;
    Pengkajian_Subjektif: string;
    Pengobatan_Terdahulu: string;
    Psikologis_Lain_Lain: number;
    Dokter_Mata_Cornea_OD: string;
    Dokter_Mata_Cornea_OS: string;
    Dokter_Mata_Posisi_OD: string;
    Dokter_Mata_Posisi_OS: string;
    ID_Dokter_Mata_Dokter: string;
    Keperawatan_Rencana_0: number;
    Keperawatan_Rencana_1: number;
    Keperawatan_Rencana_2: number;
    Keperawatan_Rencana_3: number;
    Keperawatan_Rencana_4: number;
    Keperawatan_Rencana_5: number;
    Keperawatan_Rencana_6: number;
    Keperawatan_Rencana_7: number;
    Penurunan_Berat_Badan: number;
    Penurunan_Nafsu_Makan: number;
    Status_Kehamilan_HPHT: string;
    Status_Kehamilan_Para: string;
    Keperawatan_Diagnosa_0: number;
    Keperawatan_Diagnosa_1: number;
    Keperawatan_Diagnosa_2: number;
    Keperawatan_Diagnosa_3: number;
    Keperawatan_Diagnosa_4: number;
    Keperawatan_Diagnosa_5: number;
    Keperawatan_Diagnosa_6: number;
    Keperawatan_Diagnosa_7: number;
    Nama_Pengkajian_Dokter: string;
    Pengkajian_Fungsi_Teks: string;
    Pengkajian_Tenggorokan: string;
    Penilaian_Risiko_Jatuh: number;
    Risiko_Jatuh_Ibu_Hamil: number;
    Vital_Respiratory_Rate: string;
    Asal_Informasi_Hubungan: string;
    Dokter_Mata_Vitreous_OD: string;
    Dokter_Mata_Vitreous_OS: string;
    Nama_Dokter_Mata_Dokter: string;
    Nutrisi_Diagnosa_Khusus: string;
    Pengkajian_OD_Tonometri: string;
    Pengkajian_OS_Tonometri: string;
    Risiko_Jatuh_Alat_Bantu: number;
    Risiko_Jatuh_Lanjut_Usia: number;
    Status_Kehamilan_Abortus: string;
    Status_Kehamilan_Gravida: string;
    Dokter_Mata_Conj_Bulbi_OD: string;
    Dokter_Mata_Conj_Bulbi_OS: string;
    Dokter_Mata_Funduscopy_OD: string;
    Dokter_Mata_Funduscopy_OS: string;
    Dokter_Mata_Pergerakan_OD: string;
    Dokter_Mata_Pergerakan_OS: string;
    Sirkulasi_Resusitasi_Teks: string;
    Mental_Perilaku_Keterangan: string;
    Sirkulasi_Resusitasi_Value: string;
    Keperawatan_Rencana_Lainnya: string;
    Mental_Kekerasan_Keterangan: string;
    Penurunan_Berat_Badan_Nilai: number;
    Keperawatan_Diagnosa_Lainnya: string;
    Dokter_Mata_Rencana_Pengobatan: string;
    Pengkajian_Terapi_Penatalaksaan: string;
    Psikologis_Lain_Lain_Keterangan: string;
    Dokter_Mata_Palpebra_Superior_OD: string;
    Dokter_Mata_Palpebra_Superior_OS: string;
    Pengkajian_Pemeriksaan_Penunjang: string;
    Nutrisi_Diagnosa_Khusus_Keterangan: string;
    Dokter_Mata_Conj_Tarsal_Inferior_OD: string;
    Dokter_Mata_Conj_Tarsal_Inferior_OS: string;
    Dokter_Mata_Conj_Tarsal_Superior_OD: string;
    Dokter_Mata_Conj_Tarsal_Superior_OS: string;
    Psikologis_Kecenderungan_Bunuh_Diri: number;
    TTD_Perawat: string;
    ID_Perawat: string;
    Nama_Perawat: string;
}

export class AssessmentUgdFormModel {
    GCS_E: string;
    GCS_M: string;
    GCS_V: string;
    Resep: Array<IPrescription>;
    Resep_Umum: Array<IPrescription>;
    GCS_Score: string;
    GCS_E_Teks: string;
    GCS_M_Teks: string;
    GCS_V_Teks: string;
    ID_Petugas: string;
    Updated_At: string;
    Updated_By: string;
    Vital_Suhu: string;
    Alergi_Obat: string;
    Skala_Nyeri: string;
    Kerabat_Nama: string;
    Mental_Sadar: number;
    Nama_Petugas: string;
    Nutrisi_Berat: string;
    Alergi_Lainnya: string;
    Alergi_Makanan: string;
    Asal_Informasi: string;
    Gambar_Mata_OD: string;
    Gambar_Mata_OS: string;
    Kesadaran_Teks: string;
    Nutrisi_Tinggi: string;
    Sirkulasi_Teks: string;
    Kerabat_Telepon: string;
    Kesadaran_Value: string;
    Mental_Perilaku: number;
    Pengkajian_Dada: string;
    Pengkajian_Gigi: string;
    Pengkajian_Mata: string;
    Pengkajian_Paru: string;
    Pernafasan_Teks: string;
    Sirkulasi_Value: string;
    Spiritual_Agama: string;
    TTD_Dokter_Mata: string;
    Triase_Sekunder: any;
    Vital_Kesadaran: string;
    Jalan_Nafas_Teks: string;
    Kerabat_Hubungan: string;
    Mental_Kekerasan: number;
    Pengkajian_Leher: string;
    Pengkajian_OD_VA: string;
    Pengkajian_OS_VA: string;
    Pernafasan_Value: string;
    Psikologis_Cemas: number;
    Psikologis_Marah: number;
    Psikologis_Sedih: number;
    Psikologis_Takut: number;
    Status_Kehamilan: number;
    Jalan_Nafas_Value: string;
    Kedatangan_Pasien: string;
    Pengkajian_Fungsi: string;
    Pengkajian_Hidung: string;
    Pengkajian_Kepala: string;
    Vital_Denyut_Nadi: string;
    Bantuan_Nafas_Teks: string;
    Dokter_Mata_COA_OD: string;
    Dokter_Mata_COA_OS: string;
    Dokter_Mata_Terapi: string;
    Nutrisi_Total_Skor: string;
    Pengkajian_Abdomen: string;
    Pengkajian_Anjuran: string;
    Pengkajian_Jantung: string;
    Pengkajian_Telinga: string;
    Penyakit_Terdahulu: string;
    Asal_Informasi_Teks: string;
    Bantuan_Nafas_Value: string;
    Dokter_Mata_Anjuran: string;
    Dokter_Mata_Iris_OD: string;
    Dokter_Mata_Iris_OS: string;
    Pengkajian_Assesmen: string;
    Pengkajian_Eks_Atas: string;
    Pertolongan_Pertama: string;
    TTD_Dokter_Pengkaji: string;
    Tindakan_Resusitasi: string;
    Vital_Tekanan_Darah: string;
    Dokter_Mata_Diagnosa: string;
    Dokter_Mata_Lensa_OD: string;
    Dokter_Mata_Lensa_OS: string;
    Dokter_Mata_Pupil_OD: string;
    Dokter_Mata_Pupil_OS: string;
    ID_Pengkajian_Dokter: string;
    Nutrisi_Lebih_Lanjut: string;
    Pengkajian_Eks_Bawah: string;
    Pengkajian_Genitalia: string;
    Pengkajian_Kandungan: string;
    Pengkajian_Subjektif: string;
    Pengobatan_Terdahulu: string;
    Psikologis_Lain_Lain: number;
    Dokter_Mata_Cornea_OD: string;
    Dokter_Mata_Cornea_OS: string;
    Dokter_Mata_Posisi_OD: string;
    Dokter_Mata_Posisi_OS: string;
    ID_Dokter_Mata_Dokter: string;
    Keperawatan_Rencana_0: number;
    Keperawatan_Rencana_1: number;
    Keperawatan_Rencana_2: number;
    Keperawatan_Rencana_3: number;
    Keperawatan_Rencana_4: number;
    Keperawatan_Rencana_5: number;
    Keperawatan_Rencana_6: number;
    Keperawatan_Rencana_7: number;
    Penurunan_Berat_Badan: number;
    Penurunan_Nafsu_Makan: number;
    Status_Kehamilan_HPHT: string;
    Status_Kehamilan_Para: string;
    Keperawatan_Diagnosa_0: number;
    Keperawatan_Diagnosa_1: number;
    Keperawatan_Diagnosa_2: number;
    Keperawatan_Diagnosa_3: number;
    Keperawatan_Diagnosa_4: number;
    Keperawatan_Diagnosa_5: number;
    Keperawatan_Diagnosa_6: number;
    Keperawatan_Diagnosa_7: number;
    Nama_Pengkajian_Dokter: string;
    Pengkajian_Fungsi_Teks: string;
    Pengkajian_Tenggorokan: string;
    Penilaian_Risiko_Jatuh: number;
    Risiko_Jatuh_Ibu_Hamil: number;
    Vital_Respiratory_Rate: string;
    Asal_Informasi_Hubungan: string;
    Dokter_Mata_Vitreous_OD: string;
    Dokter_Mata_Vitreous_OS: string;
    Nama_Dokter_Mata_Dokter: string;
    Nutrisi_Diagnosa_Khusus: string;
    Pengkajian_OD_Tonometri: string;
    Pengkajian_OS_Tonometri: string;
    Risiko_Jatuh_Alat_Bantu: number;
    Risiko_Jatuh_Lanjut_Usia: number;
    Status_Kehamilan_Abortus: string;
    Status_Kehamilan_Gravida: string;
    Dokter_Mata_Conj_Bulbi_OD: string;
    Dokter_Mata_Conj_Bulbi_OS: string;
    Dokter_Mata_Funduscopy_OD: string;
    Dokter_Mata_Funduscopy_OS: string;
    Dokter_Mata_Pergerakan_OD: string;
    Dokter_Mata_Pergerakan_OS: string;
    Sirkulasi_Resusitasi_Teks: string;
    Mental_Perilaku_Keterangan: string;
    Sirkulasi_Resusitasi_Value: string;
    Keperawatan_Rencana_Lainnya: string;
    Mental_Kekerasan_Keterangan: string;
    Penurunan_Berat_Badan_Nilai: number;
    Keperawatan_Diagnosa_Lainnya: string;
    Dokter_Mata_Rencana_Pengobatan: string;
    Pengkajian_Terapi_Penatalaksaan: string;
    Psikologis_Lain_Lain_Keterangan: string;
    Dokter_Mata_Palpebra_Superior_OD: string;
    Dokter_Mata_Palpebra_Superior_OS: string;
    Pengkajian_Pemeriksaan_Penunjang: string;
    Nutrisi_Diagnosa_Khusus_Keterangan: string;
    Dokter_Mata_Conj_Tarsal_Inferior_OD: string;
    Dokter_Mata_Conj_Tarsal_Inferior_OS: string;
    Dokter_Mata_Conj_Tarsal_Superior_OD: string;
    Dokter_Mata_Conj_Tarsal_Superior_OS: string;
    Psikologis_Kecenderungan_Bunuh_Diri: number;
    TTD_Perawat: string;
    ID_Perawat: string;
    Nama_Perawat: string;

    constructor(request: IAssessmentUgdFormModel) {
      this.GCS_E = request.GCS_E;
      this.GCS_M = request.GCS_M;
      this.GCS_V = request.GCS_V;
      this.Resep = request.Resep;
      this.Resep_Umum = request.Resep_Umum;
      this.GCS_Score = request.GCS_Score;
      this.GCS_E_Teks = request.GCS_E_Teks;
      this.GCS_M_Teks = request.GCS_M_Teks;
      this.GCS_V_Teks = request.GCS_V_Teks;
      this.ID_Petugas = request.ID_Petugas;
      this.Updated_At = request.Updated_At;
      this.Updated_By = request.Updated_By;
      this.Vital_Suhu = request.Vital_Suhu;
      this.Alergi_Obat = request.Alergi_Obat;
      this.Skala_Nyeri = request.Skala_Nyeri;
      this.Kerabat_Nama = request.Kerabat_Nama;
      this.Mental_Sadar = request.Mental_Sadar;
      this.Nama_Petugas = request.Nama_Petugas;
      this.Nutrisi_Berat = request.Nutrisi_Berat;
      this.Alergi_Lainnya = request.Alergi_Lainnya;
      this.Alergi_Makanan = request.Alergi_Makanan;
      this.Asal_Informasi = request.Asal_Informasi;
      this.Gambar_Mata_OD = request.Gambar_Mata_OD;
      this.Gambar_Mata_OS = request.Gambar_Mata_OS;
      this.Kesadaran_Teks = request.Kesadaran_Teks;
      this.Nutrisi_Tinggi = request.Nutrisi_Tinggi;
      this.Sirkulasi_Teks = request.Sirkulasi_Teks;
      this.Kerabat_Telepon = request.Kerabat_Telepon;
      this.Kesadaran_Value = request.Kesadaran_Value;
      this.Mental_Perilaku = request.Mental_Perilaku;
      this.Pengkajian_Dada = request.Pengkajian_Dada;
      this.Pengkajian_Gigi = request.Pengkajian_Gigi;
      this.Pengkajian_Mata = request.Pengkajian_Mata;
      this.Pengkajian_Paru = request.Pengkajian_Paru;
      this.Pernafasan_Teks = request.Pernafasan_Teks;
      this.Sirkulasi_Value = request.Sirkulasi_Value;
      this.Spiritual_Agama = request.Spiritual_Agama;
      this.TTD_Dokter_Mata = request.TTD_Dokter_Mata;
      this.Triase_Sekunder = request.Triase_Sekunder;
      this.Vital_Kesadaran = request.Vital_Kesadaran;
      this.Jalan_Nafas_Teks = request.Jalan_Nafas_Teks;
      this.Kerabat_Hubungan = request.Kerabat_Hubungan;
      this.Mental_Kekerasan = request.Mental_Kekerasan;
      this.Pengkajian_Leher = request.Pengkajian_Leher;
      this.Pengkajian_OD_VA = request.Pengkajian_OD_VA;
      this.Pengkajian_OS_VA = request.Pengkajian_OS_VA;
      this.Pernafasan_Value = request.Pernafasan_Value;
      this.Psikologis_Cemas = request.Psikologis_Cemas;
      this.Psikologis_Marah = request.Psikologis_Marah;
      this.Psikologis_Sedih = request.Psikologis_Sedih;
      this.Psikologis_Takut = request.Psikologis_Takut;
      this.Status_Kehamilan = request.Status_Kehamilan;
      this.Jalan_Nafas_Value = request.Jalan_Nafas_Value;
      this.Kedatangan_Pasien = request.Kedatangan_Pasien;
      this.Pengkajian_Fungsi = request.Pengkajian_Fungsi;
      this.Pengkajian_Hidung = request.Pengkajian_Hidung;
      this.Pengkajian_Kepala = request.Pengkajian_Kepala;
      this.Vital_Denyut_Nadi = request.Vital_Denyut_Nadi;
      this.Bantuan_Nafas_Teks = request.Bantuan_Nafas_Teks;
      this.Dokter_Mata_COA_OD = request.Dokter_Mata_COA_OD;
      this.Dokter_Mata_COA_OS = request.Dokter_Mata_COA_OS;
      this.Dokter_Mata_Terapi = request.Dokter_Mata_Terapi;
      this.Nutrisi_Total_Skor = request.Nutrisi_Total_Skor;
      this.Pengkajian_Abdomen = request.Pengkajian_Abdomen;
      this.Pengkajian_Anjuran = request.Pengkajian_Anjuran;
      this.Pengkajian_Jantung = request.Pengkajian_Jantung;
      this.Pengkajian_Telinga = request.Pengkajian_Telinga;
      this.Penyakit_Terdahulu = request.Penyakit_Terdahulu;
      this.Asal_Informasi_Teks = request.Asal_Informasi_Teks;
      this.Bantuan_Nafas_Value = request.Bantuan_Nafas_Value;
      this.Dokter_Mata_Anjuran = request.Dokter_Mata_Anjuran;
      this.Dokter_Mata_Iris_OD = request.Dokter_Mata_Iris_OD;
      this.Dokter_Mata_Iris_OS = request.Dokter_Mata_Iris_OS;
      this.Pengkajian_Assesmen = request.Pengkajian_Assesmen;
      this.Pengkajian_Eks_Atas = request.Pengkajian_Eks_Atas;
      this.Pertolongan_Pertama = request.Pertolongan_Pertama;
      this.TTD_Dokter_Pengkaji = request.TTD_Dokter_Pengkaji;
      this.Tindakan_Resusitasi = request.Tindakan_Resusitasi;
      this.Vital_Tekanan_Darah = request.Vital_Tekanan_Darah;
      this.Dokter_Mata_Diagnosa = request.Dokter_Mata_Diagnosa;
      this.Dokter_Mata_Lensa_OD = request.Dokter_Mata_Lensa_OD;
      this.Dokter_Mata_Lensa_OS = request.Dokter_Mata_Lensa_OS;
      this.Dokter_Mata_Pupil_OD = request.Dokter_Mata_Pupil_OD;
      this.Dokter_Mata_Pupil_OS = request.Dokter_Mata_Pupil_OS;
      this.ID_Pengkajian_Dokter = request.ID_Pengkajian_Dokter;
      this.Nutrisi_Lebih_Lanjut = request.Nutrisi_Lebih_Lanjut;
      this.Pengkajian_Eks_Bawah = request.Pengkajian_Eks_Bawah;
      this.Pengkajian_Genitalia = request.Pengkajian_Genitalia;
      this.Pengkajian_Kandungan = request.Pengkajian_Kandungan;
      this.Pengkajian_Subjektif = request.Pengkajian_Subjektif;
      this.Pengobatan_Terdahulu = request.Pengobatan_Terdahulu;
      this.Psikologis_Lain_Lain = request.Psikologis_Lain_Lain;
      this.Dokter_Mata_Cornea_OD = request.Dokter_Mata_Cornea_OD;
      this.Dokter_Mata_Cornea_OS = request.Dokter_Mata_Cornea_OS;
      this.Dokter_Mata_Posisi_OD = request.Dokter_Mata_Posisi_OD;
      this.Dokter_Mata_Posisi_OS = request.Dokter_Mata_Posisi_OS;
      this.ID_Dokter_Mata_Dokter = request.ID_Dokter_Mata_Dokter;
      this.Keperawatan_Rencana_0 = request.Keperawatan_Rencana_0;
      this.Keperawatan_Rencana_1 = request.Keperawatan_Rencana_1;
      this.Keperawatan_Rencana_2 = request.Keperawatan_Rencana_2;
      this.Keperawatan_Rencana_3 = request.Keperawatan_Rencana_3;
      this.Keperawatan_Rencana_4 = request.Keperawatan_Rencana_4;
      this.Keperawatan_Rencana_5 = request.Keperawatan_Rencana_5;
      this.Keperawatan_Rencana_6 = request.Keperawatan_Rencana_6;
      this.Keperawatan_Rencana_7 = request.Keperawatan_Rencana_7;
      this.Penurunan_Berat_Badan = request.Penurunan_Berat_Badan;
      this.Penurunan_Nafsu_Makan = request.Penurunan_Nafsu_Makan;
      this.Status_Kehamilan_HPHT = request.Status_Kehamilan_HPHT;
      this.Status_Kehamilan_Para = request.Status_Kehamilan_Para;
      this.Keperawatan_Diagnosa_0 = request.Keperawatan_Diagnosa_0;
      this.Keperawatan_Diagnosa_1 = request.Keperawatan_Diagnosa_1;
      this.Keperawatan_Diagnosa_2 = request.Keperawatan_Diagnosa_2;
      this.Keperawatan_Diagnosa_3 = request.Keperawatan_Diagnosa_3;
      this.Keperawatan_Diagnosa_4 = request.Keperawatan_Diagnosa_4;
      this.Keperawatan_Diagnosa_5 = request.Keperawatan_Diagnosa_5;
      this.Keperawatan_Diagnosa_6 = request.Keperawatan_Diagnosa_6;
      this.Keperawatan_Diagnosa_7 = request.Keperawatan_Diagnosa_7;
      this.Nama_Pengkajian_Dokter = request.Nama_Pengkajian_Dokter;
      this.Pengkajian_Fungsi_Teks = request.Pengkajian_Fungsi_Teks;
      this.Pengkajian_Tenggorokan = request.Pengkajian_Tenggorokan;
      this.Penilaian_Risiko_Jatuh = request.Penilaian_Risiko_Jatuh;
      this.Risiko_Jatuh_Ibu_Hamil = request.Risiko_Jatuh_Ibu_Hamil;
      this.Vital_Respiratory_Rate = request.Vital_Respiratory_Rate;
      this.Asal_Informasi_Hubungan = request.Asal_Informasi_Hubungan;
      this.Dokter_Mata_Vitreous_OD = request.Dokter_Mata_Vitreous_OD;
      this.Dokter_Mata_Vitreous_OS = request.Dokter_Mata_Vitreous_OS;
      this.Nama_Dokter_Mata_Dokter = request.Nama_Dokter_Mata_Dokter;
      this.Nutrisi_Diagnosa_Khusus = request.Nutrisi_Diagnosa_Khusus;
      this.Pengkajian_OD_Tonometri = request.Pengkajian_OD_Tonometri;
      this.Pengkajian_OS_Tonometri = request.Pengkajian_OS_Tonometri;
      this.Risiko_Jatuh_Alat_Bantu = request.Risiko_Jatuh_Alat_Bantu;
      this.Risiko_Jatuh_Lanjut_Usia = request.Risiko_Jatuh_Lanjut_Usia;
      this.Status_Kehamilan_Abortus = request.Status_Kehamilan_Abortus;
      this.Status_Kehamilan_Gravida = request.Status_Kehamilan_Gravida;
      this.Dokter_Mata_Conj_Bulbi_OD = request.Dokter_Mata_Conj_Bulbi_OD;
      this.Dokter_Mata_Conj_Bulbi_OS = request.Dokter_Mata_Conj_Bulbi_OS;
      this.Dokter_Mata_Funduscopy_OD = request.Dokter_Mata_Funduscopy_OD;
      this.Dokter_Mata_Funduscopy_OS = request.Dokter_Mata_Funduscopy_OS;
      this.Dokter_Mata_Pergerakan_OD = request.Dokter_Mata_Pergerakan_OD;
      this.Dokter_Mata_Pergerakan_OS = request.Dokter_Mata_Pergerakan_OS;
      this.Sirkulasi_Resusitasi_Teks = request.Sirkulasi_Resusitasi_Teks;
      this.Mental_Perilaku_Keterangan = request.Mental_Perilaku_Keterangan;
      this.Sirkulasi_Resusitasi_Value = request.Sirkulasi_Resusitasi_Value;
      this.Keperawatan_Rencana_Lainnya = request.Keperawatan_Rencana_Lainnya;
      this.Mental_Kekerasan_Keterangan = request.Mental_Kekerasan_Keterangan;
      this.Penurunan_Berat_Badan_Nilai = request.Penurunan_Berat_Badan_Nilai;
      this.Keperawatan_Diagnosa_Lainnya = request.Keperawatan_Diagnosa_Lainnya;
      this.Dokter_Mata_Rencana_Pengobatan = request.Dokter_Mata_Rencana_Pengobatan;
      this.Pengkajian_Terapi_Penatalaksaan = request.Pengkajian_Terapi_Penatalaksaan;
      this.Psikologis_Lain_Lain_Keterangan = request.Psikologis_Lain_Lain_Keterangan;
      this.Dokter_Mata_Palpebra_Superior_OD = request.Dokter_Mata_Palpebra_Superior_OD;
      this.Dokter_Mata_Palpebra_Superior_OS = request.Dokter_Mata_Palpebra_Superior_OS;
      this.Pengkajian_Pemeriksaan_Penunjang = request.Pengkajian_Pemeriksaan_Penunjang;
      this.Nutrisi_Diagnosa_Khusus_Keterangan = request.Nutrisi_Diagnosa_Khusus_Keterangan;
      this.Dokter_Mata_Conj_Tarsal_Inferior_OD = request.Dokter_Mata_Conj_Tarsal_Inferior_OD;
      this.Dokter_Mata_Conj_Tarsal_Inferior_OS = request.Dokter_Mata_Conj_Tarsal_Inferior_OS;
      this.Dokter_Mata_Conj_Tarsal_Superior_OD = request.Dokter_Mata_Conj_Tarsal_Superior_OD;
      this.Dokter_Mata_Conj_Tarsal_Superior_OS = request.Dokter_Mata_Conj_Tarsal_Superior_OS;
      this.Psikologis_Kecenderungan_Bunuh_Diri = request.Psikologis_Kecenderungan_Bunuh_Diri;
      this.TTD_Perawat = request.TTD_Perawat;
      this.ID_Perawat = request.ID_Perawat;
      this.Nama_Perawat = request.Nama_Perawat;
    }
}

export interface IDaftarTebus {
    Catatan: string;
    ID_AturanPakai: string;
    ID_Satuan: string;
    Jumlah: string;
    Kode_AturanPakai: string;
    Kode_Obat: string;
    Nama_AturanPakai: string;
    Nama_Obat: string;
    Nama_Satuan: string;
  }

export interface IFormFarmasi {
    Daftar_Tebus: Array<IDaftarTebus>;
    Keterangan: string;
    Status_Tebus: string;
    Waktu_Tebus: string;
  }

export class FormFarmasi {
    Daftar_Tebus: Array<IDaftarTebus>;
    Keterangan: string;
    Status_Tebus: string;
    Waktu_Tebus: string;

    constructor(req: IFormFarmasi) {
      this.Daftar_Tebus = req.Daftar_Tebus;
      this.Keterangan = req.Keterangan;
      this.Status_Tebus = req.Status_Tebus;
      this.Waktu_Tebus = req.Waktu_Tebus;
    }
}

export interface IAssessmentUgdModel extends IDataModel  {
    form:  IAssessmentUgdFormModel;
    formFarmasi: IFormFarmasi;
    isDefault: boolean;
    obat: Array<IMedicine>;
    aturan_pakai: Array<IHowToUse>;
    dokter: Array<IDoctorModel>;
}

export class AssessmentUgdModel extends DataModel {
    form:  IAssessmentUgdFormModel;
    formFarmasi: IFormFarmasi;
    isDefault: boolean;
    obat: Array<IMedicine>;
    aturan_pakai: Array<IHowToUse>;
    dokter: Array<IDoctorModel>;

    constructor(assessment: IAssessmentUgdModel) {
      super(assessment);
      this.form = assessment.form;
      this.formFarmasi = assessment.formFarmasi;
      this.isDefault = assessment.isDefault;
      this.obat = (Array.isArray(assessment.obat)) ? assessment.obat.map((a) => new Medicine(a)) : [];
      this.aturan_pakai = (Array.isArray(assessment.aturan_pakai)) ? assessment.aturan_pakai.map((a) => new HowToUse(a)) : [];
      this.dokter = (Array.isArray(assessment.dokter)) ? assessment.dokter.map((a) => new DoctorModel(a)) : [];
    }
}