import { IDataModel, DataModel } from "@src/shared/model";

export interface ISafetyChecklistForm {
    Waktu: string;
    ID_Petugas: string;
    Updated_At: string;
    Updated_By: string;
    Nama_Petugas: string;
    Sign_In_Tanda: number;
    Sign_In_Waktu: string;
    Sign_In_Alergi: number;
    Sign_In_Implan: number;
    Sign_Out_Waktu: string;
    Time_Out_Hasil: number;
    Time_Out_Waktu: string;
    Sign_In_Lengkap: number;
    Time_Out_Steril: number;
    Sign_In_Informed: number;
    Sign_Out_ID_Mata: string;
    Time_Out_Masalah: string;
    Sign_In_ID_Dokter: string;
    Sign_In_ID_Penata: string;
    Sign_Out_TTD_Mata: string;
    Sign_In_ID_Perawat: string;
    Sign_In_Pendarahan: number;
    Sign_In_Pernafasan: number;
    Sign_In_TTD_Dokter: string;
    Sign_In_TTD_Penata: string;
    Sign_Out_ID_Dokter: string;
    Sign_Out_ID_Penata: string;
    Sign_Out_Nama_Mata: string;
    Time_Out_ID_Dokter: string;
    Time_Out_ID_Penata: string;
    Time_Out_Peralatan: number;
    Sign_In_Nama_Dokter: string;
    Sign_In_Nama_Penata: string;
    Sign_In_TTD_Perawat: string;
    Sign_Out_ID_Perawat: string;
    Sign_Out_TTD_Dokter: string;
    Sign_Out_TTD_Penata: string;
    Time_Out_Baca_Ulang: number;
    Time_Out_ID_Perawat: string;
    Time_Out_Pendarahan: number;
    Time_Out_TTD_Dokter: string;
    Time_Out_TTD_Penata: string;
    Sign_In_Nama_Perawat: string;
    Sign_Out_ID_Sirkuler: string;
    Sign_Out_Nama_Dokter: string;
    Sign_Out_Nama_Penata: string;
    Sign_Out_TTD_Perawat: string;
    Time_Out_Nama_Dokter: string;
    Time_Out_Nama_Penata: string;
    Time_Out_TTD_Perawat: string;
    Time_Out_Tidak_Rutin: number;
    Sign_Out_Nama_Perawat: string;
    Sign_Out_TTD_Sirkuler: string;
    Time_Out_Nama_Perawat: string;
    Sign_In_Ruangan_Dokter: number;
    Sign_In_Ruangan_Penata: number;
    Sign_Out_Nama_Sirkuler: string;
    Sign_Out_Nama_Tindakan: number;
    Sign_Out_Ruangan_Bedah: number;
    Time_Out_Ruangan_Bedah: number;
    Sign_In_Pulse_Oksimetri: number;
    Sign_In_Ruangan_Perawat: number;
    Sign_Out_Catatan_Khusus: number;
    Sign_Out_Ruangan_Dokter: number;
    Sign_Out_Ruangan_Penata: number;
    Time_Out_Ruangan_Dokter: number;
    Time_Out_Ruangan_Penata: number;
    Sign_Out_Ruangan_Perawat: number;
    Time_Out_Anestesi_Khusus: number;
    Time_Out_Perkenalan_Diri: number;
    Time_Out_Ruangan_Perawat: number;
    Sign_Out_Kelengkapan_Alat: number;
    Sign_Out_Masalah_Peralatan: number;
    Time_Out_Tidak_Rutin_Waktu: string;
    Sign_Out_Pelabelan_Spesimen: number;
    Time_Out_Profilaksis_Antibiotik: number;
}

export class SafetyChecklistForm {
    Waktu: string;
    ID_Petugas: string;
    Updated_At: string;
    Updated_By: string;
    Nama_Petugas: string;
    Sign_In_Tanda: number;
    Sign_In_Waktu: string;
    Sign_In_Alergi: number;
    Sign_In_Implan: number;
    Sign_Out_Waktu: string;
    Time_Out_Hasil: number;
    Time_Out_Waktu: string;
    Sign_In_Lengkap: number;
    Time_Out_Steril: number;
    Sign_In_Informed: number;
    Sign_Out_ID_Mata: string;
    Time_Out_Masalah: string;
    Sign_In_ID_Dokter: string;
    Sign_In_ID_Penata: string;
    Sign_Out_TTD_Mata: string;
    Sign_In_ID_Perawat: string;
    Sign_In_Pendarahan: number;
    Sign_In_Pernafasan: number;
    Sign_In_TTD_Dokter: string;
    Sign_In_TTD_Penata: string;
    Sign_Out_ID_Dokter: string;
    Sign_Out_ID_Penata: string;
    Sign_Out_Nama_Mata: string;
    Time_Out_ID_Dokter: string;
    Time_Out_ID_Penata: string;
    Time_Out_Peralatan: number;
    Sign_In_Nama_Dokter: string;
    Sign_In_Nama_Penata: string;
    Sign_In_TTD_Perawat: string;
    Sign_Out_ID_Perawat: string;
    Sign_Out_TTD_Dokter: string;
    Sign_Out_TTD_Penata: string;
    Time_Out_Baca_Ulang: number;
    Time_Out_ID_Perawat: string;
    Time_Out_Pendarahan: number;
    Time_Out_TTD_Dokter: string;
    Time_Out_TTD_Penata: string;
    Sign_In_Nama_Perawat: string;
    Sign_Out_ID_Sirkuler: string;
    Sign_Out_Nama_Dokter: string;
    Sign_Out_Nama_Penata: string;
    Sign_Out_TTD_Perawat: string;
    Time_Out_Nama_Dokter: string;
    Time_Out_Nama_Penata: string;
    Time_Out_TTD_Perawat: string;
    Time_Out_Tidak_Rutin: number;
    Sign_Out_Nama_Perawat: string;
    Sign_Out_TTD_Sirkuler: string;
    Time_Out_Nama_Perawat: string;
    Sign_In_Ruangan_Dokter: number;
    Sign_In_Ruangan_Penata: number;
    Sign_Out_Nama_Sirkuler: string;
    Sign_Out_Nama_Tindakan: number;
    Sign_Out_Ruangan_Bedah: number;
    Time_Out_Ruangan_Bedah: number;
    Sign_In_Pulse_Oksimetri: number;
    Sign_In_Ruangan_Perawat: number;
    Sign_Out_Catatan_Khusus: number;
    Sign_Out_Ruangan_Dokter: number;
    Sign_Out_Ruangan_Penata: number;
    Time_Out_Ruangan_Dokter: number;
    Time_Out_Ruangan_Penata: number;
    Sign_Out_Ruangan_Perawat: number;
    Time_Out_Anestesi_Khusus: number;
    Time_Out_Perkenalan_Diri: number;
    Time_Out_Ruangan_Perawat: number;
    Sign_Out_Kelengkapan_Alat: number;
    Sign_Out_Masalah_Peralatan: number;
    Time_Out_Tidak_Rutin_Waktu: string;
    Sign_Out_Pelabelan_Spesimen: number;
    Time_Out_Profilaksis_Antibiotik: number;
    constructor(form: ISafetyChecklistForm) {
      this.Waktu = form.Waktu;
      this.ID_Petugas = form.ID_Petugas;
      this.Updated_At = form.Updated_At;
      this.Updated_By = form.Updated_By;
      this.Nama_Petugas = form.Nama_Petugas;
      this.Sign_In_Tanda = form.Sign_In_Tanda;
      this.Sign_In_Waktu = form.Sign_In_Waktu;
      this.Sign_In_Alergi = form.Sign_In_Alergi;
      this.Sign_In_Implan = form.Sign_In_Implan;
      this.Sign_Out_Waktu = form.Sign_Out_Waktu;
      this.Time_Out_Hasil = form.Time_Out_Hasil;
      this.Time_Out_Waktu = form.Time_Out_Waktu;
      this.Sign_In_Lengkap = form.Sign_In_Lengkap;
      this.Time_Out_Steril = form.Time_Out_Steril;
      this.Sign_In_Informed = form.Sign_In_Informed;
      this.Sign_Out_ID_Mata = form.Sign_Out_ID_Mata;
      this.Time_Out_Masalah = form.Time_Out_Masalah;
      this.Sign_In_ID_Dokter = form.Sign_In_ID_Dokter;
      this.Sign_In_ID_Penata = form.Sign_In_ID_Penata;
      this.Sign_Out_TTD_Mata = form.Sign_Out_TTD_Mata;
      this.Sign_In_ID_Perawat = form.Sign_In_ID_Perawat;
      this.Sign_In_Pendarahan = form.Sign_In_Pendarahan;
      this.Sign_In_Pernafasan = form.Sign_In_Pernafasan;
      this.Sign_In_TTD_Dokter = form.Sign_In_TTD_Dokter;
      this.Sign_In_TTD_Penata = form.Sign_In_TTD_Penata;
      this.Sign_Out_ID_Dokter = form.Sign_Out_ID_Dokter;
      this.Sign_Out_ID_Penata = form.Sign_Out_ID_Penata;
      this.Sign_Out_Nama_Mata = form.Sign_Out_Nama_Mata;
      this.Time_Out_ID_Dokter = form.Time_Out_ID_Dokter;
      this.Time_Out_ID_Penata = form.Time_Out_ID_Penata;
      this.Time_Out_Peralatan = form.Time_Out_Peralatan;
      this.Sign_In_Nama_Dokter = form.Sign_In_Nama_Dokter;
      this.Sign_In_Nama_Penata = form.Sign_In_Nama_Penata;
      this.Sign_In_TTD_Perawat = form.Sign_In_TTD_Perawat;
      this.Sign_Out_ID_Perawat = form.Sign_Out_ID_Perawat;
      this.Sign_Out_TTD_Dokter = form.Sign_Out_TTD_Dokter;
      this.Sign_Out_TTD_Penata = form.Sign_Out_TTD_Penata;
      this.Time_Out_Baca_Ulang = form.Time_Out_Baca_Ulang;
      this.Time_Out_ID_Perawat = form.Time_Out_ID_Perawat;
      this.Time_Out_Pendarahan = form.Time_Out_Pendarahan;
      this.Time_Out_TTD_Dokter = form.Time_Out_TTD_Dokter;
      this.Time_Out_TTD_Penata = form.Time_Out_TTD_Penata;
      this.Sign_In_Nama_Perawat = form.Sign_In_Nama_Perawat;
      this.Sign_Out_ID_Sirkuler = form.Sign_Out_ID_Sirkuler;
      this.Sign_Out_Nama_Dokter = form.Sign_Out_Nama_Dokter;
      this.Sign_Out_Nama_Penata = form.Sign_Out_Nama_Penata;
      this.Sign_Out_TTD_Perawat = form.Sign_Out_TTD_Perawat;
      this.Time_Out_Nama_Dokter = form.Time_Out_Nama_Dokter;
      this.Time_Out_Nama_Penata = form.Time_Out_Nama_Penata;
      this.Time_Out_TTD_Perawat = form.Time_Out_TTD_Perawat;
      this.Time_Out_Tidak_Rutin = form.Time_Out_Tidak_Rutin;
      this.Sign_Out_Nama_Perawat = form.Sign_Out_Nama_Perawat;
      this.Sign_Out_TTD_Sirkuler = form.Sign_Out_TTD_Sirkuler;
      this.Time_Out_Nama_Perawat = form.Time_Out_Nama_Perawat;
      this.Sign_In_Ruangan_Dokter = form.Sign_In_Ruangan_Dokter;
      this.Sign_In_Ruangan_Penata = form.Sign_In_Ruangan_Penata;
      this.Sign_Out_Nama_Sirkuler = form.Sign_Out_Nama_Sirkuler;
      this.Sign_Out_Nama_Tindakan = form.Sign_Out_Nama_Tindakan;
      this.Sign_Out_Ruangan_Bedah = form.Sign_Out_Ruangan_Bedah;
      this.Time_Out_Ruangan_Bedah = form.Time_Out_Ruangan_Bedah;
      this.Sign_In_Pulse_Oksimetri = form.Sign_In_Pulse_Oksimetri;
      this.Sign_In_Ruangan_Perawat = form.Sign_In_Ruangan_Perawat;
      this.Sign_Out_Catatan_Khusus = form.Sign_Out_Catatan_Khusus;
      this.Sign_Out_Ruangan_Dokter = form.Sign_Out_Ruangan_Dokter;
      this.Sign_Out_Ruangan_Penata = form.Sign_Out_Ruangan_Penata;
      this.Time_Out_Ruangan_Dokter = form.Time_Out_Ruangan_Dokter;
      this.Time_Out_Ruangan_Penata = form.Time_Out_Ruangan_Penata;
      this.Sign_Out_Ruangan_Perawat = form.Sign_Out_Ruangan_Perawat;
      this.Time_Out_Anestesi_Khusus = form.Time_Out_Anestesi_Khusus;
      this.Time_Out_Perkenalan_Diri = form.Time_Out_Perkenalan_Diri;
      this.Time_Out_Ruangan_Perawat = form.Time_Out_Ruangan_Perawat;
      this.Sign_Out_Kelengkapan_Alat = form.Sign_Out_Kelengkapan_Alat;
      this.Sign_Out_Masalah_Peralatan = form.Sign_Out_Masalah_Peralatan;
      this.Time_Out_Tidak_Rutin_Waktu = form.Time_Out_Tidak_Rutin_Waktu;
      this.Sign_Out_Pelabelan_Spesimen = form.Sign_Out_Pelabelan_Spesimen;
      this.Time_Out_Profilaksis_Antibiotik = form.Time_Out_Profilaksis_Antibiotik; 
    }
}

export interface ISafetyChecklist extends IDataModel {
    form: ISafetyChecklistForm;
}

export class SafetyChecklist extends DataModel {
    form: ISafetyChecklistForm;
    constructor(req: ISafetyChecklist) {
      super(req)
      this.form = req.form;
    }
}