import { DateTimeConverter } from "@src/shared/datetime-converter";
import { AppRequest, IAppRequest } from "@src/shared/request";

export interface IHaisSurveillanceInfectionFormRequest extends IAppRequest {
  ruangan_hais: string;
  tanggal_berobat: string;
  diagnosa_masuk: string;
  asal_masuk: string;
  vena_sentral_check: string;
  vena_perifer_check: string;
  lokasi_vs: string;
  mulai_vs: string;
  selesai_vs: string;
  total_hari_vs: string;
  tanggal_infeksi_vs: string;
  catatan_vs: string;
  lokasi_vp: string;
  mulai_vp: string;
  selesai_vp: string;
  total_hari_vp: string;
  tanggal_infeksi_vp: string;
  catatan_vp: string;
  tindakan_alkes_lain: string;
  lokasi_lain: string;
  mulai_lain: string;
  selesai_lain: string;
  total_hari_lain: string;
  tanggal_infeksi_lain: string;
  catatan_lain: string;
  hbs_ag: string;
  anti_hcv: string;
  anti_hiv: string;
  faktor_penyakit_lain: string;
  lab_leukocyt: string;
  lab_led: string;
  lab_lain: string;
  hasil_radiologi: string;
  merokok: string;
  steroid_jangka_panjang: string;
  mandi_sebelum_operasi: string;
  operasi_karena_trauma: string;
  obat_pengencer_darah: string;
  memakai_make_up: string;
  gula_darah: string
  suhu_pasien: string;
  infeksi_mata_check: string;
  infeksi_tht_check: string;
  infeksi_mulut_check: string;
  infeksi_paru_check: string;
  infeksi_kulit_check: string;
  infeksi_gi_check: string;
  infeksi_lainnya_check: string;
  infeksi_lainnya_text: string;
  penyakit_dm_check: string;
  penyakit_hipertensi_check: string;
  penyakit_ggk_check: string;
  penyakit_sepsis_check: string;
  riwayat_pasien_sekarang: string;
  jenis_operasi: string;
  asa_score: string;
  jenis_anestesi: string;
  operator_anestesi: string;
  kelembapan_udara: string;
  suhu_ruangan: string;
  komplikasi_saat_operasi: string;
  profilaksis: string;
  obat_profilaksis: string;
  antibiotik_tambahan: string;
  obat_antibiotik: string;
  dosis_antibiotik: string;
  jam_diberikan_antibiotik: string;
  probe_laser: string;
  tubing_vitrectomy: string;
  chlorhexidine_check: string;
  povidone_iodine_check: string;
  alkohol_70_check: string;
  jahitan: string;
  indikator_instrumen: string;
  sterilisasi_cssd: string;
  inisial_dr: string;
  asisten_op: string;
  urutan_op: string;
  implant: string;
  lama_op: string;
  ruang_operasi: string;
  klasifikasi_luka: string;
  prosedur_op: string;
  kualifikasi_dokter_bedah: string;
  jumlah_staf: string;
  diagnosa_akhir: string;
  tanggal_pasien_keluar: string;
  cara_pasien_keluar: string;
  nama_pindah_faskes: string;
  id_perawat: string;
  ttd_perawat: string;
  id_perawat_ipcn: string;
  ttd_perawat_ipcn: string;
}

export class HaisSurveillanceInfectionFormRequest extends AppRequest {
  ruangan_hais: string;
  tanggal_berobat: string;
  diagnosa_masuk: string;
  asal_masuk: string;
  vena_sentral_check: string;
  vena_perifer_check: string;
  lokasi_vs: string;
  mulai_vs: string;
  selesai_vs: string;
  total_hari_vs: string;
  tanggal_infeksi_vs: string;
  catatan_vs: string;
  lokasi_vp: string;
  mulai_vp: string;
  selesai_vp: string;
  total_hari_vp: string;
  tanggal_infeksi_vp: string;
  catatan_vp: string;
  tindakan_alkes_lain: string;
  lokasi_lain: string;
  mulai_lain: string;
  selesai_lain: string;
  total_hari_lain: string;
  tanggal_infeksi_lain: string;
  catatan_lain: string;
  hbs_ag: string;
  anti_hcv: string;
  anti_hiv: string;
  faktor_penyakit_lain: string;
  lab_leukocyt: string;
  lab_led: string;
  lab_lain: string;
  hasil_radiologi: string;
  merokok: string;
  steroid_jangka_panjang: string;
  mandi_sebelum_operasi: string;
  operasi_karena_trauma: string;
  obat_pengencer_darah: string;
  memakai_make_up: string;
  gula_darah: string
  suhu_pasien: string;
  infeksi_mata_check: string;
  infeksi_tht_check: string;
  infeksi_mulut_check: string;
  infeksi_paru_check: string;
  infeksi_kulit_check: string;
  infeksi_gi_check: string;
  infeksi_lainnya_check: string;
  infeksi_lainnya_text: string;
  penyakit_dm_check: string;
  penyakit_hipertensi_check: string;
  penyakit_ggk_check: string;
  penyakit_sepsis_check: string;
  riwayat_pasien_sekarang: string;
  jenis_operasi: string;
  asa_score: string;
  jenis_anestesi: string;
  operator_anestesi: string;
  kelembapan_udara: string;
  suhu_ruangan: string;
  komplikasi_saat_operasi: string;
  profilaksis: string;
  obat_profilaksis: string;
  antibiotik_tambahan: string;
  obat_antibiotik: string;
  dosis_antibiotik: string;
  jam_diberikan_antibiotik: string;
  probe_laser: string;
  tubing_vitrectomy: string;
  chlorhexidine_check: string;
  povidone_iodine_check: string;
  alkohol_70_check: string;
  jahitan: string;
  indikator_instrumen: string;
  sterilisasi_cssd: string;
  inisial_dr: string;
  asisten_op: string;
  urutan_op: string;
  implant: string;
  lama_op: string;
  ruang_operasi: string;
  klasifikasi_luka: string;
  prosedur_op: string;
  kualifikasi_dokter_bedah: string;
  jumlah_staf: string;
  diagnosa_akhir: string;
  tanggal_pasien_keluar: string;
  cara_pasien_keluar: string;
  nama_pindah_faskes: string;
  id_perawat: string;
  ttd_perawat: string;
  id_perawat_ipcn: string;
  ttd_perawat_ipcn: string;

  constructor(req: IHaisSurveillanceInfectionFormRequest) {
    super(req);
    this.ruangan_hais = req.ruangan_hais;
    this.tanggal_berobat = req.tanggal_berobat ? DateTimeConverter.convertToNormalDatetime(req.tanggal_berobat) : '';
    this.diagnosa_masuk = req.diagnosa_masuk;
    this.asal_masuk = req.asal_masuk;
    this.vena_sentral_check = req.vena_sentral_check;
    this.vena_perifer_check = req.vena_perifer_check;
    this.lokasi_vs = req.lokasi_vs;
    this.mulai_vs = req.mulai_vs ? DateTimeConverter.convertToNormalDatetime(req.mulai_vs) : '';
    this.selesai_vs = req.selesai_vs ? DateTimeConverter.convertToNormalDatetime(req.selesai_vs) : '';
    this.total_hari_vs = req.total_hari_vs;
    this.tanggal_infeksi_vs = req.tanggal_infeksi_vs ? DateTimeConverter.convertToNormalDatetime(req.tanggal_infeksi_vs) : '';
    this.catatan_vs = req.catatan_vs;
    this.lokasi_vp = req.lokasi_vp;
    this.mulai_vp = req.mulai_vp ? DateTimeConverter.convertToNormalDatetime(req.mulai_vp) : '';
    this.selesai_vp = req.selesai_vp ? DateTimeConverter.convertToNormalDatetime(req.selesai_vp) : '';
    this.total_hari_vp = req.total_hari_vp;
    this.tanggal_infeksi_vp = req.tanggal_infeksi_vp ? DateTimeConverter.convertToNormalDatetime(req.tanggal_infeksi_vp) : '';
    this.catatan_vp = req.catatan_vp;
    this.tindakan_alkes_lain = req.tindakan_alkes_lain;
    this.lokasi_lain = req.lokasi_lain;
    this.mulai_lain = req.mulai_lain ? DateTimeConverter.convertToNormalDatetime(req.mulai_lain) : '';
    this.selesai_lain = req.selesai_lain ? DateTimeConverter.convertToNormalDatetime(req.selesai_lain) : '';
    this.total_hari_lain = req.total_hari_lain;
    this.tanggal_infeksi_lain = req.tanggal_infeksi_lain ? DateTimeConverter.convertToNormalDatetime(req.tanggal_infeksi_lain) : '';
    this.catatan_lain = req.catatan_lain;
    this.hbs_ag = req.hbs_ag;
    this.anti_hcv = req.anti_hcv;
    this.anti_hiv = req.anti_hiv;
    this.faktor_penyakit_lain = req.faktor_penyakit_lain;
    this.lab_leukocyt = req.lab_leukocyt;
    this.lab_led = req.lab_led;
    this.lab_lain = req.lab_lain;
    this.hasil_radiologi = req.hasil_radiologi;
    this.merokok = req.merokok;
    this.steroid_jangka_panjang = req.steroid_jangka_panjang;
    this.mandi_sebelum_operasi = req.mandi_sebelum_operasi;
    this.operasi_karena_trauma = req.operasi_karena_trauma;
    this.obat_pengencer_darah = req.obat_pengencer_darah;
    this.memakai_make_up = req.memakai_make_up
    this.gula_darah = req.gula_darah;
    this.suhu_pasien = req.suhu_pasien;
    this.infeksi_mata_check = req.infeksi_mata_check;
    this.infeksi_tht_check = req.infeksi_tht_check;
    this.infeksi_mulut_check = req.infeksi_mulut_check;
    this.infeksi_paru_check = req.infeksi_paru_check;
    this.infeksi_kulit_check = req.infeksi_kulit_check;
    this.infeksi_gi_check = req.infeksi_gi_check;
    this.infeksi_lainnya_check = req.infeksi_lainnya_check;
    this.infeksi_lainnya_text = req.infeksi_lainnya_text;
    this.penyakit_dm_check = req.penyakit_dm_check;
    this.penyakit_hipertensi_check = req.penyakit_hipertensi_check;
    this.penyakit_ggk_check = req.penyakit_ggk_check;
    this.penyakit_sepsis_check = req.penyakit_sepsis_check;
    this.riwayat_pasien_sekarang = req.riwayat_pasien_sekarang;
    this.jenis_operasi = req.jenis_operasi;
    this.asa_score = req.asa_score;
    this.jenis_anestesi = req.jenis_anestesi;
    this.operator_anestesi = req.operator_anestesi;
    this.kelembapan_udara = req.kelembapan_udara;
    this.suhu_ruangan = req.suhu_ruangan;
    this.komplikasi_saat_operasi = req.komplikasi_saat_operasi;
    this.profilaksis = req.profilaksis;
    this.obat_profilaksis = req.obat_profilaksis;
    this.antibiotik_tambahan = req.antibiotik_tambahan;
    this.obat_antibiotik = req.obat_antibiotik;
    this.dosis_antibiotik = req.dosis_antibiotik;
    this.jam_diberikan_antibiotik = req.jam_diberikan_antibiotik;
    this.probe_laser = req.probe_laser;
    this.tubing_vitrectomy = req.tubing_vitrectomy;
    this.chlorhexidine_check = req.chlorhexidine_check;
    this.povidone_iodine_check = req.povidone_iodine_check;
    this.alkohol_70_check = req.alkohol_70_check;
    this.jahitan = req.jahitan;
    this.indikator_instrumen = req.indikator_instrumen;
    this.sterilisasi_cssd = req.sterilisasi_cssd;
    this.inisial_dr = req.inisial_dr;
    this.asisten_op = req.asisten_op;
    this.urutan_op = req.urutan_op;
    this.implant = req.implant;
    this.lama_op = req.lama_op;
    this.ruang_operasi = req.ruang_operasi;
    this.klasifikasi_luka = req.klasifikasi_luka;
    this.prosedur_op = req.prosedur_op;
    this.kualifikasi_dokter_bedah = req.kualifikasi_dokter_bedah;
    this.jumlah_staf = req.jumlah_staf;
    this.diagnosa_akhir = req.diagnosa_akhir;
    this.tanggal_pasien_keluar = req.tanggal_pasien_keluar ? DateTimeConverter.convertToNormalDatetime(req.tanggal_pasien_keluar) : '';
    this.cara_pasien_keluar = req.cara_pasien_keluar;
    this.nama_pindah_faskes = req.nama_pindah_faskes;
    this.id_perawat = req.id_perawat;
    this.ttd_perawat = req.ttd_perawat;
    this.id_perawat_ipcn = req.id_perawat_ipcn;
    this.ttd_perawat_ipcn = req.ttd_perawat_ipcn;
  }

  static createFromJson(json: IHaisSurveillanceInfectionFormRequest) {
    return new HaisSurveillanceInfectionFormRequest(json);
  }
}
