import { Circle, Watch } from 'react-feather';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faHospitalUser } from '@fortawesome/free-solid-svg-icons'

export default [
  {
    id: 'rawat-jalan',
    title: 'Rawat Jalan',
    icon: <FontAwesomeIcon icon={ faHospitalUser }/>,
    resource: 'EMR.RawatJalan',
    action: 'read',
    isTreatmentRequired: true,
    children: [
      {
        id: 'rawat-jalan-pengkajian-risiko-jatuh',
        title: 'Pengkajian Risiko Jatuh (Skala Up and Go)',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/risiko-jatuh',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-pengkajian-awal-keperawatan',
        title: 'Pengkajian Awal Keperawatan',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/pengkajian-awal',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-pengkajian-awal-dokter',
        title: 'Pengkajian Awal Dokter',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/pengkajian-awal-dokter',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-cppt',
        title: 'CPPT',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/cppt',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-resep-kacamata',
        title: 'Resep Kacamata',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/resep-kacamata',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-bukti-pelayanan-rawat-jalan',
        title: 'Bukti Pelayanan Rawat Jalan',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/bukti-pelayanan-rawat-jalan',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-inform-consent',
        title: 'Formulir Persetujuan Tindakan Kedokteran',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/inform-consent',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-lembar-konsultasi',
        title: 'Lembar Konsultasi',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/lembar-konsultasi',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-edukasi-harian',
        title: 'Edukasi Harian',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/edukasi-harian',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-penandaan-area-pembedahan',
        title: 'Formulir Penandaan Area Pembedahan',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/penandaan-area-pembedahan',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-catatan-keperawatan-peri-operatif',
        title: 'Catatan Keperawatan Peri Operatif (PRA OPERASI)',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/catatan-keperawatan-peri-operasi',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-checklist-pra-operasi',
        title: 'Checklist Pra Operasi',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/checklist-pra-operasi',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-patient-handover-form',
        title: 'Formulir Serah Terima Pasien',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/formulir-serah-terima-pasien',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-transfer-pasien',
        title: 'Transfer Pasien',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/transfer-pasien',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-hasil-pemeriksaan-biometri',
        title: 'Hasil Pemeriksaan Alat',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/hasil-pemeriksaan',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-tindakan-yag-laser-dan-laser-retina',
        title: 'Hasil Tindakan Laser',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/tindakan-yag-laser-dan-laser-retina',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
      {
        id: 'rawat-jalan-ringkasan-medis-rawat-jalan',
        title: 'Ringkasan Medis Rawat Jalan',
        icon: <Circle size={20} />,
        navLink: '/rawat-jalan/ringkasan-medis-rawat-jalan',
        resource: 'EMR.RawatJalan',
        action: 'read',
      },
    ],
  },
];
