import { Circle, Watch } from 'react-feather';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faHospitalUser } from '@fortawesome/free-solid-svg-icons'

export default [
  {
    id: 'rawat-inap',
    title: 'Rawat Inap',
    icon: <FontAwesomeIcon icon={ faHospitalUser }/>,
    resource: 'EMR.RawatInap',
    action: 'read',
    isTreatmentRequired: true,
    children: [
      {
        id: 'rawat-inap-general-consent',
        title: 'General Consent',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/general-consent',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'inform-consent',
        title: 'Formulir Persetujuan Tindakan Kedokteran',
        icon: <Circle size={20}/>,
        navLink: '/rawat-inap/inform-consent',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'pengkajian-early-warning-scoring-system',
        title: 'Pengkajian Nursing Early Warning Scoring System',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/pengkajian-early-warning-scoring-system',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'surat-perintah-rawat-inap',
        title: 'Surat Perintah Rawat Inap',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/surat-perintah-rawat-inap',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'rencana-pemulangan-pasien',
        title: 'Rencana Pemulangan Pasien',
        icon: <Circle size={20}/>,
        navLink: '/rawat-inap/rencana-pemulangan-pasien',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'transfer-pasien',
        title: 'Transfer Pasien',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/transfer-pasien',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'rawat-inap-pengkajian-awal-keperawatan',
        title: 'Pengkajian Awal Keperawatan',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/pengkajian-awal-keperawatan',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'rawat-inap-pengkajian-awal-keperawatan-anak',
        title: 'Pengkajian Awal Keperawatan Anak',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/pengkajian-awal-keperawatan-anak',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'rawat-inap-lembar-konsultasi',
        title: 'Lembar Konsultasi',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/lembar-konsultasi',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'lembar-dpjp',
        title: 'Lembar Dpjp',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/lembar-dpjp',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'catatan-medis-awal',
        title: 'Catatan Medis Awal',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/catatan-medis-awal',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'rawat-inap-cppt',
        title: 'CPPT',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/cppt',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'edukasi-terintegrasi',
        title: 'Edukasi Terintegrasi',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/edukasi-terintegrasi',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'rencana-asuhan-keperawatan',
        title: 'Rencana Asuhan Keperawatan',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/rencana-asuhan-keperawatan',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'pengkajian-risiko-jatuh-dewasa',
        title: 'Pengkajian Risiko Jatuh Dewasa (Skala Morse)',
        icon: <Circle size={20}/>,
        navLink: '/rawat-inap/pengkajian-risiko-jatuh-dewasa',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'pengkajian-resiko-jatuh-anak',
        title: 'Pengkajian Resiko Jatuh Anak',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/pengkajian-resiko-jatuh-anak',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'dokumentasi-pemberian-informasi-pasien-jatuh',
        title: 'Dokumentasi Pemberian Informasi Risiko Pasien Jatuh',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/dokumentasi-pemberian-informasi-pasien-jatuh',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'implementasi-pasien-resiko-jatuh',
        title: 'Implementasi Pasien Resiko Jatuh',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/implementasi-pasien-resiko-jatuh',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'monitoring-skala-nyeri',
        title: 'Formulir Monitoring Skala Nyeri',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/monitoring-skala-nyeri',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'asesmen-ulang-tanda-vital',
        title: 'Asesmen Ulang Tanda Vital',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/asesmen-ulang-tanda-vital',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'ringkasan-pasien-pulang-rawat-inap',
        title: 'Ringkasan Pasien Pulang Rawat Inap',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/ringkasan-pasien-pulang-rawat-inap',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'formulir-pra-anestesi',
        title: 'Formulir Pra Anestesi & Sedasi',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/formulir-pra-anestesi',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'formulir-surveilans-infeksi-hais',
        title: 'Formulir Surveilans Infeksi HAIs',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/formulir-surveilans-infeksi-hais',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'rawat-inap-patient-handover-form',
        title: 'Formulir Serah Terima Pasien',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/formulir-serah-terima-pasien',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      // {
      //   id: 'pengkajian-awal-gizi',
      //   title: 'Pengkajian Awal Gizi',
      //   icon: <Circle size={20}/>,
      //   navLink: '/rawat-inap/pengkajian-awal-gizi',
      //   resource: 'EMR.RawatInap',
      //   action: 'read',
      // },
      {
        id: 'asesmen-pra-operasi',
        title: 'Asesmen Pra Operasi',
        icon: <Circle size={20}/>,
        navLink: '/rawat-inap/asesmen-pra-operasi',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'penandaan-area-pembedahan',
        title: 'Formulir Penandaan Area Pembedahan',
        icon: <Circle size={20}/>,
        navLink: '/rawat-inap/penandaan-area-pembedahan',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'checklist-pra-operasi',
        title: 'Checklist Pra Operasi',
        icon: <Circle size={20}/>,
        navLink: '/rawat-inap/checklist-pra-operasi',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'catatan-keperawatan-pra-operatif',
        title: 'Catatan Keperawatan Peri Operatif (Pra-Operasi)',
        icon: <Circle size={20}/>,
        navLink: '/rawat-inap/catatan-keperawatan-pra-operatif',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
      {
        id: 'persetujuan-tindakan-anestesi',
        title: 'Persetujuan-Tindakan-Anestesi',
        icon: <Circle size={20} />,
        navLink: '/rawat-inap/persetujuan-tindakan-anestesi',
        resource: 'EMR.RawatInap',
        action: 'read',
      },
    ],
  },
];
