import citymapping from "@src/modules/outpatient/proof-of-outpatient-services/const/citymapping";
import { ITreatmentModel } from "@src/modules/site/patient-list/models";
import { DateTimeConverter } from "@src/shared/datetime-converter";
import { CreatePDFRequest, ICreatePDFRequest } from "@src/shared/pdf/requests/create-pdf.request";

export interface IPdfApprovalOrRefusalOfAnestheticActionRequest extends ICreatePDFRequest {
  data: {
    nomor_mr: string,
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string,
    'pasien.Jenis_Kelamin': string,
    'pasien.Alamat': string,
    dokter_pelaksana: string,
    pemberi_informasi: string,
    penerima_informasi: string,
    tanda_1: string,
    dasar_klinis: string,
    dasar_radiologi: string,
    dasar_ekg: string,
    dasar_laboratorium: string,
    tanda_2: string,
    tanda_3: string,
    '3_1_1': string,
    '3_1_2': string,
    '3_1_3': string,
    '3_1_4': string,
    '3_2_1': string,
    '3_2_2': string,
    '3_2_3': string,
    tanda_4: string,
    tanda_5: string,
    tata_cara_tindakan: string,
    '6_1': string,
    '6_2': string,
    '6_3': string,
    tanda_6: string,
    tujuan: string,
    tanda_7: string,
    tanda_8: string,
    '8_1_1': string,
    '8_1_2': string,
    '8_1_3': string,
    '8_1_4': string,
    '8_1_5': string,
    '8_1_6': string,
    '8_1_7': string,
    '8_1_8': string,
    '8_1_9': string,
    '8_1_10': string,
    '8_2_1': string,
    '8_2_2': string,
    '8_2_3': string,
    '8_2_4': string,
    '8_2_5': string,
    '8_2_6': string,
    '8_2_8': string,
    '8_2_9': string,
    '8_2_10': string,
    '8_2_11': string,
    '8_2_12': string,
    '8_2_13': string,
    prognosis: string,
    tanda_9: string,
    alternatif: string,
    tanda_10: string,
    lain_lain: string,
    tanda_11: string,
    ttd_dokter_pelaksana: string,
    nama_dokter_ttd: string,
    ttd_penerima_informasi: string,
    isPersetujuan: boolean,
    nama_pasien_atau_wali: string,
    ttl_pasien_atau_wali: string,
    jk_pasien_atau_wali: string,
    alamat_pasien_atau_wali: string,
    pasien_atau_wali: string,
    kota: string,
    tanggal_tandatangan: string,
    jam_tandatangan: string,
    ttd_pasien_wali: string,
    nama_pasien_wali: string,
    ttd_saksi_keluarga: string,
    // nama_saksi_keluarga: string,
    ttd_saksi_rs: string,
    nama_saksi_rs: string,
    isPenolakan: boolean,
    nik: string,
  }
}

export class PdfApprovalOrRefusalOfAnestheticActionRequest extends CreatePDFRequest {
  data: {
    nomor_mr: string,
    'pasien.Nama': string,
    'pasien.Tgl_Lahir': string,
    'pasien.Umur': string,
    'pasien.Jenis_Kelamin': string,
    'pasien.Alamat': string,
    dokter_pelaksana: string,
    pemberi_informasi: string,
    penerima_informasi: string,
    tanda_1: string,
    dasar_klinis: string,
    dasar_radiologi: string,
    dasar_ekg: string,
    dasar_laboratorium: string,
    tanda_2: string,
    tanda_3: string,
    '3_1_1': string,
    '3_1_2': string,
    '3_1_3': string,
    '3_1_4': string,
    '3_2_1': string,
    '3_2_2': string,
    '3_2_3': string,
    tanda_4: string,
    tanda_5: string,
    tata_cara_tindakan: string,
    '6_1': string,
    '6_2': string,
    '6_3': string,
    tanda_6: string,
    tujuan: string,
    tanda_7: string,
    tanda_8: string,
    '8_1_1': string,
    '8_1_2': string,
    '8_1_3': string,
    '8_1_4': string,
    '8_1_5': string,
    '8_1_6': string,
    '8_1_7': string,
    '8_1_8': string,
    '8_1_9': string,
    '8_1_10': string,
    '8_2_1': string,
    '8_2_2': string,
    '8_2_3': string,
    '8_2_4': string,
    '8_2_5': string,
    '8_2_6': string,
    '8_2_8': string,
    '8_2_9': string,
    '8_2_10': string,
    '8_2_11': string,
    '8_2_12': string,
    '8_2_13': string,
    prognosis: string,
    tanda_9: string,
    alternatif: string,
    tanda_10: string,
    lain_lain: string,
    tanda_11: string,
    ttd_dokter_pelaksana: string,
    nama_dokter_ttd: string,
    ttd_penerima_informasi: string,
    isPersetujuan: boolean,
    nama_pasien_atau_wali: string,
    ttl_pasien_atau_wali: string,
    jk_pasien_atau_wali: string,
    alamat_pasien_atau_wali: string,
    pasien_atau_wali: string,
    kota: string,
    tanggal_tandatangan: string,
    jam_tandatangan: string,
    ttd_pasien_wali: string,
    nama_pasien_wali: string,
    ttd_saksi_keluarga: string,
    // nama_saksi_keluarga: string,
    ttd_saksi_rs: string,
    nama_saksi_rs: string,
    isPenolakan: boolean,
    nik: string,
  }
  constructor(req: IPdfApprovalOrRefusalOfAnestheticActionRequest) {
    super(req);
    this.data = req.data;
  }

  static createFromJson(json: IPdfApprovalOrRefusalOfAnestheticActionRequest) {
    return new PdfApprovalOrRefusalOfAnestheticActionRequest(json);
  }

  static createPdfRequest(val: any, treatment: ITreatmentModel): PdfApprovalOrRefusalOfAnestheticActionRequest {
    const getCity = (companyCode: string) => {
      const selected = citymapping.find((item: any) => item.company_code === companyCode);
      if (selected) {
        return selected.city;
      } else {
        return '';
      }
    }
    return new PdfApprovalOrRefusalOfAnestheticActionRequest({
      emr_id: treatment.EMR_ID,
      form_name: 'rawat-inap_persetujuan-tindakan-anestesi',
      row_filter: '',
      preview: false,
      data: {
        nomor_mr: val?.nomor_mr ?? '',
        'pasien.Nama': val?.pasien?.Nama ?? '',
        'pasien.Tgl_Lahir': DateTimeConverter.convertToNormalDate(val?.pasien?.Tgl_Lahir),
        'pasien.Umur': this.normalizeAge(val?.umur_lengkap),
        'pasien.Jenis_Kelamin': val?.pasien?.Jenis_Kelamin ?? '',
        'pasien.Alamat': val?.pasien?.Alamat ?? '',
        dokter_pelaksana: val?.form?.Nama_Dokter_Pelaksana ?? '',
        pemberi_informasi: val?.form?.Nama_Pemberi_Informasi ?? '',
        penerima_informasi: val?.form?.Penerima_Informasi && val?.form?.Penerima_Informasi === 'Pasien' ? treatment.Pasien.Nama : val?.form?.Penerima_Informasi && val?.form?.Penerima_Informasi === 'Wali' ? val?.form?.Nama_Wali : '',
        tanda_1: PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Diagnosis_Check === '1'),
        dasar_klinis: val?.form?.Dasar_Klinis ?? 'harun',
        dasar_radiologi: val?.form?.Dasar_Radiologi ?? '',
        dasar_ekg: val?.form?.Dasar_EKG ?? '',
        dasar_laboratorium: val?.form?.Dasar_Laboratorium ?? '',
        tanda_2: PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Dasar_Diagnosis_Check === '1'),
        tanda_3: PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Tindakan_Kedokteran_Check === '1'),
        '3_1_1': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Anestesi_Umum_Intubasi_Check === '1'),
        '3_1_2': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Anestesi_Umum_LMA_Check === '1'),
        '3_1_3': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Anestesi_Umum_FM_Check === '1'),
        '3_1_4': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Anestesi_Umum_TIVA_Check === '1'),
        '3_2_1': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Anestesi_Regional_Spinal_Check === '1'),
        '3_2_2': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Anestesi_Regional_Epidural_Check === '1'),
        '3_2_3': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Anestesi_Regional_Perifer_Check === '1'),
        tanda_4: PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Indikasi_Tindakan_Tujuan_Check === '1'),
        tanda_5: PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Tata_Cara_Tindakan_Check === '1'),
        tata_cara_tindakan: val?.form?.Tata_Cara_Tindakan ?? '',
        '6_1': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Shock_Check === '1'),
        '6_2': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Henti_Jantung_Check === '1'),
        '6_3': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Meninggal_Check === '1'),
        tanda_6: PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Risiko_Check === '1'),
        tujuan: val?.form?.Tujuan ?? '',
        tanda_7: PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Tujuan_Check === '1'),
        tanda_8: PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Check === '1'),
        '8_1_1': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Umum_1 === '1'),
        '8_1_2': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Umum_2 === '1'),
        '8_1_3': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Umum_3 === '1'),
        '8_1_4': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Umum_4 === '1'),
        '8_1_5': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Umum_5 === '1'),
        '8_1_6': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Umum_6 === '1'),
        '8_1_7': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Umum_7 === '1'),
        '8_1_8': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Umum_8 === '1'),
        '8_1_9': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Umum_9 === '1'),
        '8_1_10': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Umum_10 === '1'),
        '8_2_1': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Regional_1 === '1'),
        '8_2_2': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Regional_2 === '1'),
        '8_2_3': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Regional_3 === '1'),
        '8_2_4': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Regional_4 === '1'),
        '8_2_5': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Regional_5 === '1'),
        '8_2_6': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Regional_6 === '1'),
        '8_2_8': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Regional_7 === '1'),
        '8_2_9': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Regional_8 === '1'),
        '8_2_10': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Regional_9 === '1'),
        '8_2_11': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Regional_10 === '1'),
        '8_2_12': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Regional_11 === '1'),
        '8_2_13': PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Komplikasi_Regional_12 === '1'),
        prognosis: val?.form?.Prognosis ?? '',
        tanda_9: PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Prognosis_Check === '1'),
        alternatif: val?.form?.Alternatif_Tindakan ?? '',
        tanda_10: PdfApprovalOrRefusalOfAnestheticActionRequest?.getCheckImage(val?.form?.Alternatif_Tindakan_Check === '1'),
        lain_lain: val?.form?.Lain_Lain ?? '',
        tanda_11: PdfApprovalOrRefusalOfAnestheticActionRequest.getCheckImage(val?.form?.Lain_Lain_Check === '1'),
        ttd_dokter_pelaksana: val?.form?.TTD_Dokter_Pelaksana && val?.form?.TTD_Dokter_Pelaksana !== '' ? val?.form?.TTD_Dokter_Pelaksana : 'https://bucket.rsmatasmec.com/gambar_putih_ttd.jpeg',
        nama_dokter_ttd: (val?.form?.Nama_Dokter_Pelaksana_TTD !== '') ? val?.form?.Nama_Dokter_Pelaksana_TTD : undefined,
        ttd_penerima_informasi: val?.form?.TTD_Penerima_Informasi && val?.form?.TTD_Penerima_Informasi !== '' ? val?.form?.TTD_Penerima_Informasi : 'https://bucket.rsmatasmec.com/gambar_putih_ttd.jpeg',
        isPersetujuan: !!(val?.form?.Pernyataan_Id && val?.form?.Pernyataan_Id === '1'),
        nama_pasien_atau_wali: val?.form?.Tanda_Tangan_Nama ? val?.form?.Tanda_Tangan_Nama.toUpperCase() : '',
        ttl_pasien_atau_wali: DateTimeConverter.convertToNormalDate(val?.form?.Tanda_Tangan_Tgl_Lahir),
        jk_pasien_atau_wali: val?.form?.Tanda_Tangan_JK ?? '',
        alamat_pasien_atau_wali: val?.form?.Tanda_Tangan_Alamat ?? '',
        pasien_atau_wali: val?.form?.Tanda_Tangan && val?.form?.Tanda_Tangan === 'Pasien' ? 'saya' : val?.form?.Tanda_Tangan && val?.form?.Tanda_Tangan === 'Wali' && val?.form?.Tanda_Tangan_Hubungan ? `${val?.form?.Tanda_Tangan_Hubungan} saya` : '',
        kota: getCity(treatment.Kode_Cabang),
        tanggal_tandatangan: DateTimeConverter.convertToNormalDate(val?.form?.Pasien_Tanggal && val?.form?.Pasien_Tanggal !== '' ? val?.form?.Pasien_Tanggal.substring(0, 10) : ''),
        jam_tandatangan: val?.form?.Pasien_Tanggal && val?.form?.Pasien_Tanggal !== '' ? val?.form?.Pasien_Tanggal.substring(11, 16) : '',
        ttd_pasien_wali: val?.form?.Tanda_Tangan_Pasien && val?.form?.Tanda_Tangan_Pasien !== '' ? val?.form?.Tanda_Tangan_Pasien : 'https://bucket.rsmatasmec.com/gambar_putih_ttd.jpeg',
        nama_pasien_wali: val?.form?.Tanda_Tangan && val?.form?.Tanda_Tangan === 'Pasien' ? 'Pasien' : val?.form?.Tanda_Tangan && val?.form?.Tanda_Tangan === 'Wali' ? 'Keluarga/Wali' : '',
        ttd_saksi_keluarga: val?.form?.Tanda_Tangan_Saksi_2 && val?.form?.Tanda_Tangan_Saksi_2 !== '' ? val?.form.Tanda_Tangan_Saksi_2 : 'https://bucket.rsmatasmec.com/gambar_putih_ttd.jpeg',
        // nama_saksi_keluarga:
        ttd_saksi_rs: val?.form?.Tanda_Tangan_Saksi && val?.form?.Tanda_Tangan_Saksi !== '' ? val?.form?.Tanda_Tangan_Saksi : 'https://bucket.rsmatasmec.com/gambar_putih_ttd.jpeg',
        nama_saksi_rs: (val?.form?.Nama_Saksi !== '') ? val?.form?.Nama_Saksi : undefined,
        isPenolakan: !!(val?.form?.Pernyataan_Id && val?.form?.Pernyataan_Id === '0'),
        nik: val?.pasien?.NIK ?? '',
      },
    })
  }
}
