import { IDataModel, DataModel } from "@src/shared/model";

export interface IAktual {
    Masalah_Aktual_Teks: string;
    Time_Masalah_Aktual: string;
    Masalah_Aktual_Tindakan_Teks: string;
    Masalah_Aktual_Instruksi_Teks: string;
}

export class Aktual  {
    Masalah_Aktual_Teks: string;
    Time_Masalah_Aktual: string;
    Masalah_Aktual_Tindakan_Teks: string;
    Masalah_Aktual_Instruksi_Teks: string;
    constructor(res: IAktual) {
      this.Masalah_Aktual_Teks = res.Masalah_Aktual_Teks;
      this.Time_Masalah_Aktual = res.Time_Masalah_Aktual;
      this.Masalah_Aktual_Tindakan_Teks = res.Masalah_Aktual_Tindakan_Teks;
      this.Masalah_Aktual_Instruksi_Teks = res.Masalah_Aktual_Instruksi_Teks;
    }

    static createFromModel(json: IAktual) {
      return {
        masalah_aktual_teks: json.Masalah_Aktual_Teks ?? '',
        time_masalah_aktual: json.Time_Masalah_Aktual ?? '',
        masalah_aktual_tindakan_teks: json.Masalah_Aktual_Tindakan_Teks ?? '',
        masalah_aktual_instruksi: json.Masalah_Aktual_Instruksi_Teks ?? '',
      }
    }
}

export interface ICatatanKeperawatanPascaForm {
    Skor: number;
    Tanggal_Pasca_Operasi: string;
    LA_GA: string;
    Aktual: Array<IAktual>;
    Sirkulasi: number;
    Transport: number;
    ID_Perawat: string;
    ID_Petugas: string;
    Pernafasan: number;
    Updated_At: string;
    Updated_By: string;
    Jalan_Nafas: number;
    Rawat_Pasca: number;
    TTD_Perawat: string;
    Keadaan_Umum: number;
    Nama_Perawat: string;
    Nama_Petugas: string;
    Posisi_Pasien: number;
    Grid_Chart_Img: string;
    Skala_Anestesi: string;
    Terapi_Oksigen: number;
    Time_Out_Waktu: string;
    Time_Spo_Masuk: string;
    Time_Urine_Dua: string;
    Grid_Chart_Data: string;
    Time_Spo_Keluar: string;
    Time_Urine_Satu: string;
    Time_Urine_Tiga: string;
    Time_Urine_Empat: string;
    Time_Urine_Total: string;
    Aldrette_Saturasi: number;
    ID_Perawat_Dokter: string;
    Kulit_Datang_Biru: number;
    Kulit_Datang_Lain: number;
    Kulit_Keluar_Biru: number;
    Kulit_Keluar_Lain: number;
    Steward_Kesadaran: number;
    Tingkat_Kesadaran: number;
    Aldrette_Aktivitas: number;
    Aldrette_Kesadaran: number;
    Aldrette_Sirkulasi: number;
    Steward_Pergerakan: number;
    Steward_Pernafasan: number;
    Time_Perawat_Ruang: string;
    Aldrette_Pernafasan: number;
    Kulit_Datang_Dingin: number;
    Kulit_Datang_Hangat: number;
    Kulit_Datang_Kering: number;
    Kulit_Datang_Lembab: number;
    Kulit_Keluar_Dingin: number;
    Kulit_Keluar_Hangat: number;
    Kulit_Keluar_Kering: number;
    Kulit_Keluar_Lembab: number;
    Nama_Perawat_Dokter: string;
    Check_Time_Spo_Masuk: number;
    Check_Time_Urine_Dua: number;
    Time_Nadi_Kuat_Masuk: string;
    Check_Time_Spo_Keluar: number;
    Check_Time_Urine_Satu: number;
    Check_Time_Urine_Tiga: number;
    Time_Nadi_Kuat_Keluar: string;
    Time_Nadi_Lemah_Masuk: string;
    Check_Time_Urine_Empat: number;
    Kulit_Datang_Lain_Teks: string;
    Kulit_Keluar_Lain_Teks: string;
    Time_Nadi_Lemah_Keluar: string;
    Time_Napas_Dalam_Masuk: string;
    Time_Napas_Sukar_Masuk: string;
    Time_Pemberitahu_Ruang: string;
    Kulit_Datang_Merah_Muda: number;
    Kulit_Keluar_Merah_Muda: number;
    Posisi_Pasien_Lain_Teks: string;
    Time_Nadi_Teratur_Masuk: string;
    Time_Napas_Dalam_Keluar: string;
    Time_Napas_Sukar_Keluar: string;
    Time_Napas_Terapi_Masuk: string;
    Terapi_Oksigen_Lain_Teks: string;
    Time_Nadi_Teratur_Keluar: string;
    Time_Napas_Dangkal_Masuk: string;
    Time_Napas_Terapi_Keluar: string;
    Time_Napas_Teratur_Masuk: string;
    Time_Napas_Dangkal_Keluar: string;
    Time_Napas_Teratur_Keluar: string;
    Check_Time_Nadi_Kuat_Masuk: number;
    Check_Time_Nadi_Kuat_Keluar: number;
    Check_Time_Nadi_Lemah_Masuk: number;
    Check_Time_Nadi_Lemah_Keluar: number;
    Check_Time_Napas_Dalam_Masuk: number;
    Check_Time_Napas_Sukar_Masuk: number;
    Time_Nadi_Tidakteratur_Masuk: string;
    Check_Time_Nadi_Teratur_Masuk: number;
    Check_Time_Napas_Dalam_Keluar: number;
    Check_Time_Napas_Sukar_Keluar: number;
    Check_Time_Napas_Terapi_Masuk: number;
    Time_Nadi_Tidakteratur_Keluar: string;
    Time_Napas_Tidakteratur_Masuk: string;
    Check_Time_Nadi_Teratur_Keluar: number;
    Check_Time_Napas_Dangkal_Masuk: number;
    Check_Time_Napas_Terapi_Keluar: number;
    Check_Time_Napas_Teratur_Masuk: number;
    Time_Napas_Tidakteratur_Keluar: string;
    Check_Time_Napas_Dangkal_Keluar: number;
    Check_Time_Napas_Teratur_Keluar: number;
    Check_Time_Nadi_Tidakteratur_Masuk: number;
    Check_Time_Nadi_Tidakteratur_Keluar: number;
    Check_Time_Napas_Tidakteratur_Masuk: number;
    Check_Time_Napas_Tidakteratur_Keluar: number;
}

export class CatatanKeperawatanPascaForm {
    Skor: number;
    Tanggal_Pasca_Operasi: string;
    LA_GA: string;
    Aktual: Array<IAktual>;
    Sirkulasi: number;
    Transport: number;
    ID_Perawat: string;
    ID_Petugas: string;
    Pernafasan: number;
    Updated_At: string;
    Updated_By: string;
    Jalan_Nafas: number;
    Rawat_Pasca: number;
    TTD_Perawat: string;
    Keadaan_Umum: number;
    Nama_Perawat: string;
    Nama_Petugas: string;
    Posisi_Pasien: number;
    Grid_Chart_Img: string;
    Skala_Anestesi: string;
    Terapi_Oksigen: number;
    Time_Out_Waktu: string;
    Time_Spo_Masuk: string;
    Time_Urine_Dua: string;
    Grid_Chart_Data: string;
    Time_Spo_Keluar: string;
    Time_Urine_Satu: string;
    Time_Urine_Tiga: string;
    Time_Urine_Empat: string;
    Time_Urine_Total: string;
    Aldrette_Saturasi: number;
    ID_Perawat_Dokter: string;
    Kulit_Datang_Biru: number;
    Kulit_Datang_Lain: number;
    Kulit_Keluar_Biru: number;
    Kulit_Keluar_Lain: number;
    Steward_Kesadaran: number;
    Tingkat_Kesadaran: number;
    Aldrette_Aktivitas: number;
    Aldrette_Kesadaran: number;
    Aldrette_Sirkulasi: number;
    Steward_Pergerakan: number;
    Steward_Pernafasan: number;
    Time_Perawat_Ruang: string;
    Aldrette_Pernafasan: number;
    Kulit_Datang_Dingin: number;
    Kulit_Datang_Hangat: number;
    Kulit_Datang_Kering: number;
    Kulit_Datang_Lembab: number;
    Kulit_Keluar_Dingin: number;
    Kulit_Keluar_Hangat: number;
    Kulit_Keluar_Kering: number;
    Kulit_Keluar_Lembab: number;
    Nama_Perawat_Dokter: string;
    Check_Time_Spo_Masuk: number;
    Check_Time_Urine_Dua: number;
    Time_Nadi_Kuat_Masuk: string;
    Check_Time_Spo_Keluar: number;
    Check_Time_Urine_Satu: number;
    Check_Time_Urine_Tiga: number;
    Time_Nadi_Kuat_Keluar: string;
    Time_Nadi_Lemah_Masuk: string;
    Check_Time_Urine_Empat: number;
    Kulit_Datang_Lain_Teks: string;
    Kulit_Keluar_Lain_Teks: string;
    Time_Nadi_Lemah_Keluar: string;
    Time_Napas_Dalam_Masuk: string;
    Time_Napas_Sukar_Masuk: string;
    Time_Pemberitahu_Ruang: string;
    Kulit_Datang_Merah_Muda: number;
    Kulit_Keluar_Merah_Muda: number;
    Posisi_Pasien_Lain_Teks: string;
    Time_Nadi_Teratur_Masuk: string;
    Time_Napas_Dalam_Keluar: string;
    Time_Napas_Sukar_Keluar: string;
    Time_Napas_Terapi_Masuk: string;
    Terapi_Oksigen_Lain_Teks: string;
    Time_Nadi_Teratur_Keluar: string;
    Time_Napas_Dangkal_Masuk: string;
    Time_Napas_Terapi_Keluar: string;
    Time_Napas_Teratur_Masuk: string;
    Time_Napas_Dangkal_Keluar: string;
    Time_Napas_Teratur_Keluar: string;
    Check_Time_Nadi_Kuat_Masuk: number;
    Check_Time_Nadi_Kuat_Keluar: number;
    Check_Time_Nadi_Lemah_Masuk: number;
    Check_Time_Nadi_Lemah_Keluar: number;
    Check_Time_Napas_Dalam_Masuk: number;
    Check_Time_Napas_Sukar_Masuk: number;
    Time_Nadi_Tidakteratur_Masuk: string;
    Check_Time_Nadi_Teratur_Masuk: number;
    Check_Time_Napas_Dalam_Keluar: number;
    Check_Time_Napas_Sukar_Keluar: number;
    Check_Time_Napas_Terapi_Masuk: number;
    Time_Nadi_Tidakteratur_Keluar: string;
    Time_Napas_Tidakteratur_Masuk: string;
    Check_Time_Nadi_Teratur_Keluar: number;
    Check_Time_Napas_Dangkal_Masuk: number;
    Check_Time_Napas_Terapi_Keluar: number;
    Check_Time_Napas_Teratur_Masuk: number;
    Time_Napas_Tidakteratur_Keluar: string;
    Check_Time_Napas_Dangkal_Keluar: number;
    Check_Time_Napas_Teratur_Keluar: number;
    Check_Time_Nadi_Tidakteratur_Masuk: number;
    Check_Time_Nadi_Tidakteratur_Keluar: number;
    Check_Time_Napas_Tidakteratur_Masuk: number;
    Check_Time_Napas_Tidakteratur_Keluar: number;

    constructor(request: ICatatanKeperawatanPascaForm) {
      this.Skor = request.Skor;
      this.Tanggal_Pasca_Operasi = request.Tanggal_Pasca_Operasi;
      this.LA_GA = request.LA_GA;
      this.Aktual = request.Aktual;
      this.Sirkulasi = request.Sirkulasi;
      this.Transport = request.Transport;
      this.ID_Perawat = request.ID_Perawat;
      this.ID_Petugas = request.ID_Petugas;
      this.Pernafasan = request.Pernafasan;
      this.Updated_At = request.Updated_At;
      this.Updated_By = request.Updated_By;
      this.Jalan_Nafas = request.Jalan_Nafas;
      this.Rawat_Pasca = request.Rawat_Pasca;
      this.TTD_Perawat = request.TTD_Perawat;
      this.Keadaan_Umum = request.Keadaan_Umum;
      this.Nama_Perawat = request.Nama_Perawat;
      this.Nama_Petugas = request.Nama_Petugas;
      this.Posisi_Pasien = request.Posisi_Pasien;
      this.Grid_Chart_Img = request.Grid_Chart_Img;
      this.Skala_Anestesi = request.Skala_Anestesi;
      this.Terapi_Oksigen = request.Terapi_Oksigen;
      this.Time_Out_Waktu = request.Time_Out_Waktu;
      this.Time_Spo_Masuk = request.Time_Spo_Masuk;
      this.Time_Urine_Dua = request.Time_Urine_Dua;
      this.Grid_Chart_Data = request.Grid_Chart_Data;
      this.Time_Spo_Keluar = request.Time_Spo_Keluar;
      this.Time_Urine_Satu = request.Time_Urine_Satu;
      this.Time_Urine_Tiga = request.Time_Urine_Tiga;
      this.Time_Urine_Empat = request.Time_Urine_Empat;
      this.Time_Urine_Total = request.Time_Urine_Total;
      this.Aldrette_Saturasi = request.Aldrette_Saturasi;
      this.ID_Perawat_Dokter = request.ID_Perawat_Dokter;
      this.Kulit_Datang_Biru = request.Kulit_Datang_Biru;
      this.Kulit_Datang_Lain = request.Kulit_Datang_Lain;
      this.Kulit_Keluar_Biru = request.Kulit_Keluar_Biru;
      this.Kulit_Keluar_Lain = request.Kulit_Keluar_Lain;
      this.Steward_Kesadaran = request.Steward_Kesadaran;
      this.Tingkat_Kesadaran = request.Tingkat_Kesadaran;
      this.Aldrette_Aktivitas = request.Aldrette_Aktivitas;
      this.Aldrette_Kesadaran = request.Aldrette_Kesadaran;
      this.Aldrette_Sirkulasi = request.Aldrette_Sirkulasi;
      this.Steward_Pergerakan = request.Steward_Pergerakan;
      this.Steward_Pernafasan = request.Steward_Pernafasan;
      this.Time_Perawat_Ruang = request.Time_Perawat_Ruang;
      this.Aldrette_Pernafasan = request.Aldrette_Pernafasan;
      this.Kulit_Datang_Dingin = request.Kulit_Datang_Dingin;
      this.Kulit_Datang_Hangat = request.Kulit_Datang_Hangat;
      this.Kulit_Datang_Kering = request.Kulit_Datang_Kering;
      this.Kulit_Datang_Lembab = request.Kulit_Datang_Lembab;
      this.Kulit_Keluar_Dingin = request.Kulit_Keluar_Dingin;
      this.Kulit_Keluar_Hangat = request.Kulit_Keluar_Hangat;
      this.Kulit_Keluar_Kering = request.Kulit_Keluar_Kering;
      this.Kulit_Keluar_Lembab = request.Kulit_Keluar_Lembab;
      this.Nama_Perawat_Dokter = request.Nama_Perawat_Dokter;
      this.Check_Time_Spo_Masuk = request.Check_Time_Spo_Masuk;
      this.Check_Time_Urine_Dua = request.Check_Time_Urine_Dua;
      this.Time_Nadi_Kuat_Masuk = request.Time_Nadi_Kuat_Masuk;
      this.Check_Time_Spo_Keluar = request.Check_Time_Spo_Keluar;
      this.Check_Time_Urine_Satu = request.Check_Time_Urine_Satu;
      this.Check_Time_Urine_Tiga = request.Check_Time_Urine_Tiga;
      this.Time_Nadi_Kuat_Keluar = request.Time_Nadi_Kuat_Keluar;
      this.Time_Nadi_Lemah_Masuk = request.Time_Nadi_Lemah_Masuk;
      this.Check_Time_Urine_Empat = request.Check_Time_Urine_Empat;
      this.Kulit_Datang_Lain_Teks = request.Kulit_Datang_Lain_Teks;
      this.Kulit_Keluar_Lain_Teks = request.Kulit_Keluar_Lain_Teks;
      this.Time_Nadi_Lemah_Keluar = request.Time_Nadi_Lemah_Keluar;
      this.Time_Napas_Dalam_Masuk = request.Time_Napas_Dalam_Masuk;
      this.Time_Napas_Sukar_Masuk = request.Time_Napas_Sukar_Masuk;
      this.Time_Pemberitahu_Ruang = request.Time_Pemberitahu_Ruang;
      this.Kulit_Datang_Merah_Muda = request.Kulit_Datang_Merah_Muda;
      this.Kulit_Keluar_Merah_Muda = request.Kulit_Keluar_Merah_Muda;
      this.Posisi_Pasien_Lain_Teks = request.Posisi_Pasien_Lain_Teks;
      this.Time_Nadi_Teratur_Masuk = request.Time_Nadi_Teratur_Masuk;
      this.Time_Napas_Dalam_Keluar = request.Time_Napas_Dalam_Keluar;
      this.Time_Napas_Sukar_Keluar = request.Time_Napas_Sukar_Keluar;
      this.Time_Napas_Terapi_Masuk = request.Time_Napas_Terapi_Masuk;
      this.Terapi_Oksigen_Lain_Teks = request.Terapi_Oksigen_Lain_Teks;
      this.Time_Nadi_Teratur_Keluar = request.Time_Nadi_Teratur_Keluar;
      this.Time_Napas_Dangkal_Masuk = request.Time_Napas_Dangkal_Masuk;
      this.Time_Napas_Terapi_Keluar = request.Time_Napas_Terapi_Keluar;
      this.Time_Napas_Teratur_Masuk = request.Time_Napas_Teratur_Masuk;
      this.Time_Napas_Dangkal_Keluar = request.Time_Napas_Dangkal_Keluar;
      this.Time_Napas_Teratur_Keluar = request.Time_Napas_Teratur_Keluar;
      this.Check_Time_Nadi_Kuat_Masuk = request.Check_Time_Nadi_Kuat_Masuk;
      this.Check_Time_Nadi_Kuat_Keluar = request.Check_Time_Nadi_Kuat_Keluar;
      this.Check_Time_Nadi_Lemah_Masuk = request.Check_Time_Nadi_Lemah_Masuk;
      this.Check_Time_Nadi_Lemah_Keluar = request.Check_Time_Nadi_Lemah_Keluar;
      this.Check_Time_Napas_Dalam_Masuk = request.Check_Time_Napas_Dalam_Masuk;
      this.Check_Time_Napas_Sukar_Masuk = request.Check_Time_Napas_Sukar_Masuk;
      this.Time_Nadi_Tidakteratur_Masuk = request.Time_Nadi_Tidakteratur_Masuk;
      this.Check_Time_Nadi_Teratur_Masuk = request.Check_Time_Nadi_Teratur_Masuk;
      this.Check_Time_Napas_Dalam_Keluar = request.Check_Time_Napas_Dalam_Keluar;
      this.Check_Time_Napas_Sukar_Keluar = request.Check_Time_Napas_Sukar_Keluar;
      this.Check_Time_Napas_Terapi_Masuk = request.Check_Time_Napas_Terapi_Masuk;
      this.Time_Nadi_Tidakteratur_Keluar = request.Time_Nadi_Tidakteratur_Keluar;
      this.Time_Napas_Tidakteratur_Masuk = request.Time_Napas_Tidakteratur_Masuk;
      this.Check_Time_Nadi_Teratur_Keluar = request.Check_Time_Nadi_Teratur_Keluar;
      this.Check_Time_Napas_Dangkal_Masuk = request.Check_Time_Napas_Dangkal_Masuk;
      this.Check_Time_Napas_Terapi_Keluar = request.Check_Time_Napas_Terapi_Keluar;
      this.Check_Time_Napas_Teratur_Masuk = request.Check_Time_Napas_Teratur_Masuk;
      this.Time_Napas_Tidakteratur_Keluar = request.Time_Napas_Tidakteratur_Keluar;
      this.Check_Time_Napas_Dangkal_Keluar = request.Check_Time_Napas_Dangkal_Keluar;
      this.Check_Time_Napas_Teratur_Keluar = request.Check_Time_Napas_Teratur_Keluar;
      this.Check_Time_Nadi_Tidakteratur_Masuk = request.Check_Time_Nadi_Tidakteratur_Masuk;
      this.Check_Time_Nadi_Tidakteratur_Keluar = request.Check_Time_Nadi_Tidakteratur_Keluar;
      this.Check_Time_Napas_Tidakteratur_Masuk = request.Check_Time_Napas_Tidakteratur_Masuk;
      this.Check_Time_Napas_Tidakteratur_Keluar = request.Check_Time_Napas_Tidakteratur_Keluar;
    }
}

// export interface ICatatanKeperawatanPascaModel extends IDataModel{
//     formCatatanPasca: ICatatanKeperawatanPascaForm;
//   }

// export class CatatanKeperawatanPascaModel extends DataModel {
//     formCatatanPasca: ICatatanKeperawatanPascaForm;

//     constructor(request: ICatatanKeperawatanPascaModel) {
//       super(request);
//       this.formCatatanPasca = request.formCatatanPasca;
//     }
// }