import { IDataModel, DataModel } from "@src/shared/model";

export interface IDiagnosaIntraOperatifForm {
    Waktu: string;
    ID_Petugas: string;
    Updated_At: string;
    Updated_By: string;
    Nama_Dokter: string;
    Nama_Petugas: string;
    ID_Perawat_Nyeri: string;
    TTD_Perawat_Nyeri: string;
    ID_Perawat_Infeksi: string;
    Nama_Perawat_Nyeri: string;
    Nyeri_Diagnosa_Luka: number;
    TTD_Perawat_Infeksi: string;
    ID_Perawat_Kecemasan: string;
    Nama_Perawat_Infeksi: string;
    Nyeri_Evaluasi_Teknik: number;
    TTD_Perawat_Kecemasan: string;
    Tanggal_Perawat_Nyeri: string;
    ID_Perawat_Penglihatan: string;
    Nama_Perawat_Kecemasan: string;
    Infeksi_Diagnosa_Trauma: number;
    TTD_Perawat_Penglihatan: string;
    Tanggal_Perawat_Infeksi: string;
    ID_Perawat_Tinggi_Cedera: string;
    Nama_Perawat_Penglihatan: string;
    Nyeri_Evaluasi_Berkurang: number;
    Kecemasan_Evaluasi_Tenang: number;
    TTD_Perawat_Tinggi_Cedera: string;
    Tanggal_Perawat_Kecemasan: string;
    Infeksi_Diagnosa_Peralatan: number;
    Infeksi_Intervensi_Penutup: number;
    Nama_Perawat_Tinggi_Cedera: string;
    Infeksi_Diagnosa_Lingkungan: number;
    Kecemasan_Diagnosa_Prosedur: number;
    Nyeri_Intervensi_Kolaborasi: number;
    Tanggal_Perawat_Penglihatan: string;
    ID_Perawat_Kekurangan_Cairan: string;
    Infeksi_Evaluasi_Pertahankan: number;
    Kecemasan_Evaluasi_Berkurang: number;
    Nyeri_Intervensi_Skala_Nyeri: number;
    Infeksi_Intervensi_Disinfeksi: number;
    Infeksi_Intervensi_Kadaluarsa: number;
    Infeksi_Intervensi_Sterilitas: number;
    Kecemasan_Intervensi_Gambaran: number;
    TTD_Perawat_Kekurangan_Cairan: string;
    Tanggal_Perawat_Tinggi_Cedera: string;
    Tinggi_Cedera_Evaluasi_Jumlah: number;
    Tinggi_Cedera_Evaluasi_Posisi: number;
    ID_Perawat_Gangguan_Pola_Nafas: string;
    Infeksi_Intervensi_Cuci_Tangan: number;
    Kecemasan_Intervensi_Informasi: number;
    Kekurangan_Cairan_Evaluasi_TTV: number;
    Nama_Perawat_Kekurangan_Cairan: string;
    Nyeri_Diagnosa_Pemasangan_Alat: number;
    Nyeri_Intervensi_Posisi_Nyaman: number;
    Penglihatan_Diagnosa_Penurunan: number;
    Penglihatan_Evaluasi_Kemampuan: number;
    Penglihatan_Evaluasi_Perubahan: number;
    Gangguan_Pola_Nafas_Evaluasi_O2: number;
    Kecemasan_Intervensi_Beri_Waktu: number;
    Kecemasan_Intervensi_Kesempatan: number;
    TTD_Perawat_Gangguan_Pola_Nafas: string;
    Tinggi_Cedera_Diagnosa_Hipoksia: number;
    Tinggi_Cedera_Evaluasi_Prosedur: number;
    Tinggi_Cedera_Intervensi_Cairan: number;
    Tinggi_Cedera_Intervensi_Posisi: number;
    Gangguan_Pola_Nafas_Evaluasi_TTV: number;
    Kekurangan_Cairan_Diagnosa_Puasa: number;
    Kekurangan_Cairan_Evaluasi_Input: number;
    Kekurangan_Cairan_Intervensi_TTV: number;
    Nama_Perawat_Gangguan_Pola_Nafas: string;
    Penglihatan_Intervensi_Ketajaman: number;
    Penglihatan_Intervensi_Orientasi: number;
    Tinggi_Cedera_Diagnosa_Pemajanan: number;
    Gangguan_Pola_Nafas_Intervensi_O2: number;
    Kekurangan_Cairan_Diagnosa_Intake: number;
    Kekurangan_Cairan_Evaluasi_Mukosa: number;
    Kekurangan_Cairan_Evaluasi_Output: number;
    Kekurangan_Cairan_Evaluasi_Turgor: number;
    Kekurangan_Cairan_Intervensi_Ukur: number;
    Nyeri_Intervensi_Teknik_Distraksi: number;
    Nyeri_Intervensi_Teknik_Relaksasi: number;
    Penglihatan_Diagnosa_Perlindungan: number;
    Tanggal_Perawat_Kekurangan_Cairan: string;
    Tinggi_Cedera_Intervensi_Terkunci: number;
    Gangguan_Pola_Nafas_Intervensi_TTV: number;
    Penglihatan_Intervensi_Alternative: number;
    Penglihatan_Intervensi_Cegah_Sinar: number;
    Gangguan_Pola_Nafas_Diagnosa_Sekret: number;
    Gangguan_Pola_Nafas_Intervensi_Obat: number;
    Kekurangan_Cairan_Diagnosa_Abnormal: number;
    Tanggal_Perawat_Gangguan_Pola_Nafas: string;
    Tinggi_Cedera_Intervensi_Elektrikal: number;
    Tinggi_Cedera_Intervensi_Lepas_Gigi: number;
    Gangguan_Pola_Nafas_Evaluasi_O2_Teks: string;
    Gangguan_Pola_Nafas_Evaluasi_Sianosis: number;
    Gangguan_Pola_Nafas_Intervensi_Rahang: number;
    Kecemasan_Diagnosa_Kurang_Pengetahuan: number;
    Kekurangan_Cairan_Diagnosa_Integritas: number;
    Kekurangan_Cairan_Evaluasi_Input_Teks: string;
    Gangguan_Pola_Nafas_Evaluasi_Observasi: number;
    Gangguan_Pola_Nafas_Intervensi_Suction: number;
    Kekurangan_Cairan_Evaluasi_Output_Teks: string;
    Kekurangan_Cairan_Intervensi_Suhu_Tubuh: number;
    Tinggi_Cedera_Intervensi_Plate_Diatermi: number;
    Tinggi_Cedera_Intervensi_Sabuk_Pengaman: number;
    Gangguan_Pola_Nafas_Intervensi_Observasi: number;
    Kekurangan_Cairan_Intervensi_Mual_Muntah: number;
    Penglihatan_Intervensi_Optimal_Lingkungan: number;
    Tinggi_Cedera_Intervensi_Jumlah_Pemakaian: number;
    Gangguan_Pola_Nafas_Diagnosa_Neuromuskular: number;
    Gangguan_Pola_Nafas_Evaluasi_Nafas_Spontan: number;
    Kekurangan_Cairan_Intervensi_Pembalut_Luka: number;
    Tinggi_Cedera_Intervensi_Periksa_Identitas: number;
    Gangguan_Pola_Nafas_Intervensi_Miringkan_Kepala: number;
}

export class DiagnosaIntraOperatifForm {
    Waktu: string;
    ID_Petugas: string;
    Updated_At: string;
    Updated_By: string;
    Nama_Dokter: string;
    Nama_Petugas: string;
    ID_Perawat_Nyeri: string;
    TTD_Perawat_Nyeri: string;
    ID_Perawat_Infeksi: string;
    Nama_Perawat_Nyeri: string;
    Nyeri_Diagnosa_Luka: number;
    TTD_Perawat_Infeksi: string;
    ID_Perawat_Kecemasan: string;
    Nama_Perawat_Infeksi: string;
    Nyeri_Evaluasi_Teknik: number;
    TTD_Perawat_Kecemasan: string;
    Tanggal_Perawat_Nyeri: string;
    ID_Perawat_Penglihatan: string;
    Nama_Perawat_Kecemasan: string;
    Infeksi_Diagnosa_Trauma: number;
    TTD_Perawat_Penglihatan: string;
    Tanggal_Perawat_Infeksi: string;
    ID_Perawat_Tinggi_Cedera: string;
    Nama_Perawat_Penglihatan: string;
    Nyeri_Evaluasi_Berkurang: number;
    Kecemasan_Evaluasi_Tenang: number;
    TTD_Perawat_Tinggi_Cedera: string;
    Tanggal_Perawat_Kecemasan: string;
    Infeksi_Diagnosa_Peralatan: number;
    Infeksi_Intervensi_Penutup: number;
    Nama_Perawat_Tinggi_Cedera: string;
    Infeksi_Diagnosa_Lingkungan: number;
    Kecemasan_Diagnosa_Prosedur: number;
    Nyeri_Intervensi_Kolaborasi: number;
    Tanggal_Perawat_Penglihatan: string;
    ID_Perawat_Kekurangan_Cairan: string;
    Infeksi_Evaluasi_Pertahankan: number;
    Kecemasan_Evaluasi_Berkurang: number;
    Nyeri_Intervensi_Skala_Nyeri: number;
    Infeksi_Intervensi_Disinfeksi: number;
    Infeksi_Intervensi_Kadaluarsa: number;
    Infeksi_Intervensi_Sterilitas: number;
    Kecemasan_Intervensi_Gambaran: number;
    TTD_Perawat_Kekurangan_Cairan: string;
    Tanggal_Perawat_Tinggi_Cedera: string;
    Tinggi_Cedera_Evaluasi_Jumlah: number;
    Tinggi_Cedera_Evaluasi_Posisi: number;
    ID_Perawat_Gangguan_Pola_Nafas: string;
    Infeksi_Intervensi_Cuci_Tangan: number;
    Kecemasan_Intervensi_Informasi: number;
    Kekurangan_Cairan_Evaluasi_TTV: number;
    Nama_Perawat_Kekurangan_Cairan: string;
    Nyeri_Diagnosa_Pemasangan_Alat: number;
    Nyeri_Intervensi_Posisi_Nyaman: number;
    Penglihatan_Diagnosa_Penurunan: number;
    Penglihatan_Evaluasi_Kemampuan: number;
    Penglihatan_Evaluasi_Perubahan: number;
    Gangguan_Pola_Nafas_Evaluasi_O2: number;
    Kecemasan_Intervensi_Beri_Waktu: number;
    Kecemasan_Intervensi_Kesempatan: number;
    TTD_Perawat_Gangguan_Pola_Nafas: string;
    Tinggi_Cedera_Diagnosa_Hipoksia: number;
    Tinggi_Cedera_Evaluasi_Prosedur: number;
    Tinggi_Cedera_Intervensi_Cairan: number;
    Tinggi_Cedera_Intervensi_Posisi: number;
    Gangguan_Pola_Nafas_Evaluasi_TTV: number;
    Kekurangan_Cairan_Diagnosa_Puasa: number;
    Kekurangan_Cairan_Evaluasi_Input: number;
    Kekurangan_Cairan_Intervensi_TTV: number;
    Nama_Perawat_Gangguan_Pola_Nafas: string;
    Penglihatan_Intervensi_Ketajaman: number;
    Penglihatan_Intervensi_Orientasi: number;
    Tinggi_Cedera_Diagnosa_Pemajanan: number;
    Gangguan_Pola_Nafas_Intervensi_O2: number;
    Kekurangan_Cairan_Diagnosa_Intake: number;
    Kekurangan_Cairan_Evaluasi_Mukosa: number;
    Kekurangan_Cairan_Evaluasi_Output: number;
    Kekurangan_Cairan_Evaluasi_Turgor: number;
    Kekurangan_Cairan_Intervensi_Ukur: number;
    Nyeri_Intervensi_Teknik_Distraksi: number;
    Nyeri_Intervensi_Teknik_Relaksasi: number;
    Penglihatan_Diagnosa_Perlindungan: number;
    Tanggal_Perawat_Kekurangan_Cairan: string;
    Tinggi_Cedera_Intervensi_Terkunci: number;
    Gangguan_Pola_Nafas_Intervensi_TTV: number;
    Penglihatan_Intervensi_Alternative: number;
    Penglihatan_Intervensi_Cegah_Sinar: number;
    Gangguan_Pola_Nafas_Diagnosa_Sekret: number;
    Gangguan_Pola_Nafas_Intervensi_Obat: number;
    Kekurangan_Cairan_Diagnosa_Abnormal: number;
    Tanggal_Perawat_Gangguan_Pola_Nafas: string;
    Tinggi_Cedera_Intervensi_Elektrikal: number;
    Tinggi_Cedera_Intervensi_Lepas_Gigi: number;
    Gangguan_Pola_Nafas_Evaluasi_O2_Teks: string;
    Gangguan_Pola_Nafas_Evaluasi_Sianosis: number;
    Gangguan_Pola_Nafas_Intervensi_Rahang: number;
    Kecemasan_Diagnosa_Kurang_Pengetahuan: number;
    Kekurangan_Cairan_Diagnosa_Integritas: number;
    Kekurangan_Cairan_Evaluasi_Input_Teks: string;
    Gangguan_Pola_Nafas_Evaluasi_Observasi: number;
    Gangguan_Pola_Nafas_Intervensi_Suction: number;
    Kekurangan_Cairan_Evaluasi_Output_Teks: string;
    Kekurangan_Cairan_Intervensi_Suhu_Tubuh: number;
    Tinggi_Cedera_Intervensi_Plate_Diatermi: number;
    Tinggi_Cedera_Intervensi_Sabuk_Pengaman: number;
    Gangguan_Pola_Nafas_Intervensi_Observasi: number;
    Kekurangan_Cairan_Intervensi_Mual_Muntah: number;
    Penglihatan_Intervensi_Optimal_Lingkungan: number;
    Tinggi_Cedera_Intervensi_Jumlah_Pemakaian: number;
    Gangguan_Pola_Nafas_Diagnosa_Neuromuskular: number;
    Gangguan_Pola_Nafas_Evaluasi_Nafas_Spontan: number;
    Kekurangan_Cairan_Intervensi_Pembalut_Luka: number;
    Tinggi_Cedera_Intervensi_Periksa_Identitas: number;
    Gangguan_Pola_Nafas_Intervensi_Miringkan_Kepala: number;

    constructor(request: IDiagnosaIntraOperatifForm) {
      this.Waktu = request.Waktu;
      this.ID_Petugas = request.ID_Petugas;
      this.Updated_At = request.Updated_At;
      this.Updated_By = request.Updated_By;
      this.Nama_Dokter = request.Nama_Dokter;
      this.Nama_Petugas = request.Nama_Petugas;
      this.ID_Perawat_Nyeri = request.ID_Perawat_Nyeri;
      this.TTD_Perawat_Nyeri = request.TTD_Perawat_Nyeri;
      this.ID_Perawat_Infeksi = request.ID_Perawat_Infeksi;
      this.Nama_Perawat_Nyeri = request.Nama_Perawat_Nyeri;
      this.Nyeri_Diagnosa_Luka = request.Nyeri_Diagnosa_Luka;
      this.TTD_Perawat_Infeksi = request.TTD_Perawat_Infeksi;
      this.ID_Perawat_Kecemasan = request.ID_Perawat_Kecemasan;
      this.Nama_Perawat_Infeksi = request.Nama_Perawat_Infeksi;
      this.Nyeri_Evaluasi_Teknik = request.Nyeri_Evaluasi_Teknik;
      this.TTD_Perawat_Kecemasan = request.TTD_Perawat_Kecemasan;
      this.Tanggal_Perawat_Nyeri = request.Tanggal_Perawat_Nyeri;
      this.ID_Perawat_Penglihatan = request.ID_Perawat_Penglihatan;
      this.Nama_Perawat_Kecemasan = request.Nama_Perawat_Kecemasan;
      this.Infeksi_Diagnosa_Trauma = request.Infeksi_Diagnosa_Trauma;
      this.TTD_Perawat_Penglihatan = request.TTD_Perawat_Penglihatan;
      this.Tanggal_Perawat_Infeksi = request.Tanggal_Perawat_Infeksi;
      this.ID_Perawat_Tinggi_Cedera = request.ID_Perawat_Tinggi_Cedera;
      this.Nama_Perawat_Penglihatan = request.Nama_Perawat_Penglihatan;
      this.Nyeri_Evaluasi_Berkurang = request.Nyeri_Evaluasi_Berkurang;
      this.Kecemasan_Evaluasi_Tenang = request.Kecemasan_Evaluasi_Tenang;
      this.TTD_Perawat_Tinggi_Cedera = request.TTD_Perawat_Tinggi_Cedera;
      this.Tanggal_Perawat_Kecemasan = request.Tanggal_Perawat_Kecemasan;
      this.Infeksi_Diagnosa_Peralatan = request.Infeksi_Diagnosa_Peralatan;
      this.Infeksi_Intervensi_Penutup = request.Infeksi_Intervensi_Penutup;
      this.Nama_Perawat_Tinggi_Cedera = request.Nama_Perawat_Tinggi_Cedera;
      this.Infeksi_Diagnosa_Lingkungan = request.Infeksi_Diagnosa_Lingkungan;
      this.Kecemasan_Diagnosa_Prosedur = request.Kecemasan_Diagnosa_Prosedur;
      this.Nyeri_Intervensi_Kolaborasi = request.Nyeri_Intervensi_Kolaborasi;
      this.Tanggal_Perawat_Penglihatan = request.Tanggal_Perawat_Penglihatan;
      this.ID_Perawat_Kekurangan_Cairan = request.ID_Perawat_Kekurangan_Cairan;
      this.Infeksi_Evaluasi_Pertahankan = request.Infeksi_Evaluasi_Pertahankan;
      this.Kecemasan_Evaluasi_Berkurang = request.Kecemasan_Evaluasi_Berkurang;
      this.Nyeri_Intervensi_Skala_Nyeri = request.Nyeri_Intervensi_Skala_Nyeri;
      this.Infeksi_Intervensi_Disinfeksi = request.Infeksi_Intervensi_Disinfeksi;
      this.Infeksi_Intervensi_Kadaluarsa = request.Infeksi_Intervensi_Kadaluarsa;
      this.Infeksi_Intervensi_Sterilitas = request.Infeksi_Intervensi_Sterilitas;
      this.Kecemasan_Intervensi_Gambaran = request.Kecemasan_Intervensi_Gambaran;
      this.TTD_Perawat_Kekurangan_Cairan = request.TTD_Perawat_Kekurangan_Cairan;
      this.Tanggal_Perawat_Tinggi_Cedera = request.Tanggal_Perawat_Tinggi_Cedera;
      this.Tinggi_Cedera_Evaluasi_Jumlah = request.Tinggi_Cedera_Evaluasi_Jumlah;
      this.Tinggi_Cedera_Evaluasi_Posisi = request.Tinggi_Cedera_Evaluasi_Posisi;
      this.ID_Perawat_Gangguan_Pola_Nafas = request.ID_Perawat_Gangguan_Pola_Nafas;
      this.Infeksi_Intervensi_Cuci_Tangan = request.Infeksi_Intervensi_Cuci_Tangan;
      this.Kecemasan_Intervensi_Informasi = request.Kecemasan_Intervensi_Informasi;
      this.Kekurangan_Cairan_Evaluasi_TTV = request.Kekurangan_Cairan_Evaluasi_TTV;
      this.Nama_Perawat_Kekurangan_Cairan = request.Nama_Perawat_Kekurangan_Cairan;
      this.Nyeri_Diagnosa_Pemasangan_Alat = request.Nyeri_Diagnosa_Pemasangan_Alat;
      this.Nyeri_Intervensi_Posisi_Nyaman = request.Nyeri_Intervensi_Posisi_Nyaman;
      this.Penglihatan_Diagnosa_Penurunan = request.Penglihatan_Diagnosa_Penurunan;
      this.Penglihatan_Evaluasi_Kemampuan = request.Penglihatan_Evaluasi_Kemampuan;
      this.Penglihatan_Evaluasi_Perubahan = request.Penglihatan_Evaluasi_Perubahan;
      this.Gangguan_Pola_Nafas_Evaluasi_O2 = request.Gangguan_Pola_Nafas_Evaluasi_O2;
      this.Kecemasan_Intervensi_Beri_Waktu = request.Kecemasan_Intervensi_Beri_Waktu;
      this.Kecemasan_Intervensi_Kesempatan = request.Kecemasan_Intervensi_Kesempatan;
      this.TTD_Perawat_Gangguan_Pola_Nafas = request.TTD_Perawat_Gangguan_Pola_Nafas;
      this.Tinggi_Cedera_Diagnosa_Hipoksia = request.Tinggi_Cedera_Diagnosa_Hipoksia;
      this.Tinggi_Cedera_Evaluasi_Prosedur = request.Tinggi_Cedera_Evaluasi_Prosedur;
      this.Tinggi_Cedera_Intervensi_Cairan = request.Tinggi_Cedera_Intervensi_Cairan;
      this.Tinggi_Cedera_Intervensi_Posisi = request.Tinggi_Cedera_Intervensi_Posisi;
      this.Gangguan_Pola_Nafas_Evaluasi_TTV = request.Gangguan_Pola_Nafas_Evaluasi_TTV;
      this.Kekurangan_Cairan_Diagnosa_Puasa = request.Kekurangan_Cairan_Diagnosa_Puasa;
      this.Kekurangan_Cairan_Evaluasi_Input = request.Kekurangan_Cairan_Evaluasi_Input;
      this.Kekurangan_Cairan_Intervensi_TTV = request.Kekurangan_Cairan_Intervensi_TTV;
      this.Nama_Perawat_Gangguan_Pola_Nafas = request.Nama_Perawat_Gangguan_Pola_Nafas;
      this.Penglihatan_Intervensi_Ketajaman = request.Penglihatan_Intervensi_Ketajaman;
      this.Penglihatan_Intervensi_Orientasi = request.Penglihatan_Intervensi_Orientasi;
      this.Tinggi_Cedera_Diagnosa_Pemajanan = request.Tinggi_Cedera_Diagnosa_Pemajanan;
      this.Gangguan_Pola_Nafas_Intervensi_O2 = request.Gangguan_Pola_Nafas_Intervensi_O2;
      this.Kekurangan_Cairan_Diagnosa_Intake = request.Kekurangan_Cairan_Diagnosa_Intake;
      this.Kekurangan_Cairan_Evaluasi_Mukosa = request.Kekurangan_Cairan_Evaluasi_Mukosa;
      this.Kekurangan_Cairan_Evaluasi_Output = request.Kekurangan_Cairan_Evaluasi_Output;
      this.Kekurangan_Cairan_Evaluasi_Turgor = request.Kekurangan_Cairan_Evaluasi_Turgor;
      this.Kekurangan_Cairan_Intervensi_Ukur = request.Kekurangan_Cairan_Intervensi_Ukur;
      this.Nyeri_Intervensi_Teknik_Distraksi = request.Nyeri_Intervensi_Teknik_Distraksi;
      this.Nyeri_Intervensi_Teknik_Relaksasi = request.Nyeri_Intervensi_Teknik_Relaksasi;
      this.Penglihatan_Diagnosa_Perlindungan = request.Penglihatan_Diagnosa_Perlindungan;
      this.Tanggal_Perawat_Kekurangan_Cairan = request.Tanggal_Perawat_Kekurangan_Cairan;
      this.Tinggi_Cedera_Intervensi_Terkunci = request.Tinggi_Cedera_Intervensi_Terkunci;
      this.Gangguan_Pola_Nafas_Intervensi_TTV = request.Gangguan_Pola_Nafas_Intervensi_TTV;
      this.Penglihatan_Intervensi_Alternative = request.Penglihatan_Intervensi_Alternative;
      this.Penglihatan_Intervensi_Cegah_Sinar = request.Penglihatan_Intervensi_Cegah_Sinar;
      this.Gangguan_Pola_Nafas_Diagnosa_Sekret = request.Gangguan_Pola_Nafas_Diagnosa_Sekret;
      this.Gangguan_Pola_Nafas_Intervensi_Obat = request.Gangguan_Pola_Nafas_Intervensi_Obat;
      this.Kekurangan_Cairan_Diagnosa_Abnormal = request.Kekurangan_Cairan_Diagnosa_Abnormal;
      this.Tanggal_Perawat_Gangguan_Pola_Nafas = request.Tanggal_Perawat_Gangguan_Pola_Nafas;
      this.Tinggi_Cedera_Intervensi_Elektrikal = request.Tinggi_Cedera_Intervensi_Elektrikal;
      this.Tinggi_Cedera_Intervensi_Lepas_Gigi = request.Tinggi_Cedera_Intervensi_Lepas_Gigi;
      this.Gangguan_Pola_Nafas_Evaluasi_O2_Teks = request.Gangguan_Pola_Nafas_Evaluasi_O2_Teks;
      this.Gangguan_Pola_Nafas_Evaluasi_Sianosis = request.Gangguan_Pola_Nafas_Evaluasi_Sianosis;
      this.Gangguan_Pola_Nafas_Intervensi_Rahang = request.Gangguan_Pola_Nafas_Intervensi_Rahang;
      this.Kecemasan_Diagnosa_Kurang_Pengetahuan = request.Kecemasan_Diagnosa_Kurang_Pengetahuan;
      this.Kekurangan_Cairan_Diagnosa_Integritas = request.Kekurangan_Cairan_Diagnosa_Integritas;
      this.Kekurangan_Cairan_Diagnosa_Integritas = request.Kekurangan_Cairan_Diagnosa_Integritas;
      this.Kekurangan_Cairan_Evaluasi_Input_Teks = request.Kekurangan_Cairan_Evaluasi_Input_Teks;
      this.Gangguan_Pola_Nafas_Evaluasi_Observasi = request.Gangguan_Pola_Nafas_Evaluasi_Observasi;
      this.Gangguan_Pola_Nafas_Intervensi_Suction = request.Gangguan_Pola_Nafas_Intervensi_Suction;
      this.Kekurangan_Cairan_Evaluasi_Output_Teks = request.Kekurangan_Cairan_Evaluasi_Output_Teks;
      this.Kekurangan_Cairan_Intervensi_Suhu_Tubuh = request.Kekurangan_Cairan_Intervensi_Suhu_Tubuh;
      this.Tinggi_Cedera_Intervensi_Plate_Diatermi = request.Tinggi_Cedera_Intervensi_Plate_Diatermi;
      this.Tinggi_Cedera_Intervensi_Sabuk_Pengaman = request.Tinggi_Cedera_Intervensi_Sabuk_Pengaman;
      this.Gangguan_Pola_Nafas_Intervensi_Observasi = request.Gangguan_Pola_Nafas_Intervensi_Observasi;
      this.Kekurangan_Cairan_Intervensi_Mual_Muntah = request.Kekurangan_Cairan_Intervensi_Mual_Muntah;
      this.Penglihatan_Intervensi_Optimal_Lingkungan = request.Penglihatan_Intervensi_Optimal_Lingkungan;
      this.Tinggi_Cedera_Intervensi_Jumlah_Pemakaian = request.Tinggi_Cedera_Intervensi_Jumlah_Pemakaian;
      this.Gangguan_Pola_Nafas_Diagnosa_Neuromuskular = request.Gangguan_Pola_Nafas_Diagnosa_Neuromuskular;
      this.Gangguan_Pola_Nafas_Evaluasi_Nafas_Spontan = request.Gangguan_Pola_Nafas_Evaluasi_Nafas_Spontan;
      this.Kekurangan_Cairan_Intervensi_Pembalut_Luka = request.Kekurangan_Cairan_Intervensi_Pembalut_Luka;
      this.Tinggi_Cedera_Intervensi_Periksa_Identitas = request.Tinggi_Cedera_Intervensi_Periksa_Identitas;
      this.Gangguan_Pola_Nafas_Intervensi_Miringkan_Kepala = request.Gangguan_Pola_Nafas_Intervensi_Miringkan_Kepala;
    }
}

// export interface IDiagnosaIntraOperatifModel extends IDataModel{
//     formIntraOperatif: IDiagnosaIntraOperatifForm;
//   }

// export class DiagnosaIntraOperatifModel extends DataModel {
//     formIntraOperatif: IDiagnosaIntraOperatifForm;

//     constructor(request: IDiagnosaIntraOperatifModel) {
//       super(request);
//       this.formIntraOperatif = request.formIntraOperatif;
//     }
// }
