import { IDataModel, DataModel } from "@src/shared/model";

export interface IDiagnosaPascaOperatifForm {
    Waktu: string;
    ID_Petugas: string;
    Updated_At: string;
    Updated_By: string;
    Nama_Dokter: string;
    Nama_Petugas: string;
    ID_Perawat_Nyeri: string;
    TTD_Perawat_Nyeri: string;
    ID_Perawat_Infeksi: string;
    Nama_Perawat_Nyeri: string;
    Nyeri_Evaluasi_Ttv: number;
    Nyeri_Diagnosa_Luka: number;
    TTD_Perawat_Infeksi: string;
    ID_Perawat_Perubahan: string;
    Nama_Perawat_Infeksi: string;
    TTD_Perawat_Perubahan: string;
    Tanggal_Perawat_Nyeri: string;
    Nama_Perawat_Perubahan: string;
    Infeksi_Diagnosa_Trauma: number;
    Perubahan_Diagnosa_Obat: number;
    Perubahan_Diagnosa_Suhu: number;
    Tanggal_Perawat_Infeksi: string;
    Nyeri_Intervensi_Kaji_Ttv: number;
    Tanggal_Perawat_Perubahan: string;
    Evaluasi_Suhu_Ruangan_Teks: string;
    ID_Perawat_Kecemasan_Pasca: string;
    Infeksi_Diagnosa_Peralatan: number;
    Infeksi_Intervensi_Penutup: number;
    Nyeri_Evaluasi_Diobservasi: number;
    Infeksi_Diagnosa_Lingkungan: number;
    TTD_Perawat_Kecemasan_Pasca: string;
    Infeksi_Evaluasi_Pertahankan: number;
    Nama_Perawat_Kecemasan_Pasca: string;
    Nyeri_Intervensi_Kaji_Lokasi: number;
    Perubahan_Diagnosa_Dehidrasi: number;
    Infeksi_Intervensi_Disinfeksi: number;
    Infeksi_Intervensi_Kadaluarsa: number;
    Infeksi_Intervensi_Sterilitas: number;
    Infeksi_Intervensi_Cuci_Tangan: number;
    Nyeri_Diagnosa_Gaangguan_Kulit: number;
    Nyeri_Evaluasi_Nyeri_Berkurang: number;
    Nyeri_Intervensi_Posisi_Nyaman: number;
    Perubahan_Intervensi_Kaji_Suhu: number;
    Nyeri_Evaluasi_Nyeri_Terkontrol: number;
    Perubahan_Evaluasi_Suhu_Ruangan: number;
    Perubahan_Intervensi_Kolaborasi: number;
    Tanggal_Perawat_Kecemasan: string;
    Perubahan_Evaluasi_Pasien_Dingin: number;
    Nyeri_Intervensi_Teknik_Distraksi: number;
    Perubahan_Intervensi_Catatan_Suhu: number;
    Nyeri_Intervensi_Teknik_Relaksaksi: number;
    Perubahan_Evaluasi_Pasien_Menggigil: number;
    Nyeri_Intervensi_Pemeberian_Analgesi: number;
    Kecemasan_Pasca_Operatif_Evaluasi_Kecemasan: number;
    Kecemasan_Pasca_Operatif_Evaluasi_Tenang_Selama: number;
    Kecemasan_Pasca_Operatif_Intervensi_Gambar_Luka: number;
    Kecemasan_Pasca_Operatif_Diagnosa_Perawatan_Luka: number;
    Kecemasan_Pasca_Operatif_Intervensi_Nomor_Pasien: number;
    Kecemasan_Pasca_Operatif_Intervensi_Beri_Informasi: number;
    Kecemasan_Pasca_Operatif_Intervensi_Perasaan_Klien: number;
    Kecemasan_Pasca_Operatif_Intervensi_Waktu_Perasaan: number;
    Kecemasan_Pasca_Operatif_Intervensi_Kesempatan_Bertanya: number;
    Kecemasan_Pasca_Operatif_Intervensi_Perbaikan_Pengelihatan: number;
}

export class DiagnosaPascaOperatifForm {
    Waktu: string;
    ID_Petugas: string;
    Updated_At: string;
    Updated_By: string;
    Nama_Dokter: string;
    Nama_Petugas: string;
    ID_Perawat_Nyeri: string;
    TTD_Perawat_Nyeri: string;
    ID_Perawat_Infeksi: string;
    Nama_Perawat_Nyeri: string;
    Nyeri_Evaluasi_Ttv: number;
    Nyeri_Diagnosa_Luka: number;
    TTD_Perawat_Infeksi: string;
    ID_Perawat_Perubahan: string;
    Nama_Perawat_Infeksi: string;
    TTD_Perawat_Perubahan: string;
    Tanggal_Perawat_Nyeri: string;
    Nama_Perawat_Perubahan: string;
    Infeksi_Diagnosa_Trauma: number;
    Perubahan_Diagnosa_Obat: number;
    Perubahan_Diagnosa_Suhu: number;
    Tanggal_Perawat_Infeksi: string;
    Nyeri_Intervensi_Kaji_Ttv: number;
    Tanggal_Perawat_Perubahan: string;
    Evaluasi_Suhu_Ruangan_Teks: string;
    ID_Perawat_Kecemasan_Pasca: string;
    Infeksi_Diagnosa_Peralatan: number;
    Infeksi_Intervensi_Penutup: number;
    Nyeri_Evaluasi_Diobservasi: number;
    Infeksi_Diagnosa_Lingkungan: number;
    TTD_Perawat_Kecemasan_Pasca: string;
    Infeksi_Evaluasi_Pertahankan: number;
    Nama_Perawat_Kecemasan_Pasca: string;
    Nyeri_Intervensi_Kaji_Lokasi: number;
    Perubahan_Diagnosa_Dehidrasi: number;
    Infeksi_Intervensi_Disinfeksi: number;
    Infeksi_Intervensi_Kadaluarsa: number;
    Infeksi_Intervensi_Sterilitas: number;
    Infeksi_Intervensi_Cuci_Tangan: number;
    Nyeri_Diagnosa_Gaangguan_Kulit: number;
    Nyeri_Evaluasi_Nyeri_Berkurang: number;
    Nyeri_Intervensi_Posisi_Nyaman: number;
    Perubahan_Intervensi_Kaji_Suhu: number;
    Nyeri_Evaluasi_Nyeri_Terkontrol: number;
    Perubahan_Evaluasi_Suhu_Ruangan: number;
    Perubahan_Intervensi_Kolaborasi: number;
    Tanggal_Perawat_Kecemasan: string;
    Perubahan_Evaluasi_Pasien_Dingin: number;
    Nyeri_Intervensi_Teknik_Distraksi: number;
    Perubahan_Intervensi_Catatan_Suhu: number;
    Nyeri_Intervensi_Teknik_Relaksaksi: number;
    Perubahan_Evaluasi_Pasien_Menggigil: number;
    Nyeri_Intervensi_Pemeberian_Analgesi: number;
    Kecemasan_Pasca_Operatif_Evaluasi_Kecemasan: number;
    Kecemasan_Pasca_Operatif_Evaluasi_Tenang_Selama: number;
    Kecemasan_Pasca_Operatif_Intervensi_Gambar_Luka: number;
    Kecemasan_Pasca_Operatif_Diagnosa_Perawatan_Luka: number;
    Kecemasan_Pasca_Operatif_Intervensi_Nomor_Pasien: number;
    Kecemasan_Pasca_Operatif_Intervensi_Beri_Informasi: number;
    Kecemasan_Pasca_Operatif_Intervensi_Perasaan_Klien: number;
    Kecemasan_Pasca_Operatif_Intervensi_Waktu_Perasaan: number;
    Kecemasan_Pasca_Operatif_Intervensi_Kesempatan_Bertanya: number;
    Kecemasan_Pasca_Operatif_Intervensi_Perbaikan_Pengelihatan: number;

    constructor(request: IDiagnosaPascaOperatifForm) {
      this.Waktu = request.Waktu;
      this.ID_Petugas = request.ID_Petugas;
      this.Updated_At = request.Updated_At;
      this.Updated_By = request.Updated_By;
      this.Nama_Dokter =  request.Nama_Dokter;
      this.Nama_Petugas = request.Nama_Petugas;
      this.ID_Perawat_Nyeri = request.ID_Perawat_Nyeri;
      this.TTD_Perawat_Nyeri = request.TTD_Perawat_Nyeri;
      this.ID_Perawat_Infeksi = request.ID_Perawat_Infeksi;
      this.Nama_Perawat_Nyeri = request.Nama_Perawat_Nyeri;
      this.Nyeri_Evaluasi_Ttv =  request.Nyeri_Evaluasi_Ttv;
      this.Nyeri_Diagnosa_Luka = request.Nyeri_Diagnosa_Luka;
      this.TTD_Perawat_Infeksi = request.TTD_Perawat_Infeksi;
      this.ID_Perawat_Perubahan =  request.ID_Perawat_Perubahan;
      this.Nama_Perawat_Infeksi = request.Nama_Perawat_Infeksi;
      this.TTD_Perawat_Perubahan = request.TTD_Perawat_Perubahan;
      this.Tanggal_Perawat_Nyeri = request.Tanggal_Perawat_Nyeri;
      this.Nama_Perawat_Perubahan = request.Nama_Perawat_Perubahan;
      this.Infeksi_Diagnosa_Trauma = request.Infeksi_Diagnosa_Trauma;
      this.Perubahan_Diagnosa_Obat = request.Perubahan_Diagnosa_Obat;
      this.Perubahan_Diagnosa_Suhu = request.Perubahan_Diagnosa_Suhu;
      this.Tanggal_Perawat_Infeksi = request.Tanggal_Perawat_Infeksi;
      this.Nyeri_Intervensi_Kaji_Ttv = request.Nyeri_Intervensi_Kaji_Ttv;
      this.Tanggal_Perawat_Perubahan = request.Tanggal_Perawat_Perubahan;
      this.Evaluasi_Suhu_Ruangan_Teks = request.Evaluasi_Suhu_Ruangan_Teks;
      this.ID_Perawat_Kecemasan_Pasca = request.ID_Perawat_Kecemasan_Pasca;
      this.Infeksi_Diagnosa_Peralatan = request.Infeksi_Diagnosa_Peralatan;
      this.Infeksi_Intervensi_Penutup = request.Infeksi_Intervensi_Penutup;
      this.Nyeri_Evaluasi_Diobservasi = request.Nyeri_Evaluasi_Diobservasi;
      this.Infeksi_Diagnosa_Lingkungan = request.Infeksi_Diagnosa_Lingkungan;
      this.TTD_Perawat_Kecemasan_Pasca = request.TTD_Perawat_Kecemasan_Pasca;
      this.Infeksi_Evaluasi_Pertahankan = request.Infeksi_Evaluasi_Pertahankan;
      this.Nama_Perawat_Kecemasan_Pasca = request.Nama_Perawat_Kecemasan_Pasca;
      this.Nyeri_Intervensi_Kaji_Lokasi = request.Nyeri_Intervensi_Kaji_Lokasi;
      this.Perubahan_Diagnosa_Dehidrasi = request.Perubahan_Diagnosa_Dehidrasi;
      this.Infeksi_Intervensi_Disinfeksi = request.Infeksi_Intervensi_Disinfeksi;
      this.Infeksi_Intervensi_Kadaluarsa = request.Infeksi_Intervensi_Kadaluarsa;
      this.Infeksi_Intervensi_Sterilitas = request.Infeksi_Intervensi_Sterilitas;
      this.Infeksi_Intervensi_Cuci_Tangan = request.Infeksi_Intervensi_Cuci_Tangan;
      this.Nyeri_Diagnosa_Gaangguan_Kulit = request.Nyeri_Diagnosa_Gaangguan_Kulit;
      this.Nyeri_Evaluasi_Nyeri_Berkurang = request.Nyeri_Evaluasi_Nyeri_Berkurang;
      this.Nyeri_Intervensi_Posisi_Nyaman = request.Nyeri_Intervensi_Posisi_Nyaman;
      this.Perubahan_Intervensi_Kaji_Suhu = request.Perubahan_Intervensi_Kaji_Suhu;
      this.Nyeri_Evaluasi_Nyeri_Terkontrol = request.Nyeri_Evaluasi_Nyeri_Terkontrol;
      this.Perubahan_Evaluasi_Suhu_Ruangan = request.Perubahan_Evaluasi_Suhu_Ruangan;
      this.Perubahan_Intervensi_Kolaborasi = request.Perubahan_Intervensi_Kolaborasi;
      this.Tanggal_Perawat_Kecemasan = request.Tanggal_Perawat_Kecemasan;
      this.Perubahan_Evaluasi_Pasien_Dingin = request.Perubahan_Evaluasi_Pasien_Dingin;
      this.Nyeri_Intervensi_Teknik_Distraksi = request.Nyeri_Intervensi_Teknik_Distraksi;
      this.Perubahan_Intervensi_Catatan_Suhu =  request.Perubahan_Intervensi_Catatan_Suhu;
      this.Nyeri_Intervensi_Teknik_Relaksaksi = request.Nyeri_Intervensi_Teknik_Relaksaksi;
      this.Perubahan_Evaluasi_Pasien_Menggigil = request.Perubahan_Evaluasi_Pasien_Menggigil;
      this.Nyeri_Intervensi_Pemeberian_Analgesi = request.Nyeri_Intervensi_Pemeberian_Analgesi;
      this.Kecemasan_Pasca_Operatif_Evaluasi_Kecemasan = request.Kecemasan_Pasca_Operatif_Evaluasi_Kecemasan;
      this.Kecemasan_Pasca_Operatif_Evaluasi_Tenang_Selama = request.Kecemasan_Pasca_Operatif_Evaluasi_Tenang_Selama;
      this.Kecemasan_Pasca_Operatif_Intervensi_Gambar_Luka = request.Kecemasan_Pasca_Operatif_Intervensi_Gambar_Luka;
      this.Kecemasan_Pasca_Operatif_Diagnosa_Perawatan_Luka = request.Kecemasan_Pasca_Operatif_Diagnosa_Perawatan_Luka;
      this.Kecemasan_Pasca_Operatif_Intervensi_Nomor_Pasien = request.Kecemasan_Pasca_Operatif_Intervensi_Nomor_Pasien;
      this.Kecemasan_Pasca_Operatif_Intervensi_Beri_Informasi = request.Kecemasan_Pasca_Operatif_Intervensi_Beri_Informasi;
      this.Kecemasan_Pasca_Operatif_Intervensi_Perasaan_Klien = request.Kecemasan_Pasca_Operatif_Intervensi_Perasaan_Klien;
      this.Kecemasan_Pasca_Operatif_Intervensi_Waktu_Perasaan = request.Kecemasan_Pasca_Operatif_Intervensi_Waktu_Perasaan;
      this.Kecemasan_Pasca_Operatif_Intervensi_Kesempatan_Bertanya = request.Kecemasan_Pasca_Operatif_Intervensi_Kesempatan_Bertanya;
      this.Kecemasan_Pasca_Operatif_Intervensi_Perbaikan_Pengelihatan = request.Kecemasan_Pasca_Operatif_Intervensi_Perbaikan_Pengelihatan;
    }
}

// export interface IDiagnosaPascaOperatifModel extends IDataModel{
//     formPascaOperatif: IDiagnosaPascaOperatifForm;
//   }

// export class DiagnosaPascaOperatifModel extends DataModel {
//     formPascaOperatif: IDiagnosaPascaOperatifForm;

//     constructor(request: IDiagnosaPascaOperatifModel) {
//       super(request);
//       this.formPascaOperatif = request.formPascaOperatif;
//     }
// }
